import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const ONE=65536;
const wasmPath=process.argv[2],nativeReceiptPath=process.argv[3];assert.ok(wasmPath&&nativeReceiptPath,'usage: node coupled_wasm.test.mjs module.wasm native-output.txt');
const nativeLines=fs.readFileSync(nativeReceiptPath,'utf8').trim().split(/\r?\n/);const native=JSON.parse(nativeLines.find(x=>x.startsWith('{')));
const bytes=fs.readFileSync(wasmPath),mod=await WebAssembly.compile(bytes),imports=WebAssembly.Module.imports(mod);assert.equal(imports.length,0,'coupled WASM must be freestanding');const{exports:e}=await WebAssembly.instantiate(mod,{});assert.equal(e.genesis_coupled_model_version()>>>0,0x00020001);assert.equal(e.genesis_model_version()>>>0,0x00040001);assert.equal(e.genesis_body_model_version()>>>0,0x00010001);
function fixture(){e.genesis_init(24,20,24,0x55aa7711,72);e.genesis_clear();assert.ok((e.genesis_paint(3,12,2,12,4)|0)>0);assert.ok((e.genesis_paint(1,12,7,12,2)|0)>0);assert.ok((e.genesis_paint(2,18,8,18,3)|0)>0);assert.equal(e.genesis_body_seed_organism(12*ONE,11*ONE,12*ONE),18);assert.ok((e.genesis_coupled_sync_solids()|0)>0);assert.ok((e.genesis_coupled_rock_count()>>>0)>0);assert.ok((e.genesis_coupled_sand_count()>>>0)>0);assert.ok((e.genesis_coupled_water_count()>>>0)>0);assert.equal(e.genesis_body_apply_impulse(3,ONE,0,ONE>>1),1);for(let i=0;i<90;i++)e.genesis_coupled_step(1,1);assert.equal(e.genesis_coupled_material_invariant(),1);assert.equal(e.genesis_body_node_count(),18);assert.equal(e.genesis_coupled_body_step_index()>>>0,90);return{hash:e.genesis_coupled_hash()>>>0,comY:e.genesis_body_com_y()|0};}
const a=fixture(),b=fixture();assert.deepEqual(a,b,'coupled WASM replay must be deterministic');assert.equal(a.hash,native.hash,'native/WASM coupled hash mismatch');assert.equal(a.comY,native.comY,'native/WASM coupled COM mismatch');
console.log(JSON.stringify({model:'genesis-native-body-volume-coupling-v2',wasmBytes:bytes.byteLength,wasmSha256:crypto.createHash('sha256').update(bytes).digest('hex'),imports:imports.length,hash:a.hash,comY:a.comY}));console.log('PASS GENESIS coupled native/WASM parity: zero imports and exact material-fluid-body replay agreement');
