#include <stdint.h>
#if defined(__wasm__)
#define EXPORT(name) __attribute__((export_name(name)))
#else
#define EXPORT(name)
#endif
extern "C" {int genesis_material_at(int,int,int);int genesis_water_velocity_x_at(int,int,int);int genesis_water_velocity_y_at(int,int,int);int genesis_water_velocity_z_at(int,int,int);int genesis_pressure_at(int,int,int);int genesis_body_node_count();int genesis_body_node_x(int);int genesis_body_node_y(int);int genesis_body_node_z(int);int genesis_body_node_vx(int);int genesis_body_node_vy(int);int genesis_body_node_vz(int);int genesis_body_apply_impulse(int,int,int,int);}
namespace hydro1 {constexpr int ONE=65536,SAMPLE_R=ONE/2,DRAG_Q16=8192,BUOYANCY_Q16=6200,PRESSURE_SCALE=4;static uint32_t submergedNodes=0,submergedSamples=0;static uint64_t buoyancyImpulse=0,dragImpulse=0,pressureImpulse=0;static int32_t netX=0,netY=0,netZ=0,dragX=0,dragY=0,dragZ=0,pressureX=0,pressureY=0,pressureZ=0;inline int absi(int v){return v<0?-v:v;}inline int qmul(int a,int b){return(int)(((int64_t)a*b)>>16);}inline int cell(int q){return q>=0?q/ONE:-1;}int sample_water(int x,int y,int z){return genesis_material_at(cell(x),cell(y),cell(z))==2;}int submerged_fraction(int x,int y,int z){int n=sample_water(x,y,z)+sample_water(x+SAMPLE_R,y,z)+sample_water(x-SAMPLE_R,y,z)+sample_water(x,y+SAMPLE_R,z)+sample_water(x,y-SAMPLE_R,z)+sample_water(x,y,z+SAMPLE_R)+sample_water(x,y,z-SAMPLE_R);submergedSamples+=(uint32_t)n;return(n*ONE)/7;}void reset(){submergedNodes=submergedSamples=0;buoyancyImpulse=dragImpulse=pressureImpulse=0;netX=netY=netZ=dragX=dragY=dragZ=pressureX=pressureY=pressureZ=0;}void apply_node(int i){int x=genesis_body_node_x(i),y=genesis_body_node_y(i),z=genesis_body_node_z(i),f=submerged_fraction(x,y,z);if(f<=0)return;submergedNodes++;int cx=cell(x),cy=cell(y),cz=cell(z);int rvx=(genesis_water_velocity_x_at(cx,cy,cz)<<8)-genesis_body_node_vx(i),rvy=(genesis_water_velocity_y_at(cx,cy,cz)<<8)-genesis_body_node_vy(i),rvz=(genesis_water_velocity_z_at(cx,cy,cz)<<8)-genesis_body_node_vz(i);int ds=qmul(DRAG_Q16,f),jdx=qmul(rvx,ds),jdy=qmul(rvy,ds),jdz=qmul(rvz,ds),buoy=qmul(BUOYANCY_Q16,f);int gx=(genesis_pressure_at(cx+1,cy,cz)-genesis_pressure_at(cx-1,cy,cz))/2,gy=(genesis_pressure_at(cx,cy+1,cz)-genesis_pressure_at(cx,cy-1,cz))/2,gz=(genesis_pressure_at(cx,cy,cz+1)-genesis_pressure_at(cx,cy,cz-1))/2;int jpx=qmul(-gx*PRESSURE_SCALE,f),jpy=qmul(-gy*PRESSURE_SCALE,f),jpz=qmul(-gz*PRESSURE_SCALE,f);int ix=jdx+jpx,iy=jdy+buoy+jpy,iz=jdz+jpz;genesis_body_apply_impulse(i,ix,iy,iz);buoyancyImpulse+=absi(buoy);dragImpulse+=absi(jdx)+absi(jdy)+absi(jdz);pressureImpulse+=absi(jpx)+absi(jpy)+absi(jpz);dragX+=jdx;dragY+=jdy;dragZ+=jdz;pressureX+=jpx;pressureY+=jpy;pressureZ+=jpz;netX+=ix;netY+=iy;netZ+=iz;}void apply(){reset();for(int i=0;i<genesis_body_node_count();i++)apply_node(i);}}
extern "C" {EXPORT("genesis_hydro_apply") void genesis_hydro_apply(){hydro1::apply();}EXPORT("genesis_hydro_submerged_nodes") uint32_t genesis_hydro_submerged_nodes(){return hydro1::submergedNodes;}EXPORT("genesis_hydro_submerged_samples") uint32_t genesis_hydro_submerged_samples(){return hydro1::submergedSamples;}EXPORT("genesis_hydro_buoyancy_impulse") uint32_t genesis_hydro_buoyancy_impulse(){return(uint32_t)hydro1::buoyancyImpulse;}EXPORT("genesis_hydro_drag_impulse") uint32_t genesis_hydro_drag_impulse(){return(uint32_t)hydro1::dragImpulse;}EXPORT("genesis_hydro_pressure_impulse") uint32_t genesis_hydro_pressure_impulse(){return(uint32_t)hydro1::pressureImpulse;}EXPORT("genesis_hydro_drag_x") int32_t genesis_hydro_drag_x(){return hydro1::dragX;}EXPORT("genesis_hydro_drag_y") int32_t genesis_hydro_drag_y(){return hydro1::dragY;}EXPORT("genesis_hydro_drag_z") int32_t genesis_hydro_drag_z(){return hydro1::dragZ;}EXPORT("genesis_hydro_pressure_x") int32_t genesis_hydro_pressure_x(){return hydro1::pressureX;}EXPORT("genesis_hydro_pressure_y") int32_t genesis_hydro_pressure_y(){return hydro1::pressureY;}EXPORT("genesis_hydro_pressure_z") int32_t genesis_hydro_pressure_z(){return hydro1::pressureZ;}EXPORT("genesis_hydro_net_x") int32_t genesis_hydro_net_x(){return hydro1::netX;}EXPORT("genesis_hydro_net_y") int32_t genesis_hydro_net_y(){return hydro1::netY;}EXPORT("genesis_hydro_net_z") int32_t genesis_hydro_net_z(){return hydro1::netZ;}EXPORT("genesis_hydro_model_version") uint32_t genesis_hydro_model_version(){return 0x00010001u;}}
