(() => {
  'use strict';
  const assets = ['./index.html','./style.css?v=6','./science-v7.css?v=7','./debug-v7.js?v=7','./science-game-v7.js?v=7','./science-sim-v7.js?v=7','./sw.js?v=7'];
  const state = { build: '7.0.0', errors: [], tests: [], online: navigator.onLine, tier: null };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const capture = (kind, value) => { state.errors.push({ time: new Date().toISOString(), kind, message: String(value?.message || value), stack: value?.stack || null }); state.errors = state.errors.slice(-16); render(); };
  addEventListener('error', e => capture('error', e.error || e.message));
  addEventListener('unhandledrejection', e => capture('promise', e.reason));
  addEventListener('online', () => { state.online = true; render(); });
  addEventListener('offline', () => { state.online = false; render(); });
  const style = document.createElement('style');
  style.textContent = `#fwDebugButton{position:fixed;right:max(10px,env(safe-area-inset-right));bottom:max(10px,env(safe-area-inset-bottom));z-index:9900;border:1px solid #7fffe055;border-radius:999px;padding:9px 12px;background:#06131de8;color:#c7fff0;font:900 10px system-ui;letter-spacing:.09em;box-shadow:0 0 24px #45ffd533}#fwDebugPanel{position:fixed;inset:0;z-index:9998;display:none;place-items:center;padding:16px;background:#01050bed;color:#eafffa;font:13px system-ui;overflow:auto}#fwDebugPanel.open{display:grid}#fwDebugCard{width:min(680px,100%);max-height:92vh;overflow:auto;border:1px solid #64f8d844;border-radius:24px;background:linear-gradient(145deg,#091722,#03070d);padding:20px;box-shadow:0 30px 90px #000,0 0 60px #3cf4d322}#fwDebugCard h2{margin:0 0 4px}.fwRows{display:grid;gap:7px}.fwRow{display:grid;grid-template-columns:1fr auto;gap:10px;padding:9px 10px;border-radius:12px;background:#0a1822}.fwOk{color:#70ffd5}.fwBad{color:#ff7793}.fwWait{color:#ffd66e}.fwButtons{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:14px}.fwButtons button{min-height:44px;border:0;border-radius:14px;background:#132431;color:#eafffa;font-weight:850}.fwButtons .accent{background:#70ffd5;color:#03110c}.fwClose{float:right;border:0;background:transparent;color:#fff;font-size:24px}#fwDebugLog{white-space:pre-wrap;word-break:break-word;background:#02070b;border:1px solid #20333d;border-radius:14px;padding:12px;color:#b9d9e5;max-height:220px;overflow:auto}`;
  document.head.append(style);
  const button = document.createElement('button'); button.id = 'fwDebugButton'; button.textContent = '⚙ DEBUG';
  const panel = document.createElement('section'); panel.id = 'fwDebugPanel';
  panel.innerHTML = `<article id="fwDebugCard"><button class="fwClose">×</button><h2>Fracture Science Debug</h2><p>Build 7 · direct files · adaptive device profile</p><div id="fwDebugSummary"></div><div class="fwButtons"><button id="fwTest" class="accent">TEST NETWORK</button><button id="fwCopy">COPY AI REPORT</button><button id="fwRepair">FIX CACHE + RELOAD</button><button id="fwSafe">SAFE GRAPHICS</button></div><pre id="fwDebugLog">No runtime errors captured.</pre></article>`;
  document.addEventListener('DOMContentLoaded', () => { document.body.append(button, panel); bind(); runTests(); }, { once: true });
  function bind() {
    button.onclick = () => panel.classList.add('open'); panel.querySelector('.fwClose').onclick = () => panel.classList.remove('open'); panel.onclick = e => { if (e.target === panel) panel.classList.remove('open'); };
    panel.querySelector('#fwTest').onclick = runTests; panel.querySelector('#fwCopy').onclick = copyReport; panel.querySelector('#fwRepair').onclick = repair;
    panel.querySelector('#fwSafe').onclick = () => { localStorage.setItem('fw_quality_v7', 'low'); localStorage.setItem('fw_safe', '1'); location.reload(); };
  }
  async function testAsset(url) { const start = performance.now(); try { const response = await fetch(url, { cache: 'no-store' }); if (response.body) response.body.cancel().catch(() => {}); return { url, ok: response.ok, status: response.status, ms: Math.round(performance.now() - start) }; } catch (error) { return { url, ok: false, status: 0, ms: Math.round(performance.now() - start), error: String(error.message || error) }; } }
  async function runTests() { state.tests = assets.map(url => ({ url, pending: true })); render(); state.tests = await Promise.all(assets.map(testAsset)); render(); }
  async function serviceWorkerInfo() { const reg = await navigator.serviceWorker?.getRegistration?.(); return { supported: 'serviceWorker' in navigator, controller: !!navigator.serviceWorker?.controller, scope: reg?.scope || null, active: reg?.active?.state || null }; }
  async function report() { const connection = navigator.connection || {}; return { ...state, url: location.href, userAgent: navigator.userAgent, visibility: document.visibilityState, connection: { effectiveType: connection.effectiveType || null, downlink: connection.downlink || null, rtt: connection.rtt || null, saveData: connection.saveData || false }, serviceWorker: await serviceWorkerInfo(), memory: navigator.deviceMemory || null, cores: navigator.hardwareConcurrency || null, dpr: devicePixelRatio || 1, viewport: { width: innerWidth, height: innerHeight } }; }
  async function copyReport() { const text = JSON.stringify(await report(), null, 2); try { await navigator.clipboard.writeText(text); button.textContent = '✓ COPIED'; setTimeout(() => button.textContent = '⚙ DEBUG', 1400); } catch { prompt('Copy this report', text); } }
  async function repair() { const names = await caches.keys(); await Promise.all(names.map(name => caches.delete(name))); const regs = await navigator.serviceWorker?.getRegistrations?.() || []; await Promise.all(regs.map(reg => reg.unregister())); location.replace(`${location.pathname}?v=7&fresh=${Date.now()}`); }
  function render() { const summary = panel.querySelector?.('#fwDebugSummary'), log = panel.querySelector?.('#fwDebugLog'); if (!summary || !log) return; const rows = [`<div class="fwRow"><span>Network</span><b class="${state.online?'fwOk':'fwBad'}">${state.online?'ONLINE':'OFFLINE'}</b></div>`, ...state.tests.map(t => `<div class="fwRow"><span>${esc(t.url)}</span><b class="${t.pending?'fwWait':t.ok?'fwOk':'fwBad'}">${t.pending?'TESTING':t.ok?`${t.status} · ${t.ms}ms`:`FAIL ${t.status || ''}`}</b></div>`)].join(''); summary.innerHTML = `<div class="fwRows">${rows}</div>`; log.textContent = state.errors.length ? JSON.stringify(state.errors, null, 2) : 'No runtime errors captured.'; }
  window.__FW_DEBUG__ = { state, runTests, report, repair };
})();
