import { World } from './organism-world-v8.js?v=8';
import { Renderer, QUALITY } from './organism-render-v8.js?v=8';
import { clamp } from './organism-core-v8.js?v=8';

const $=id=>document.getElementById(id),canvas=$('game');
const capability=(()=>{const memory=navigator.deviceMemory||4,cores=navigator.hardwareConcurrency||4,pixels=Math.max(screen.width,innerWidth)*Math.max(screen.height,innerHeight)*(devicePixelRatio||1),reduced=matchMedia?.('(prefers-reduced-motion: reduce)').matches||false;let tier='medium';if(memory<=2||cores<=3||pixels<650000||reduced)tier='low';else if(memory>=8&&cores>=8&&pixels>2200000)tier='ultra';else if(memory>=6&&cores>=6)tier='high';return{memory,cores,pixels,reduced,tier};})();
let preference=localStorage.getItem('fw_quality_v8')||'auto',tier=preference==='auto'?capability.tier:preference;if(!QUALITY[tier])tier=capability.tier;
let world=new World((Date.now()^0x8f31c7)>>>0,{performanceTier:tier}),renderer=new Renderer(canvas,world,tier);
let last=performance.now(),accumulator=0,fps=60,uiClock=0,adaptiveClock=0,stableClock=0,deferredInstall=null;
const keys=new Set(),control={x:0,y:0,jump:false,grab:false,bite:false,dash:false,scan:false},touch={stickId:null,stickX:0,stickY:0,jump:false,grab:false,bite:false,dash:false,scan:false};
const ui={cycle:$('cycle'),food:$('food'),health:$('health'),energy:$('energy'),stamina:$('stamina'),hydration:$('hydration'),rain:$('rain'),room:$('room'),points:$('points'),bucks:$('bucks'),research:$('research'),species:$('species'),plants:$('plants'),biomass:$('biomass'),moisture:$('moisture'),day:$('day'),mission:$('mission'),missionProgress:$('missionProgress'),samples:$('samples'),oxygen:$('oxygen'),toxin:$('toxin'),population:$('population'),fps:$('fps'),quality:$('qualityLabel'),message:$('message'),pause:$('pausePanel'),death:$('deathPanel'),intro:$('introPanel'),evolution:$('evolutionPanel'),evolutionChoices:$('evolutionChoices')};

class AudioCore{
  constructor(){this.ctx=null;this.master=null;this.enabled=localStorage.getItem('fw_sound')!=='off';}
  start(){if(!this.enabled||this.ctx)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=.08;this.master.connect(this.ctx.destination);const o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type='sine';o.frequency.value=38;f.type='lowpass';f.frequency.value=130;g.gain.value=.055;o.connect(f).connect(g).connect(this.master);o.start();this.amb={o,g,f};}
  tone(freq=180,duration=.08,volume=.08,type='sine'){if(!this.ctx||!this.enabled)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+duration);o.connect(g).connect(this.master);o.start();o.stop(this.ctx.currentTime+duration);}
  update(){if(!this.amb)return;const target=34+world.rainIntensity*30+world.ecology.toxin*14+world.daylight*8;this.amb.o.frequency.setTargetAtTime(target,this.ctx.currentTime,.5);this.amb.f.frequency.setTargetAtTime(100+world.daylight*120+world.plants.totalBiomass()*.12,this.ctx.currentTime,.8);}
}
const audio=new AudioCore();

function readControls(){let x=touch.stickX,y=touch.stickY;if(keys.has('ArrowLeft')||keys.has('KeyA'))x-=1;if(keys.has('ArrowRight')||keys.has('KeyD'))x+=1;if(keys.has('ArrowUp')||keys.has('KeyW'))y-=1;if(keys.has('ArrowDown')||keys.has('KeyS'))y+=1;control.x=clamp(x,-1,1);control.y=clamp(y,-1,1);control.jump=touch.jump||keys.has('Space')||keys.has('KeyW')||keys.has('ArrowUp');control.grab=touch.grab||keys.has('ShiftLeft')||keys.has('KeyE');control.bite=touch.bite||keys.has('KeyF')||keys.has('KeyK');control.dash=touch.dash||keys.has('ControlLeft')||keys.has('KeyL');control.scan=touch.scan||keys.has('KeyQ')||keys.has('KeyR');return control;}
addEventListener('keydown',e=>{keys.add(e.code);if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'||e.code==='KeyP')togglePause();});addEventListener('keyup',e=>keys.delete(e.code));
function bindHold(id,field,freq){const el=$(id);if(!el)return;const down=e=>{e.preventDefault();audio.start();touch[field]=true;el.classList.add('pressed');el.setPointerCapture?.(e.pointerId);audio.tone(freq,.045,.045);},up=e=>{e.preventDefault();touch[field]=false;el.classList.remove('pressed');};el.addEventListener('pointerdown',down);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);el.addEventListener('lostpointercapture',up);}
bindHold('jumpBtn','jump',250);bindHold('grabBtn','grab',105);bindHold('biteBtn','bite',68);bindHold('dashBtn','dash',145);bindHold('scanBtn','scan',520);
const stick=$('stick'),knob=$('stickKnob');
function moveStick(e){if(touch.stickId!==e.pointerId)return;const r=stick.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),max=r.width*.31,len=Math.hypot(dx,dy)||1,s=Math.min(1,max/len),px=dx*s,py=dy*s;touch.stickX=clamp(px/max,-1,1);touch.stickY=clamp(py/max,-1,1);knob.style.transform=`translate(${px}px,${py}px)`;}
stick.addEventListener('pointerdown',e=>{e.preventDefault();audio.start();touch.stickId=e.pointerId;stick.setPointerCapture(e.pointerId);moveStick(e);});stick.addEventListener('pointermove',moveStick);function endStick(e){if(touch.stickId!==e.pointerId)return;touch.stickId=null;touch.stickX=touch.stickY=0;knob.style.transform='translate(0,0)';}stick.addEventListener('pointerup',endStick);stick.addEventListener('pointercancel',endStick);

function togglePause(force){const next=typeof force==='boolean'?force:!world.paused;if(world.pendingEvolution&&!next)return;world.paused=next;ui.pause?.classList.toggle('show',next&&!world.pendingEvolution);audio.tone(next?85:170,.08,.05);}
$('pauseBtn').onclick=()=>togglePause();$('resumeBtn').onclick=()=>togglePause(false);$('restartBtn').onclick=()=>{world=new World((Date.now()^0x8a13d)>>>0,{performanceTier:tier});renderer.setWorld(world);togglePause(false);};$('respawnBtn').onclick=()=>{world.respawn();ui.death?.classList.remove('show');renderer.camera.x=world.player.x;renderer.camera.y=world.player.y;};$('playBtn').onclick=()=>{audio.start();ui.intro?.classList.remove('show');};$('howBtn').onclick=()=>$('howPanel')?.classList.toggle('show');
function setTier(next,announce=false){if(!QUALITY[next])next='medium';tier=next;world.setPerformanceTier(next);renderer.setTier(next);if(ui.quality)ui.quality.textContent=`${preference.toUpperCase()} · ${next.toUpperCase()}`;if(announce)world.toast(`Adaptive organism renderer: ${next.toUpperCase()} mode.`);}
$('qualityBtn').onclick=()=>{preference=preference==='auto'?'ultra':preference==='ultra'?'high':preference==='high'?'medium':preference==='medium'?'low':'auto';localStorage.setItem('fw_quality_v8',preference);setTier(preference==='auto'?capability.tier:preference,true);};
addEventListener('resize',()=>renderer.resize(),{passive:true});
addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn')?.classList.add('ready');});$('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;}else world.toast('iPhone: Safari Share → Add to Home Screen.');};

function createRating(){const stars=$('stars'),saved=Number(localStorage.getItem('fw_rating')||0),choice=localStorage.getItem('fw_choice')||'';if(stars&&!stars.children.length)for(let i=1;i<=10;i++){const b=document.createElement('button');b.textContent='★';b.classList.toggle('on',i<=saved);b.onclick=()=>{localStorage.setItem('fw_rating',String(i));[...stars.children].forEach((x,n)=>x.classList.toggle('on',n<i));$('ratingText').textContent=`${i}/10`;};stars.append(b);}if(saved&&$('ratingText'))$('ratingText').textContent=`${saved}/10`;document.querySelectorAll('[data-feedback]').forEach(b=>{b.classList.toggle('selected',b.dataset.feedback===choice);b.onclick=()=>{localStorage.setItem('fw_choice',b.dataset.feedback);document.querySelectorAll('[data-feedback]').forEach(x=>x.classList.toggle('selected',x===b));};});}createRating();

function showEvolution(){if(!world.pendingEvolution){ui.evolution?.classList.remove('show');return;}if(ui.evolution?.classList.contains('show'))return;ui.evolutionChoices.innerHTML='';for(const option of world.pendingEvolution){const b=document.createElement('button');b.className='evolution-choice';b.innerHTML=`<strong>${option.title}</strong><small>${option.text}</small>`;b.onclick=()=>{world.applyEvolution(option.id);ui.evolution.classList.remove('show');audio.tone(420,.22,.1,'triangle');};ui.evolutionChoices.append(b);}ui.evolution.classList.add('show');}
function updateUI(){const p=world.player,s=world.stats();if(!p)return;ui.cycle.textContent=`CYCLE ${s.cycle}`;ui.food.textContent=`${p.food}/4`;ui.health.style.width=`${clamp(p.health,0,1)*100}%`;ui.energy.style.width=`${clamp(p.energy,0,1)*100}%`;if(ui.stamina)ui.stamina.style.width=`${clamp(p.stamina,0,1)*100}%`;if(ui.hydration)ui.hydration.style.width=`${clamp(p.hydration,0,1)*100}%`;ui.rain.textContent=s.rainPhase==='clear'?`FRACTURE ${Math.ceil(s.rainRemaining)}s`:s.rainPhase==='warning'?`WARNING ${Math.ceil(s.rainRemaining)}s`:`RAIN ${Math.ceil(s.rainRemaining)}s`;ui.rain.classList.toggle('danger',s.rainPhase!=='clear');ui.room.textContent=s.biome;ui.points.textContent=s.points;ui.bucks.textContent=s.bucks;ui.research.textContent=s.research;ui.species.textContent=s.species;ui.population.textContent=s.population;ui.samples.textContent=s.samples;if(ui.plants)ui.plants.textContent=s.plants;if(ui.biomass)ui.biomass.textContent=Math.round(s.biomass);if(ui.moisture)ui.moisture.textContent=`${Math.round(s.soilMoisture*100)}%`;if(ui.day)ui.day.textContent=`${s.day}`;ui.oxygen.style.width=`${clamp(s.ecology.oxygen,0,1)*100}%`;ui.toxin.style.width=`${clamp(s.ecology.toxin,0,1)*100}%`;ui.mission.textContent=s.mission.title;ui.missionProgress.textContent=`${Math.min(s.mission.progress,s.mission.target)}/${s.mission.target} · ${s.mission.text}`;ui.fps.textContent=Math.round(fps);ui.quality.textContent=`${preference.toUpperCase()} · ${tier.toUpperCase()}`;ui.message.textContent=world.message;ui.message.classList.toggle('show',world.messageTime>0);ui.death.classList.toggle('show',world.gameOver);showEvolution();}

function adaptiveQuality(dt){if(preference!=='auto')return;adaptiveClock+=dt;if(fps<43){stableClock=0;if(adaptiveClock>4){adaptiveClock=0;const next=tier==='ultra'?'high':tier==='high'?'medium':tier==='medium'?'low':'low';if(next!==tier){setTier(next);world.toast('Graphics reduced to protect organism simulation speed.');}}}else if(fps>57){stableClock+=dt;if(stableClock>18){stableClock=0;const ceiling=capability.tier,next=tier==='low'?'medium':tier==='medium'&&(ceiling==='high'||ceiling==='ultra')?'high':tier==='high'&&ceiling==='ultra'?'ultra':tier;if(next!==tier)setTier(next);}}else stableClock=Math.max(0,stableClock-dt*.4);}

function loop(now){const dt=Math.min(.1,(now-last)/1000);last=now;fps=fps*.93+(dt?1/dt:60)*.07;accumulator+=dt;const input=readControls();let guard=0;while(accumulator>=1/60&&guard++<5){world.step(1/60,input);accumulator-=1/60;}renderer.render(now,dt);audio.update();uiClock+=dt;if(uiClock>.12){uiClock=0;updateUI();}adaptiveQuality(dt);requestAnimationFrame(loop);}
addEventListener('visibilitychange',()=>{if(document.hidden){world.paused=true;ui.pause?.classList.add('show');}});setTier(tier);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=8',{updateViaCache:'none'}).catch(()=>{});requestAnimationFrame(loop);
