'use strict';
/* GENESIS creature/world rig overhaul.
   Improves the existing sandbox without replacing its simulation. */
(function(){
  if(typeof drawCreature!=='function'||typeof worldToScreen!=='function'||typeof Node!=='function')return;
  const BASE_CREATURE=drawCreature,BASE_TERRAIN=typeof drawTerrain==='function'?drawTerrain:null,BASE_UI=typeof updateUI==='function'?updateUI:null,BASE_STEP=typeof stepCreature==='function'?stepCreature:null;
  const EPS=1e-6;
  const PROFILE={
    crab:{headW:9.8,headH:6.6,snout:2.2,jawF:1.8,jawD:5.1,open:3.1,eyeF:1.1,eyeU:5.8,limb:1.18,mouth:'mandible'},
    bug:{headW:8.5,headH:6.8,snout:4.8,jawF:5.2,jawD:3.5,open:4.1,eyeF:3,eyeU:2.6,limb:.95,mouth:'mandible'},
    silkborn:{headW:9.2,headH:8.3,snout:3.6,jawF:4,jawD:4,open:3.2,eyeF:2.2,eyeU:2,limb:.92,mouth:'chelicerae'},
    mirekin:{headW:8.2,headH:8.8,snout:4,jawF:4.5,jawD:4.3,open:4,eyeF:2.4,eyeU:2.1,limb:1.02,mouth:'jaw'},
    scavenger:{headW:8.8,headH:7.8,snout:5,jawF:5.4,jawD:3.9,open:3.8,eyeF:3,eyeU:1.8,limb:1,mouth:'jaw'},
    reedscale:{headW:10.5,headH:6.8,snout:8,jawF:8,jawD:3.2,open:4.3,eyeF:4.1,eyeU:2.2,limb:1.04,mouth:'longjaw'},
    hunter:{headW:10.8,headH:7,snout:9,jawF:8.8,jawD:3.5,open:4.8,eyeF:4.3,eyeU:2.2,limb:1.08,mouth:'longjaw'},
    grazer:{headW:10.2,headH:7.5,snout:7.1,jawF:7.2,jawD:3.5,open:3.4,eyeF:3.5,eyeU:2.5,limb:1.08,mouth:'muzzle'},
    climber:{headW:9,headH:7.2,snout:6.1,jawF:6.4,jawD:3.5,open:3.7,eyeF:3.2,eyeU:2.2,limb:.98,mouth:'muzzle'},
    amphib:{headW:9.6,headH:6.6,snout:6.8,jawF:6.8,jawD:3.6,open:4,eyeF:3.5,eyeU:3,limb:1.02,mouth:'wide'},
    burrower:{headW:10,headH:8.4,snout:4.8,jawF:4.9,jawD:4.6,open:3,eyeF:2,eyeU:1.6,limb:1,mouth:'blunt'},
    winged:{headW:7.3,headH:6.2,snout:7.3,jawF:7,jawD:2.1,open:2.4,eyeF:2.9,eyeU:2,limb:.76,mouth:'beak'},
    melt:{headW:10.6,headH:7.5,snout:4.4,jawF:4.6,jawD:4.8,open:3.7,eyeF:2.5,eyeU:1.9,limb:.92,mouth:'slit'},
    bone:{headW:9.6,headH:7.3,snout:6.1,jawF:6,jawD:3.5,open:5,eyeF:3.2,eyeU:1.8,limb:.9,mouth:'skull'},
    default:{headW:9,headH:7,snout:5.5,jawF:5.7,jawD:3.7,open:3.8,eyeF:3,eyeU:2.1,limb:1,mouth:'jaw'}
  };
  const profileFor=c=>PROFILE[c?.spec?.family]||PROFILE.default;
  function norm(x,y,fx=1,fy=0){const d=Math.hypot(x,y);return d<EPS?{x:fx,y:fy}:{x:x/d,y:y/d}}
  function headFrame(c){const h=c?.head?.()||c?.nodes?.[0]||{x:0,y:0},face=c?.face||1,n=c?.nodes?.[1]||{x:h.x-face,y:h.y};let r=norm(h.x-n.x,h.y-n.y,face,0);if(r.x*face<0){r.x*=-1;r.y*=-1}let f=norm(face*.48+r.x*.52,r.y*.52,face,0);if(f.x*face<.18)f=norm(face*.82,f.y*.35,face,0);let d={x:-f.y,y:f.x};if(d.y<0){d.x*=-1;d.y*=-1}return{hx:h.x,hy:h.y,fx:f.x,fy:f.y,dx:d.x,dy:d.y,face}}
  function mouthPose(c,gapeOverride=null){const p=profileFor(c),fr=headFrame(c),s=c?.g?.size||1,g=Math.max(0,Math.min(1,gapeOverride??c?.v107?.gape??0));return{frame:fr,profile:p,gape:g,snout:{x:fr.hx+fr.fx*p.snout*s+fr.dx*.35*s,y:fr.hy+fr.fy*p.snout*s+fr.dy*.35*s},jaw:{x:fr.hx+fr.fx*p.jawF*s+fr.dx*(p.jawD+g*p.open)*s,y:fr.hy+fr.fy*p.jawF*s+fr.dy*(p.jawD+g*p.open)*s},tongue:{x:fr.hx+fr.fx*(p.jawF+1.8+g*3)*s+fr.dx*(p.jawD*.78+g*p.open*.55)*s,y:fr.hy+fr.fy*(p.jawF+1.8+g*3)*s+fr.dy*(p.jawD*.78+g*p.open*.55)*s}}}
  function ensureRig(c){if(!c||!c.nodes?.length)return null;if(!c._rigOverhaul){const p=mouthPose(c,0);c._rigOverhaul={snout:Node(p.snout.x,p.snout.y,Math.max(1.3,2.2*(c.g?.size||1)),.22),frame:p.frame}}return c._rigOverhaul}
  function stepRig(c){const r=ensureRig(c);if(!r)return;const p=mouthPose(c),s=c.g?.size||1,h=c.head();r.frame=p.frame;integrateNode(r.snout,c.alive?.08:.34,.92);r.snout.x=lerp(r.snout.x,p.snout.x,.62);r.snout.y=lerp(r.snout.y,p.snout.y,.62);constrain(h,r.snout,Math.max(2,p.profile.snout*s),.58);if(c.v107){const j=c.v107.jaw,t=c.v107.tongue;j.x=lerp(j.x,p.jaw.x,.74);j.y=lerp(j.y,p.jaw.y,.74);t.x=lerp(t.x,p.tongue.x,.66);t.y=lerp(t.y,p.tongue.y,.66);constrain(h,j,Math.hypot(p.jaw.x-h.x,p.jaw.y-h.y),.48);constrain(h,t,Math.hypot(p.tongue.x-h.x,p.tongue.y-h.y),.42)}}
  if(BASE_STEP)stepCreature=function(c){BASE_STEP(c);stepRig(c)};
  const W=n=>worldToScreen(n.x,n.y),Z=()=>camera.zoom;
  function rgb(h){h=(h||'#718b72').replace('#','');if(h.length===3)h=h.split('').map(x=>x+x).join('');return[parseInt(h.slice(0,2),16)||0,parseInt(h.slice(2,4),16)||0,parseInt(h.slice(4,6),16)||0]}
  function mix(a,b,t){const A=rgb(a),B=rgb(b);return`rgb(${Math.round(lerp(A[0],B[0],t))},${Math.round(lerp(A[1],B[1],t))},${Math.round(lerp(A[2],B[2],t))})`}
  function drawLimb(c,l){if(l.disabled)return;const A=W(c.nodes[l.anchor]),H=W(l.hand),zz=Z(),s=(c.g?.size||1)*zz,p=profileFor(c),dx=H.x-A.x,dy=H.y-A.y,dd=Math.hypot(dx,dy)||1,nx=-dy/dd,ny=dx/dd,b=l.side*(l.arm?-.28:.30)*Math.min(dd,24*s),K={x:lerp(A.x,H.x,l.arm?.45:.52)+nx*b,y:lerp(A.y,H.y,l.arm?.45:.52)+ny*b},bw=(l.arm?4.5:3.6)*s*p.limb,mw=bw*.62;X.lineCap='round';X.lineJoin='round';X.strokeStyle='rgba(2,5,4,.88)';X.lineWidth=bw+2.2*zz;X.beginPath();X.moveTo(A.x,A.y);X.lineTo(K.x,K.y);X.lineTo(H.x,H.y);X.stroke();X.strokeStyle=c.alive?(c.spec?.color||'#708070'):'#575854';X.lineWidth=bw;X.beginPath();X.moveTo(A.x,A.y);X.lineTo(K.x,K.y);X.stroke();X.lineWidth=mw;X.beginPath();X.moveTo(K.x,K.y);X.lineTo(H.x,H.y);X.stroke();X.strokeStyle='rgba(229,250,235,.20)';X.lineWidth=Math.max(.6,bw*.16);X.beginPath();X.moveTo(A.x-ny*bw*.15,A.y+nx*bw*.15);X.lineTo(K.x-ny*bw*.12,K.y+nx*bw*.12);X.stroke();X.fillStyle=c.alive?(c.spec?.hi||'#b8c8b1'):'#696a66';X.beginPath();X.arc(K.x,K.y,Math.max(1.2,bw*.53),0,TAU);X.fill();if(l.arm&&['crab','bug','silkborn'].includes(c.spec?.family)){X.save();X.translate(H.x,H.y);X.rotate(Math.atan2(dy,dx));X.fillStyle=c.spec?.hi||'#b5c6ad';X.beginPath();X.ellipse(1.2*s,0,4.8*s,2.8*s,0,0,TAU);X.fill();X.strokeStyle='rgba(17,22,19,.92)';X.lineWidth=Math.max(.7,.8*zz);X.beginPath();X.moveTo(1.8*s,0);X.lineTo(6*s,-2.4*s);X.moveTo(1.8*s,0);X.lineTo(6*s,2.2*s);X.stroke();X.restore()}}
  function thick(c,i){const n=Math.max(1,c.nodes.length-1),u=i/n,f=c.spec?.family,s=c.g?.size||1;if(f==='mirekin'||f==='scavenger')return(7.2-1.8*u)*s;if(f==='reedscale'||f==='hunter'||f==='grazer')return(8.8-1.5*u)*s;if(f==='silkborn')return(8.5+3*Math.sin(u*Math.PI))*s;if(f==='burrower')return(8.5-2*u)*s;if(f==='crab')return 9.5*s;if(f==='bug')return 7.3*s;if(f==='melt')return 8.8*s;return(7.6-1.2*u)*s}
  function drawBody(c){if(!c.nodes?.length)return;const pts=c.nodes.map(W),zz=Z(),wet=Math.max(0,Math.min(1,c._oldSimWet||0)),fam=c.spec?.family||'',col=c.alive?(c.spec?.color||'#71806f'):'#52534f',hi=c.alive?(c.spec?.hi||'#aebda9'):'#6b6b66';X.lineCap='round';X.lineJoin='round';X.strokeStyle='rgba(2,5,4,.92)';X.lineWidth=Math.max(6,thick(c,0)*2.15*zz);X.beginPath();X.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)X.lineTo(pts[i].x,pts[i].y);X.stroke();for(let i=pts.length-1;i>=0;i--){const q=pts[i],r=thick(c,i)*zz,g=X.createRadialGradient(q.x-r*.35,q.y-r*.48,Math.max(1,r*.1),q.x,q.y,r*1.18);g.addColorStop(0,mix(hi,'#ffffff',wet*.18));g.addColorStop(.34,hi);g.addColorStop(.62,col);g.addColorStop(1,mix(col,'#07100d',.62));X.fillStyle=g;let rx=r*1.15,ry=r*.83;if(fam==='crab'){rx=r*1.55;ry=r*.72}else if(fam==='silkborn'){rx=r*1.28;ry=r*.92}else if(fam==='mirekin'||fam==='scavenger'){rx=r*.93;ry=r*1.18}else if(['reedscale','hunter','grazer'].includes(fam)){rx=r*1.35;ry=r*.78}X.beginPath();X.ellipse(q.x,q.y,rx,ry,0,0,TAU);X.fill();X.strokeStyle='rgba(222,247,232,.14)';X.lineWidth=Math.max(.55,.75*zz);X.stroke();if(['crab','bug','bone','reedscale'].includes(fam)){X.strokeStyle='rgba(4,7,6,.34)';X.lineWidth=Math.max(.6,.8*zz);X.beginPath();X.arc(q.x,q.y,Math.max(2,r*.58),-.9,.9);X.stroke()}}if(wet>.08){X.globalCompositeOperation='screen';X.strokeStyle=`rgba(210,246,235,${.04+wet*.11})`;X.lineWidth=Math.max(.7,1.2*zz);X.beginPath();for(let i=0;i<pts.length;i++){const q=pts[i],yy=q.y-thick(c,i)*zz*.48;if(i===0)X.moveTo(q.x,yy);else X.lineTo(q.x,yy)}X.stroke();X.globalCompositeOperation='source-over'}}
  function drawTail(c){if(!c.tail?.length)return;const pts=[c.nodes[c.nodes.length-1],...c.tail],zz=Z(),col=c.alive?(c.spec?.color||'#71806f'):'#555';X.lineCap='round';for(let i=0;i<pts.length-1;i++){const a=W(pts[i]),b=W(pts[i+1]),w=Math.max(1.1,(4.6-i*.42)*(c.g?.size||1)*zz);X.strokeStyle='rgba(3,6,5,.9)';X.lineWidth=w+1.8*zz;X.beginPath();X.moveTo(a.x,a.y);X.lineTo(b.x,b.y);X.stroke();X.strokeStyle=col;X.lineWidth=w;X.stroke()}}
  function drawHead(c){const p=mouthPose(c),fr=p.frame,pr=p.profile,zz=Z(),s=(c.g?.size||1)*zz,H=worldToScreen(fr.hx,fr.hy),a=Math.atan2(fr.fy,fr.fx),fam=c.spec?.family||'',wet=Math.max(0,Math.min(1,c._oldSimWet||0)),col=c.alive?(c.spec?.color||'#71806f'):'#555651',hi=c.alive?(c.spec?.hi||'#b5c2ac'):'#72736d';X.save();X.translate(H.x,H.y);X.rotate(a);const hg=X.createLinearGradient(0,-pr.headH*s,0,pr.headH*s);hg.addColorStop(0,mix(hi,'#ffffff',wet*.15));hg.addColorStop(.42,hi);hg.addColorStop(1,mix(col,'#06100d',.58));X.fillStyle=hg;X.strokeStyle='rgba(4,8,7,.86)';X.lineWidth=Math.max(1,1.15*zz);if(fam==='crab'){X.beginPath();X.moveTo(-5*s,2*s);X.quadraticCurveTo(-1*s,-7*s,8*s,-5*s);X.quadraticCurveTo(11*s,0,7*s,5*s);X.quadraticCurveTo(0,8*s,-5*s,2*s);X.fill();X.stroke()}else if(fam==='bug'||fam==='silkborn'){X.beginPath();X.moveTo(-5*s,-4.7*s);X.lineTo(7*s,-5.6*s);X.lineTo(10*s,0);X.lineTo(5*s,6*s);X.lineTo(-5*s,4.7*s);X.closePath();X.fill();X.stroke()}else{X.beginPath();X.ellipse(0,0,pr.headW*s*.76,pr.headH*s*.73,0,0,TAU);X.fill();X.stroke();X.fillStyle=col;X.beginPath();X.ellipse(pr.snout*s*.56,1*s,Math.max(2.8,pr.snout*.58)*s,Math.max(2.5,pr.headH*.38)*s,0,0,TAU);X.fill();X.stroke()}const eyes=fam==='silkborn'?4:2;for(let i=0;i<eyes;i++){const row=eyes===4?(i<2?-1:1):0,side=eyes===4?(i%2?-1:1):(i?-1:1),ex=(pr.eyeF+(eyes===4?row*.9:0))*s,ey=(-pr.eyeU+side*(eyes===4?1.25:1.55))*s;X.fillStyle=fam==='melt'?'rgba(192,246,204,.78)':'#dce7d4';X.beginPath();X.ellipse(ex,ey,1.55*s,1.18*s,0,0,TAU);X.fill();X.fillStyle='#07100c';X.beginPath();X.arc(ex+.45*s,ey,.68*s,0,TAU);X.fill()}const g=p.gape,mx=pr.jawF*s,my=pr.jawD*s;if(pr.mouth==='beak'){X.fillStyle='#d1c69e';X.beginPath();X.moveTo(mx-1*s,my-1*s);X.lineTo((pr.snout+5)*s,my+.2*s);X.lineTo(mx-1*s,my+2.2*s);X.closePath();X.fill()}else{X.fillStyle=fam==='melt'?'#213b31':'#170b0d';X.beginPath();X.ellipse(mx,my+g*pr.open*s*.46,Math.max(2.8,pr.snout*.42)*s,(1.2+g*2.5)*s,.02,0,TAU);X.fill();if(pr.mouth==='mandible'||pr.mouth==='chelicerae'){X.strokeStyle=hi;X.lineWidth=Math.max(1,1.4*zz);X.lineCap='round';for(const side of[-1,1]){X.beginPath();X.moveTo((mx-1)*s,(my+side*.55)*s);X.quadraticCurveTo((mx+3)*s,(my+side*3.2)*s,(mx+5.8)*s,(my+side*1.1)*s);X.stroke()}}else if(fam!=='grazer'&&fam!=='melt'){X.fillStyle='#e0d7bb';const n=Math.max(2,Math.min(6,2+Math.floor((c.g?.size||1)*2)));for(let i=0;i<n;i++){const tx=(mx-pr.snout*.22+i*(pr.snout*.44/Math.max(1,n-1)))*s;X.beginPath();X.moveTo(tx,(my-1)*s);X.lineTo(tx+.65*s,(my+1.15+g*.5)*s);X.lineTo(tx+1.2*s,(my-.8)*s);X.closePath();X.fill()}}}X.globalCompositeOperation='screen';X.fillStyle=`rgba(224,250,237,${.045+wet*.11})`;X.beginPath();X.ellipse(-.5*s,-pr.headH*.33*s,pr.headW*.48*s,pr.headH*.16*s,-.08,0,TAU);X.fill();X.restore()}
  drawCreature=function(c,t){BASE_CREATURE(c,t);if(!c||c.gone)return;X.save();for(const l of c.limbs||[])drawLimb(c,l);drawTail(c);drawBody(c);drawHead(c);X.restore()};
  function matColor(m){if(typeof V104_MAT==='undefined')return'rgba(40,55,48,.7)';if(m===V104_MAT.ROCK)return'rgba(31,39,36,.78)';if(m===V104_MAT.DIRT)return'rgba(76,58,40,.72)';if(m===V104_MAT.MUD)return'rgba(49,48,35,.78)';if(m===V104_MAT.SAND)return'rgba(126,108,67,.62)';if(m===V104_MAT.OBSIDIAN)return'rgba(20,19,29,.84)';if(m===V104_MAT.ASH)return'rgba(72,69,65,.66)';return'rgba(30,38,34,.68)'}
  function drawRelief(){if(typeof v104VisibleMicroBounds!=='function'||typeof v104Get!=='function'||typeof v104SolidMat!=='function')return;const b=v104VisibleMicroBounds(4),step=Math.max(2,Math.floor(3/Math.max(.75,camera.zoom))),pts=[];for(let x=b.l;x<=b.r;x+=step){let sy=-1,m=0;for(let y=b.t;y<=b.b;y++){const mm=v104Get(x,y);if(v104SolidMat(mm)&&!v104SolidMat(v104Get(x,y-1))){sy=y;m=mm;break}}if(sy<0)continue;const p=worldToScreen((x+.5)*V104_CELL,sy*V104_CELL);pts.push({x:p.x,y:p.y,m,wx:x,wy:sy})}if(pts.length<2)return;const d=Math.max(5,11*camera.zoom);X.save();X.beginPath();X.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++){const a=pts[i-1],p=pts[i];X.quadraticCurveTo(a.x,a.y,(a.x+p.x)*.5,(a.y+p.y)*.5)}for(let i=pts.length-1;i>=0;i--)X.lineTo(pts[i].x,pts[i].y+d);X.closePath();X.fillStyle='rgba(2,7,6,.28)';X.fill();for(let i=1;i<pts.length;i++){const a=pts[i-1],p=pts[i];X.strokeStyle=matColor(p.m);X.lineWidth=Math.max(1.2,2.4*camera.zoom);X.beginPath();X.moveTo(a.x,a.y);X.lineTo(p.x,p.y);X.stroke()}X.restore()}
  if(BASE_TERRAIN)drawTerrain=function(t){BASE_TERRAIN(t);drawRelief()};
  if(BASE_UI)updateUI=function(){BASE_UI();if(stats&&!stats.innerHTML.includes('rig2'))stats.innerHTML+='<br><span class="dim">rig2 · head-local jaws · articulated surface pass</span>'};
  window.GENESIS_CREATURE_RIG={status:'implemented-source',headFrame,mouthPose,profileFor,note:'head-local jaw re-anchoring + procedural rendering over existing simulation; not a new biomechanics solver'};
})();