(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('sim'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true}),info=$('info'),selected=$('selected');
let worker=null,state=null,meta=null,surface=null,paused=false,speed=1,rainMode=0,last=performance.now(),fps=0,fc=0,ft=0,ready=false,wasmBytes=0,busy=false;
let cam={yaw:-.72,pitch:.58,zoom:8.7,targetYaw:-.72,targetPitch:.58,targetZoom:8.7,panX:0,panY:0,targetPanX:0,targetPanY:0};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function setStatus(t,ok=false){info.textContent=t;info.classList.toggle('good',ok);}
function fatal(t){ready=false;document.body.classList.add('blocked');setStatus('C++ WASM BLOCKED');selected.textContent=t;console.error(t);}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0);}
resize();addEventListener('resize',resize,{passive:true});
function rebuildSurface(){surface=globalThis.GENESIS_SURFACE?.build(state,meta)||null;}
function start(){setStatus('loading C++ → WebAssembly…');worker=new Worker('../volume3d/worker.js?v=native-active-1');worker.onerror=e=>fatal('Worker boot failed: '+(e.message||'unknown'));worker.onmessage=e=>{const m=e.data||{};if(m.type==='fatal'||m.type==='error'){fatal(m.message||'C++ worker failed');return;}if(m.type==='ready'){ready=true;wasmBytes=m.wasmBytes||0;setStatus('C++/WASM native kernel',true);return;}if(m.type==='state'){state=new Uint32Array(m.buffer);meta=m.meta;rebuildSurface();busy=false;document.body.classList.remove('blocked');if(!paused)queueStep();}};worker.postMessage({type:'init',w:40,h:28,d:40,seed:0x3d5a17,cohesion:72});}
function queueStep(){if(!worker||busy||paused||!ready)return;busy=true;worker.postMessage({type:'step',iterations:speed===4?4:speed===2?2:1});}
function proj(x,y,z){const cy=Math.cos(cam.yaw),sy=Math.sin(cam.yaw),cp=Math.cos(cam.pitch),sp=Math.sin(cam.pitch);const X=x-meta.w*.5,Z=z-meta.d*.5,Y=y-meta.h*.35,rx=X*cy-Z*sy,rz=X*sy+Z*cy,ry=Y*cp-rz*sp,depth=Y*sp+rz*cp,s=cam.zoom*(1+depth*.002);return{x:innerWidth*.5+cam.panX+rx*s,y:innerHeight*.48+cam.panY-ry*s,d:depth};}
function lambert(f){const lx=-.36,ly=.86,lz=-.36;return clamp(.28+.86*Math.max(0,f.nx*lx+f.ny*ly+f.nz*lz),.28,1.12);}
function terrainColor(f,l){if(f.mat===3){const v=Math.floor(67*l);return`rgb(${v},${Math.floor(76*l)},${Math.floor(79*l)})`;}const wet=clamp(f.wet/255,0,1),r=122-wet*40,g=86-wet*27,b=52-wet*15;return`rgb(${Math.floor(r*l)},${Math.floor(g*l)},${Math.floor(b*l)})`;}
function waterColor(f,l){const turb=clamp(f.sed/255,0,1);return`rgba(${Math.floor((22+62*turb)*l)},${Math.floor((116-24*turb)*l)},${Math.floor((164-58*turb)*l)},${(.55+.2*(1-turb)).toFixed(3)})`;}
function facePoints(f){return[proj(f.x,f.h00,f.z),proj(f.x+1,f.h10,f.z),proj(f.x+1,f.h11,f.z+1),proj(f.x,f.h01,f.z+1)];}
function drawFace(f,water=false){const p=facePoints(f),area=Math.abs((p[1].x-p[0].x)*(p[3].y-p[0].y)-(p[1].y-p[0].y)*(p[3].x-p[0].x));if(area<.15)return;ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<4;i++)ctx.lineTo(p[i].x,p[i].y);ctx.closePath();const l=lambert(f);ctx.fillStyle=water?waterColor(f,l):terrainColor(f,l);ctx.fill();if(water){ctx.strokeStyle='rgba(190,235,245,.16)';ctx.lineWidth=.5;ctx.stroke();}}
function render(){const w=innerWidth,h=innerHeight,g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#07131d');g.addColorStop(.55,'#0b1718');g.addColorStop(1,'#030807');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);if(!surface||!meta){ctx.fillStyle='#d8e8ea';ctx.font='700 13px ui-monospace,monospace';ctx.fillText('waiting for compiled C++ world state…',18,70);return;}const faces=[];for(const f of surface.terrain)faces.push({f,water:false,d:proj(f.x+.5,(f.h00+f.h10+f.h11+f.h01)*.25,f.z+.5).d});for(const f of surface.water)faces.push({f,water:true,d:proj(f.x+.5,(f.h00+f.h10+f.h11+f.h01)*.25,f.z+.5).d});faces.sort((a,b)=>a.d-b.d);ctx.lineJoin='round';ctx.lineCap='round';for(const q of faces)drawFace(q.f,q.water);ctx.globalCompositeOperation='screen';const glow=ctx.createRadialGradient(w*.54,h*.20,10,w*.54,h*.20,Math.max(w,h)*.66);glow.addColorStop(0,'rgba(150,202,180,.08)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='source-over';}
function telemetry(){if(!meta)return;const inv=meta.invariant?'PASS':'FAIL',tf=surface?.terrain.length||0,wf=surface?.water.length||0;info.innerHTML=`<b>C++/WASM</b> · ${meta.w}×${meta.h}×${meta.d} · ${(meta.w*meta.h*meta.d).toLocaleString()} cells · ${fps.toFixed(0)} fps`;selected.textContent=`step ${meta.step} · mesh ${tf}+${wf} faces · water ${meta.waterVoxels} · sand ${(meta.sandUnits/255).toFixed(0)} eq · erosion ${meta.erosion} · deposition ${meta.deposition} · invariant ${inv} · WASM ${(wasmBytes/1024).toFixed(1)} KB`;}
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;cam.yaw+=(cam.targetYaw-cam.yaw)*(1-Math.exp(-dt*12));cam.pitch+=(cam.targetPitch-cam.pitch)*(1-Math.exp(-dt*12));cam.zoom+=(cam.targetZoom-cam.zoom)*(1-Math.exp(-dt*12));cam.panX+=(cam.targetPanX-cam.panX)*(1-Math.exp(-dt*12));cam.panY+=(cam.targetPanY-cam.panY)*(1-Math.exp(-dt*12));render();fc++;ft+=dt;if(ft>.5){fps=fc/ft;fc=0;ft=0;telemetry();}if(!paused&&!busy)queueStep();requestAnimationFrame(loop);}
const pts=new Map();let gesture=null;canvas.addEventListener('pointerdown',e=>{e.preventDefault();pts.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture?.(e.pointerId);gesture=null;},{passive:false});canvas.addEventListener('pointermove',e=>{if(!pts.has(e.pointerId))return;e.preventDefault();const p=pts.get(e.pointerId),dx=e.clientX-p.x,dy=e.clientY-p.y;p.x=e.clientX;p.y=e.clientY;if(pts.size===1){cam.targetYaw+=dx*.009;cam.targetPitch=clamp(cam.targetPitch+dy*.007,.12,1.22);}else{const a=[...pts.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(gesture)cam.targetZoom=clamp(cam.targetZoom*d/gesture.d,3.5,20);gesture={d};}},{passive:false});for(const ev of['pointerup','pointercancel'])canvas.addEventListener(ev,e=>{pts.delete(e.pointerId);gesture=null;},{passive:true});
function button(id,fn){$(id)?.addEventListener('click',fn);}button('pause',()=>{paused=!paused;$('pause').textContent=paused?'▶':'Ⅱ';if(!paused)queueStep();});button('speed',()=>{speed=speed===1?2:speed===2?4:1;$('speed').textContent='×'+speed;});button('weather',()=>{if(!meta)return;rainMode=(rainMode+1)%3;const r=rainMode===1?4:rainMode===2?6:3;worker.postMessage({type:'paint',kind:2,x:Math.floor(meta.w*.7),y:Math.floor(meta.h*.8),z:Math.floor(meta.d*.35),radius:r});});button('reset',()=>worker?.postMessage({type:'reset'}));button('toggleUI',()=>document.body.classList.toggle('clean'));
start();requestAnimationFrame(loop);
})();
