/* ---------- CAMERA / INPUT ---------- */
const camera={x:500,y:520,zoom:1.05,follow:true,shake:0};let selected=null;
function worldToScreen(x,y){const z=camera.zoom,sx=(x-camera.x)*z+SW*.5,sy=(y-camera.y)*z+SH*.52;return{x:sx,y:sy}}
function screenToWorld(x,y){return{x:(x-SW*.5)/camera.zoom+camera.x,y:(y-SH*.52)/camera.zoom+camera.y}}
const ptr=new Map();let drag=false,lastP=null,pinch=0,pinchZoom=1;
C.addEventListener('pointerdown',e=>{ptr.set(e.pointerId,{x:e.clientX,y:e.clientY});C.setPointerCapture(e.pointerId);drag=false;lastP={x:e.clientX,y:e.clientY};if(ptr.size===2){const a=[...ptr.values()];pinch=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);pinchZoom=camera.zoom}});
C.addEventListener('pointermove',e=>{if(!ptr.has(e.pointerId))return;const prev=ptr.get(e.pointerId);ptr.set(e.pointerId,{x:e.clientX,y:e.clientY});if(ptr.size===2){const a=[...ptr.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);camera.zoom=clamp(pinchZoom*d/Math.max(1,pinch),.55,2.4);drag=true;return}const dx=e.clientX-prev.x,dy=e.clientY-prev.y;if(Math.abs(dx)+Math.abs(dy)>2)drag=true;if(drag){camera.follow=false;camera.x=clamp(camera.x-dx/camera.zoom,0,WORLD_W);camera.y=clamp(camera.y-dy/camera.zoom,200,WORLD_H)}});
C.addEventListener('pointerup',e=>{if(!drag&&ptr.size===1){const w=screenToWorld(e.clientX,e.clientY);let best=null,bd=42*42;for(const c of creatures){if(c.gone)continue;const q=c.center(),d=(q.x-w.x)**2+(q.y-w.y)**2;if(d<bd){bd=d;best=c}}selected=best}ptr.delete(e.pointerId);if(!ptr.size)lastP=null});
function drawBackground(t){const grad=X.createLinearGradient(0,0,0,SH);grad.addColorStop(0,'#111b20');grad.addColorStop(.52,'#172024');grad.addColorStop(1,'#080c0d');X.fillStyle=grad;X.fillRect(0,0,SW,SH);for(let layer=0;layer<3;layer++){const par=.08+layer*.08,base=SH*(.50+layer*.09);X.fillStyle=['#0b1215','#0d1517','#101817'][layer];X.beginPath();X.moveTo(0,SH);for(let sx=-80;sx<SW+100;sx+=60){const wx=(camera.x*par+sx)*.012,hh=40+hash((wx|0)+layer*991)*120;X.lineTo(sx,base-hh);X.lineTo(sx+35,base-hh*(.65+hash((wx|0)+77)*.25))}X.lineTo(SW,SH);X.closePath();X.fill()}if(weather.rain>.25){X.fillStyle=`rgba(72,93,102,${weather.rain*.10})`;X.fillRect(0,0,SW,SH)}if(weather.lightning>.02){X.fillStyle=`rgba(220,238,244,${weather.lightning*.35})`;X.fillRect(0,0,SW,SH)}}
function tileVisibleBounds(){const z=camera.zoom,l=(camera.x-SW/(2*z))/TILE-2,r=(camera.x+SW/(2*z))/TILE+2,t=(camera.y-SH/(2*z))/TILE-2,b=(camera.y+SH/(2*z))/TILE+2;return{l:clamp(Math.floor(l),0,COLS-1),r:clamp(Math.ceil(r),0,COLS-1),t:clamp(Math.floor(t),0,ROWS-1),b:clamp(Math.ceil(b),0,ROWS-1)}}
function drawTerrain(t){const b=tileVisibleBounds(),z=camera.zoom;for(let y=b.t;y<=b.b;y++)for(let x=b.l;x<=b.r;x++){if(!isSolidCell(x,y))continue;const p=worldToScreen(x*TILE,y*TILE),top=!isSolidCell(x,y-1),left=!isSolidCell(x-1,y),right=!isSolidCell(x+1,y),w=TILE*z+1;X.fillStyle=top?'#35423b':'#242c29';X.fillRect(p.x,p.y,w,w);if(top){X.fillStyle='#52644d';X.fillRect(p.x,p.y,w,Math.max(2,z*3));if(hash(x*71+y*337)>.52){X.strokeStyle='#708262';X.lineWidth=Math.max(1,z);X.beginPath();const gx=p.x+(hash(x*13+y)*TILE)*z;X.moveTo(gx,p.y);X.lineTo(gx+Math.sin(t*.002+x)*4,p.y-8*z);X.stroke()}}if(left){X.fillStyle='#171d1b';X.fillRect(p.x,p.y,Math.max(2,z*3),w)}if(right){X.fillStyle='#3f4a45';X.fillRect(p.x+w-Math.max(2,z*2),p.y,Math.max(2,z*2),w)}}}
function drawPlants(t){for(const p of plants){if(!p.alive)continue;const s=worldToScreen(p.x,p.y);if(s.x<-30||s.x>SW+30||s.y<-30||s.y>SH+30)continue;const sway=Math.sin(t*.002+p.phase)*3*weather.rain;X.strokeStyle='#5c7754';X.lineWidth=2*camera.zoom;X.beginPath();X.moveTo(s.x,s.y);X.quadraticCurveTo(s.x+sway,s.y-12*camera.zoom,s.x+sway*.7,s.y-20*camera.zoom);X.stroke();X.fillStyle='#8d9e68';X.beginPath();X.ellipse(s.x+sway*.7,s.y-20*camera.zoom,5*camera.zoom,3*camera.zoom,.2,0,TAU);X.fill()}}
function drawStructures(){for(const s of structures){const p=worldToScreen(s.x,s.y);if(p.x<-220||p.x>SW+220||p.y<-220||p.y>SH+220)continue;if(s.type==='net'){const a=worldToScreen(s.a.x,s.a.y),b=worldToScreen(s.b.x,s.b.y);X.strokeStyle='#b7aa75';X.lineWidth=Math.max(1,1.3*camera.zoom);X.beginPath();X.moveTo(a.x,a.y);X.lineTo(b.x,b.y);X.stroke();for(let i=1;i<6;i++){const u=i/6,x=lerp(a.x,b.x,u),y=lerp(a.y,b.y,u);X.beginPath();X.moveTo(x-7*camera.zoom,y-10*camera.zoom);X.lineTo(x+7*camera.zoom,y+10*camera.zoom);X.stroke()}}else if(s.type==='web'){const r=s.radius*camera.zoom;X.strokeStyle='rgba(205,215,220,.55)';X.lineWidth=Math.max(.6,camera.zoom*.7);for(let k=0;k<8;k++){const a=k/8*TAU;X.beginPath();X.moveTo(p.x,p.y);X.lineTo(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r);X.stroke()}for(let rr=.25;rr<=1;rr+=.22){X.beginPath();X.arc(p.x,p.y,r*rr,0,TAU);X.stroke()}}else if(s.type==='shelter'){X.strokeStyle='#8b7b59';X.lineWidth=4*camera.zoom;X.strokeRect(p.x-s.w*.5*camera.zoom,p.y-45*camera.zoom,s.w*camera.zoom,45*camera.zoom)}}}
function drawFlies(t){for(const f of flies){if(!f.alive)continue;const p=worldToScreen(f.x,f.y);if(p.x<-20||p.x>SW+20||p.y<-20||p.y>SH+20)continue;X.fillStyle=f.caught?'#d6cfa9':'#9fc2bd';X.beginPath();X.arc(p.x,p.y,1.5+Math.sin(t*.03+f.x)*.5,0,TAU);X.fill()}}
function drawLimb(c,l,col){if(l.disabled)return;const a=c.nodes[l.anchor],h=l.hand,A=worldToScreen(a.x,a.y),H=worldToScreen(h.x,h.y),dx=H.x-A.x,dy=H.y-A.y,d=Math.hypot(dx,dy)||1,nx=-dy/d,ny=dx/d,bend=(l.side*(l.arm?1:-1))*Math.min(12*camera.zoom,d*.28),mx=(A.x+H.x)*.5+nx*bend,my=(A.y+H.y)*.5+ny*bend;X.strokeStyle='#161b19';X.lineWidth=5.5*camera.zoom*c.g.size;X.lineCap='round';X.beginPath();X.moveTo(A.x,A.y);X.quadraticCurveTo(mx,my,H.x,H.y);X.stroke();X.strokeStyle=col;X.lineWidth=3.2*camera.zoom*c.g.size;X.beginPath();X.moveTo(A.x,A.y);X.quadraticCurveTo(mx,my,H.x,H.y);X.stroke();X.fillStyle=l.planted?'#c7d0bb':col;X.beginPath();X.arc(H.x,H.y,2.8*camera.zoom*c.g.size,0,TAU);X.fill()}
function drawCreature(c){if(c.gone)return;const q=c.center(),s=worldToScreen(q.x,q.y);if(s.x<-120||s.x>SW+120||s.y<-120||s.y>SH+120)return;const col=c.alive?c.spec.color:'#4b4b46',hi=c.alive?c.spec.hi:'#68645f';for(const l of c.limbs)drawLimb(c,l,col);if(c.tail.length){X.strokeStyle=col;X.lineWidth=4*camera.zoom*c.g.size;X.beginPath();let a=worldToScreen(c.nodes[c.nodes.length-1].x,c.nodes[c.nodes.length-1].y);X.moveTo(a.x,a.y);for(const n of c.tail){const p=worldToScreen(n.x,n.y);X.lineTo(p.x,p.y)}X.stroke()}for(let i=c.nodes.length-1;i>=0;i--){const n=c.nodes[i],p=worldToScreen(n.x,n.y),r=n.r*camera.zoom;X.fillStyle=col;X.beginPath();X.ellipse(p.x,p.y,r*1.18,r*.88,0,0,TAU);X.fill();if(i===0){X.fillStyle=hi;X.beginPath();X.ellipse(p.x-c.face*r*.12,p.y-r*.28,r*.7,r*.28,0,0,TAU);X.fill();X.fillStyle=c.alive?'#e6ddb3':'#181818';X.beginPath();X.arc(p.x+c.face*r*.68,p.y-r*.17,Math.max(1.2,1.6*camera.zoom),0,TAU);X.fill()}}if(c.spec.family==='spider'){const rear=c.nodes[c.nodes.length-1],rp=worldToScreen(rear.x,rear.y),rr=rear.r*camera.zoom;X.fillStyle=col;X.beginPath();X.ellipse(rp.x-c.face*rr*.7,rp.y+rr*.15,rr*1.35,rr*1.05,0,0,TAU);X.fill();if(c.spec.feminine){const hp=worldToScreen(c.head().x,c.head().y),r=c.head().r*camera.zoom*c.spec.torsoAccent;X.fillStyle=c.spec.hi;X.beginPath();X.arc(hp.x-c.face*r*.28,hp.y+r*.62,r*.34,0,TAU);X.arc(hp.x+c.face*r*.08,hp.y+r*.62,r*.34,0,TAU);X.fill()}}if(c.spec.family==='lizard'){const hp=worldToScreen(c.head().x,c.head().y),r=c.head().r*camera.zoom;X.fillStyle=c.spec.hi;for(let k=0;k<3;k++){X.beginPath();X.moveTo(hp.x-c.face*r*(.2+k*.35),hp.y-r*.55);X.lineTo(hp.x-c.face*r*(.35+k*.35),hp.y-r*(1+.1*k));X.lineTo(hp.x-c.face*r*(.5+k*.35),hp.y-r*.5);X.fill()}}if(c.spec.family==='mirekin'){const hp=worldToScreen(c.head().x,c.head().y),r=c.head().r*camera.zoom;X.strokeStyle=c.spec.hi;X.lineWidth=2*camera.zoom;X.beginPath();X.moveTo(hp.x-c.face*r*.2,hp.y-r*.6);X.quadraticCurveTo(hp.x,hp.y-r*1.25,hp.x+c.face*r*.35,hp.y-r*.85);X.stroke()}if(debugBody){X.strokeStyle='#8fe0be66';for(const n of c.nodes){const p=worldToScreen(n.x,n.y);X.beginPath();X.arc(p.x,p.y,n.r*camera.zoom,0,TAU);X.stroke()}}}
function drawWeather(){if(weather.rain>.08){X.strokeStyle=`rgba(150,184,197,${.22+.42*weather.rain})`;const n=Math.floor(40+weather.rain*120);for(let i=0;i<n;i++){const x=(hash(i*313+(simTick>>1))*SW)|0,y=(hash(i*991+(simTick>>1)+7)*SH)|0;X.beginPath();X.moveTo(x,y);X.lineTo(x-4-weather.rain*4,y+14+weather.rain*12);X.stroke()}}for(const p of fx){const s=worldToScreen(p.x,p.y);X.fillStyle=p.c;X.fillRect(s.x,s.y,2.5,2.5)}}
function render(t){if(camera.shake>0){X.save();X.translate((rnd()-.5)*camera.shake,(rnd()-.5)*camera.shake);camera.shake*=.88}drawBackground(t);drawTerrain(t);drawStructures();drawPlants(t);drawFlies(t);for(const c of creatures.filter(c=>!c.gone).sort((a,b)=>a.center().y-b.center().y))drawCreature(c);drawWeather();if(camera.shake>0)X.restore();updateUI()}
let paused=false,speed=1,debugBody=false,simTick=0;
function updateUI(){const alive=creatures.filter(c=>c.alive),activeTypes=new Set(alive.map(c=>c.type)).size,pred=alive.filter(c=>c.spec.role==='pred').length,intel=alive.filter(c=>c.spec.intelligent).length,corpses=creatures.filter(c=>!c.alive&&!c.gone).length,caught=structures.reduce((n,s)=>n+s.caught.filter(f=>!f.alive).length,0)+flies.filter(f=>f.alive&&f.caught).length;stats.innerHTML=`${alive.length} bodies · ${activeTypes}/100 local types<br>${intel} tribal NPC · ${pred} hunter · ${corpses} corpses<br>${structures.length} builds · ${caught} trap catches · gen ${maxGen}`;if(!selected||selected.gone){inspect.style.display='none';return}inspect.style.display='block';inspect.innerHTML=`<b class="gold">${selected.spec.name} #${selected.id}</b><div class="row"><span>family</span><b>${selected.spec.family}</b></div><div class="row"><span>state</span><b>${selected.alive?selected.state:'CORPSE'}</b></div><div class="row"><span>generation</span><b>${selected.gen}</b></div><div class="row"><span>energy</span><b>${selected.energy.toFixed(0)}</b></div><div class="row"><span>fiber / silk</span><b>${selected.inventory.fiber.toFixed(1)} / ${selected.inventory.silk.toFixed(1)}</b></div><div class="row"><span>limbs</span><b>${selected.limbs.length}</b></div>`}
function reset(){seed=(Math.random()*0xffffffff)>>>0;genWorld();seedLife();selected=creatures[0];camera.x=selected.center().x;camera.y=selected.center().y;camera.follow=true;weather.rain=.15;weather.target=.15;simTick=0}
function step(){simTick++;stepWeather();stepFlies();stepStructures();for(const c of creatures)if(!c.gone)stepCreature(c);stepFx();if(simTick%600===0){for(let i=0;i<metaPop.length;i++){const s=SPEC[SPECIES_KEYS[i]],pressure=s.role==='pred'?.985:s.intelligent?1.002:1.008;metaPop[i]=clamp(metaPop[i]*pressure+(rnd()-.48)*3,2,180)}if(creatures.filter(c=>c.alive).length<42){const missing=SPECIES_KEYS.filter(k=>!creatures.some(c=>c.alive&&c.type===k));if(missing.length)spawnCreature(missing[(rnd()*missing.length)|0])}}if(simTick%300===0){for(let i=creatures.length-1;i>=0;i--)if(creatures[i].gone)creatures.splice(i,1);for(let i=flies.length-1;i>=0;i--)if(!flies[i].alive)flies.splice(i,1)}if(camera.follow&&selected&&!selected.gone){const q=selected.center();camera.x=lerp(camera.x,q.x,.06);camera.y=lerp(camera.y,q.y,.05)}}
let last=performance.now(),acc=0;const FIX=1000/60;function loop(t){const dt=Math.min(60,t-last);last=t;acc+=dt;if(!paused){while(acc>=FIX){for(let i=0;i<speed;i++)step();acc-=FIX}}render(t);requestAnimationFrame(loop)}
document.querySelector('#pause').onclick=()=>{paused=!paused;document.querySelector('#pause').textContent=paused?'▶':'Ⅱ'};document.querySelector('#speed').onclick=()=>{speed=speed===1?2:speed===2?4:1;document.querySelector('#speed').textContent='×'+speed};document.querySelector('#follow').onclick=()=>{camera.follow=!!selected&&!camera.follow;document.querySelector('#follow').textContent=camera.follow?'●':'◎'};document.querySelector('#storm').onclick=()=>{weather.target=weather.target>.6?.12:.95};document.querySelector('#debug').onclick=()=>{debugBody=!debugBody;document.querySelector('#debug').textContent=debugBody?'HIDE':'BODY'};document.querySelector('#reset').onclick=reset;
reset();requestAnimationFrame(loop);
