'use strict';
/* GENESIS ECOSYSTEM 100
   Original side-view artificial-life simulation.
   The core design is physics chunks + distance constraints + limbs that search for contacts.
   No sprite-sheet locomotion. */
const C=document.querySelector('#game'),X=C.getContext('2d',{alpha:false}),stats=document.querySelector('#stats'),inspect=document.querySelector('#inspect');
let DPR=1,SW=innerWidth,SH=innerHeight;
function resize(){DPR=Math.min(devicePixelRatio||1,2);SW=innerWidth;SH=innerHeight;C.width=SW*DPR;C.height=SH*DPR;X.setTransform(DPR,0,0,DPR,0,0);X.imageSmoothingEnabled=true}addEventListener('resize',resize);resize();
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
let seed=(Math.random()*0xffffffff)>>>0;function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function gauss(){let u=0,v=0;while(!u)u=rnd();while(!v)v=rnd();return Math.sqrt(-2*Math.log(u))*Math.cos(TAU*v)}
function hash(n){n|=0;n=(n+0x7ed55d16)+(n<<12);n=(n^0xc761c23c)^(n>>>19);n=(n+0x165667b1)+(n<<5);n=(n+0xd3a2646c)^(n<<9);n=(n+0xfd7046c5)+(n<<3);n=(n^0xb55a4f09)^(n>>>16);return(n>>>0)/4294967296}
function noise1(x,s=0){const a=Math.floor(x),t=x-a,u=t*t*(3-2*t);return lerp(hash(a*928371+s*97),hash((a+1)*928371+s*97),u)}function fbm1(x,s=0){let a=.56,f=.008,v=0,n=0;for(let i=0;i<5;i++){v+=noise1(x*f,s+i*19)*a;n+=a;a*=.5;f*=2.05}return v/n}

/* ---------- WORLD TILES ---------- */
const TILE=28,COLS=280,ROWS=38,WORLD_W=COLS*TILE,WORLD_H=ROWS*TILE;
const solid=new Uint8Array(COLS*ROWS),wet=new Float32Array(COLS*ROWS);const tidx=(x,y)=>y*COLS+x;
function inGrid(x,y){return x>=0&&y>=0&&x<COLS&&y<ROWS}function isSolidCell(x,y){return !inGrid(x,y)||solid[tidx(x,y)]===1}function isSolidAt(x,y){return isSolidCell(Math.floor(x/TILE),Math.floor(y/TILE))}
const surfaceY=new Float32Array(COLS);
function genWorld(){solid.fill(0);wet.fill(0);for(let x=0;x<COLS;x++){let h=26+Math.floor((fbm1(x,5)-.5)*8+(fbm1(x+70,8)-.5)*5);h=clamp(h,19,31);surfaceY[x]=h*TILE;for(let y=h;y<ROWS;y++)solid[tidx(x,y)]=1}
  for(let cave=0;cave<20;cave++){let cx=8+Math.floor(rnd()*(COLS-16)),cy=21+Math.floor(rnd()*9),len=10+Math.floor(rnd()*25),rad=1+Math.floor(rnd()*2);for(let k=0;k<len;k++){cx=clamp(cx+(rnd()<.55?1:(rnd()<.5?-1:0)),2,COLS-3);cy=clamp(cy+(rnd()<.22?(rnd()<.5?-1:1):0),15,ROWS-3);for(let oy=-rad;oy<=rad;oy++)for(let ox=-rad;ox<=rad;ox++)if(inGrid(cx+ox,cy+oy))solid[tidx(cx+ox,cy+oy)]=0}}
  for(let p=0;p<38;p++){const x=4+Math.floor(rnd()*(COLS-10)),y=10+Math.floor(rnd()*14),w=3+Math.floor(rnd()*8);for(let xx=x;xx<x+w&&xx<COLS-1;xx++)solid[tidx(xx,y)]=1;if(rnd()<.45){const hh=3+Math.floor(rnd()*6);for(let yy=y;yy<y+hh&&yy<ROWS-1;yy++)solid[tidx(x,yy)]=1}}
  for(let x=2;x<18;x++)for(let y=10;y<25;y++)solid[tidx(x,y)]=0;
}
function exposedSurfacePoint(cx,cy,px,py){if(!isSolidCell(cx,cy))return null;const x=cx*TILE,y=cy*TILE;let best=null,bd=1e9;const test=(sx,sy,nx,ny)=>{if(isSolidCell(cx+nx,cy+ny))return;const d=(sx-px)**2+(sy-py)**2;if(d<bd){bd=d;best={x:sx,y:sy,nx:-nx,ny:-ny}}};test(x+TILE*.5,y,0,-1);test(x+TILE*.5,y+TILE,0,1);test(x,y+TILE*.5,-1,0);test(x+TILE,y+TILE*.5,1,0);return best}
function findContact(px,py,desX,desY,rad,front=0){const minX=Math.floor((desX-rad)/TILE),maxX=Math.floor((desX+rad)/TILE),minY=Math.floor((desY-rad)/TILE),maxY=Math.floor((desY+rad)/TILE);let best=null,bs=1e9;for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const p=exposedSurfacePoint(x,y,desX,desY);if(!p)continue;const d=Math.hypot(p.x-desX,p.y-desY);const reach=Math.hypot(p.x-px,p.y-py);if(reach>rad*1.35)continue;const score=d-front*(p.x-px);if(score<bs){bs=score;best=p}}return best}
function pointCollide(n){const minX=Math.floor((n.x-n.r)/TILE),maxX=Math.floor((n.x+n.r)/TILE),minY=Math.floor((n.y-n.r)/TILE),maxY=Math.floor((n.y+n.r)/TILE);for(let cy=minY;cy<=maxY;cy++)for(let cx=minX;cx<=maxX;cx++){if(!isSolidCell(cx,cy))continue;const rx=cx*TILE,ry=cy*TILE,qx=clamp(n.x,rx,rx+TILE),qy=clamp(n.y,ry,ry+TILE),dx=n.x-qx,dy=n.y-qy,d2=dx*dx+dy*dy;if(d2<n.r*n.r){let d=Math.sqrt(d2),nx=0,ny=-1;if(d>.0001){nx=dx/d;ny=dy/d}else{const dl=Math.abs(n.x-rx),dr=Math.abs(n.x-(rx+TILE)),dt=Math.abs(n.y-ry),db=Math.abs(n.y-(ry+TILE)),m=Math.min(dl,dr,dt,db);if(m===dl){nx=-1;ny=0}else if(m===dr){nx=1;ny=0}else if(m===db){nx=0;ny=1}}const push=n.r-(d||0);n.x+=nx*push;n.y+=ny*push;const vx=n.x-n.px,vy=n.y-n.py,dot=vx*nx+vy*ny;if(dot<0){n.px+=nx*dot*.55;n.py+=ny*dot*.55}n.contact=Math.max(n.contact,ny<-.5?1:0)}}}

function Node(x,y,r=8,mass=1){return{x,y,px:x,py:y,r,inv:1/Math.max(.001,mass),contact:0}}
function integrateNode(n,gravity=.38,drag=.994){n.contact=0;const vx=(n.x-n.px)*drag,vy=(n.y-n.py)*drag;n.px=n.x;n.py=n.y;n.x+=vx;n.y+=vy+gravity;pointCollide(n)}
function constrain(a,b,len,stiff=1){let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.0001,diff=(d-len)/d*stiff,wa=a.inv/(a.inv+b.inv),wb=1-wa;a.x+=dx*diff*wa;a.y+=dy*diff*wa;b.x-=dx*diff*wb;b.y-=dy*diff*wb}
function spring(a,b,len,k=.04){let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,f=(d-len)*k,fx=dx/d*f,fy=dy/d*f;a.x+=fx*a.inv;b.x-=fx*b.inv;a.y+=fy*a.inv;b.y-=fy*b.inv}
function velocity(n){return{x:n.x-n.px,y:n.y-n.py}}function impulse(n,x,y){n.px-=x;n.py-=y}

const SPEC={};
const FAMILY_DATA=[
 {family:'mirekin',role:'tribe',intelligent:1,builder:1,neter:0,weaver:0,move:'climb',body:3,legs:2,arms:2,tail:2,baseSpeed:.34,gravity:.36,palette:['#718b72','#a7c49a'],names:['Mirekin Gatherer','Mirekin Scout','Mirekin Reedwalker','Mirekin Mossback','Mirekin Cliffhand','Mirekin Raincaller','Mirekin Cavekeeper','Mirekin Bonecarver','Mirekin Rootfinder','Mirekin Nightwatch']},
 {family:'reedscale',role:'lizard',intelligent:1,builder:1,neter:1,weaver:0,move:'climb',body:3,legs:2,arms:2,tail:5,baseSpeed:.39,gravity:.37,palette:['#55754b','#a6bb78'],names:['Reedscale Netmaker','Reedscale Spearjaw','Reedscale Fisher','Reedscale Stonehide','Reedscale Marshguard','Reedscale Longtail','Reedscale Reedstalker','Reedscale Trapwright','Reedscale Eggkeeper','Reedscale Mireking']},
 {family:'silkborn',role:'spider',intelligent:1,builder:0,neter:0,weaver:1,move:'climb',body:3,legs:6,arms:2,tail:0,baseSpeed:.31,gravity:.31,palette:['#6c5a78','#c29bc8'],names:['Silk Matron','Silk Weaver','Silk Huntress','Silk Broodkeeper','Silk Lantern','Silk Paleleg','Silk Widowguard','Silk Threadseer','Silk Cavernmother','Silk Spinner']},
 {family:'grazer',role:'herb',move:'ground',body:3,legs:4,arms:0,tail:3,baseSpeed:.34,gravity:.39,palette:['#82965f','#ccd194'],names:['Miregrazer','Ashhorn','Reed Deer','Stoneback Grazer','Lantern Elk','Moss Antler','Dusk Ram','Cave Doe','Marsh Boar','Glasshorn']},
 {family:'hunter',role:'pred',move:'ground',body:3,legs:4,arms:0,tail:4,baseSpeed:.47,gravity:.39,palette:['#82474a','#dc796b'],names:['Needlejaw','Rust Prowler','Blackmaw','Cave Raptor','Spine Hound','Mudfang','Night Lancer','Hookjaw','Red Stalker','Pale Pursuer']},
 {family:'scavenger',role:'scav',move:'climb',body:2,legs:2,arms:2,tail:2,baseSpeed:.38,gravity:.39,palette:['#64747a','#a9bbc0'],names:['Gutterclaw','Bone Thief','Carrion Hand','Tin Snout','Rotpicker','Ash Scraper','Muck Raker','Skull Runner','Grave Nipper','Rubble Eater']},
 {family:'climber',role:'herb',move:'climb',body:2,legs:4,arms:2,tail:4,baseSpeed:.36,gravity:.34,palette:['#667b66','#a9c39f'],names:['Wallmoss','Hookfoot','Cliff Lemur','Vineback','Ceiling Skitter','Griptail','Stone Gecko','Moss Climber','Cave Slink','Branch Crawler']},
 {family:'burrower',role:'scav',move:'ground',body:4,legs:6,arms:0,tail:1,baseSpeed:.27,gravity:.40,palette:['#766552','#b99c77'],names:['Root Mole','Tunnel Hog','Gravel Worm','Mud Borer','Bone Burrower','Clay Snout','Rubble Mole','Deep Grub','Chalk Digger','Iron Noser']},
 {family:'winged',role:'herb',move:'fly',body:2,legs:2,arms:2,tail:2,baseSpeed:.42,gravity:.11,palette:['#547985','#a4cad0'],names:['Fogwing','Glass Moth','Rain Kite','Cave Flutter','Blue Lantern','Ashwing','Needle Moth','Storm Skimmer','Pale Glider','Mire Bat']},
 {family:'amphib',role:'scav',move:'hopper',body:2,legs:4,arms:0,tail:3,baseSpeed:.36,gravity:.34,palette:['#547e73','#9dc4a8'],names:['Bog Hopper','Mud Newt','Rain Toad','Glass Frog','Marsh Slink','Pool Crawler','Fen Jumper','Mire Salamander','Flood Skipper','Cave Toad']}
];
function keyName(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
for(const fam of FAMILY_DATA){fam.names.forEach((name,i)=>{SPEC[keyName(name)]={name,family:fam.family,role:fam.role,intelligent:!!fam.intelligent,builder:!!fam.builder,netter:!!fam.neter,weaver:!!fam.weaver,move:fam.move,body:fam.body+(i%4===3?1:0),legs:fam.legs,arms:fam.arms,tail:Math.max(0,fam.tail+(i%3===2?1:0)),baseSpeed:fam.baseSpeed*(.88+(i%5)*.045),gravity:fam.gravity,color:fam.palette[0],hi:fam.palette[1],variant:i,small:(fam.family==='winged'||i===8),feminine:(name==='Silk Matron'||name==='Silk Huntress'||name==='Silk Cavernmother'),torsoAccent:name==='Silk Matron'?1.45:name==='Silk Cavernmother'?1.25:1};})}
const SPECIES_KEYS=Object.keys(SPEC),SPEC_INDEX=Object.fromEntries(SPECIES_KEYS.map((k,i)=>[k,i]));
function genes(base=null){const keys=['size','speed','vision','fear','aggression','grip','limb','metabolism','fertility','stamina'];const o={};for(const k of keys)o[k]=base?clamp(base[k]+gauss()*.045,.55,1.55):.82+rnd()*.36;return o}
function crossGenes(a,b){const o={};for(const k of Object.keys(a))o[k]=clamp((rnd()<.5?a[k]:b[k])+gauss()*.035,.5,1.65);return o}
let nextId=1,maxGen=0;
class Creature{constructor(type,x,y,gene=null,gen=0){this.id=nextId++;this.type=type;this.spec=SPEC[type];this.g=gene||genes();this.gen=gen;maxGen=Math.max(maxGen,gen);this.alive=true;this.health=100;this.energy=70+rnd()*25;this.age=0;this.state='ROAM';this.stateT=0;this.face=rnd()<.5?-1:1;this.homeX=x;this.memory={food:null,threat:null,corpse:null,structure:null};this.mateCooldown=600+rnd()*600;this.grab=null;this.biteCooldown=0;this.stun=0;this.trapped=0;this.nodes=[];this.constraints=[];this.limbs=[];this.tail=[];this.parts=[];this.struggle=0;this.inventory={fiber:0,food:0,scrap:0,silk:0};this.buildCooldown=100+rnd()*300;this.tribe=this.spec.family;this.sex=this.spec.feminine?'F':(rnd()<.5?'F':'M');this.buildBody(x,y)}buildBody(x,y){const s=this.g.size,n=this.spec.body;for(let i=0;i<n;i++)this.nodes.push(Node(x-i*13*s,y-i*2,7*s*(i===0?1:.95),1));for(let i=0;i<n-1;i++)this.constraints.push([i,i+1,13*s]);if(n>2)this.constraints.push([0,2,25*s]);for(let i=0;i<this.spec.tail;i++){const prev=i?this.tail[i-1]:this.nodes[n-1],q=Node(prev.x-9*this.face,prev.y,3.2*s,.6);this.tail.push(q)}const limbCount=this.spec.legs+this.spec.arms;for(let i=0;i<limbCount;i++){const arm=i>=this.spec.legs,anchor=arm?0:(i%2===0?0:Math.min(1,n-1)),side=i%2===0?-1:1;this.limbs.push({arm,anchor,side,phase:(i/Math.max(1,limbCount))*TAU,hand:Node(x,y,2.7*s,.35),planted:false,target:null,reach:(arm?24:28)*this.g.limb*s,cool:rnd()*20,disabled:false})}}head(){return this.nodes[0]}center(){let x=0,y=0;for(const n of this.nodes){x+=n.x;y+=n.y}return{x:x/this.nodes.length,y:y/this.nodes.length}}speed(){return Math.abs(velocity(this.head()).x)}}
const creatures=[],plants=[],looseParts=[],structures=[],flies=[];const metaPop=new Float32Array(SPECIES_KEYS.length);
function linePointDistance(px,py,x1,y1,x2,y2){const dx=x2-x1,dy=y2-y1,l2=dx*dx+dy*dy||1,t=clamp(((px-x1)*dx+(py-y1)*dy)/l2,0,1),x=x1+t*dx,y=y1+t*dy;return Math.hypot(px-x,py-y)}
function spawnFly(x,y){flies.push({x,y,vx:(rnd()-.5)*1.2,vy:(rnd()-.5)*.8,alive:true,caught:null,life:500+rnd()*2200})}
function addStructure(type,x,y,owner,extra={}){const s={id:structures.length+1,type,x,y,owner:owner?.tribe||owner||'wild',age:0,strength:100,caught:[],...extra};structures.push(s);return s}
function nearbyStructure(c,type,r=200){const q=c.center();let best=null,bd=r*r;for(const s of structures){if(type&&s.type!==type)continue;const d=(s.x-q.x)**2+(s.y-q.y)**2;if(d<bd){bd=d;best=s}}return best}
function nearestFly(c,r=220,onlyFree=true){const q=c.center();let best=null,bd=r*r;for(const f of flies){if(!f.alive||(onlyFree&&f.caught))continue;const d=(f.x-q.x)**2+(f.y-q.y)**2;if(d<bd){bd=d;best=f}}return best}
function findAnchorPair(x,y,span=120){const a=findContact(x,y,x-span*.45,y-35,span,.1),b=findContact(x,y,x+span*.45,y-30,span,-.1);if(a&&b&&Math.hypot(a.x-b.x,a.y-b.y)>36)return[a,b];return null}
function randomFloorX(){for(let t=0;t<100;t++){const x=3+Math.floor(rnd()*(COLS-6)),sy=surfaceY[x];if(sy>0)return{x:x*TILE+TILE*.5,y:sy-22}}return{x:200,y:500}}
function spawnCreature(type,parentA=null,parentB=null,x=null,y=null){const p=x==null?randomFloorX():{x,y},g=parentA?crossGenes(parentA.g,parentB?.g||parentA.g):genes(),gen=parentA?Math.max(parentA.gen,parentB?.gen||0)+1:0,c=new Creature(type,p.x,p.y,g,gen);creatures.push(c);return c}
function spawnPlant(x,y){plants.push({x,y,food:18+rnd()*16,phase:rnd()*TAU,alive:true})}
function seedLife(){creatures.length=0;plants.length=0;looseParts.length=0;structures.length=0;flies.length=0;nextId=1;maxGen=0;metaPop.forEach((_,i)=>metaPop[i]=18+rnd()*70);for(const type of ['mirekin_gatherer','reedscale_netmaker','silk_matron'])for(let i=0;i<4;i++)spawnCreature(type);for(const type of ['miregrazer','ashhorn','needlejaw','rust_prowler','gutterclaw','bone_thief','wallmoss','hookfoot','root_mole','bog_hopper','fogwing','glass_moth'])for(let i=0;i<2;i++)spawnCreature(type);for(let x=3;x<COLS-3;x+=2){if(rnd()<.62){const y=surfaceY[x]/TILE|0;if(y>2&&!isSolidCell(x,y-1))spawnPlant(x*TILE+5+rnd()*(TILE-10),y*TILE-2)}}for(let i=0;i<95;i++){const p=plants.length?plants[(rnd()*plants.length)|0]:randomFloorX();spawnFly(p.x+(rnd()-.5)*90,p.y-25-rnd()*150)}}
