/* ---------- PERCEPTION / AI ---------- */
function nearest(c,pred,r=420){const cc=c.center();let best=null,bd=r*r;for(const o of creatures){if(o===c||!pred(o))continue;const q=o.center(),d=(q.x-cc.x)**2+(q.y-cc.y)**2;if(d<bd){bd=d;best=o}}return best}
function nearestPlant(c,r=320){const q=c.center();let best=null,bd=r*r;for(const p of plants){if(!p.alive||p.food<=0)continue;const d=(p.x-q.x)**2+(p.y-q.y)**2;if(d<bd){bd=d;best=p}}return best}
function lineClear(a,b){const d=Math.hypot(b.x-a.x,b.y-a.y),steps=Math.ceil(d/(TILE*.55));for(let i=1;i<steps;i++){const t=i/steps;if(isSolidAt(lerp(a.x,b.x,t),lerp(a.y,b.y,t)))return false}return true}
function chooseAI(c){if(!c.alive)return;if(c.stun>0||c.trapped>0){c.state='STUN';return}const q=c.center(),storm=weather.rain;let target=null;
  if(c.spec.intelligent){const threat=nearest(c,o=>o.alive&&o.spec.role==='pred',c.g.vision*330);if(threat&&lineClear(q,threat.center())){c.state='EVADE';target=threat}
    else if(c.spec.weaver){const web=nearbyStructure(c,'web',180),caught=web?.caught.find(f=>f.alive);if(caught){c.state='FEED_WEB';target=caught}else if(c.inventory.silk>=4&&!web&&c.buildCooldown<=0){c.state='WEAVE';target=nearestFly(c,320,true)||nearestPlant(c,280)}else if(c.energy<62){const f=nearestFly(c,220,false),corpse=nearest(c,o=>!o.alive&&!o.gone,240);target=f||corpse;c.state=f?'HUNT_FLY':corpse?'SCAVENGE':'ROAM'}else c.state='ROAM'}
    else if(c.spec.netter){const net=nearbyStructure(c,'net',220),caught=net?.caught.find(f=>f.alive);if(caught){c.state='HARVEST_NET';target=caught}else if(c.inventory.fiber>=5&&!net&&c.buildCooldown<=0){c.state='BUILD_NET';target=nearestFly(c,340,true)||nearestPlant(c,300)}else if(c.inventory.fiber<5){const p=nearestPlant(c,260);c.state=p?'GATHER':'ROAM';target=p}else c.state='ROAM'}
    else {const shelter=nearbyStructure(c,'shelter',240);if(c.inventory.fiber>=6&&!shelter&&c.buildCooldown<=0)c.state='BUILD_SHELTER';else if(c.inventory.fiber<6){const p=nearestPlant(c,260);c.state=p?'GATHER':'ROAM';target=p}else if(c.energy<58){const p=nearestPlant(c,220);c.state=p?'FORAGE':'ROAM';target=p}else c.state='ROAM'}
  } else if(c.spec.role==='herb'){const threat=nearest(c,o=>o.alive&&o.spec.role==='pred',c.g.vision*360);if(threat&&lineClear(q,threat.center())){c.memory.threat=threat.center();c.state='FLEE';target=threat}else if(storm>.72&&rnd()<.7){c.state='SHELTER'}else if(c.energy<82){const p=nearestPlant(c,c.g.vision*300);if(p){c.memory.food={x:p.x,y:p.y};c.state='FORAGE';target=p}else c.state='ROAM'}else c.state='ROAM'}
  else if(c.spec.role==='pred'){const prey=nearest(c,o=>o.alive&&(o.spec.role==='herb'||(o.spec.small&&!o.spec.intelligent)),c.g.vision*430);const corpse=nearest(c,o=>!o.alive&&o.decay<6000,c.g.vision*260);if(c.energy<38&&corpse){c.state='SCAVENGE';target=corpse}else if(prey&&lineClear(q,prey.center())){const d=dist(q,prey.center());c.state=d<110?'POUNCE':'STALK';target=prey}else if(storm>.85&&c.energy>45)c.state='SHELTER';else c.state='ROAM'}
  else {const corpse=nearest(c,o=>!o.alive&&o.decay<7000,c.g.vision*420);const threat=nearest(c,o=>o.alive&&o.spec.role==='pred',c.g.vision*280);if(threat&&c.energy>28){c.state='EVADE';target=threat}else if(corpse){c.memory.corpse=corpse.center();c.state='SCAVENGE';target=corpse}else if(c.energy<55){const p=nearestPlant(c,220);c.state=p?'FORAGE':'ROAM';target=p}else c.state='ROAM'}
  c.aiTarget=target;c.stateT=45+Math.floor(rnd()*70)}
function desiredMotion(c){let dx=c.face,dy=0,speed=c.spec.baseSpeed*c.g.speed,state=c.state,q=c.center(),t=c.aiTarget;const tx=t?(t.x??t.center?.().x):null,ty=t?(t.y??t.center?.().y):null;if(tx!=null){dx=Math.sign(tx-q.x)||c.face;dy=clamp((ty-q.y)/100,-1,1);c.face=dx||c.face}if(state==='FLEE'||state==='EVADE'){if(t){dx=Math.sign(q.x-(t.center?t.center().x:t.x))||c.face;c.face=dx}speed*=1.45}if(state==='STALK')speed*=.7;if(state==='POUNCE')speed*=1.8;if(state==='SHELTER'){const roof=findRoofPoint(q.x,q.y);if(roof){dx=Math.sign(roof.x-q.x)||c.face;dy=clamp((roof.y-q.y)/100,-1,1)}speed*=.95}if(state==='REST'||state==='STUN')speed=0;return{dx,dy,speed}}
function findRoofPoint(x,y){for(let s=1;s<18;s++){for(const dir of [-1,1]){const px=x+dir*s*TILE,cy=Math.floor(y/TILE);for(let yy=cy-1;yy>=Math.max(1,cy-5);yy--){if(isSolidAt(px,yy*TILE)&&!isSolidAt(px,(yy+1)*TILE))return{x:px,y:(yy+1)*TILE+20}}}}return null}
function updateLimb(c,l,dt){if(l.disabled)return;const body=c.nodes[l.anchor],motion=desiredMotion(c),reach=l.reach,bx=body.x,by=body.y;l.cool-=dt;if(l.planted){l.hand.x=l.target.x;l.hand.y=l.target.y;l.hand.px=l.hand.x;l.hand.py=l.hand.y;const stretched=Math.hypot(l.hand.x-bx,l.hand.y-by)>reach*1.18,behind=(l.hand.x-bx)*c.face<-(l.arm?8:15);if(stretched||behind||!isSolidAt(l.target.x+l.target.nx*3,l.target.y+l.target.ny*3)){l.planted=false;l.target=null;l.cool=4+rnd()*8}}if(!l.planted){integrateNode(l.hand,.30,.91);const desiredX=bx+c.face*(l.arm?18:22)+c.face*motion.speed*34+Math.sin(simTick*.10+l.phase)*9,desiredY=by+(l.arm?-4:reach*.78)+motion.dy*12;if(l.cool<=0){const hit=findContact(bx,by,desiredX,desiredY,reach*1.05,c.face*.15);if(hit){l.target=hit;l.planted=true;l.hand.x=hit.x;l.hand.y=hit.y;l.cool=7+rnd()*7}}}if(l.planted){const dx=l.hand.x-bx,dy=l.hand.y-by,d=Math.hypot(dx,dy)||1,rest=l.arm?reach*.70:reach*.78,f=(d-rest)*.055*c.g.grip;body.x+=dx/d*f;body.y+=dy/d*f;const drive=motion.speed*(l.arm?.25:.55);body.x+=motion.dx*drive;body.y+=motion.dy*drive*.35}constrain(body,l.hand,reach*.82,.45)}
function detectWall(c){const h=c.head(),fx=h.x+c.face*18;return isSolidAt(fx,h.y)||isSolidAt(fx,h.y-15)}
function bodyController(c){if(!c.alive)return;const m=desiredMotion(c);if(c.stun>0||c.trapped>0)return;const ground=c.nodes.some(n=>n.contact>0),wall=detectWall(c);let drive=m.speed*(ground?1:.18);if(c.spec.move==='fly'){drive=m.speed*.72;for(const n of c.nodes){n.y-=.18+.12*Math.sin(simTick*.11+c.id);n.x+=m.dx*drive;n.y+=m.dy*.22}}else{for(const n of c.nodes){n.x+=m.dx*drive;n.y+=m.dy*drive*.08}}if(c.spec.move==='hopper'&&ground&&Math.abs(m.dx)>.2&&simTick%42===c.id%42){for(const n of c.nodes)impulse(n,m.dx*1.1,-1.9*c.g.stamina)}if(wall){for(const l of c.limbs)if(l.arm||c.spec.role==='pred')l.cool=0;if(c.limbs.some(l=>l.planted&&l.target&&Math.abs(l.target.nx)>.5)){for(const n of c.nodes)n.y-=.24*c.g.grip}}if(c.state==='POUNCE'&&c.biteCooldown<=0&&ground&&c.aiTarget){for(const n of c.nodes)impulse(n,c.face*(2.1+.9*c.g.speed),-1.5*c.g.stamina);c.biteCooldown=34;c.state='STALK'}if(c.state==='FLEE'&&wall&&ground){for(const n of c.nodes)impulse(n,c.face*1.0,-2.0*c.g.stamina)}}
function solveCreature(c){const grav=c.spec.gravity??.39;for(const n of c.nodes)integrateNode(n,grav,.994);for(const t of c.tail)integrateNode(t,grav+.02,.992);for(const l of c.limbs)updateLimb(c,l,1);for(let iter=0;iter<5;iter++){for(const [a,b,len] of c.constraints)constrain(c.nodes[a],c.nodes[b],len*c.g.size,.72);for(let i=0;i<c.tail.length;i++){const a=i?c.tail[i-1]:c.nodes[c.nodes.length-1],b=c.tail[i];constrain(a,b,9*c.g.size,.75)}for(const l of c.limbs)constrain(c.nodes[l.anchor],l.hand,l.reach*.82,.35);for(const n of c.nodes)pointCollide(n);for(const t of c.tail)pointCollide(t)}bodyController(c);handleInteractions(c)}
function closestNode(creature,p){let best=creature.nodes[0],bd=1e9;for(const n of creature.nodes){const d=(n.x-p.x)**2+(n.y-p.y)**2;if(d<bd){bd=d;best=n}}return best}
function handleInteractions(c){if(c.biteCooldown>0)c.biteCooldown--;if(c.stun>0)c.stun--;if(!c.alive)return;const q=c.head();if(c.spec.role==='herb'&&c.state==='FORAGE'){const p=c.aiTarget;if(p&&p.alive&&Math.hypot(q.x-p.x,q.y-p.y)<22){const eat=Math.min(.18,p.food);p.food-=eat;c.energy=Math.min(105,c.energy+eat*3.2);if(p.food<=0)p.alive=false}}if(c.spec.role==='pred'&&(c.state==='POUNCE'||c.state==='STALK'||c.grab)){let prey=c.grab||c.aiTarget;if(prey&&prey.alive){const pn=closestNode(prey,q),d=Math.hypot(pn.x-q.x,pn.y-q.y);if(!c.grab&&d<22&&c.biteCooldown<=0){c.grab=prey;c.biteCooldown=18;prey.health-=12+10*c.g.aggression;prey.stun=8;particlesBlood(pn.x,pn.y,5)}if(c.grab){const gn=closestNode(prey,q);spring(q,gn,10,.12*c.g.grip);gn.x-=c.face*.15*c.g.grip;prey.struggle+=.05;prey.health-=.11*c.g.aggression;if(prey.struggle>2&&rnd()<.015*prey.g.stamina){c.grab=null;prey.struggle=0}if(prey.health<=0){killCreature(prey,c);c.grab=prey}}}else c.grab=null}if((c.spec.role==='scav'||c.spec.role==='pred')&&c.state==='SCAVENGE'){const corpse=c.aiTarget;if(corpse&&!corpse.alive){const cn=closestNode(corpse,q),d=Math.hypot(cn.x-q.x,cn.y-q.y);if(d<28){c.grab=corpse;spring(q,cn,13,.08*c.g.grip);if(simTick%8===0&&corpse.meat>0){const e=Math.min(1.5,corpse.meat);corpse.meat-=e;c.energy=Math.min(105,c.energy+e*.8)}if(c.spec.role==='scav')cn.x-=c.face*.20*c.g.grip}}}handleCulture(c);cultureInteraction(c);if(c.energy>84&&c.age>900&&c.mateCooldown<=0&&creatures.length<48){const mate=nearest(c,o=>o.alive&&o.type===c.type&&o!==c&&o.energy>78&&o.mateCooldown<=0,75);if(mate&&dist(c.center(),mate.center())<50&&rnd()<.006*c.g.fertility){const p=c.center();spawnCreature(c.type,c,mate,p.x+8,p.y-8);c.energy-=18;mate.energy-=18;c.mateCooldown=900;mate.mateCooldown=900}}}
function handleCulture(c){if(!c.spec.intelligent)return;const q=c.head();c.inventory.silk=Math.min(12,c.inventory.silk+(c.spec.weaver?.006:0));c.buildCooldown--;if((c.state==='GATHER'||c.state==='FORAGE')&&c.aiTarget?.food!=null){const p=c.aiTarget;if(p.alive&&Math.hypot(q.x-p.x,q.y-p.y)<26){const take=Math.min(.12,p.food);p.food-=take;c.inventory.fiber+=take*1.6;c.inventory.food+=take*.8;c.energy=Math.min(105,c.energy+take*1.4);if(p.food<=0)p.alive=false}}if(c.state==='BUILD_NET'&&c.spec.netter&&c.inventory.fiber>=5&&c.buildCooldown<=0&&(!c.aiTarget||Math.hypot(q.x-(c.aiTarget.x??q.x),q.y-(c.aiTarget.y??q.y))<95)){const pair=findAnchorPair(q.x,q.y,170);if(pair){addStructure('net',(pair[0].x+pair[1].x)/2,(pair[0].y+pair[1].y)/2,c,{a:pair[0],b:pair[1]});c.inventory.fiber-=5;c.buildCooldown=700;c.state='ROAM'}}if(c.state==='WEAVE'&&c.spec.weaver&&c.inventory.silk>=4&&c.buildCooldown<=0&&(!c.aiTarget||Math.hypot(q.x-(c.aiTarget.x??q.x),q.y-(c.aiTarget.y??q.y))<95)){const pair=findAnchorPair(q.x,q.y,200);if(pair){addStructure('web',(pair[0].x+pair[1].x)/2,(pair[0].y+pair[1].y)/2,c,{a:pair[0],b:pair[1],radius:82+rnd()*42});c.inventory.silk-=4;c.buildCooldown=600;c.state='ROAM'}}if(c.state==='BUILD_SHELTER'&&c.spec.builder&&c.inventory.fiber>=6&&c.buildCooldown<=0){const tx=clamp(Math.floor(q.x/TILE),2,COLS-4),gy=clamp(Math.floor(q.y/TILE),4,ROWS-4);for(let xx=tx;xx<tx+4;xx++)if(inGrid(xx,gy-3))solid[tidx(xx,gy-3)]=1;addStructure('shelter',(tx+2)*TILE,(gy-2)*TILE,c,{w:4*TILE});c.inventory.fiber-=6;c.buildCooldown=900;c.state='ROAM'}}
function stepStructures(){for(const s of structures){s.age++;if(s.type==='net'||s.type==='web'){for(const f of flies){if(!f.alive||f.caught)continue;const hit=s.type==='net'?linePointDistance(f.x,f.y,s.a.x,s.a.y,s.b.x,s.b.y)<18:Math.hypot(f.x-s.x,f.y-s.y)<s.radius*1.12;if(hit){f.caught=s;s.caught.push(f);f.vx=f.vy=0}}for(const c of creatures){if(!c.alive||c.spec.intelligent||!c.spec.small)continue;const q=c.center(),hit=s.type==='net'?linePointDistance(q.x,q.y,s.a.x,s.a.y,s.b.x,s.b.y)<18:Math.hypot(q.x-s.x,q.y-s.y)<s.radius*.8;if(hit)c.trapped=Math.max(c.trapped,45)}}}}
function stepFlies(){for(const f of flies){if(!f.alive)continue;f.life--;if(f.caught){const s=f.caught;f.x=lerp(f.x,s.x,.08);f.y=lerp(f.y,s.y,.08);continue}f.vx+=(rnd()-.5)*.10;f.vy+=(rnd()-.5)*.08-.01;if(simTick%18===0){let tx=null,ty=null,bd=260*260;for(const p of plants){if(!p.alive)continue;const d=(p.x-f.x)**2+(p.y-f.y)**2;if(d<bd){bd=d;tx=p.x;ty=p.y-35}}for(const c of creatures){if(c.alive||c.gone)continue;const q=c.center(),d=(q.x-f.x)**2+(q.y-f.y)**2;if(d<bd){bd=d;tx=q.x;ty=q.y-25}}if(tx!=null){const d=Math.hypot(tx-f.x,ty-f.y)||1;f.vx+=(tx-f.x)/d*.08;f.vy+=(ty-f.y)/d*.05}}f.vx*=.97;f.vy*=.97;f.x=clamp(f.x+f.vx,0,WORLD_W);f.y=clamp(f.y+f.vy,40,WORLD_H-50);if(isSolidAt(f.x,f.y)){f.y-=18;f.vy=-Math.abs(f.vy)-.4}if(f.life<=0)f.alive=false}if(simTick%140===0&&flies.filter(f=>f.alive).length<110){const p=plants.length?plants[(rnd()*plants.length)|0]:randomFloorX();spawnFly(p.x+(rnd()-.5)*80,p.y-30-rnd()*120)}}
function consumeCaught(c,kind){const s=nearbyStructure(c,kind,120),f=s?.caught.find(f=>f.alive);if(f&&Math.hypot(c.head().x-f.x,c.head().y-f.y)<45){f.alive=false;c.energy=Math.min(105,c.energy+10);c.inventory.food+=1}}
function cultureInteraction(c){if(c.state==='HARVEST_NET')consumeCaught(c,'net');if(c.state==='FEED_WEB')consumeCaught(c,'web');if(c.state==='HUNT_FLY'){const f=c.aiTarget;if(f?.alive&&Math.hypot(c.head().x-f.x,c.head().y-f.y)<30){f.alive=false;c.energy=Math.min(105,c.energy+8)}}}
function killCreature(c,killer=null){if(!c.alive)return;c.alive=false;c.decay=0;c.meat=22*c.g.size;c.state='CORPSE';c.grab=null;for(const l of c.limbs){l.planted=false;l.target=null}if(killer)killer.energy=Math.min(105,killer.energy+5);if(rnd()<.28){const l=c.limbs[(rnd()*c.limbs.length)|0];if(l&&!l.disabled){l.disabled=true;looseParts.push({node:l.hand,type:c.type,life:2200,color:c.spec.color})}}}
function stepDead(c){c.decay++;for(const n of c.nodes)integrateNode(n,.42,.993);for(const t of c.tail)integrateNode(t,.42,.992);for(const l of c.limbs)if(!l.disabled){integrateNode(l.hand,.42,.992);constrain(c.nodes[l.anchor],l.hand,l.reach*.84,.20)}for(let i=0;i<4;i++){for(const [a,b,len] of c.constraints)constrain(c.nodes[a],c.nodes[b],len*c.g.size,.55);for(let j=0;j<c.tail.length;j++)constrain(j?c.tail[j-1]:c.nodes[c.nodes.length-1],c.tail[j],9*c.g.size,.55)}if(c.meat<=0&&c.decay>4000)c.gone=true}
function stepCreature(c){c.age++;c.mateCooldown--;if(c.trapped>0)c.trapped--;c.energy-=c.alive?.0045*c.g.metabolism:0;if(c.alive){c.stateT--;if(c.stateT<=0||simTick%20===c.id%20)chooseAI(c);solveCreature(c);if(c.energy<=0||c.health<=0||c.age>24000*c.g.stamina)killCreature(c)}else stepDead(c)}
const weather={rain:.18,target:.18,lightning:0,cycle:0};const fx=[];
function particlesBlood(x,y,n){for(let i=0;i<n;i++)fx.push({x,y,vx:(rnd()-.5)*2,vy:-rnd()*1.5,life:40+Math.floor(rnd()*30),c:'#8e3e43'})}
function stepWeather(){weather.cycle++;weather.rain+=(weather.target-weather.rain)*.002;if(weather.cycle%1800===0)weather.target=rnd()<.55?.15:.88;if(weather.rain>.75&&rnd()<.0018){weather.lightning=1;camera.shake=10}weather.lightning*=.86;for(let i=0;i<wet.length;i++)wet[i]=clamp(wet[i]+weather.rain*.00015-.00005,0,1);for(const p of plants)if(!p.alive&&rnd()<.0007*(1+weather.rain*3)){p.alive=true;p.food=8+rnd()*10}else if(p.alive)p.food=Math.min(34,p.food+.002*(1+weather.rain))}
function stepFx(){if(simTick%240===0){for(const c of creatures)if(!c.alive&&!c.gone&&c.meat>3&&rnd()<.35)spawnFly(c.center().x+(rnd()-.5)*30,c.center().y-20-rnd()*40)}for(const p of fx){p.x+=p.vx;p.y+=p.vy;p.vy+=.08;p.vx*=.98;p.life--}for(let i=fx.length-1;i>=0;i--)if(fx[i].life<=0)fx.splice(i,1);for(const p of looseParts){if(p.life-->0){integrateNode(p.node,.42,.992);pointCollide(p.node)}}}
