'use strict';
/* GENESIS V107 — MORPHOLOGY
   Species-specific body topology, gait and high-detail rendering.
   Loaded after V106. No generic "same chain wearing a skin" for the major families.
*/
(function(){
const P=(x,y,r,m=1)=>Node(x,y,r,m);
function clearBody(c){c.nodes.length=0;c.constraints.length=0;c.limbs.length=0;c.tail.length=0;}
function addLimb(c,anchor,side,arm,reach,phase){const b=c.nodes[anchor];c.limbs.push({arm,anchor,side,phase,hand:P(b.x,b.y,2.2*c.g.size,.3),planted:false,target:null,reach:reach*c.g.limb*c.g.size,cool:rnd()*12,disabled:false});}
function chainTail(c,from,count,len,r){let prev=c.nodes[from];for(let i=0;i<count;i++){const q=P(prev.x-c.face*len,prev.y+(i%2?1:-1),Math.max(1.5,r-i*.35)*c.g.size,.45);c.tail.push(q);prev=q;}}
function rebuild(c){if(!c||c.v107Morph)return;c.v107Morph=1;const q=c.center(),x=q.x,y=q.y,s=c.g.size,f=c.spec.family,t=c.type;clearBody(c);
 if(f==='crab'){
   c.nodes.push(P(x+9*c.face,y,7.5*s,1.3),P(x-9*c.face,y,8*s,1.4),P(x,y-5*s,6.8*s,1.2),P(x,y+5*s,6.8*s,1.2));
   c.constraints.push([0,1,18*s],[0,2,10.5*s],[0,3,10.5*s],[1,2,10.5*s],[1,3,10.5*s],[2,3,10*s]);
   for(let i=0;i<6;i++){const a=i<3?0:1,side=i%2?-1:1;addLimb(c,a,side,false,30+(i%3)*3,i/6*TAU);}
   addLimb(c,0,-1,true,42,.1);addLimb(c,0,1,true,42,.6);
 } else if(f==='bug'){
   const mant=t==='widow_mantis',fly=t==='glass_cicada';
   c.nodes.push(P(x+9*c.face,y-2,5.2*s,1),P(x,y,6.4*s,1.1),P(x-11*c.face,y+1,8.8*s,1.25));
   c.constraints.push([0,1,10*s],[1,2,12*s],[0,2,21*s]);
   for(let i=0;i<4;i++)addLimb(c,i<2?1:2,i%2?-1:1,false,27+(i%2)*4,i/4*TAU);
   if(mant){addLimb(c,0,-1,true,48,.05);addLimb(c,0,1,true,48,.55);}else{addLimb(c,1,-1,false,25,.2);addLimb(c,1,1,false,25,.7);}
   if(fly)c.v107WingPhase=rnd()*TAU;
 } else if(f==='melt'){
   const n=t==='wax_slug'?6:5;for(let i=0;i<n;i++)c.nodes.push(P(x-i*8*c.face,y+(i%2?1:-1)*2,7.2*s*(1-i*.05),1));
   for(let i=0;i<n-1;i++)c.constraints.push([i,i+1,8.2*s]);for(let i=0;i<n-2;i++)c.constraints.push([i,i+2,15*s]);
   if(t==='melt_hound'){for(let i=0;i<4;i++)addLimb(c,i<2?1:3,i%2?-1:1,false,25,i/4*TAU);chainTail(c,n-1,3,7,3.2);}
 } else if(f==='bone'){
   c.nodes.push(P(x+10*c.face,y-3,5.5*s,1),P(x,y,5.2*s,1),P(x-11*c.face,y+2,5*s,1));c.constraints.push([0,1,11*s],[1,2,12*s],[0,2,22*s]);
   for(let i=0;i<(t==='bone_crawler'?6:4);i++)addLimb(c,i<2?0:2,i%2?-1:1,i>=4,31+(i%3)*2,i/6*TAU);chainTail(c,2,2,8,2.6);
 } else return;
 c.v107BaseY=y;
}
const SPAWN=spawnCreature;spawnCreature=function(type,a=null,b=null,x=null,y=null){const c=SPAWN(type,a,b,x,y);if(['crab','bug','melt','bone'].includes(c.spec.family))rebuild(c);return c;};
for(const c of creatures)if(['crab','bug','melt','bone'].includes(c.spec.family))rebuild(c);
const BC=bodyController;
bodyController=function(c){BC(c);if(!c.alive)return;const f=c.spec.family,m=desiredMotion(c),ground=c.nodes.some(n=>n.contact>0),phase=simTick*.12+c.id;
 if(f==='crab'){for(const n of c.nodes){n.y+=Math.sin(phase)*.025;n.x+=m.dx*m.speed*.42;}for(let i=0;i<c.limbs.length;i++){const l=c.limbs[i];if(!l.arm)l.phase=phase+i*.8;}if(ground&&Math.abs(m.dx)>.2&&simTick%18===c.id%18)for(const n of c.nodes)impulse(n,m.dx*.35,-.18);
 }else if(f==='bug'){if(c.spec.move==='fly'){const flap=.25+.18*Math.sin(simTick*.42+(c.v107WingPhase||0));for(const n of c.nodes){n.y-=flap;n.x+=m.dx*m.speed*.22;}}else if(ground){const stacc=(Math.sin(phase*1.7)>.2?1:.28);for(const n of c.nodes)n.x+=m.dx*m.speed*.24*stacc;}if(c.type==='widow_mantis'&&c.state==='AMBUSH'){for(const n of c.nodes){n.x-=m.dx*m.speed*.20;n.y+=.02;}}
 }else if(f==='melt'){for(let i=0;i<c.nodes.length;i++){const n=c.nodes[i],w=Math.sin(simTick*.11-i*.9+c.id);n.x+=m.dx*m.speed*(.13+.09*w);if(ground)n.y+=Math.max(0,w)*.025;}
 }else if(f==='bone'){if(ground&&Math.sin(phase*1.35)>.72)for(const n of c.nodes)n.x+=m.dx*m.speed*.36;}
};
const W=(n)=>worldToScreen(n.x,n.y), Z=()=>camera.zoom;
function shadow(c,rx,ry){const q=W(c.nodes[Math.min(1,c.nodes.length-1)]),z=Z();X.fillStyle='rgba(0,0,0,.28)';X.beginPath();X.ellipse(q.x,q.y+10*z,rx*z*c.g.size,ry*z*c.g.size,0,0,TAU);X.fill();}
function seg(a,b,w,col,hi=null){const A=W(a),B=W(b),ang=Math.atan2(B.y-A.y,B.x-A.x),z=Z();X.strokeStyle='rgba(5,8,7,.85)';X.lineWidth=w*z+2*z;X.lineCap='round';X.beginPath();X.moveTo(A.x,A.y);X.lineTo(B.x,B.y);X.stroke();X.strokeStyle=col;X.lineWidth=w*z;X.stroke();if(hi){X.strokeStyle=hi;X.globalAlpha=.28;X.lineWidth=Math.max(.6,w*.2*z);X.beginPath();X.moveTo(A.x-Math.sin(ang)*w*z*.18,A.y+Math.cos(ang)*w*z*.18);X.lineTo(B.x-Math.sin(ang)*w*z*.18,B.y+Math.cos(ang)*w*z*.18);X.stroke();X.globalAlpha=1;}}
function limb2(c,l,col,hi,spike=false){if(l.disabled)return;const a=c.nodes[l.anchor],A=W(a),H=W(l.hand),dx=H.x-A.x,dy=H.y-A.y,d=Math.hypot(dx,dy)||1,nx=-dy/d,ny=dx/d;const bend=l.side*(l.arm?-1:1)*Math.min(18*Z(),d*.34),K={x:(A.x+H.x)*.5+nx*bend,y:(A.y+H.y)*.5+ny*bend};X.strokeStyle='#0b0e0d';X.lineWidth=(l.arm?5:3.6)*Z()*c.g.size;X.lineCap='round';X.beginPath();X.moveTo(A.x,A.y);X.lineTo(K.x,K.y);X.lineTo(H.x,H.y);X.stroke();X.strokeStyle=col;X.lineWidth=(l.arm?3.1:2.1)*Z()*c.g.size;X.stroke();if(spike){X.strokeStyle=hi;X.lineWidth=.75*Z();for(let i=1;i<4;i++){const t=i/4,px=lerp(K.x,H.x,t),py=lerp(K.y,H.y,t);X.beginPath();X.moveTo(px,py);X.lineTo(px-c.face*4*Z(),py+4*Z());X.stroke();}}}
function drawCrab(c,t){shadow(c,28,7);const z=Z(),q=c.center(),S=worldToScreen(q.x,q.y),w=24*z*c.g.size,h=13*z*c.g.size;for(let i=0;i<c.limbs.length;i++){const l=c.limbs[i];limb2(c,l,c.spec.color,c.spec.hi,false);if(l.arm&&!l.disabled){const H=W(l.hand),r=5.5*z*c.g.size;X.fillStyle=c.spec.hi;X.beginPath();X.ellipse(H.x,H.y,r*1.35,r,.15*c.face,0,TAU);X.fill();X.strokeStyle='#241c18';X.lineWidth=1.1*z;X.beginPath();X.moveTo(H.x+c.face*r*.2,H.y);X.lineTo(H.x+c.face*r*1.5,H.y-r*.6);X.moveTo(H.x+c.face*r*.2,H.y);X.lineTo(H.x+c.face*r*1.5,H.y+r*.55);X.stroke();}}
 const gr=X.createLinearGradient(S.x,S.y-h,S.x,S.y+h);gr.addColorStop(0,c.spec.hi);gr.addColorStop(.38,c.spec.color);gr.addColorStop(1,'#20241e');X.fillStyle=gr;X.beginPath();X.moveTo(S.x-w,S.y+2*z);X.quadraticCurveTo(S.x-w*.8,S.y-h,S.x,S.y-h*1.1);X.quadraticCurveTo(S.x+w*.8,S.y-h,S.x+w,S.y+2*z);X.quadraticCurveTo(S.x+w*.7,S.y+h,S.x,S.y+h*.9);X.quadraticCurveTo(S.x-w*.7,S.y+h,S.x-w,S.y+2*z);X.fill();X.strokeStyle='#111512';X.lineWidth=1.7*z;X.stroke();X.strokeStyle='rgba(225,238,210,.22)';X.lineWidth=.8*z;for(let i=-2;i<=2;i++){X.beginPath();X.moveTo(S.x+i*w*.28,S.y-h*.75);X.quadraticCurveTo(S.x+i*w*.18,S.y,S.x+i*w*.25,S.y+h*.55);X.stroke();}for(let i=0;i<9;i++){const a=hash(c.id*113+i)*TAU,rr=Math.sqrt(hash(c.id*179+i))*w*.72;X.fillStyle='rgba(0,0,0,.10)';X.beginPath();X.arc(S.x+Math.cos(a)*rr,S.y+Math.sin(a)*rr*.38,Math.max(.6,1.2*z),0,TAU);X.fill();}for(const side of[-1,1]){X.strokeStyle=c.spec.color;X.lineWidth=1.5*z;X.beginPath();X.moveTo(S.x+side*w*.25,S.y-h*.65);X.lineTo(S.x+side*w*.34,S.y-h*1.25);X.stroke();X.fillStyle='#d8e1c7';X.beginPath();X.arc(S.x+side*w*.34,S.y-h*1.25,2.3*z,0,TAU);X.fill();X.fillStyle='#10130f';X.beginPath();X.arc(S.x+side*w*.34+c.face*.7*z,S.y-h*1.25,1.1*z,0,TAU);X.fill();}}
function drawBug(c,t){const mant=c.type==='widow_mantis',fly=c.type==='glass_cicada',z=Z();shadow(c,24,6);for(const l of c.limbs)limb2(c,l,c.spec.color,c.spec.hi,mant&&l.arm);const H=W(c.nodes[0]),T=W(c.nodes[1]),A=W(c.nodes[2]),ang=Math.atan2(H.y-A.y,H.x-A.x);if(fly){const flap=Math.sin(t*.035+c.id)*.15;X.fillStyle='rgba(196,232,228,.18)';X.strokeStyle='rgba(211,244,238,.36)';X.lineWidth=.8*z;for(const s of[-1,1]){X.save();X.translate(T.x,T.y);X.rotate(s*(.55+flap));X.beginPath();X.ellipse(-7*z,0,18*z,7*z,-.15,0,TAU);X.fill();X.stroke();for(let k=0;k<3;k++){X.beginPath();X.moveTo(0,0);X.lineTo((-7-9*k)*z,s*(k-1)*2*z);X.stroke();}X.restore();}}X.save();X.translate(A.x,A.y);X.rotate(ang);const ag=X.createLinearGradient(0,-10*z,0,10*z);ag.addColorStop(0,c.spec.hi);ag.addColorStop(.45,c.spec.color);ag.addColorStop(1,'#1d241b');X.fillStyle=ag;X.beginPath();X.ellipse(0,0,(mant?10:13)*z*c.g.size,(mant?6:9)*z*c.g.size,0,0,TAU);X.fill();if(!mant){X.strokeStyle='rgba(0,0,0,.28)';X.lineWidth=1*z;X.beginPath();X.moveTo(0,-8*z);X.lineTo(0,8*z);X.stroke();}X.restore();X.fillStyle=c.spec.color;X.beginPath();X.ellipse(T.x,T.y,(mant?6:8)*z*c.g.size,(mant?8:7)*z*c.g.size,ang,0,TAU);X.fill();X.fillStyle=c.spec.hi;X.beginPath();if(mant){X.moveTo(H.x+c.face*8*z,H.y);X.lineTo(H.x-c.face*5*z,H.y-6*z);X.lineTo(H.x-c.face*5*z,H.y+6*z);X.closePath();}else X.ellipse(H.x,H.y,6*z*c.g.size,5*z*c.g.size,ang,0,TAU);X.fill();X.fillStyle='#0b0e0b';for(const side of[-1,1]){X.beginPath();X.arc(H.x+c.face*3*z,H.y+side*2.2*z,1.2*z,0,TAU);X.fill();}X.strokeStyle=c.spec.hi;X.lineWidth=.75*z;for(const side of[-1,1]){X.beginPath();X.moveTo(H.x+c.face*4*z,H.y+side*2*z);X.quadraticCurveTo(H.x+c.face*10*z,H.y+side*7*z,H.x+c.face*14*z,H.y+side*10*z);X.stroke();}}
function drawMelt(c,t){const z=Z(),pts=c.nodes.map(W),q=c.center(),S=W({x:q.x,y:q.y});shadow(c,28,7);if(pts.length<2)return;X.beginPath();const top=[],bot=[];for(let i=0;i<pts.length;i++){const a=pts[Math.max(0,i-1)],b=pts[Math.min(pts.length-1,i+1)],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1,nx=-dy/l,ny=dx/l,r=c.nodes[i].r*z*(1.15+.10*Math.sin(t*.006+i+c.id));top.push({x:pts[i].x+nx*r,y:pts[i].y+ny*r});bot.push({x:pts[i].x-nx*r,y:pts[i].y-ny*r});}X.moveTo(top[0].x,top[0].y);for(let i=1;i<top.length;i++)X.quadraticCurveTo(top[i-1].x,top[i-1].y,top[i].x,top[i].y);for(let i=bot.length-1;i>=0;i--)X.quadraticCurveTo(bot[Math.min(bot.length-1,i+1)].x,bot[Math.min(bot.length-1,i+1)].y,bot[i].x,bot[i].y);X.closePath();const gr=X.createLinearGradient(S.x,S.y-20*z,S.x,S.y+18*z);gr.addColorStop(0,'rgba(205,244,196,.82)');gr.addColorStop(.35,c.spec.color);gr.addColorStop(1,'rgba(25,48,39,.94)');X.fillStyle=gr;X.fill();X.strokeStyle='rgba(190,244,207,.22)';X.lineWidth=1.1*z;X.stroke();X.save();X.clip();for(let i=0;i<6;i++){const p=pts[i%pts.length],rr=(2+hash(c.id*91+i)*3)*z;X.fillStyle=i%2?'rgba(226,255,224,.10)':'rgba(8,30,25,.16)';X.beginPath();X.arc(p.x+(hash(i*31+c.id)-.5)*10*z,p.y+(hash(i*57+c.id)-.5)*8*z,rr,0,TAU);X.fill();}X.restore();if(c.type==='melt_hound')for(const l of c.limbs)limb2(c,l,c.spec.color,c.spec.hi,false);const H=pts[0];X.fillStyle='#07100c';X.beginPath();X.ellipse(H.x+c.face*4*z,H.y-2*z,1.5*z,2*z,0,0,TAU);X.fill();}
function drawBone(c,t){const z=Z();shadow(c,24,5);X.strokeStyle='#d8d0bd';X.lineCap='round';for(let i=0;i<c.nodes.length-1;i++)seg(c.nodes[i],c.nodes[i+1],2.4,c.spec.hi,'#fff7df');for(const l of c.limbs){if(l.disabled)continue;const A=c.nodes[l.anchor],H=l.hand;seg(A,H,1.4,c.spec.hi,'#fff7df');const hp=W(H);X.fillStyle='#d7cebb';X.beginPath();X.arc(hp.x,hp.y,1.8*z,0,TAU);X.fill();}for(let i=0;i<c.tail.length;i++)seg(i?c.tail[i-1]:c.nodes[c.nodes.length-1],c.tail[i],1.3,c.spec.hi);const H=W(c.head()),r=5.5*z*c.g.size;X.fillStyle='#e4dac5';X.beginPath();X.moveTo(H.x+c.face*r,H.y);X.lineTo(H.x-c.face*r*.7,H.y-r*.75);X.lineTo(H.x-c.face*r*.9,H.y+r*.65);X.closePath();X.fill();X.fillStyle='#14120f';for(const side of[-1,1]){X.beginPath();X.arc(H.x+c.face*r*.12,H.y+side*r*.26,r*.18,0,TAU);X.fill();}}
function drawSpider(c,t){const z=Z(),q=c.center(),S=worldToScreen(q.x,q.y),rear=W(c.nodes[c.nodes.length-1]),head=W(c.head());shadow(c,25,6);for(const l of c.limbs)limb2(c,l,c.spec.color,c.spec.hi,false);const rg=X.createRadialGradient(rear.x-4*z,rear.y-5*z,1,rear.x,rear.y,14*z*c.g.size);rg.addColorStop(0,c.spec.hi);rg.addColorStop(.45,c.spec.color);rg.addColorStop(1,'#241d28');X.fillStyle=rg;X.beginPath();X.ellipse(rear.x,rear.y,13*z*c.g.size,10*z*c.g.size,0,0,TAU);X.fill();X.fillStyle=c.spec.color;X.beginPath();X.ellipse(head.x,head.y,8*z*c.g.size,6*z*c.g.size,0,0,TAU);X.fill();X.fillStyle='#d9d0c8';for(let i=0;i<4;i++){const a=(i-1.5)*.9;X.beginPath();X.arc(head.x+c.face*4*z+Math.cos(a)*2*z,head.y+Math.sin(a)*3*z,1*z,0,TAU);X.fill();}}
function drawLizard(c,t){const z=Z(),pts=c.nodes.map(W);shadow(c,28,7);for(const l of c.limbs)limb2(c,l,c.spec.color,c.spec.hi,false);if(c.tail.length){X.strokeStyle=c.spec.color;X.lineWidth=6*z*c.g.size;X.beginPath();let p=W(c.nodes[c.nodes.length-1]);X.moveTo(p.x,p.y);for(const n of c.tail){p=W(n);X.lineTo(p.x,p.y)}X.stroke();}const q=c.center(),S=worldToScreen(q.x,q.y),gr=X.createLinearGradient(S.x,S.y-12*z,S.x,S.y+12*z);gr.addColorStop(0,c.spec.hi);gr.addColorStop(.35,c.spec.color);gr.addColorStop(1,'#20281e');X.fillStyle=gr;X.beginPath();for(let i=0;i<pts.length;i++){const p=pts[i];if(i===0)X.moveTo(p.x+c.face*8*z,p.y);else X.lineTo(p.x,p.y);}for(let i=pts.length-1;i>=0;i--)X.lineTo(pts[i].x,pts[i].y+7*z*c.g.size);X.closePath();X.fill();const H=pts[0];X.fillStyle='#080b08';X.beginPath();X.arc(H.x+c.face*7*z,H.y-2*z,1.5*z,0,TAU);X.fill();}
function drawGrazer(c,t){const z=Z(),q=c.center(),S=worldToScreen(q.x,q.y);shadow(c,30,8);for(const l of c.limbs)limb2(c,l,c.spec.color,c.spec.hi,false);X.fillStyle=c.spec.color;X.beginPath();X.ellipse(S.x-5*c.face*z,S.y,20*z*c.g.size,10*z*c.g.size,0,0,TAU);X.fill();const H=W(c.head());X.beginPath();X.ellipse(H.x+c.face*5*z,H.y-4*z,8*z*c.g.size,6*z*c.g.size,0,0,TAU);X.fill();X.strokeStyle=c.spec.hi;X.lineWidth=1.5*z;for(const s of[-1,1]){X.beginPath();X.moveTo(H.x+c.face*2*z,H.y-8*z);X.quadraticCurveTo(H.x-c.face*2*z,H.y-15*z,H.x-c.face*7*z,H.y+s*2*z-14*z);X.stroke();}X.fillStyle='#111';X.beginPath();X.arc(H.x+c.face*9*z,H.y-5*z,1.3*z,0,TAU);X.fill();}
function drawHunter(c,t){const z=Z(),q=c.center(),S=worldToScreen(q.x,q.y);shadow(c,31,7);for(const l of c.limbs)limb2(c,l,c.spec.color,c.spec.hi,false);X.fillStyle=c.spec.color;X.beginPath();X.ellipse(S.x-4*c.face*z,S.y,22*z*c.g.size,8*z*c.g.size,0,0,TAU);X.fill();const H=W(c.head());X.beginPath();X.moveTo(H.x+c.face*13*z,H.y);X.lineTo(H.x-c.face*6*z,H.y-6*z);X.lineTo(H.x-c.face*7*z,H.y+6*z);X.closePath();X.fill();X.fillStyle='#0a0c09';X.beginPath();X.arc(H.x+c.face*5*z,H.y-2*z,1.4*z,0,TAU);X.fill();X.strokeStyle='#e1d7bd';X.lineWidth=.8*z;for(let i=0;i<3;i++){X.beginPath();X.moveTo(H.x+c.face*(8+i*2)*z,H.y+2*z);X.lineTo(H.x+c.face*(9+i*2)*z,H.y+5*z);X.stroke();}}
function drawAmphib(c,t){const z=Z(),q=c.center(),S=worldToScreen(q.x,q.y);shadow(c,21,7);for(const l of c.limbs)limb2(c,l,c.spec.color,c.spec.hi,false);X.fillStyle=c.spec.color;X.beginPath();X.ellipse(S.x,S.y,15*z*c.g.size,10*z*c.g.size,0,0,TAU);X.fill();const H=W(c.head());X.fillStyle=c.spec.hi;X.beginPath();X.ellipse(H.x+c.face*4*z,H.y-3*z,7*z,5*z,0,0,TAU);X.fill();X.fillStyle='#121512';for(const s of[-1,1]){X.beginPath();X.arc(H.x+c.face*7*z,H.y+s*3*z-4*z,1.5*z,0,TAU);X.fill();}}
function drawWinged(c,t){const z=Z(),q=c.center(),S=worldToScreen(q.x,q.y),flap=Math.sin(t*.04+c.id)*.28;shadow(c,18,5);for(const l of c.limbs)limb2(c,l,c.spec.color,c.spec.hi,false);X.fillStyle='rgba(190,225,228,.20)';X.strokeStyle='rgba(215,242,240,.32)';for(const s of[-1,1]){X.save();X.translate(S.x,S.y);X.rotate(s*(.6+flap));X.beginPath();X.ellipse(-5*z,0,21*z,6*z,-.1,0,TAU);X.fill();X.stroke();X.restore();}X.fillStyle=c.spec.color;X.beginPath();X.ellipse(S.x,S.y,12*z*c.g.size,6*z*c.g.size,0,0,TAU);X.fill();const H=W(c.head());X.fillStyle=c.spec.hi;X.beginPath();X.arc(H.x,H.y,5*z,0,TAU);X.fill();}
const DRAW=drawCreature;
drawCreature=function(c,t){if(c.gone)return;const f=c.spec.family;if(f==='crab')return drawCrab(c,t);if(f==='bug')return drawBug(c,t);if(f==='melt')return drawMelt(c,t);if(f==='bone')return drawBone(c,t);if(f==='spider'||f==='silkborn')return drawSpider(c,t);if(f==='lizard'||f==='reedscale')return drawLizard(c,t);if(f==='grazer')return drawGrazer(c,t);if(f==='hunter')return drawHunter(c,t);if(f==='amphib')return drawAmphib(c,t);if(f==='winged')return drawWinged(c,t);return DRAW(c,t);};
const UI=updateUI;updateUI=function(){UI();if(stats)stats.innerHTML+=`<br><span class="dim">V107 morphology · species-specific bodies + gaits</span>`;};
})();
