import * as pc from 'https://cdn.jsdelivr.net/npm/playcanvas@2.21.1/build/playcanvas.mjs';
const $=id=>document.getElementById(id),canvas=$('app'),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let seed=0x62ab91ef;const rnd=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296},rr=(a,b)=>a+rnd()*(b-a);
const cfg={temp:335,pressure:1.2,diff:1,bond:1,activation:1,uv:.7,mutation:.02,abiogenesis:.7,orbit:1,lum:.82,activity:1.35,mass:.72,atm:1.4,greenhouse:.55,ocean:.76,geo:.9,impacts:.35,tilt:18,day:18,speed:1,maxAtoms:720,quality:1.2};
const spec={temp:[' K',0],pressure:[' atm',1],diff:['×',2],bond:['×',2],activation:['×',2],uv:['×',2],mutation:['',3],abiogenesis:['×',2],orbit:[' AU',2],lum:[' L☉',2],activity:['×',2],mass:[' M⊕',2],atm:['×',2],greenhouse:['×',2],ocean:['',2],geo:['×',2],impacts:['×',2],tilt:['°',0],day:[' h',0],speed:['×',2],maxAtoms:['',0],quality:['×',1]};
for(const [k,[u,d]] of Object.entries(spec)){const e=$(k),o=$(k+'V');const f=()=>{cfg[k]=+e.value;o.textContent=cfg[k].toFixed(d)+u};e.addEventListener('input',f);f()}
$('settings').onclick=()=>panel.style.display=panel.style.display==='block'?'none':'block';$('close').onclick=()=>panel.style.display='none';
let linked=true;$('link').onclick=()=>{linked=!linked;$('link').textContent=linked?'Planet Link ON':'Planet Link OFF'};
try{
const device=await pc.createGraphicsDevice(canvas,{deviceTypes:[pc.DEVICETYPE_WEBGPU,pc.DEVICETYPE_WEBGL2],antialias:true,depth:true,powerPreference:'high-performance'}),app=new pc.Application(canvas,{graphicsDevice:device});app.setCanvasFillMode(pc.FILLMODE_FILL_WINDOW);app.setCanvasResolution(pc.RESOLUTION_AUTO);app.scene.ambientLight=new pc.Color(.025,.04,.055);app.scene.exposure=1.4;app.scene.toneMapping=pc.TONEMAP_ACES;app.start();$('backend').textContent=device.isWebGPU?'WEBGPU':'WEBGL2';
const mkMat=(c,o=.95,g=.75,em=.05)=>{const m=new pc.StandardMaterial();m.diffuse=new pc.Color(...c);m.opacity=o;m.gloss=g;m.metalness=.02;m.emissive=new pc.Color(c[0]*em,c[1]*em,c[2]*em);m.emissiveIntensity=.7;if(o<1){m.blendType=pc.BLEND_NORMAL;m.depthWrite=false;m.cull=pc.CULLFACE_NONE}m.update();return m},prim=(t,n,m,p=app.root)=>{const e=new pc.Entity(n);e.addComponent('render',{type:t,material:m});p.addChild(e);return e};
const mats={star:mkMat([1,.47,.08],1,.96,.8),rock:mkMat([.26,.16,.1],1,.55,.02),ocean:mkMat([.02,.18,.28],.68,.98,.08),atm:mkMat([.16,.52,.72],.12,.99,.16),dust:mkMat([.7,.38,.16],.78,.58,.12),bond:mkMat([.65,.78,.82],.44,.85,.04),env:mkMat([.18,.64,.72],.13,.97,.08),poly:mkMat([.64,.22,.95],.2,.93,.22)};
const aM=[mkMat([.45,.5,.54],.98,.72),mkMat([.95,.97,1],.98,.86),mkMat([.96,.1,.14],.98,.78,.2),mkMat([.14,.28,.95],.98,.8,.18),mkMat([1,.55,.07],.98,.76,.18),mkMat([.95,.8,.08],.98,.72,.16)],rad=[.14,.09,.13,.13,.15,.15],val=[4,1,2,3,5,2],mix=[0,0,0,0,1,1,1,1,1,1,2,2,2,3,3,4,5];
const key=new pc.Entity('sunlight');key.addComponent('light',{type:'directional',color:new pc.Color(1,.84,.63),intensity:2.8,castShadows:true,shadowResolution:1024});key.setEulerAngles(38,-28,0);app.root.addChild(key);const fill=new pc.Entity('ocean glow');fill.addComponent('light',{type:'omni',color:new pc.Color(.08,.5,.64),intensity:8,range:30});fill.setPosition(-6,4,5);app.root.addChild(fill);
const planet=prim('sphere','planet',mats.rock);planet.setPosition(0,-14,0);const ocean=prim('sphere','ocean',mats.ocean);ocean.setPosition(0,-14,0);const atm=prim('sphere','atmosphere',mats.atm);atm.setPosition(0,-14,0);const star=prim('sphere','young star',mats.star);star.setPosition(-64,34,-78);
const debris=[];for(let i=0;i<110;i++){const e=prim('sphere','planetesimal',mats.dust),r=rr(20,60),ang=rr(0,Math.PI*2),sc=rr(.06,.24),h=rr(-5,5);e.setScale(sc,sc*rr(.7,1.4),sc);debris.push({e,r,ang,h,w:rr(.02,.08),m:sc**3})}
const chamber=prim('cylinder','primordial basin',mats.ocean);chamber.setScale(12,.16,12);chamber.setPosition(0,-5.7,0);
const camera=new pc.Entity('camera');camera.addComponent('camera',{clearColor:new pc.Color(.002,.006,.012),fov:48,nearClip:.025,farClip:260});app.root.addChild(camera);let yaw=-20,pitch=14,dist=22,target=new pc.Vec3(0,0,0),solar=false;function cam(){const py=pitch*pc.math.DEG_TO_RAD,yy=yaw*pc.math.DEG_TO_RAD,cp=Math.cos(py);camera.setPosition(target.x+dist*cp*Math.sin(yy),target.y+dist*Math.sin(py),target.z+dist*cp*Math.cos(yy));camera.lookAt(target)}cam();
const atoms=[],bonds=[],hash=new Map();let planetHeat=1.1,accreted=0,impact=0,stats={mol:0,poly:0,rep:0,proto:0};const hk=p=>`${Math.floor(p.x)},${Math.floor(p.y)},${Math.floor(p.z)}`;
function atom(type,p){if(atoms.length>=cfg.maxAtoms)return null;const e=prim('sphere','atom',aM[type]);e.setScale(rad[type],rad[type],rad[type]);e.setPosition(p);const a={type,p:p.clone(),prev:p.clone().add(new pc.Vec3(rr(-.03,.03),rr(-.03,.03),rr(-.03,.03))),b:[],e,energy:rr(0,.2)};atoms.push(a);return a}
function bond(a,b){if(!a||!b||a===b||a.b.length>=val[a.type]||b.b.length>=val[b.type]||a.b.some(x=>x.o===b))return;const e=bonds.length<480?prim('cylinder','bond',mats.bond):null,ob={a,b,rest:(rad[a.type]+rad[b.type])*2.1,e};a.b.push({o:b,l:ob});b.b.push({o:a,l:ob});bonds.push(ob)}
function spawn(n=140){for(let i=0;i<n&&atoms.length<cfg.maxAtoms;i++){const t=mix[Math.floor(rr(0,mix.length))],a=rr(0,Math.PI*2),r=Math.sqrt(rnd())*8;atom(t,new pc.Vec3(Math.cos(a)*r,rr(-4,4.5),Math.sin(a)*r))}}
function rebuild(){hash.clear();for(const a of atoms){const k=hk(a.p);if(!hash.has(k))hash.set(k,[]);hash.get(k).push(a)}}
function near(p){const r=[];for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++){const q=hash.get(`${Math.floor(p.x)+x},${Math.floor(p.y)+y},${Math.floor(p.z)+z}`);if(q)r.push(...q)}return r}
function integrate(dt){const th=Math.sqrt(cfg.temp/335)*cfg.diff;for(const a of atoms){const v=a.p.clone().sub(a.prev).mulScalar(.985),old=a.p.clone();v.x+=rr(-1,1)*th*.018;v.y+=rr(-1,1)*th*.018;v.z+=rr(-1,1)*th*.018;a.p.add(v.mulScalar(dt*60));a.prev.copy(old);if(a.p.length()>9.3)a.p.normalize().mulScalar(9.3);a.p.y=clamp(a.p.y,-5.1,5.5);a.e.setPosition(a.p)}}
function solve(){for(let k=0;k<2;k++)for(const b of bonds){const d=b.b.p.clone().sub(b.a.p),l=Math.max(.001,d.length()),c=d.mulScalar((l-b.rest)/l*.36);b.a.p.add(c);b.b.p.sub(c)}for(const b of bonds)if(b.e){const d=b.b.p.clone().sub(b.a.p),m=b.a.p.clone().add(b.b.p).mulScalar(.5),q=new pc.Quat();b.e.setPosition(m);q.setFromDirections(pc.Vec3.UP,d.clone().normalize());b.e.setRotation(q);b.e.setScale(.025,d.length()*.5,.025)}}
function chemistry(dt){rebuild();const tf=Math.exp((cfg.temp-335)/170);for(const a of atoms){for(const b of near(a.p)){if(a===b||a.p.distance(b.p)>.55)continue;if(a.b.length<val[a.type]&&b.b.length<val[b.type]&&!a.b.some(x=>x.o===b)&&rnd()<dt*.34*tf*cfg.pressure/Math.max(.2,cfg.activation))bond(a,b)}}const seen=new Set(),cls=[];for(const a of atoms){if(seen.has(a))continue;const st=[a],c=[];seen.add(a);while(st.length){const x=st.pop();c.push(x);for(const z of x.b)if(!seen.has(z.o)){seen.add(z.o);st.push(z.o)}}cls.push(c)}let poly=0,rep=0,proto=0;const reps=[];for(const c of cls){const cnt=[0,0,0,0,0,0];c.forEach(a=>cnt[a.type]++);const heavy=c.length-cnt[1],p=heavy>=8&&cnt[0]>=3&&(cnt[2]+cnt[3]+cnt[4])>=3,r=p&&cnt[4]>=2&&cnt[3]>=3;poly+=p;rep+=r;if(r)reps.push(c);if(r&&cnt[0]>=5&&cnt[4]>=2)proto++}stats={mol:cls.length,poly,rep,proto};}
function planetStep(dt){const mass=Math.max(.1,cfg.mass+accreted),r=Math.pow(mass,.27),g=mass/(r*r),flux=cfg.lum/(cfg.orbit*cfg.orbit),teq=278*Math.pow(Math.max(.05,flux),.25),ret=clamp(cfg.atm*g/(.55+cfg.activity*.2/cfg.orbit),.03,8);planetHeat+=(cfg.geo*.0015+impact*.004-planetHeat*.0008)*dt*60;impact=Math.max(0,impact-dt*.15);const temp=teq+42*cfg.greenhouse*Math.log1p(ret)+18*planetHeat+8*(1-cfg.ocean),uv=clamp(cfg.activity*flux*Math.exp(-ret*.18),0,3);if(linked){cfg.temp+=(temp-cfg.temp)*dt*.05;cfg.pressure+=(ret-cfg.pressure)*dt*.05;cfg.uv+=(uv-cfg.uv)*dt*.06;for(const k of ['temp','pressure','uv']){const e=$(k),o=$(k+'V');if(document.activeElement!==e){e.value=cfg[k];o.textContent=cfg[k].toFixed(spec[k][1])+spec[k][0]}}}const pr=15*r;planet.setScale(pr,pr*.955,pr);ocean.setScale(pr*(1+.012*cfg.ocean),pr*.955*(1+.012*cfg.ocean),pr*(1+.012*cfg.ocean));atm.setScale(pr*(1.04+.024*ret),pr*.955*(1.04+.024*ret),pr*(1.04+.024*ret));star.setScale(8.5*Math.pow(cfg.lum,.22),8.5*Math.pow(cfg.lum,.22),8.5*Math.pow(cfg.lum,.22));for(const b of debris){b.ang+=b.w*dt*(1+cfg.impacts*.3);b.r-=dt*.002*cfg.impacts;if(b.r<16){accreted+=b.m*.02;planetHeat+=b.m;b.r=rr(30,60)}b.e.setPosition(Math.cos(b.ang)*b.r,-14+b.h,Math.sin(b.ang)*b.r)}if(rnd()<dt*.002*cfg.impacts){impact+=rr(.1,.6);planetHeat+=rr(.03,.15)}$('planet').textContent=`${mass.toFixed(2)}M⊕ ${temp.toFixed(0)}K`;$('star').textContent=`${cfg.lum.toFixed(2)}L☉`;return{mass,g,temp,ret,uv,flux}}
spawn(380);for(let i=0;i<40;i++){integrate(1/120);chemistry(1/120);solve()}
$('mix').onclick=()=>spawn(130);$('pulse').onclick=()=>{impact+=.5;for(const a of atoms)a.energy=clamp(a.energy+rr(.1,.35),0,1)};$('impact').onclick=()=>{impact+=1.8;planetHeat+=.8;for(const a of atoms)a.prev.add(new pc.Vec3(rr(-.2,.2),rr(-.2,.2),rr(-.2,.2)))};$('solar').onclick=()=>{solar=!solar;if(solar){dist=96;yaw=-36;pitch=20;$('solar').textContent='Micro View'}else{dist=22;yaw=-20;pitch=14;$('solar').textContent='Solar View'}cam()};$('reset').onclick=()=>location.reload();
const pts=new Map();let last={x:0,y:0},pinch=0;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});last={x:e.clientX,y:e.clientY};if(pts.size===2){const p=[...pts.values()];pinch=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}});canvas.addEventListener('pointermove',e=>{if(!pts.has(e.pointerId))return;pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===1){yaw-=(e.clientX-last.x)*.22;pitch=clamp(pitch+(e.clientY-last.y)*.18,-78,78);last={x:e.clientX,y:e.clientY};cam()}else{const p=[...pts.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);dist=clamp(dist*pinch/Math.max(1,d),4,135);pinch=d;cam()}});canvas.addEventListener('pointerup',e=>pts.delete(e.pointerId));canvas.addEventListener('wheel',e=>{e.preventDefault();dist=clamp(dist*Math.exp(e.deltaY*.001),4,135);cam()},{passive:false});
let acc=0,frames=0,ft=0,fps=60,env={};app.on('update',dt=>{dt=Math.min(dt,.04);acc+=dt*cfg.speed;let n=0;while(acc>=1/90&&n<7){env=planetStep(1/90);integrate(1/90);chemistry(1/90);solve();acc-=1/90;n++}frames++;ft+=dt;if(ft>.5){fps=frames/ft;frames=0;ft=0}$('atoms').textContent=atoms.length;$('bonds').textContent=bonds.length;$('mols').textContent=stats.mol;$('poly').textContent=stats.poly;$('life').textContent=stats.proto;$('fps').textContent=Math.round(fps);$('scale').textContent=dist<7?'ATOMIC':dist<16?'MOLECULAR':dist<35?'MESOSCALE':dist<70?'PLANET':'SYSTEM';$('readout').innerHTML=`Scale <b>${$('scale').textContent}</b> · explicit atoms ${atoms.length}/${cfg.maxAtoms} · bonds ${bonds.length}<br>Molecular graphs ${stats.mol} · polymers ${stats.poly} · replicator-like networks ${stats.rep} · proto-life candidates ${stats.proto}<br>Planet ${(cfg.mass+accreted).toFixed(2)} M⊕ · ${env.g?.toFixed(2)||'--'} g-relative · atmosphere ${env.ret?.toFixed(2)||'--'} atm · ocean ${(cfg.ocean*100).toFixed(0)}%<br>Surface ${cfg.temp.toFixed(0)} K · stellar flux ${env.flux?.toFixed(2)||'--'}× · UV ${cfg.uv.toFixed(2)}× · geothermal ${cfg.geo.toFixed(2)}×<br>Planet/star state is coupled into the atom chemistry. Zooming changes representation, not the underlying world.`;app.graphicsDevice.maxPixelRatio=Math.min(devicePixelRatio||1,clamp(cfg.quality,.5,2))});addEventListener('resize',()=>app.resizeCanvas());
}catch(e){$('fatal').style.display='block';$('fatal').textContent='GENESIS PCX4 HALTED\n\n'+String(e?.stack||e);console.error(e)}