(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.GenesisMatter=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const MODEL={id:'genesis-matter-lj2d-v4',name:'GENESIS Matter Lab — coarse matter + reversible association + toy reaction events',integrator:'velocity-verlet',potential:'shifted Lennard-Jones + harmonic active associations',boundary:'periodic minimum-image',units:'reduced units',claims:['2D coarse-grained particle dynamics','seeded reversible pair association','explicit forward/reverse toy reaction event accounting','particle internal-state transformation with conserved particle count'],nonClaims:['not literal atoms','not chemical bonds','not validated reaction chemistry','not cells/life/evolution']};
const SPECIES=[{id:0,name:'A',mass:1,sigma:.030,epsilon:1},{id:1,name:'B',mass:1.35,sigma:.034,epsilon:.78},{id:2,name:'C',mass:.82,sigma:.027,epsilon:1.18}];
function rng32(seed){let s=(seed>>>0)||0x6d2b79f5;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return(s>>>0)/4294967296}}function gauss(r){let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}function clamp(v,a,b){return v<a?a:v>b?b:v}function wrap(v,L){v%=L;return v<0?v+L:v}function minImage(d,L){return d-L*Math.round(d/L)}function key(i,j){return i<j?i+':'+j:j+':'+i}
class MatterWorld{
constructor(o={}){this.width=o.width||1;this.height=o.height||.62;this.count=Math.max(8,Math.min(256,o.count||120));this.seed=(o.seed??0x51a7c0de)>>>0;this.rng=rng32(this.seed);this.attraction=o.attraction??1;this.cutoffScale=2.5;this.stepIndex=0;this.time=0;this.interventions=0;this.particles=[];this._potential=0;this._virial=0;this.associationEnabled=o.associationEnabled??true;this.associationRate=clamp(o.associationRate??28,0,250);this.dissociationRate=clamp(o.dissociationRate??1.15,0,100);this.associationSpring=clamp(o.associationSpring??70,1,500);this.associations=new Map();this.associationFormed=0;this.associationBroken=0;this.associationLifetimeTotal=0;this.reactionEnabled=o.reactionEnabled??true;this.reactionRate=clamp(o.reactionRate??18,0,250);this.activationAge=clamp(o.activationAge??.015,0,.5);this.reactionsForward=0;this.reactionsReverse=0;this.reactionHistory=[];this._init(o.temperature??.42);this._forces=this.particles.map(()=>({x:0,y:0}));this.computeForces()}
_init(T){const aspect=this.width/this.height,cols=Math.ceil(Math.sqrt(this.count*aspect)),rows=Math.ceil(this.count/cols),sx=this.width/cols,sy=this.height/rows;let i=0;for(let r=0;r<rows&&i<this.count;r++)for(let c=0;c<cols&&i<this.count;c++){const sp=i%3,s=SPECIES[sp],j=.08*Math.min(sx,sy);this.particles.push({x:wrap((c+.5)*sx+(this.rng()-.5)*j,this.width),y:wrap((r+.5)*sy+(this.rng()-.5)*j,this.height),vx:gauss(this.rng)*Math.sqrt(T/s.mass),vy:gauss(this.rng)*Math.sqrt(T/s.mass),species:sp,state:0});i++}this._removeDrift();this._rescaleTemperature(T)}
_removeDrift(){let px=0,py=0,m=0;for(const p of this.particles){const q=SPECIES[p.species].mass;px+=p.vx*q;py+=p.vy*q;m+=q}for(const p of this.particles){p.vx-=px/m;p.vy-=py/m}}
_rescaleTemperature(T){const t=this.temperature();if(t>0){const f=Math.sqrt(T/t);for(const p of this.particles){p.vx*=f;p.vy*=f}}}setTemperature(T){T=clamp(+T||.42,.02,3);this._removeDrift();this._rescaleTemperature(T);return this.temperature()}setAttraction(v){this.attraction=clamp(+v||1,.15,2.5);this.computeForces()}setAssociationEnabled(v){this.associationEnabled=!!v;if(!v)this.breakAllAssociations('disabled')}setAssociationKinetics(o={}){if(o.onRate!==undefined)this.associationRate=clamp(+o.onRate||0,0,250);if(o.offRate!==undefined)this.dissociationRate=clamp(+o.offRate||0,0,100)}setReactionKinetics(o={}){if(o.enabled!==undefined)this.reactionEnabled=!!o.enabled;if(o.rate!==undefined)this.reactionRate=clamp(+o.rate||0,0,250);if(o.activationAge!==undefined)this.activationAge=clamp(+o.activationAge||0,0,.5);return this.reactionSnapshot()}
kineticEnergy(){let e=0;for(const p of this.particles){const m=SPECIES[p.species].mass;e+=.5*m*(p.vx*p.vx+p.vy*p.vy)}return e}temperature(){return this.kineticEnergy()/this.count}potentialEnergy(){return this._potential}totalEnergy(){return this.kineticEnergy()+this._potential}displacement(a,b){return{x:minImage(b.x-a.x,this.width),y:minImage(b.y-a.y,this.height)}}
_stateCounts(){const c=[0,0];for(const p of this.particles)c[p.state?1:0]++;return{ground:c[0],activated:c[1],total:c[0]+c[1]}}
_recordReaction(type,b){const ev={index:this.reactionsForward+this.reactionsReverse,type,step:this.stepIndex,time:this.time,pair:[b.i,b.j],species:[this.particles[b.i].species,this.particles[b.j].species]};this.reactionHistory.push(ev);if(this.reactionHistory.length>64)this.reactionHistory.shift();return ev}
_activate(b){if(b.reacted)return false;this.particles[b.i].state=1;this.particles[b.j].state=1;b.reacted=true;this.reactionsForward++;this._recordReaction('FORWARD',b);return true}
_deactivate(b,reason='dissociation'){if(!b.reacted)return false;this.particles[b.i].state=0;this.particles[b.j].state=0;b.reacted=false;this.reactionsReverse++;const ev=this._recordReaction('REVERSE',b);ev.reason=reason;return true}
associationSnapshot(){let age=0,max=0,reacted=0;for(const b of this.associations.values()){age+=b.age;max=Math.max(max,b.age);if(b.reacted)reacted++}return{count:this.associations.size,formed:this.associationFormed,broken:this.associationBroken,reacted,meanActiveAge:this.associations.size?age/this.associations.size:0,maxActiveAge:max,meanBrokenLifetime:this.associationBroken?this.associationLifetimeTotal/this.associationBroken:0}}
reactionSnapshot(){const c=this._stateCounts();return{enabled:this.reactionEnabled,rate:this.reactionRate,activationAge:this.activationAge,forward:this.reactionsForward,reverse:this.reactionsReverse,net:this.reactionsForward-this.reactionsReverse,stateCounts:c,history:this.reactionHistory.slice(-8)}}associationList(){return Array.from(this.associations.values(),b=>({...b}))}
breakAllAssociations(reason='manual'){let n=0;for(const b of this.associations.values()){this._deactivate(b,reason);this.associationBroken++;this.associationLifetimeTotal+=b.age;n++}this.associations.clear();return{reason,broken:n}}
_updateAssociations(dt){for(const [k,b] of Array.from(this.associations)){b.age+=dt;if(this.reactionEnabled&&!b.reacted&&b.age>=this.activationAge){const p=1-Math.exp(-this.reactionRate*dt);if(this.rng()<p)this._activate(b)}const d=this.displacement(this.particles[b.i],this.particles[b.j]),r=Math.hypot(d.x,d.y),stretch=Math.max(0,r/b.r0-1),haz=this.dissociationRate*(1+2.8*stretch*stretch)*Math.max(.2,this.temperature()/.42),pBreak=1-Math.exp(-haz*dt);if(this.rng()<pBreak){this._deactivate(b,'dissociation');this.associations.delete(k);this.associationBroken++;this.associationLifetimeTotal+=b.age}}
if(!this.associationEnabled||this.associationRate<=0)return;const used=new Set();for(const b of this.associations.values()){used.add(b.i);used.add(b.j)}const order=[];for(let i=0;i<this.count;i++)for(let j=i+1;j<this.count;j++)order.push([i,j]);for(let i=order.length-1;i>0;i--){const j=Math.floor(this.rng()*(i+1));[order[i],order[j]]=[order[j],order[i]]}for(const [i,j] of order){if(used.has(i)||used.has(j))continue;const a=this.particles[i],b=this.particles[j];if(a.species===b.species)continue;const sa=SPECIES[a.species],sb=SPECIES[b.species],sigma=.5*(sa.sigma+sb.sigma),d=this.displacement(a,b),r=Math.hypot(d.x,d.y),capture=1.42*sigma;if(r>=capture||r<=.55*sigma)continue;const proximity=1-r/capture,cold=clamp(.55/(.18+this.temperature()),.35,2.4),p=1-Math.exp(-this.associationRate*proximity*cold*dt);if(this.rng()<p){const bnd={i,j,age:0,r0:1.08*sigma,sigma,createdStep:this.stepIndex,reacted:false};this.associations.set(key(i,j),bnd);used.add(i);used.add(j);this.associationFormed++}}}
computeForces(){if(!this._forces||this._forces.length!==this.count)this._forces=this.particles.map(()=>({x:0,y:0}));for(const f of this._forces){f.x=0;f.y=0}let U=0,V=0;for(let i=0;i<this.count;i++){const a=this.particles[i],sa=SPECIES[a.species];for(let j=i+1;j<this.count;j++){const b=this.particles[j],sb=SPECIES[b.species],d=this.displacement(a,b);let r2=d.x*d.x+d.y*d.y,sigma=.5*(sa.sigma+sb.sigma),cut=this.cutoffScale*sigma;if(r2>=cut*cut)continue;r2=Math.max(r2,(.38*sigma)**2);const inv=1/r2,sr2=sigma*sigma*inv,sr6=sr2**3,sr12=sr6*sr6,eps=this.attraction*Math.sqrt(sa.epsilon*sb.epsilon)*(a.state&&b.state?1.12:1),fs=24*eps*inv*(2*sr12-sr6),fx=fs*d.x,fy=fs*d.y;this._forces[i].x-=fx;this._forces[i].y-=fy;this._forces[j].x+=fx;this._forces[j].y+=fy;const rc2=1/(this.cutoffScale**2),rc6=rc2**3,rc12=rc6**2;U+=4*eps*(sr12-sr6)-4*eps*(rc12-rc6);V+=d.x*fx+d.y*fy}}
for(const b of this.associations.values()){const d=this.displacement(this.particles[b.i],this.particles[b.j]),r=Math.max(1e-9,Math.hypot(d.x,d.y)),ext=r-b.r0,k=this.associationSpring*(b.reacted?1.45:1),fm=k*ext,fx=fm*d.x/r,fy=fm*d.y/r;this._forces[b.i].x+=fx;this._forces[b.i].y+=fy;this._forces[b.j].x-=fx;this._forces[b.j].y-=fy;U+=.5*k*ext*ext;V+=d.x*(-fx)+d.y*(-fy)}this._potential=U;this._virial=V;return this._forces}
step(dt=.00035,o={}){dt=clamp(+dt||.00035,.00005,.0012);const old=this._forces;for(let i=0;i<this.count;i++){const p=this.particles[i],m=SPECIES[p.species].mass;p.vx+=.5*old[i].x/m*dt;p.vy+=.5*old[i].y/m*dt;p.x=wrap(p.x+p.vx*dt,this.width);p.y=wrap(p.y+p.vy*dt,this.height)}this._updateAssociations(dt);this.computeForces();for(let i=0;i<this.count;i++){const p=this.particles[i],m=SPECIES[p.species].mass;p.vx+=.5*this._forces[i].x/m*dt;p.vy+=.5*this._forces[i].y/m*dt}const s=clamp(+o.thermostatStrength||0,0,.08),T=clamp(+o.targetTemperature||.42,.02,3);if(s>0){const t=this.temperature();if(t>1e-12){const f=clamp(Math.sqrt(1+s*(T/t-1)),.94,1.06);for(const p of this.particles){p.vx*=f;p.vy*=f}}}this.stepIndex++;this.time+=dt;return this.snapshot()}
impulse(x,y,strength=.8,radius=.16){x=wrap(x,this.width);y=wrap(y,this.height);let n=0;for(const p of this.particles){const dx=minImage(p.x-x,this.width),dy=minImage(p.y-y,this.height),d=Math.hypot(dx,dy);if(d>0&&d<radius){const w=(1-d/radius)*strength;p.vx+=dx/d*w;p.vy+=dy/d*w;n++}}this.interventions++;return n}
radialDistribution(bins=28,maxR=Math.min(this.width,this.height)*.5){bins=Math.max(8,Math.min(96,bins|0));const c=new Array(bins).fill(0),dr=maxR/bins,pairs=this.count*(this.count-1)/2,area=this.width*this.height;for(let i=0;i<this.count;i++)for(let j=i+1;j<this.count;j++){const d=this.displacement(this.particles[i],this.particles[j]),r=Math.hypot(d.x,d.y);if(r<maxR)c[Math.min(bins-1,Math.floor(r/dr))]++}const values=c.map((count,k)=>{const r0=k*dr,r1=(k+1)*dr,expected=pairs*Math.PI*(r1*r1-r0*r0)/area;return{r:(r0+r1)/2,g:expected?count/expected:0,count}});let peak={r:0,g:0};for(const v of values)if(v.g>peak.g)peak={r:v.r,g:v.g};return{values,peak}}
pressureEstimate(){return(this.count*this.temperature()+.5*this._virial)/(this.width*this.height)}snapshot(){const a=this.associationSnapshot(),r=this.reactionSnapshot(),g=this.radialDistribution(24);return{model:MODEL.id,seed:this.seed,step:this.stepIndex,time:this.time,count:this.count,temperature:this.temperature(),kinetic:this.kineticEnergy(),potential:this._potential,total:this.totalEnergy(),pressure:this.pressureEstimate(),rdfPeakG:g.peak.g,rdfPeakR:g.peak.r,associations:a.count,reactedAssociations:a.reacted,associationsFormed:a.formed,associationsBroken:a.broken,reactionsForward:r.forward,reactionsReverse:r.reverse,activatedParticles:r.stateCounts.activated}}
invariantReport(){let finite=true,bounds=true,assoc=true,state=true;const used=new Set();for(const p of this.particles){finite&&=Number.isFinite(p.x+p.y+p.vx+p.vy);bounds&&=p.x>=0&&p.x<this.width&&p.y>=0&&p.y<this.height;state&&=(p.state===0||p.state===1)}for(const [k,b] of this.associations){if(k!==key(b.i,b.j)||b.i===b.j||used.has(b.i)||used.has(b.j))assoc=false;used.add(b.i);used.add(b.j);if(b.reacted&&(this.particles[b.i].state!==1||this.particles[b.j].state!==1))state=false}for(let i=0;i<this.count;i++)if(this.particles[i].state===1&&!used.has(i))state=false;const counts=this._stateCounts(),conserved=counts.total===this.count;return{finite,bounds,associationsValid:assoc,stateValid:state,particleCountConserved:conserved,status:finite&&bounds&&assoc&&state&&conserved?'PASS':'FAIL'}}
hash(){let h=2166136261>>>0,m=n=>{h^=n>>>0;h=Math.imul(h,16777619)>>>0};for(const p of this.particles){m(Math.round(p.x*1e6));m(Math.round(p.y*1e6));m(Math.round(p.vx*1e6));m(Math.round(p.vy*1e6));m(p.species);m(p.state)}for(const b of this.associations.values()){m(b.i);m(b.j);m(Math.round(b.age*1e6));m(b.reacted?1:0)}m(this.stepIndex);m(this.reactionsForward);m(this.reactionsReverse);return h>>>0}}
return{MODEL,SPECIES,MatterWorld,minImage,wrap};});
