const assert=require('node:assert/strict');
const {MatterWorld,MODEL,minImage,wrap}=require('./model.js');
assert.equal(MODEL.boundary,'periodic minimum-image');
assert.ok(Math.abs(minImage(.96,1)+.04)<1e-12,'minimum-image wraps long positive displacement');
assert.ok(Math.abs(minImage(-.96,1)-.04)<1e-12,'minimum-image wraps long negative displacement');
assert.ok(Math.abs(wrap(-.02,1)-.98)<1e-12,'position wrap');
const a=new MatterWorld({count:72,seed:123456,temperature:.32});
const b=new MatterWorld({count:72,seed:123456,temperature:.32});
assert.equal(a.hash(),b.hash(),'same seed must create same initial state');
const e0=a.totalEnergy();
for(let i=0;i<3000;i++)a.step(.00018,{thermostatStrength:0});
const inv=a.invariantReport();
assert.equal(inv.status,'PASS','state invariants');
const e1=a.totalEnergy(),drift=Math.abs(e1-e0)/Math.max(1,Math.abs(e0));
assert.ok(drift<.08,`energy drift too high: ${drift}`);
const rdf=a.radialDistribution(32);
assert.equal(rdf.values.length,32,'rdf bin count');
assert.ok(rdf.values.every(v=>Number.isFinite(v.g)&&v.g>=0),'rdf finite non-negative');
assert.ok(rdf.peak.g>0&&rdf.peak.r>0,'rdf detects at least one pair-separation peak');
const c=new MatterWorld({count:48,seed:999,temperature:.2});
const before=c.hash(),touched=c.impulse(.99,.31,1.1,.12);
for(let i=0;i<50;i++)c.step(.0002,{thermostatStrength:0});
assert.ok(touched>0,'periodic impulse must affect nearby particles');
assert.notEqual(c.hash(),before,'simulation state must evolve');
const q=new MatterWorld({count:48,seed:42,temperature:.8});
q.setTemperature(.12);
assert.ok(Math.abs(q.temperature()-.12)<1e-10,'quench rescale reaches requested kinetic temperature');
console.log(JSON.stringify({model:MODEL.id,e0,e1,drift,temp:a.temperature(),hash:a.hash(),maxSpeed:inv.maxSpeed,rdfPeak:rdf.peak}));
console.log('PASS genesis matter 0.2 model tests');
