(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.GenesisMatter=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const MODEL={id:'genesis-matter-lj2d-v2',name:'GENESIS Matter Lab — coarse-grained 2D molecular dynamics',integrator:'velocity-verlet',potential:'Lennard-Jones 12-6, shifted at 2.5σ',dimensions:2,boundary:'periodic minimum-image',units:'reduced Lennard-Jones units',claims:['Classical coarse-grained particle dynamics','Deterministic from seed on the same JavaScript numerical path','Periodic boundary conditions with minimum-image forces','Radial distribution function g(r) from instantaneous pair separations'],nonClaims:['Not quantum chemistry','Not literal atoms','Not chemical reactions','Not life or evolution']};
const SPECIES=[{id:0,name:'A',mass:1.00,sigma:.030,epsilon:1.00},{id:1,name:'B',mass:1.35,sigma:.034,epsilon:.78},{id:2,name:'C',mass:.82,sigma:.027,epsilon:1.18}];
function xorshift32(seed){let s=(seed>>>0)||0x6d2b79f5;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return(s>>>0)/4294967296}}
function gaussian(rng){let u=0,v=0;while(u===0)u=rng();while(v===0)v=rng();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function clamp(v,a,b){return v<a?a:v>b?b:v}function wrap(v,L){v%=L;return v<0?v+L:v}function minImage(d,L){return d-L*Math.round(d/L)}
class MatterWorld{
 constructor(options={}){this.width=options.width||1;this.height=options.height||.62;this.count=Math.max(8,Math.min(256,options.count||120));this.seed=(options.seed??0x51a7c0de)>>>0;this.attraction=options.attraction??1;this.cutoffScale=2.5;this.stepIndex=0;this.time=0;this.interventions=0;this.rng=xorshift32(this.seed);this.particles=[];this._potential=0;this._virial=0;this._init(options.temperature??.42);this._forces=this.particles.map(()=>({x:0,y:0}));this.computeForces()}
 _init(temp){const aspect=this.width/this.height,cols=Math.ceil(Math.sqrt(this.count*aspect)),rows=Math.ceil(this.count/cols),sx=this.width/cols,sy=this.height/rows;let i=0;for(let r=0;r<rows&&i<this.count;r++)for(let c=0;c<cols&&i<this.count;c++){const sp=i%3,s=SPECIES[sp],jitter=.08*Math.min(sx,sy);this.particles.push({x:(c+.5)*sx+(this.rng()-.5)*jitter,y:(r+.5)*sy+(this.rng()-.5)*jitter,vx:gaussian(this.rng)*Math.sqrt(temp/s.mass),vy:gaussian(this.rng)*Math.sqrt(temp/s.mass),species:sp});i++}this._removeDrift();this._rescaleTemperature(temp)}
 _removeDrift(){let px=0,py=0,m=0;for(const p of this.particles){const sm=SPECIES[p.species].mass;px+=p.vx*sm;py+=p.vy*sm;m+=sm}if(m<=0)return;const vx=px/m,vy=py/m;for(const p of this.particles){p.vx-=vx;p.vy-=vy}}
 _rescaleTemperature(target){const t=this.temperature();if(!(t>0))return;const scale=Math.sqrt(target/t);for(const p of this.particles){p.vx*=scale;p.vy*=scale}}
 setTemperature(target){target=clamp(Number(target)||.42,.02,3);this._removeDrift();this._rescaleTemperature(target);return this.temperature()}
 setAttraction(v){this.attraction=clamp(Number(v)||1,.15,2.5);this.computeForces()}
 kineticEnergy(){let e=0;for(const p of this.particles){const m=SPECIES[p.species].mass;e+=.5*m*(p.vx*p.vx+p.vy*p.vy)}return e}temperature(){return this.kineticEnergy()/this.count}potentialEnergy(){return this._potential}totalEnergy(){return this.kineticEnergy()+this._potential}
 displacement(a,b){return{x:minImage(b.x-a.x,this.width),y:minImage(b.y-a.y,this.height)}}
 computeForces(){const n=this.particles.length;if(!this._forces||this._forces.length!==n)this._forces=this.particles.map(()=>({x:0,y:0}));for(let i=0;i<n;i++){this._forces[i].x=0;this._forces[i].y=0}let potential=0,virial=0;for(let i=0;i<n;i++){const a=this.particles[i],sa=SPECIES[a.species];for(let j=i+1;j<n;j++){const b=this.particles[j],sb=SPECIES[b.species],d=this.displacement(a,b);let r2=d.x*d.x+d.y*d.y;const sigma=.5*(sa.sigma+sb.sigma),cutoff=this.cutoffScale*sigma;if(r2>=cutoff*cutoff)continue;const minR=.38*sigma;if(r2<minR*minR)r2=minR*minR;const invR2=1/r2,sr2=sigma*sigma*invR2,sr6=sr2*sr2*sr2,sr12=sr6*sr6,eps=this.attraction*Math.sqrt(sa.epsilon*sb.epsilon),forceScalar=24*eps*invR2*(2*sr12-sr6),fx=forceScalar*d.x,fy=forceScalar*d.y;this._forces[i].x-=fx;this._forces[i].y-=fy;this._forces[j].x+=fx;this._forces[j].y+=fy;const src2=1/(this.cutoffScale*this.cutoffScale),src6=src2*src2*src2,src12=src6*src6,uShift=4*eps*(src12-src6);potential+=4*eps*(sr12-sr6)-uShift;virial+=d.x*fx+d.y*fy}}this._potential=potential;this._virial=virial;return this._forces}
 step(dt=.00035,options={}){dt=clamp(Number(dt)||.00035,.00005,.0012);const old=this._forces;for(let i=0;i<this.particles.length;i++){const p=this.particles[i],m=SPECIES[p.species].mass;p.vx+=.5*(old[i].x/m)*dt;p.vy+=.5*(old[i].y/m)*dt;p.x=wrap(p.x+p.vx*dt,this.width);p.y=wrap(p.y+p.vy*dt,this.height)}this.computeForces();for(let i=0;i<this.particles.length;i++){const p=this.particles[i],m=SPECIES[p.species].mass;p.vx+=.5*(this._forces[i].x/m)*dt;p.vy+=.5*(this._forces[i].y/m)*dt}const strength=clamp(Number(options.thermostatStrength)||0,0,.08),target=clamp(Number(options.targetTemperature)||.42,.02,3);if(strength>0){const t=this.temperature();if(t>1e-12){const factor=clamp(Math.sqrt(1+strength*(target/t-1)),.94,1.06);for(const p of this.particles){p.vx*=factor;p.vy*=factor}}}this.stepIndex++;this.time+=dt;return this.snapshot()}
 impulse(x,y,strength=.8,radius=.16){x=wrap(x,this.width);y=wrap(y,this.height);radius=Math.max(.02,radius);let touched=0;for(const p of this.particles){const dx=minImage(p.x-x,this.width),dy=minImage(p.y-y,this.height),d=Math.hypot(dx,dy);if(d>0&&d<radius){const w=(1-d/radius)*strength;p.vx+=(dx/d)*w;p.vy+=(dy/d)*w;touched++}}this.interventions++;return touched}
 radialDistribution(bins=28,maxR=Math.min(this.width,this.height)*.5){bins=Math.max(8,Math.min(96,bins|0));maxR=Math.min(maxR,Math.min(this.width,this.height)*.5);const counts=new Array(bins).fill(0),dr=maxR/bins,n=this.particles.length,area=this.width*this.height,pairs=n*(n-1)/2;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){const d=this.displacement(this.particles[i],this.particles[j]),r=Math.hypot(d.x,d.y);if(r<maxR)counts[Math.min(bins-1,Math.floor(r/dr))]++}const values=counts.map((count,k)=>{const r0=k*dr,r1=(k+1)*dr,shell=Math.PI*(r1*r1-r0*r0),expected=pairs*shell/area;return{r:(r0+r1)/2,g:expected>0?count/expected:0,count}});let peak={r:0,g:0};for(const v of values)if(v.g>peak.g)peak={r:v.r,g:v.g};return{bins,maxR,dr,values,peak}}
 pressureEstimate(){return(this.count*this.temperature()+.5*this._virial)/(this.width*this.height)}
 snapshot(){const rdf=this.radialDistribution(24);return{model:MODEL.id,seed:this.seed,count:this.count,step:this.stepIndex,time:this.time,temperature:this.temperature(),kinetic:this.kineticEnergy(),potential:this._potential,total:this.totalEnergy(),pressure:this.pressureEstimate(),attraction:this.attraction,interventions:this.interventions,rdfPeakR:rdf.peak.r,rdfPeakG:rdf.peak.g}}
 invariantReport(){let finite=true,bounds=true,maxSpeed=0;for(const p of this.particles){if(!Number.isFinite(p.x+p.y+p.vx+p.vy))finite=false;if(p.x<0||p.x>=this.width||p.y<0||p.y>=this.height)bounds=false;maxSpeed=Math.max(maxSpeed,Math.hypot(p.vx,p.vy))}return{finite,bounds,maxSpeed,status:finite&&bounds?'PASS':'FAIL'}}
 hash(){let h=2166136261>>>0;const mix=n=>{h^=n>>>0;h=Math.imul(h,16777619)>>>0};for(const p of this.particles){mix(Math.round(p.x*1e6));mix(Math.round(p.y*1e6));mix(Math.round(p.vx*1e6));mix(Math.round(p.vy*1e6));mix(p.species)}mix(this.stepIndex);return h>>>0}
}
return{MODEL,SPECIES,MatterWorld,minImage,wrap};
});
