const assert=require('node:assert/strict');
const {MatterWorld,MODEL}=require('./model.js');
const a=new MatterWorld({count:72,seed:123456,temperature:.32});
const b=new MatterWorld({count:72,seed:123456,temperature:.32});
assert.equal(a.hash(),b.hash(),'same seed must create same initial state');
const e0=a.totalEnergy();
for(let i=0;i<3000;i++)a.step(.00018,{thermostatStrength:0});
const inv=a.invariantReport();
assert.equal(inv.status,'PASS','state invariants');
const e1=a.totalEnergy();
const drift=Math.abs(e1-e0)/Math.max(1,Math.abs(e0));
console.log(JSON.stringify({model:MODEL.id,e0,e1,drift,temp:a.temperature(),hash:a.hash(),maxSpeed:inv.maxSpeed}));
assert.ok(drift<.08,`energy drift too high: ${drift}`);
const c=new MatterWorld({count:48,seed:999,temperature:.2});
const before=c.hash();
const touched=c.impulse(.5,.31,1.1,.24);
for(let i=0;i<50;i++)c.step(.0002,{thermostatStrength:0});
assert.ok(touched>0,'impulse must affect particles');
assert.notEqual(c.hash(),before,'simulation state must evolve');
console.log('PASS genesis matter model tests');
