import { CHUNK_COLS,CHUNK_ROWS,WORLD_H,WORLD_W,chunkIndexFor } from './world.js';
export const MAP_COLS=120,MAP_ROWS=64;const CW=MAP_COLS/CHUNK_COLS,CH=MAP_ROWS/CHUNK_ROWS,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),blank=()=>Array.from({length:MAP_ROWS},()=>Array(MAP_COLS).fill(' '));
function put(g,x,y,ch){if(x>=0&&y>=0&&x<MAP_COLS&&y<MAP_ROWS)g[y][x]=ch;}function rect(c){return{x:Math.floor(c.cx*CW),y:Math.floor(c.cy*CH),w:Math.max(1,Math.ceil(CW)),h:Math.max(1,Math.ceil(CH))};}function center(c){const r=rect(c);return{x:r.x+Math.floor(r.w/2),y:r.y+Math.floor(r.h/2)};}function hashTile(x,y,id){let n=((x+17)*73856093)^((y+31)*19349663)^(id*83492791);n^=n<<13;n^=n>>>17;n^=n<<5;return(n>>>0)/4294967296;}
export function terrainGlyph(c,x,y){if(c.flood>.74)return(x+y)%3?'~':'≈';const r=hashTile(x,y,c.id);if(c.biome==='RIVER')return r>.74?'≈':'~';if(c.biome==='MARSH')return r>.82?'♣':r>.48?';':'≈';if(c.biome==='FOREST')return r>.78?'♣':r>.54?'T':r>.29?';':'.';if(c.biome==='TAIGA')return r>.79?'♣':r>.50?'Y':r>.28?';':'·';if(c.biome==='TUNDRA')return r>.84?'°':r>.52?'\'':'·';if(c.biome==='SAVANNA')return r>.82?'♣':r>.52?'"':',';if(c.biome==='DESERT')return r>.82?'°':r>.47?':':'·';if(c.biome==='BADLANDS')return r>.80?'%':r>.46?':':'/';if(c.biome==='ALPINE')return r>.70?'▲':r>.32?'^':'·';if(c.biome==='HIGHLAND')return r>.74?'▲':r>.35?'^':':';return r>.88?'"':r>.66?',':'.';}
function addSite(g,c){const p=center(c),s=c.site;if(s==='HOME'){put(g,p.x-1,p.y,'(');put(g,p.x,p.y,'*');put(g,p.x+1,p.y,')');put(g,p.x,p.y+1,'S');}else if(s==='CAVE'){put(g,p.x-1,p.y,'^');put(g,p.x,'',p.y);put(g,p.x,p.y,'O');put(g,p.x+1,p.y,'^');}else if(s==='RUIN'){put(g,p.x-1,p.y,'#');put(g,p.x,p.y,'%');put(g,p.x+1,p.y,'#');}else if(s==='BRIDGE'){put(g,p.x-1,p.y,'=');put(g,p.x,p.y,'+');put(g,p.x+1,p.y,'=');}else if(s==='SPRING'){put(g,p.x,p.y,'◉');put(g,p.x+1,p.y,'~');}else if(s==='GROVE'){put(g,p.x-1,p.y,'♣');put(g,p.x,p.y,'♣');put(g,p.x+1,p.y,'T');}if(c.floodAlarm&&s==='HOME')put(g,p.x,p.y-1,'A');if(c.pumpActive)put(g,p.x+1,p.y-1,'P');}
function staticRows(world){const g=blank();for(let y=0;y<MAP_ROWS;y++)for(let x=0;x<MAP_COLS;x++){const wx=(x+.5)/MAP_COLS*WORLD_W,wy=(y+.5)/MAP_ROWS*WORLD_H;g[y][x]=terrainGlyph(world.chunks[chunkIndexFor(wx,wy)],x,y);}for(const c of world.chunks)addSite(g,c);return g.map(r=>r.join(''));}
export function makeAsciiFrame(world,agents,selectedId=null){const rows=staticRows(world).map(r=>r.split(''));for(const a of agents){if(!a.alive)continue;const x=clamp(Math.floor(a.x/WORLD_W*MAP_COLS),0,MAP_COLS-1),y=clamp(Math.floor(a.y/WORLD_H*MAP_ROWS),0,MAP_ROWS-1);rows[y][x]=a.id===selectedId?'☻':a.lastAction==='FIGHT'?'!':a.lastAction==='SHELTER'?'⌂':a.energy<24?'☹':a.lastAction==='PLAY'?'♫':'☺';}return rows.map(r=>r.join(''));}
const COLORS={PLAINS:'#c7c58f',FOREST:'#71c67a',TAIGA:'#78b891',TUNDRA:'#c9d5d7',SAVANNA:'#d2c36f',DESERT:'#daa96a',BADLANDS:'#c27f68',MARSH:'#69b8a7',RIVER:'#6db9ef',HIGHLAND:'#b2b1bd',ALPINE:'#e0e0e7'};let cache=null,cacheW=0,cacheH=0,cacheSeed=null,cacheRev=-1,lastBuild=0;
function rebuildCache(ctx,world,W,H){if(typeof document==='undefined')return null;if(!cache)cache=document.createElement('canvas');const dpr=Math.min(2,globalThis.devicePixelRatio||1);cache.width=Math.max(1,Math.floor(W*dpr));cache.height=Math.max(1,Math.floor(H*dpr));const c=cache.getContext('2d',{alpha:false});c.setTransform(dpr,0,0,dpr,0,0);c.fillStyle='#08090d';c.fillRect(0,0,W,H);const rows=staticRows(world),lineH=H/MAP_ROWS,charW=W/MAP_COLS,font=Math.max(5.5,Math.min(13,lineH*.84));c.font=`${font}px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace`;c.textBaseline='top';c.textAlign='left';for(const ch of world.chunks){const r=rect(ch),px=r.x*charW,py=r.y*lineH,pw=r.w*charW,ph=r.h*lineH;c.fillStyle=ch.biome==='RIVER'?'rgba(36,100,160,.24)':ch.biome==='FOREST'?'rgba(25,105,50,.10)':ch.biome==='DESERT'?'rgba(150,98,35,.10)':ch.biome==='BADLANDS'?'rgba(135,55,42,.10)':ch.biome==='MARSH'?'rgba(25,95,78,.12)':ch.biome==='ALPINE'?'rgba(190,195,215,.08)':'rgba(0,0,0,0)';if(c.fillStyle!=='rgba(0, 0, 0, 0)')c.fillRect(px,py,pw,ph);if(ch.flood>.18){c.fillStyle=`rgba(50,128,205,${.03+ch.flood*.16})`;c.fillRect(px,py,pw,ph);}c.fillStyle=COLORS[ch.biome]||'#c7c58f';for(let y=r.y;y<Math.min(MAP_ROWS,r.y+r.h);y++)c.fillText(rows[y].slice(r.x,r.x+r.w),px,y*lineH,pw);}cacheW=W;cacheH=H;cacheSeed=world.seed;cacheRev=world.visualRevision;lastBuild=performance.now();return{charW,lineH};}
export function drawAsciiWorld(ctx,world,agents,selectedId,W,H){const now=performance.now(),stale=!cache||cacheW!==W||cacheH!==H||cacheSeed!==world.seed||(cacheRev!==world.visualRevision&&now-lastBuild>220);let dims;if(stale)dims=rebuildCache(ctx,world,W,H);const lineH=H/MAP_ROWS,charW=W/MAP_COLS;if(cache)ctx.drawImage(cache,0,0,cache.width,cache.height,0,0,W,H);else{ctx.fillStyle='#08090d';ctx.fillRect(0,0,W,H);}const font=Math.max(5.5,Math.min(13,lineH*.84));ctx.font=`${font}px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace`;ctx.textBaseline='top';ctx.textAlign='left';for(const a of agents){if(!a.alive)continue;const x=clamp(Math.floor(a.x/WORLD_W*MAP_COLS),0,MAP_COLS-1),y=clamp(Math.floor(a.y/WORLD_H*MAP_ROWS),0,MAP_ROWS-1),glyph=a.lastAction==='FIGHT'?'!':a.lastAction==='SHELTER'?'⌂':a.energy<24?'☹':a.lastAction==='PLAY'?'♫':'☺';ctx.fillStyle=a.id===selectedId?'#fff27a':a.energy<24?'#ff8c7a':a.lastAction==='PLAY'?'#e3a1ff':'#fff';ctx.fillText(glyph,x*charW,y*lineH,charW*1.2);if(a.id===selectedId){ctx.strokeStyle='#fff27a';ctx.strokeRect(x*charW,y*lineH,charW,lineH);}}return{charW,lineH};}
export function mapTileToWorld(x,y){return{x:(x+.5)/MAP_COLS*WORLD_W,y:(y+.5)/MAP_ROWS*WORLD_H};}
export const LEGEND=Object.freeze([['☺','person'],['♫','playing'],['☹','weak'],['*','campfire'],['S','stockpile'],['O','cave'],['◉','spring'],['%','ruin'],['=','bridge'],['~','river'],['≈','marsh'],['♣','forest'],['Y','taiga'],['\'','tundra'],['"','savanna'],[':','desert'],['/','badlands'],['^','highland'],['▲','alpine'],['A','flood alarm'],['P','pump']]);
