const MAX=900,GENES=8,SPECIES=['deer','boar','wolf','rabbit','fish','fox','bear','elk'];
let W=1600,H=1000,cols=1,rows=1,cell=64,running=true,tick=0,count=0,seed=1,zones=[],wildlife=.3,predators=.22;
const x=new Float32Array(MAX),y=new Float32Array(MAX),vx=new Float32Array(MAX),vy=new Float32Array(MAX),energy=new Float32Array(MAX),age=new Uint32Array(MAX),species=new Uint8Array(MAX),alive=new Uint8Array(MAX),genes=new Float32Array(MAX*GENES);let buckets=new Map();
const bases=[[.62,.72,.18,.46,.42,.72,.78,.74],[.47,.58,.60,.55,.37,.32,1.05,.48],[.70,.78,.90,.68,.22,.14,.78,.72],[.85,.62,.08,.40,.78,.88,.38,.35],[.60,.48,.06,.34,.55,.70,.32,.42],[.76,.72,.72,.53,.38,.36,.46,.55],[.48,.66,.88,.72,.12,.10,1.35,.30],[.58,.70,.20,.50,.30,.68,1.10,.66]];
const habitat=[['PLAINS','FOREST','SAVANNA','RAINFOREST'],['FOREST','RAINFOREST','MARSH'],['FOREST','TAIGA','HIGHLAND','TUNDRA'],['PLAINS','SAVANNA','TUNDRA','FOREST'],['RIVER','LAKE','OCEAN'],['PLAINS','FOREST','TAIGA','SAVANNA'],['FOREST','TAIGA','HIGHLAND'],['FOREST','TAIGA','PLAINS','HIGHLAND']];
const prey={2:[0,1,3,7],5:[3],6:[0,1,7]};
function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const g=(i,k)=>genes[i*GENES+k],sg=(i,k,v)=>genes[i*GENES+k]=clamp(v,.02,1.6);
function zoneAt(px,py){const cx=clamp(Math.floor(px/cell),0,cols-1),cy=clamp(Math.floor(py/cell),0,rows-1);return zones[cy*cols+cx]||zones[0];}
function goodHabitat(sp,z){return !!z&&habitat[sp].includes(z.biome);}
function randomHabitat(sp){const ok=[];for(let i=0;i<zones.length;i++)if(goodHabitat(sp,zones[i]))ok.push(i);const zi=ok.length?ok[(rnd()*ok.length)|0]:(rnd()*zones.length)|0,z=zones[zi]||{cx:0,cy:0};return{x:(z.cx+rnd())*cell,y:(z.cy+rnd())*cell};}
function spawn(sp,parent=-1){if(count>=MAX)return-1;let i=-1;for(let n=0;n<MAX;n++)if(!alive[n]){i=n;break;}if(i<0)return-1;alive[i]=1;species[i]=sp;age[i]=0;energy[i]=65+rnd()*30;if(parent>=0){x[i]=clamp(x[parent]+(rnd()-.5)*15,0,W-1);y[i]=clamp(y[parent]+(rnd()-.5)*15,0,H-1);for(let k=0;k<GENES;k++)sg(i,k,g(parent,k)+(rnd()+rnd()-1)*.075);}else{const p=randomHabitat(sp);x[i]=p.x;y[i]=p.y;for(let k=0;k<GENES;k++)sg(i,k,bases[sp][k]+(rnd()+rnd()-1)*.11);}vx[i]=vy[i]=0;count++;return i;}
function kill(i){if(alive[i]){alive[i]=0;count--;}}
function bucketKey(px,py){return`${Math.floor(px/96)},${Math.floor(py/96)}`;}
function rebuildBuckets(){buckets=new Map();for(let i=0;i<MAX;i++)if(alive[i]){const k=bucketKey(x[i],y[i]);let a=buckets.get(k);if(!a)buckets.set(k,a=[]);a.push(i);}}
function nearby(i,radius){const out=[],bx=Math.floor(x[i]/96),by=Math.floor(y[i]/96),rr=Math.ceil(radius/96);for(let oy=-rr;oy<=rr;oy++)for(let ox=-rr;ox<=rr;ox++){const a=buckets.get(`${bx+ox},${by+oy}`);if(a)for(const j of a)if(j!==i)out.push(j);}return out;}
function nearest(i,pred,radius){let best=-1,bd=radius*radius;for(const j of nearby(i,radius)){if(!alive[j]||!pred(j))continue;const dx=x[j]-x[i],dy=y[j]-y[i],d=dx*dx+dy*dy;if(d<bd){bd=d;best=j;}}return best;}
function steer(i,tx,ty,away=false,str=.22){let dx=tx-x[i],dy=ty-y[i],d=Math.hypot(dx,dy)||1;if(away){dx=-dx;dy=-dy;}vx[i]=vx[i]*.78+dx/d*str;vy[i]=vy[i]*.78+dy/d*str;}
function habitatSteer(i){const sp=species[i],z=zoneAt(x[i],y[i]);if(goodHabitat(sp,z))return;for(let tries=0;tries<8;tries++){const ang=rnd()*Math.PI*2,tx=clamp(x[i]+Math.cos(ang)*cell*1.5,0,W-1),ty=clamp(y[i]+Math.sin(ang)*cell*1.5,0,H-1);if(goodHabitat(sp,zoneAt(tx,ty))){steer(i,tx,ty,false,.35);return;}}vx[i]+=(rnd()-.5)*.2;vy[i]+=(rnd()-.5)*.2;}
function stepOne(i){if(!alive[i])return;age[i]++;const sp=species[i],speed=g(i,0),vision=g(i,1),agg=g(i,2),met=g(i,3),fert=g(i,4),fear=g(i,5),size=g(i,6),social=g(i,7),z=zoneAt(x[i],y[i]);energy[i]-=.010+.026*met*size;const predator=nearest(i,j=>prey[species[j]]?.includes(sp),45+vision*105);
if(prey[sp]){const target=nearest(i,j=>prey[sp].includes(species[j]),55+vision*120);if(target>=0){steer(i,x[target],y[target],false,.28+.20*agg);const dx=x[target]-x[i],dy=y[target]-y[i];if(dx*dx+dy*dy<(5+size*4)**2){energy[i]+=8+size*4;energy[target]-=18+agg*14;if(energy[target]<=0)kill(target);}}else{vx[i]+=(rnd()-.5)*.16;vy[i]+=(rnd()-.5)*.16;}}
else if(predator>=0&&fear>.18)steer(i,x[predator],y[predator],true,.30+.22*fear);else{if(social>.50){const mate=nearest(i,j=>species[j]===sp,65+vision*55);if(mate>=0&&rnd()<.025)steer(i,x[mate],y[mate],false,.12);}vx[i]+=(rnd()-.5)*.13;vy[i]+=(rnd()-.5)*.13;const grazing=goodHabitat(sp,z)?(.009+(z?.food||.3)*.012):.001;energy[i]=Math.min(105,energy[i]+grazing);}
habitatSteer(i);const max=.25+speed*.82/Math.sqrt(Math.max(.35,size)),m=Math.hypot(vx[i],vy[i]);if(m>max){vx[i]=vx[i]/m*max;vy[i]=vy[i]/m*max;}x[i]=clamp(x[i]+vx[i],0,W-1);y[i]=clamp(y[i]+vy[i],0,H-1);if(energy[i]>86&&age[i]>500&&count<MAX&&rnd()<fert*.00024*(sp===3?2.4:sp===4?1.5:1)){energy[i]-=16;spawn(sp,i);}if(energy[i]<=0||age[i]>18000+met*3500)kill(i);}
function initialCounts(){const area=Math.sqrt(Math.max(1,zones.length/504)),total=Math.round((48+wildlife*280)*area);const predatorShare=.025+predators*.16;const weights=[.23,.10,predatorShare*.40,.29,.15,predatorShare*.32,predatorShare*.16,.08];const sum=weights.reduce((a,b)=>a+b,0);return weights.map(w=>Math.max(1,Math.round(total*w/sum)));}
function snapshot(){const arr=[];for(let i=0;i<MAX;i++)if(alive[i])arr.push({id:i,x:x[i],y:y[i],species:species[i],energy:energy[i],speed:g(i,0),size:g(i,6),fear:g(i,5)});postMessage({type:'snapshot',tick,count,animals:arr,speciesNames:SPECIES});}
function init(m){seed=m.seed>>>0||1;W=m.width||W;H=m.height||H;cols=m.cols||1;rows=m.rows||1;cell=m.cell||64;zones=m.zones||[];wildlife=clamp(Number(m.wildlife??.3),0,1);predators=clamp(Number(m.predators??.22),0,1);for(let i=0;i<MAX;i++)alive[i]=0;count=0;const counts=initialCounts();for(let sp=0;sp<SPECIES.length;sp++)for(let n=0;n<counts[sp];n++)spawn(sp);rebuildBuckets();snapshot();}
function loop(){if(running){for(let k=0;k<2;k++){tick++;rebuildBuckets();for(let i=0;i<MAX;i++)stepOne(i);}if(tick%8===0)snapshot();}setTimeout(loop,18);}
onmessage=e=>{const m=e.data||{};if(m.type==='init')init(m);else if(m.type==='pause')running=!!m.running;else if(m.type==='hunt'){let best=-1,bd=(m.radius||85)**2;for(let i=0;i<MAX;i++){if(!alive[i]||prey[species[i]]||species[i]===4)continue;const dx=x[i]-m.x,dy=y[i]-m.y,d=dx*dx+dy*dy;if(d<bd){bd=d;best=i;}}if(best>=0){const meat=8+energy[best]*.08+g(best,6)*8,sp=species[best];kill(best);postMessage({type:'huntResult',requestId:m.requestId,ok:true,meat,species:sp});}else postMessage({type:'huntResult',requestId:m.requestId,ok:false,meat:0});}};
loop();
