const MAX=760,GENES=12,SPECIES=['deer','boar','wolf','rabbit','fish','fox','bear','elk'];
let W=1600,H=1000,cols=1,rows=1,cell=64,running=true,tick=0,count=0,seed=1,zones=[],wildlife=.3,predators=.22,buckets=new Map();
const x=new Float32Array(MAX),y=new Float32Array(MAX),vx=new Float32Array(MAX),vy=new Float32Array(MAX),energy=new Float32Array(MAX),age=new Uint32Array(MAX),species=new Uint8Array(MAX),alive=new Uint8Array(MAX),generation=new Uint16Array(MAX),mateCooldown=new Uint16Array(MAX),genes=new Float32Array(MAX*GENES),zoneFood=new Float32Array(4096),zoneBaseFood=new Float32Array(4096);
const bases=[
 [.62,.72,.18,.46,.42,.72,.78,.74,.70,.42,.52,.58],
 [.47,.58,.60,.55,.37,.32,1.05,.48,.66,.48,.55,.62],
 [.70,.78,.90,.68,.22,.14,.78,.72,.72,.58,.35,.52],
 [.85,.62,.08,.40,.78,.88,.38,.35,.82,.28,.90,.72],
 [.60,.48,.06,.34,.55,.70,.32,.42,.64,.34,.76,.80],
 [.76,.72,.72,.53,.38,.36,.46,.55,.78,.44,.54,.67],
 [.48,.66,.88,.72,.12,.10,1.35,.30,.55,.72,.22,.45],
 [.58,.70,.20,.50,.30,.68,1.10,.66,.62,.56,.40,.55]
];
const habitat=[['PLAINS','FOREST','SAVANNA','RAINFOREST'],['FOREST','RAINFOREST','MARSH'],['FOREST','TAIGA','HIGHLAND','TUNDRA'],['PLAINS','SAVANNA','TUNDRA','FOREST'],['RIVER','LAKE','OCEAN'],['PLAINS','FOREST','TAIGA','SAVANNA'],['FOREST','TAIGA','HIGHLAND'],['FOREST','TAIGA','PLAINS','HIGHLAND']];
const prey={2:[0,1,3,7],5:[3],6:[0,1,7]};
function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const g=(i,k)=>genes[i*GENES+k];
const sg=(i,k,v)=>genes[i*GENES+k]=clamp(v,.02,1.8);
function zoneIndex(px,py){const cx=clamp(Math.floor(px/cell),0,cols-1),cy=clamp(Math.floor(py/cell),0,rows-1);return cy*cols+cx;}
function zoneAt(px,py){return zones[zoneIndex(px,py)]||zones[0];}
function gCurrentFlex(sp){return bases[sp]?.[11]??.5;}
function goodHabitat(sp,z,i=-1){if(!z)return false;if(habitat[sp].includes(z.biome))return true;return i>=0&&g(i,11)>.92&&rnd()<.18;}
function randomHabitat(sp){let best=-1,bestScore=-1;for(let tries=0;tries<48;tries++){const zi=(rnd()*zones.length)|0,z=zones[zi];if(!z)continue;const score=(habitat[sp].includes(z.biome)?1:.05)+rnd()*.18+(z.food||0)*.2;if(score>bestScore){bestScore=score;best=zi;}}const z=zones[best]||zones[(rnd()*zones.length)|0]||{cx:0,cy:0};return{x:(z.cx+rnd())*cell,y:(z.cy+rnd())*cell};}
function freeSlot(){for(let i=0;i<MAX;i++)if(!alive[i])return i;return-1;}
function mutateGene(v,scale=.065){return clamp(v+(rnd()+rnd()-1)*scale,.02,1.8);}
function spawn(sp,parentA=-1,parentB=-1){if(count>=MAX)return-1;const i=freeSlot();if(i<0)return-1;alive[i]=1;species[i]=sp;age[i]=0;mateCooldown[i]=0;energy[i]=58+rnd()*28;if(parentA>=0){x[i]=clamp((x[parentA]+(parentB>=0?x[parentB]:x[parentA]))*.5+(rnd()-.5)*16,0,W-1);y[i]=clamp((y[parentA]+(parentB>=0?y[parentB]:y[parentA]))*.5+(rnd()-.5)*16,0,H-1);for(let k=0;k<GENES;k++){const source=parentB>=0&&rnd()<.5?parentB:parentA;sg(i,k,mutateGene(g(source,k),.045+.035*rnd()));}generation[i]=Math.max(generation[parentA],parentB>=0?generation[parentB]:0)+1;}else{const p=randomHabitat(sp);x[i]=p.x;y[i]=p.y;for(let k=0;k<GENES;k++)sg(i,k,bases[sp][k]+(rnd()+rnd()-1)*.11);generation[i]=0;}vx[i]=vy[i]=0;count++;return i;}
function kill(i){if(alive[i]){alive[i]=0;count--;}}
function bucketKey(px,py){return`${Math.floor(px/92)},${Math.floor(py/92)}`;}
function rebuildBuckets(){buckets=new Map();for(let i=0;i<MAX;i++)if(alive[i]){const k=bucketKey(x[i],y[i]);let a=buckets.get(k);if(!a)buckets.set(k,a=[]);a.push(i);}}
function nearby(i,radius){const out=[],bx=Math.floor(x[i]/92),by=Math.floor(y[i]/92),rr=Math.ceil(radius/92);for(let oy=-rr;oy<=rr;oy++)for(let ox=-rr;ox<=rr;ox++){const a=buckets.get(`${bx+ox},${by+oy}`);if(a)for(const j of a)if(j!==i)out.push(j);}return out;}
function nearest(i,pred,radius){let best=-1,bd=radius*radius;for(const j of nearby(i,radius)){if(!alive[j]||!pred(j))continue;const dx=x[j]-x[i],dy=y[j]-y[i],d=dx*dx+dy*dy;if(d<bd){bd=d;best=j;}}return best;}
function steer(i,tx,ty,away=false,str=.22){let dx=tx-x[i],dy=ty-y[i],d=Math.hypot(dx,dy)||1;if(away){dx=-dx;dy=-dy;}vx[i]=vx[i]*.80+dx/d*str;vy[i]=vy[i]*.80+dy/d*str;}
function habitatSteer(i){const sp=species[i],z=zoneAt(x[i],y[i]);if(goodHabitat(sp,z,i))return;let best=null,bestScore=-1;for(let tries=0;tries<12;tries++){const ang=rnd()*Math.PI*2,tx=clamp(x[i]+Math.cos(ang)*cell*1.8,0,W-1),ty=clamp(y[i]+Math.sin(ang)*cell*1.8,0,H-1),zz=zoneAt(tx,ty);const score=(habitat[sp].includes(zz?.biome)?1:g(i,11)*.25)+(zz?.food||0)*.25+rnd()*.1;if(score>bestScore){bestScore=score;best=[tx,ty];}}if(best)steer(i,best[0],best[1],false,.20+.15*g(i,11));}
function graze(i){const zi=zoneIndex(x[i],y[i]);if(zi>=zoneFood.length)return;const amount=Math.min(zoneFood[zi],.0016+.0045*g(i,3));zoneFood[zi]=Math.max(0,zoneFood[zi]-amount);energy[i]=Math.min(108,energy[i]+amount*(8+16/g(i,6)));}
function predatorStep(i,sp,vision,agg,size,endurance){const target=nearest(i,j=>prey[sp].includes(species[j]),55+vision*135);if(target<0){vx[i]+=(rnd()-.5)*.14;vy[i]+=(rnd()-.5)*.14;return;}steer(i,x[target],y[target],false,.24+.22*agg+.08*endurance);const dx=x[target]-x[i],dy=y[target]-y[i],contact=(5+size*4+g(target,6)*2);if(dx*dx+dy*dy<contact*contact){const hit=(8+agg*11+size*5)*(0.72+rnd()*.56);energy[target]-=hit;energy[i]-=.7;if(energy[target]<=0){energy[i]=Math.min(112,energy[i]+15+g(target,6)*10);kill(target);}}}
function herbivoreStep(i,sp,vision,fear,social){const predator=nearest(i,j=>prey[species[j]]?.includes(sp),45+vision*120);if(predator>=0&&fear>.12){steer(i,x[predator],y[predator],true,.29+.24*fear);energy[i]-=.012;return;}if(social>.46){const group=nearest(i,j=>species[j]===sp,48+vision*55);if(group>=0&&rnd()<.035)steer(i,x[group],y[group],false,.10+.08*social);}vx[i]+=(rnd()-.5)*.12;vy[i]+=(rnd()-.5)*.12;graze(i);}
function maybeMate(i){if(mateCooldown[i]>0){mateCooldown[i]--;return;}const sp=species[i],maturity=260+g(i,9)*720;if(age[i]<maturity||energy[i]<82)return;const mate=nearest(i,j=>species[j]===sp&&age[j]>=260+g(j,9)*720&&energy[j]>80&&mateCooldown[j]===0,45+g(i,7)*55);if(mate<0)return;const fertility=(g(i,4)+g(mate,4))*.5,litter=(g(i,10)+g(mate,10))*.5;if(rnd()<fertility*.00105){const babies=1+(rnd()<Math.max(0,litter-.55)*.55?1:0);for(let b=0;b<babies&&count<MAX;b++)spawn(sp,i,mate);energy[i]-=10+babies*4;energy[mate]-=8+babies*3;mateCooldown[i]=mateCooldown[mate]=400+((rnd()*500)|0);}}
function stepOne(i){if(!alive[i])return;age[i]++;const sp=species[i],speed=g(i,0),vision=g(i,1),agg=g(i,2),met=g(i,3),fear=g(i,5),size=g(i,6),social=g(i,7),endurance=g(i,8);const juvenile=clamp(age[i]/Math.max(220,260+g(i,9)*720),.35,1);const upkeep=(.007+.018*met*size)*(1.15-.25*endurance);energy[i]-=upkeep;if(prey[sp])predatorStep(i,sp,vision,agg,size,endurance);else herbivoreStep(i,sp,vision,fear,social);habitatSteer(i);const max=(.20+speed*.76/Math.sqrt(Math.max(.35,size)))*(0.65+.35*juvenile)*(0.78+.22*endurance),m=Math.hypot(vx[i],vy[i]);if(m>max){vx[i]=vx[i]/m*max;vy[i]=vy[i]/m*max;}x[i]=clamp(x[i]+vx[i],0,W-1);y[i]=clamp(y[i]+vy[i],0,H-1);maybeMate(i);const lifespan=13500+(1-met)*6500+endurance*3200;if(energy[i]<=0||age[i]>lifespan)kill(i);}
function regrowZones(){const n=Math.min(zones.length,zoneFood.length);for(let i=0;i<n;i++){const base=zoneBaseFood[i],f=zoneFood[i];const moisture=zones[i]?.biome==='DESERT'?.35:zones[i]?.biome==='ALPINE'?.28:1;zoneFood[i]=Math.min(base,f+(base-f)*.00085*moisture+base*.000015);}}
function initialCounts(){const area=Math.sqrt(Math.max(1,zones.length/504)),total=Math.min(430,Math.round((42+wildlife*230)*area));const predatorShare=.018+predators*.13;const weights=[.24,.10,predatorShare*.40,.30,.14,predatorShare*.30,predatorShare*.13,.08];const sum=weights.reduce((a,b)=>a+b,0);return weights.map(w=>Math.max(1,Math.round(total*w/sum)));}
function snapshot(){const arr=[];for(let i=0;i<MAX;i++)if(alive[i]){const juvenile=clamp(age[i]/Math.max(220,260+g(i,9)*720),.35,1);arr.push({id:i,x:x[i],y:y[i],species:species[i],energy:energy[i],speed:g(i,0),size:g(i,6)*juvenile,fear:g(i,5),generation:generation[i],age:age[i]});}postMessage({type:'snapshot',tick,count,animals:arr,speciesNames:SPECIES});}
function init(m){seed=m.seed>>>0||1;W=m.width||W;H=m.height||H;cols=m.cols||1;rows=m.rows||1;cell=m.cell||64;zones=m.zones||[];wildlife=clamp(Number(m.wildlife??.3),0,1);predators=clamp(Number(m.predators??.22),0,1);for(let i=0;i<MAX;i++)alive[i]=0;count=0;for(let i=0;i<Math.min(zones.length,zoneFood.length);i++){zoneBaseFood[i]=clamp(Number(zones[i]?.food??.25),.02,1);zoneFood[i]=zoneBaseFood[i];}const counts=initialCounts();for(let sp=0;sp<SPECIES.length;sp++)for(let n=0;n<counts[sp];n++)spawn(sp);rebuildBuckets();snapshot();}
function loop(){if(running){tick++;rebuildBuckets();for(let i=0;i<MAX;i++)stepOne(i);regrowZones();if(tick%7===0)snapshot();}setTimeout(loop,24);}
onmessage=e=>{const m=e.data||{};if(m.type==='init')init(m);else if(m.type==='pause')running=!!m.running;else if(m.type==='hunt'){let best=-1,bd=(m.radius||85)**2;for(let i=0;i<MAX;i++){if(!alive[i]||prey[species[i]]||species[i]===4)continue;const dx=x[i]-m.x,dy=y[i]-m.y,d=dx*dx+dy*dy;if(d<bd){bd=d;best=i;}}if(best>=0){const meat=8+energy[best]*.08+g(best,6)*8,sp=species[best];kill(best);postMessage({type:'huntResult',requestId:m.requestId,ok:true,meat,species:sp});}else postMessage({type:'huntResult',requestId:m.requestId,ok:false,meat:0});}};
loop();
