import { DEFAULT_WORLD_SETTINGS,WORLDGEN_CONTROLS,randomSeed,sanitizeWorldSettings } from './v10_config.js';
import { createWorldV10,currentChunkV10,neighboringChunksV10,rebuildOccupancyV10,takeWorldBatchV10,updateEnvironmentV10 } from './world_v10.js';
import { createPixelEngineV10,drawMiniMap } from './pixel_engine_v10.js';
import { decoratePersonV10,generatedIntent,practice,refreshGeneratedRole,remember,updateNeeds,LIFE_SKILLS } from './people_v10.js';
import { createAgent,emptyLibrary,setActiveLibrary,scoreCandidate,retargetAgent,socialLearn } from './evolution.js';
import { createChronicle,createTribeState,recordHistory,updateClock,syncInventions,runGamerSoftware,applyFireKeeper } from './caveman.js';
import { PROJECTS,createProjectState,projectReady,projectProgress,stepProject,renderProjectAscii } from './projects.js';
import { disassemble,randomProgram } from './vm.js';
import { VERIFY_CASES,evaluateProgram,unlockedTaskNames } from './tasks.js';
const $=id=>document.getElementById(id),canvas=$('world'),drawer=$('drawer'),drawerBody=$('drawerBody'),drawerTitle=$('drawerTitle');
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let world=null,engine=createPixelEngineV10(canvas),agents=[],animals=[],speciesNames=[],structures=[],library=emptyLibrary(),chronicle=createChronicle(),tribe=createTribeState(),selected=null,nextId=1,tick=0,rain=0,flood=0,paused=false,speed=1,last=performance.now(),acc=0,eco=null,huntSeq=1,pendingHunts=new Map(),drawerMode=null,lastDrawer=0,activeProject=null,projectState=null,randomTool=null,follow=false,programAttempts=0,settings={...DEFAULT_WORLD_SETTINGS,seed:randomSeed()};
const camp=()=>world?.chunks[world.campId],center=c=>({x:(c.cx+.5)*world.cell,y:(c.cy+.5)*world.cell});
function history(text,type='WORLD',key=null){recordHistory(chronicle,world.sweep,text,type,key);}
function initPerson(parent=null){const a=createAgent(nextId++,Math.random,parent,library);decoratePersonV10(a,a.id-1,Math.random,parent);a.energy=parent?70+Math.random()*16:72+Math.random()*20;a.morale=62+Math.random()*24;a.softwareState={};a.gamesPlayed=0;a.softwareUses=0;a.gameScore=0;a.inventory={food:0,wood:0,stone:0};a.lastAction='EXPLORE';agents.push(a);return a;}
function placeFounders(){const p=center(camp()),ns=neighboringChunksV10(world,camp());agents.forEach((a,i)=>{a.x=p.x+(i-2)*7;a.y=p.y+(i%2?5:-5);const n=ns[i%Math.max(1,ns.length)]||camp(),q=center(n);a.tx=q.x;a.ty=q.y;});}
function initialStructures(){const p=center(camp());structures=[{id:1,type:'FIRE',x:p.x,y:p.y+5},{id:2,type:'SHELTER',x:p.x-18,y:p.y-4,doorT:0}];}
function initEcology(){try{eco?.terminate();eco=new Worker('./src/ecology_worker_v10.js',{type:'module'});eco.onmessage=e=>{const m=e.data||{};if(m.type==='snapshot'){animals=m.animals||[];speciesNames=m.speciesNames||speciesNames;}else if(m.type==='huntResult'){const who=pendingHunts.get(m.requestId);pendingHunts.delete(m.requestId);const a=agents.find(x=>x.id===who);if(m.ok){tribe.food+=m.meat;tribe.totalHunts++;if(a){practice(a,'hunt',.045);a.morale=Math.min(100,a.morale+1.5);remember(a,`successful hunt: ${speciesNames[m.species]||'animal'}`,tick);}history(`${a?.name||'A hunter'} returned with ${m.meat.toFixed(0)} food after hunting ${speciesNames[m.species]||'wildlife'}.`,'SURVIVAL',tribe.totalHunts===1?'first-hunt':null);}}};eco.postMessage({type:'init',seed:world.seed,width:world.width,height:world.height,cols:world.cols,rows:world.rows,cell:world.cell,wildlife:world.settings.wildlife,predators:world.settings.predators,zones:world.chunks.map(c=>({cx:c.cx,cy:c.cy,biome:c.biome,food:c.food,game:c.game}))});}catch{animals=[];}}
function beginWorld(nextSettings=settings){settings=sanitizeWorldSettings(nextSettings);library=emptyLibrary();setActiveLibrary(library);chronicle=createChronicle();tribe=createTribeState();world=createWorldV10(settings);agents=[];animals=[];structures=[];nextId=1;tick=0;rain=flood=0;selected=null;activeProject=projectState=randomTool=null;programAttempts=0;for(let i=0;i<5;i++)initPerson();placeFounders();initialStructures();rebuildOccupancyV10(world,agents);selected=agents[0];engine.setWorld(world);initEcology();history('Five founders entered the generated world. Their identities and future work are not assigned classes.','FOUNDING','founding');$('worldgen').classList.add('hidden');updateHUD();openDrawer(null);}
function scoreRegion(a,c,intent){let s=(a.visited.has(c.id)?-.12:.15*(a.personality.curiosity||.5))-c.danger*.35-c.flood*.30;const n=a.needs;if(intent==='FORAGE')s+=c.food*.70+c.water*.10;if(intent==='HUNT')s+=c.game*.78+c.food*.12;if(intent==='CRAFT'||intent==='BUILD')s+=(c.wood+c.stone+c.ore)*.30;if(intent==='EXPLORE')s+=.20+(1-Math.abs(.5-c.elevation))*.05;if(intent==='REST')s+=c.shelter*.8;if(n.safety>.55)s+=c.shelter*.25-c.danger*.25;return s;}
function chooseDestination(a,c,intent){const candidates=[c,...neighboringChunksV10(world,c)],best=candidates.map(x=>[x,scoreRegion(a,x,intent)+Math.random()*.12]).sort((u,v)=>v[1]-u[1])[0]?.[0];if(best){const q=center(best);a.tx=clamp(q.x+(Math.random()-.5)*world.cell*.65,0,world.width-1);a.ty=clamp(q.y+(Math.random()-.5)*world.cell*.65,0,world.height-1);}}
function move(a,mult=1){const dx=a.tx-a.x,dy=a.ty-a.y,d=Math.hypot(dx,dy)||1;a.vx=(a.vx||0)*.68+dx/d*.32;a.vy=(a.vy||0)*.68+dy/d*.32;const pace=(1.25+(a.aptitudes.explore||.5)*.65)*mult;a.x=clamp(a.x+a.vx*pace,0,world.width-1);a.y=clamp(a.y+a.vy*pace,0,world.height-1);}
function programWork(a,c){programAttempts++;const before=Object.keys(library).length,out=scoreCandidate(a,library,Math.random);practice(a,'program',.018);practice(a,'tinker',.005);c.programs++;if(out.shipped&&out.improved){history(`${a.name} evolved verified ${a.task} code after real execution testing.`,'SOFTWARE',`skill:${a.task}`);remember(a,`verified ${a.task}`,tick);}if(Object.keys(library).length>before){syncInventions(chronicle,library,world.sweep);for(const p of agents)retargetAgent(p,library,Math.random);}}
function requestHunt(a){if(!eco||pendingHunts.size>4)return;const id=huntSeq++;pendingHunts.set(id,a.id);eco.postMessage({type:'hunt',requestId:id,x:a.x,y:a.y,radius:75+(a.aptitudes.track||.5)*70});}
function forage(a,c){const take=Math.min(c.food,.010+.014*(a.aptitudes.forage||.5)+Math.random()*.008);c.food=Math.max(0,c.food-take);tribe.food+=take*52;a.energy=Math.min(100,a.energy+take*80);a.carrying=take>.008?'food':null;practice(a,'forage',.022);}
function craft(a,c){const wood=Math.min(c.wood||0,.010+.010*a.aptitudes.craft),stone=Math.min(c.stone||c.ore||0,.008+.008*a.aptitudes.craft);c.wood=Math.max(0,(c.wood||0)-wood);c.stone=Math.max(0,(c.stone||0)-stone);tribe.wood+=wood*30;tribe.stone+=stone*30;a.carrying=wood>stone?'wood':'stone';practice(a,'craft',.024);if(tribe.wood>2.2&&tribe.stone>1.1&&Math.random()<.035+.04*a.aptitudes.craft){tribe.wood-=2.2;tribe.stone-=1.1;tribe.tools++;a.morale=Math.min(100,a.morale+1.3);history(`${a.name} made tool #${tribe.tools}.`,'TECH',tribe.tools===1?'first-tool':null);}}
function tryBuild(a){practice(a,'build',.018);const near=structures.filter(s=>Math.hypot(s.x-a.x,s.y-a.y)<48);if(tribe.wood>=5&&!near.some(s=>s.type==='SHELTER')&&Math.random()<.10){tribe.wood-=5;structures.push({id:structures.length+1,type:'SHELTER',x:a.x+10,y:a.y+4,doorT:0});history(`${a.name} assembled a new shelter with an opening that inhabitants physically pass through.`,'BUILD');remember(a,'built a shelter',tick);return true;}if(tribe.wood>=3&&tribe.tools>=1&&!near.some(s=>s.type==='WORKBENCH')&&Math.random()<.08){tribe.wood-=3;structures.push({id:structures.length+1,type:'WORKBENCH',x:a.x+8,y:a.y+3});history(`${a.name} assembled a workbench near camp.`,'BUILD');return true;}if(tribe.wood>=4&&!near.some(s=>s.type==='STORE')&&Math.random()<.07){tribe.wood-=4;structures.push({id:structures.length+1,type:'STORE',x:a.x-8,y:a.y+3});history(`${a.name} created a communal storage rack.`,'BUILD');return true;}return false;}
function nearestStructure(a,type){let best=null,bd=Infinity;for(const s of structures){if(type&&s.type!==type)continue;const d=(s.x-a.x)**2+(s.y-a.y)**2;if(d<bd){bd=d;best=s;}}return best;}
function stepPerson(a){if(!a.alive)return;const c=currentChunkV10(world,a),newRegion=!a.visited.has(c.id);a.visited.add(c.id);a.age++;a.energy-=.025+.008*(a.appearance.build||1);a.morale=Math.max(0,a.morale-.002);const peers=c.agents.filter(x=>x!==a&&x.alive);updateNeeds(a,{danger:c.danger,flood:c.flood,peers:peers.length,newRegion});let intent=generatedIntent(a,c,Math.random);a.lastAction=intent;a.anim=intent.toLowerCase();a.carrying=null;
if(intent==='REST'){const s=nearestStructure(a,'SHELTER');if(s){a.tx=s.x;a.ty=s.y;}a.energy=Math.min(100,a.energy+.20+c.shelter*.20);move(a,.72);}
else if(intent==='FORAGE'){forage(a,c);if(Math.hypot(a.tx-a.x,a.ty-a.y)<15||Math.random()<.16)chooseDestination(a,c,intent);move(a,.72);}
else if(intent==='HUNT'){practice(a,'track',.012);if(Math.random()<.12+.10*a.aptitudes.hunt)requestHunt(a);if(Math.random()<.18)chooseDestination(a,c,intent);move(a,.9);}
else if(intent==='EXPLORE'){practice(a,'explore',.018);if(Math.hypot(a.tx-a.x,a.ty-a.y)<18||Math.random()<.10)chooseDestination(a,c,intent);move(a,1.05);}
else if(intent==='CRAFT'){craft(a,c);if((c.wood+c.stone)<.25&&Math.random()<.18)chooseDestination(a,c,intent);move(a,.45);}
else if(intent==='BUILD'){if(!tryBuild(a)){craft(a,c);if(Math.random()<.12)chooseDestination(a,c,'CRAFT');}move(a,.38);}
else if(intent==='PROGRAM'){programWork(a,c);practice(a,'program',.018);const bench=nearestStructure(a,'WORKBENCH');if(bench){a.tx=bench.x;a.ty=bench.y;move(a,.35);}}
else if(intent==='PLAY'){practice(a,'play',.015);const r=runGamerSoftware(a,library,chronicle,world.sweep);if(r.used)a.morale=Math.min(100,a.morale+1);else a.morale=Math.min(100,a.morale+.10);}
else if(intent==='SOCIAL'){practice(a,'social',.018);if(peers.length){const b=peers[(Math.random()*peers.length)|0];socialLearn(a,b,Math.random);a.tx=b.x;a.ty=b.y;move(a,.5);}a.morale=Math.min(100,a.morale+.08);}
if(tick%90===a.id%90){const old=a.currentRole;refreshGeneratedRole(a,Math.random);if(old!==a.currentRole&&Math.max(...Object.values(a.lifeSkills))>.35)history(`${a.name} is now known as a ${a.currentRole}, based on what they actually practice.`,'LIFE',`role:${a.id}:${a.currentRole}`);}if(a.energy<=0||a.age>22000){a.alive=false;history(`${a.name} died.`,'DEATH',`death:${a.id}`);}if(a.energy>82&&a.morale>68&&a.age>900&&agents.length<36&&Math.random()<.00028){const child=initPerson(a);child.x=a.x+4;child.y=a.y+4;child.tx=a.x;child.ty=a.y;practice(a,'social',.04);history(`${child.name} was born with inherited and mutated traits.`,'BIRTH',`birth:${child.id}`);}}
function simStep(){if(!world)return;tick++;for(const c of takeWorldBatchV10(world,20))updateEnvironmentV10(c,{rain,flood});for(const a of agents)stepPerson(a);if(tick%3===0)rebuildOccupancyV10(world,agents);if(tick%12===0){updateClock(chronicle,world.sweep);syncInventions(chronicle,library,world.sweep);applyFireKeeper(tribe,library,chronicle,world.sweep);const need=agents.length*.035,eat=Math.min(tribe.food,need);tribe.food-=eat;if(eat<need)for(const a of agents)a.energy-=.18;if(rain>0){rain=Math.max(0,rain-.018);flood=Math.min(1,flood+.006*rain);}else flood=Math.max(0,flood-.0025);}agents=agents.filter(a=>a.alive);if(!agents.length)paused=true;}
function updateHUD(){if(!world)return;$('hudTime').textContent=`Y${chronicle.year} · ${chronicle.season}`;$('hudPop').textContent=`${agents.length} lives`;$('hudWild').textContent=`${animals.length} wild`;$('hudLearned').textContent=`${Object.keys(library).length} software`;$('eventTicker').textContent=chronicle.entries[0]?.text||'World beginning…';$('speed').textContent=`×${speed}`;$('pause').textContent=paused?'▶':'Ⅱ';}
function personCard(a){const c=currentChunkV10(world,a),top=Object.entries(a.lifeSkills).sort((x,y)=>y[1]-x[1]).slice(0,5);return`<section class="person-sheet"><div class="sheet-head"><div><small>GENERATED LIFE #${a.id}</small><h2>${esc(a.name)}</h2><b>${esc(a.currentRole)}</b></div><button data-follow="${a.id}">◎ FOLLOW</button></div><p>${esc(a.roleReason)}</p><div class="meter-grid"><span>energy <b>${a.energy.toFixed(0)}</b></span><span>morale <b>${a.morale.toFixed(0)}</b></span><span>region <b>${esc(c.region)}</b></span><span>action <b>${a.lastAction}</b></span></div><h3>Practiced skills</h3>${top.map(([k,v])=>`<div class="skill-line"><span>${k}</span><i><em style="width:${Math.min(100,v*55)}%"></em></i><b>${v.toFixed(2)}</b></div>`).join('')}<h3>Personality</h3><div class="trait-cloud">${Object.entries(a.personality).map(([k,v])=>`<span>${k} ${Math.round(v*100)}</span>`).join('')}</div><h3>Recent memories</h3>${a.memories.map(m=>`<p class="memory">${esc(m.text)}</p>`).join('')||'<p class="muted">No durable memories yet.</p>'}</section>`;}
function renderLives(){drawerTitle.textContent='LIVES';drawerBody.innerHTML=`<div class="life-grid">${agents.map(a=>`<button class="life-card ${a===selected?'selected':''}" data-person="${a.id}"><b>${esc(a.name)}</b><span>${esc(a.currentRole)}</span><small>${a.lastAction} · E${a.energy.toFixed(0)}</small></button>`).join('')}</div>${selected?personCard(selected):''}`;drawerBody.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{selected=agents.find(a=>a.id===+b.dataset.person)||selected;renderLives();});drawerBody.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>{selected=agents.find(a=>a.id===+b.dataset.follow)||selected;follow=true;engine.focus(selected.x,selected.y);$('follow').classList.add('active');closeDrawer();});}
function randomProgramNow(){const tasks=unlockedTaskNames(library),task=tasks[(Math.random()*tasks.length)|0],program=randomProgram(Math.random,2,12),report=evaluateProgram(program,task,VERIFY_CASES);randomTool={task,program,report};renderSoftware();}
function openProject(id){const p=PROJECTS.find(x=>x.id===id);if(!p||!projectReady(p,library))return;activeProject=id;projectState=createProjectState(id);renderSoftware();}
function renderSoftware(){drawerTitle.textContent='SOFTWARE LAB';const learned=Object.keys(library);drawerBody.innerHTML=`<section class="lab-hero"><small>EXECUTABLE EVOLUTION</small><h2>${programAttempts.toLocaleString()} agent search rounds</h2><p>Agents mutate executable VM programs. Nothing joins shared software until it passes the complete verifier.</p><button id="randomProgram" class="accent">⚄ GENERATE RANDOM PROGRAM</button></section>${randomTool?`<section><div class="row"><b>Random ${randomTool.task}</b><span>${Math.round(randomTool.report.passRate*96)}/96</span></div><pre>${esc(disassemble(randomTool.program))}</pre><p class="muted">This random program is a sandbox experiment. It is not injected into the tribe's verified library.</p></section>`:''}${activeProject?`<section><h3>${esc(PROJECTS.find(p=>p.id===activeProject)?.title||activeProject)}</h3><pre class="game-screen">${esc(renderProjectAscii(projectState))}</pre><div class="button-row"><button id="left">◀</button><button id="step">STEP</button><button id="right">▶</button><button id="closeRun">CLOSE</button></div></section>`:''}<section><h3>Verified shared skills</h3><div class="trait-cloud">${learned.map(k=>`<span>${k}</span>`).join('')||'<span>none yet</span>'}</div></section><div class="project-list">${PROJECTS.map(p=>{const q=projectProgress(p,library),ready=projectReady(p,library);return`<article class="project-card ${ready?'ready':''}"><div><b>${esc(p.title)}</b><small>${esc(p.kind)}</small></div><span>${ready?'RUN':`${q.learned.length}/${q.total}`}</span>${ready?`<button data-project="${p.id}">▶</button>`:''}</article>`;}).join('')}</div>`;$('randomProgram').onclick=randomProgramNow;drawerBody.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.project));const run=v=>{if(projectState){stepProject(projectState,library,v);renderSoftware();}};if($('left'))$('left').onclick=()=>run(-1);if($('right'))$('right').onclick=()=>run(1);if($('step'))$('step').onclick=()=>run(0);if($('closeRun'))$('closeRun').onclick=()=>{activeProject=null;projectState=null;renderSoftware();};}
function renderHistory(){drawerTitle.textContent='WORLD HISTORY';drawerBody.innerHTML=`<section class="history-head"><h2>${chronicle.era}</h2><p>Year ${chronicle.year} · ${chronicle.season}</p></section><div class="timeline">${chronicle.entries.slice(0,100).map(e=>`<article><time>Y${e.year} ${e.season}</time><b>${esc(e.type)}</b><p>${esc(e.text)}</p></article>`).join('')||'<p>No events yet.</p>'}</div>`;}
function renderWorld(){drawerTitle.textContent='WORLD';const s=world.summary,b=Object.entries(s.biomes).sort((a,b)=>b[1]-a[1]);drawerBody.innerHTML=`<section><canvas id="drawerMap" class="drawer-map" width="320" height="190"></canvas><div class="world-seed">SEED ${world.seed}</div></section><section><h3>Generation parameters</h3><div class="settings-readout">${Object.entries(world.settings).filter(([k])=>k!=='seed').map(([k,v])=>`<span>${k}<b>${typeof v==='number'?Math.round(v*100)+'%':v}</b></span>`).join('')}</div></section><section><h3>Geography</h3><div class="meter-grid"><span>regions <b>${world.chunks.length}</b></span><span>river tiles <b>${s.rivers}</b></span><span>lakes <b>${s.lakes}</b></span><span>caves <b>${s.caves}</b></span><span>ruins <b>${s.ruins}</b></span><span>ocean <b>${s.ocean}</b></span></div><div class="trait-cloud">${b.map(([k,v])=>`<span>${k} ${v}</span>`).join('')}</div></section>`;drawMiniMap($('drawerMap'),world,agents);}
function openDrawer(mode){drawerMode=mode;if(!mode){drawer.classList.remove('open');return;}drawer.classList.add('open');if(mode==='lives')renderLives();else if(mode==='software')renderSoftware();else if(mode==='history')renderHistory();else renderWorld();}
function closeDrawer(){drawerMode=null;drawer.classList.remove('open');}
function renderWorldgenControls(){const box=$('settingsControls');box.innerHTML=WORLDGEN_CONTROLS.map(c=>`<label class="setting"><div><b>${c.label}</b><small>${c.help}</small></div><output id="out_${c.key}">${Math.round(settings[c.key]*100)}</output><input type="range" min="0" max="100" value="${Math.round(settings[c.key]*100)}" data-setting="${c.key}"></label>`).join('');box.querySelectorAll('[data-setting]').forEach(input=>input.oninput=()=>{settings[input.dataset.setting]=+input.value/100;$(`out_${input.dataset.setting}`).textContent=input.value;schedulePreview();});document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{settings.size=b.dataset.size;document.querySelectorAll('[data-size]').forEach(x=>x.classList.toggle('selected',x===b));schedulePreview();});$('seedInput').value=settings.seed;}
let previewTimer=0;function schedulePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(updatePreview,80);}function updatePreview(){const p={...settings,seed:+$('seedInput').value||settings.seed};const w=createWorldV10(p);drawMiniMap($('worldPreview'),w);$('previewStats').textContent=`${w.cols}×${w.rows} regions · ${w.summary.rivers} river tiles · ${w.summary.caves} caves · ${Object.keys(w.summary.biomes).length} biomes`;}
function setPreset(name){const p={BALANCED:{landmass:.68,roughness:.58,wetness:.56,temperature:.52,rivers:.58,forests:.60,wildlife:.30,predators:.22,ruins:.10},ISLANDS:{landmass:.40,roughness:.46,wetness:.72,temperature:.60,rivers:.70,forests:.72,wildlife:.26,predators:.16,ruins:.07},WILD:{landmass:.70,roughness:.75,wetness:.63,temperature:.52,rivers:.70,forests:.72,wildlife:.48,predators:.55,ruins:.13},HARSH:{landmass:.72,roughness:.82,wetness:.24,temperature:.66,rivers:.24,forests:.20,wildlife:.17,predators:.36,ruins:.18}}[name];if(p){settings={...settings,...p};renderWorldgenControls();updatePreview();}}
function setupWorldgen(){settings={...DEFAULT_WORLD_SETTINGS,seed:randomSeed()};renderWorldgenControls();document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>setPreset(b.dataset.preset));$('rerollSeed').onclick=()=>{settings.seed=randomSeed();$('seedInput').value=settings.seed;updatePreview();};$('seedInput').onchange=()=>{settings.seed=+$('seedInput').value>>>0;updatePreview();};$('generateWorld').onclick=()=>{settings.seed=+$('seedInput').value>>>0||randomSeed();beginWorld(settings);};updatePreview();}
function nearestHuman(wx,wy){let best=null,bd=Infinity;for(const a of agents){const d=(a.x-wx)**2+(a.y-wy)**2;if(d<bd){bd=d;best=a;}}return bd<45*45?best:null;}
let drag=null;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY};});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=drag.x-e.clientX,dy=drag.y-e.clientY;if(Math.abs(dx)+Math.abs(dy)>1){engine.pan(dx,dy);follow=false;$('follow').classList.remove('active');}drag.x=e.clientX;drag.y=e.clientY;});canvas.addEventListener('pointerup',e=>{if(!drag)return;const moved=Math.hypot(e.clientX-drag.sx,e.clientY-drag.sy);if(moved<8){const p=engine.screenToWorld(e.clientX,e.clientY),a=nearestHuman(p.x,p.y);if(a){selected=a;openDrawer('lives');}}drag=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();const p=engine.screenToWorld(e.clientX,e.clientY);engine.zoomBy(e.deltaY<0?1.16:.86,p.x,p.y);},{passive:false});
$('zoomIn').onclick=()=>engine.zoomBy(1.22);$('zoomOut').onclick=()=>engine.zoomBy(.82);$('pause').onclick=()=>{paused=!paused;eco?.postMessage({type:'pause',running:!paused});updateHUD();};$('speed').onclick=()=>{const speeds=[1,2,4,8,16],i=speeds.indexOf(speed);speed=speeds[(i+1)%speeds.length];updateHUD();};$('storm').onclick=()=>{rain=Math.max(rain,.9);history('A storm crossed the region.','WEATHER');};$('newWorld').onclick=()=>{$('worldgen').classList.remove('hidden');closeDrawer();};$('follow').onclick=()=>{follow=!follow;$('follow').classList.toggle('active',follow);if(follow&&selected)engine.focus(selected.x,selected.y);};$('drawerClose').onclick=closeDrawer;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDrawer(b.dataset.open));addEventListener('resize',()=>engine.resize());
function frame(now){const dt=Math.min(80,now-last);last=now;if(world&&!paused){acc+=dt*speed;let steps=0;while(acc>=33&&steps<12){simStep();acc-=33;steps++;}if(steps===12&&acc>200)acc=0;}if(world){if(follow&&selected?.alive)engine.focus(selected.x,selected.y);engine.render({world,humans:agents,animals,structures,selectedId:selected?.id,storm:rain},now);if(now-lastDrawer>350){lastDrawer=now;updateHUD();if(drawerMode==='lives')renderLives();else if(drawerMode==='history')renderHistory();else if(drawerMode==='world')renderWorld();}}requestAnimationFrame(frame);}setupWorldgen();requestAnimationFrame(frame);
