import { TASKS,VERIFY_CASES,evaluateProgram,unlockedTaskNames } from './tasks.js';
import { chooseAction } from './brain.js';
import { createAgent,critiqueAgent,emptyLibrary,retargetAgent,scoreCandidate,socialLearn,setActiveLibrary } from './evolution.js';
import { CHUNK_COUNT,CHUNK_SIZE,WORLD_H,WORLD_W,chunkIndexFor,createWorld,neighboringChunks,rebuildOccupancy,takeChunkBatch,updateEnvironment } from './world.js';
import { LEGEND,MAP_COLS,MAP_ROWS,drawAsciiWorld,mapTileToWorld } from './ascii.js';
import { PROJECTS,createProjectState,projectProgress,projectReady,renderProjectAscii,stepProject } from './projects.js';
import { attachCavemanIdentity,createChronicle,createTribeState,recordHistory,syncInventions,chooseResourceNeighbor,runGamerSoftware,applyFireKeeper,eraProgress,updateClock } from './caveman.js';
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d',{alpha:false}),panel=$('panel'),hud=$('hud');
let W=1000,H=700,DPR=1,paused=false,turbo=1,tick=0,rain=0,flood=0,nextId=1,lastDraw=0,lastUI=0,frames=0,simOps=0,lastStats=performance.now(),fps=0,ops=0;
let world,agents=[],selected=null,library=emptyLibrary(),chronicle=createChronicle(),tribe=createTribeState(),events=[],tab='tribe',activeProject=null,projectState=null,popCap=+$('popCap').value;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function log(msg,type='info'){events.unshift({msg,type,sweep:world?.sweep||0});if(events.length>36)events.length=36;}
function resize(){const r=canvas.getBoundingClientRect();DPR=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(r.width*DPR));canvas.height=Math.max(1,Math.floor(r.height*DPR));W=r.width;H=r.height;ctx.setTransform(DPR,0,0,DPR,0,0);}addEventListener('resize',resize);resize();
function currentChunk(a){return world.chunks[chunkIndexFor(a.x,a.y)];}
function spawn(parent=null){if(agents.length>=popCap)return null;const a=createAgent(nextId++,Math.random,parent,library);attachCavemanIdentity(a,a.id-1);a.memory={regions:{},lastRegion:null};a.curiosity=.35+Math.random()*.65;a.courage=.25+Math.random()*.7;a.homeId=world?.campId??0;if(parent){a.x=parent.x;a.y=parent.y;if(Math.random()<.6)a.lifeRole=parent.lifeRole;}agents.push(a);return a;}
function scoreDestination(a,c){const novelty=1-Math.min(1,(a.memory.regions[c.region]||0)/12),safe=1-c.danger,water=c.water||0,food=c.food||0,game=c.game||0,wood=c.wood||0,stone=c.stone||c.ore||0;let need=food*.25+water*.20;if(a.lifeRole==='HUNTER')need=game*.72+food*.12;if(a.lifeRole==='GATHERER')need=food*.68+water*.14;if(a.lifeRole==='CRAFTER')need=(wood+stone)*.38;if(a.lifeRole==='THINKER')need=(c.jobs||0)*.55+safe*.1;if(a.lifeRole==='GAMER')need=safe*.32+food*.12;return need+novelty*a.curiosity*.45+safe*.16-c.flood*.7;}
function chooseDestination(a,c){const ns=neighboringChunks(world,c);if(!ns.length)return c;if(library.PICK_HIGH?.report?.verified){const learned=chooseResourceNeighbor(a,ns,library,Math.random);if(learned&&Math.random()<.55)return learned;}let best=ns[0],bestScore=-Infinity;for(const n of ns){const s=scoreDestination(a,n)+Math.random()*.08;if(s>bestScore){best=n;bestScore=s;}}return best;}
function setTarget(a,c){a.tx=c.cx*CHUNK_SIZE+18+Math.random()*(CHUNK_SIZE-36);a.ty=c.cy*CHUNK_SIZE+18+Math.random()*(CHUNK_SIZE-36);}
function move(a,mult=1){const dx=a.tx-a.x,dy=a.ty-a.y,d=Math.hypot(dx,dy)||1;a.vx=a.vx*.62+(dx/d)*.38;a.vy=a.vy*.62+(dy/d)*.38;a.x=clamp(a.x+a.vx*4.8*mult,0,WORLD_W-1);a.y=clamp(a.y+a.vy*4.8*mult,0,WORLD_H-1);}
function placeFounders(){const camp=world.chunks[world.campId];for(let i=0;i<agents.length;i++){const a=agents[i];a.x=camp.cx*CHUNK_SIZE+50+(i-2)*5;a.y=camp.cy*CHUNK_SIZE+50+(i%2?4:-4);const first=i<3?chooseDestination(a,camp):camp;setTarget(a,first);}}
function programWork(a,c){const before=Object.keys(library).length,out=scoreCandidate(a,library,Math.random);c.programs++;if(out.improvedPersonal&&a.bestPassRate>.10&&Math.random()<.08)log(`${a.name} improved ${a.task}: ${Math.round(a.bestPassRate*96)}/96`);if(out.shipped&&out.improved){recordHistory(chronicle,world.sweep,`${a.name} evolved verified ${a.task} code.`, 'CODE',`skill:${a.task}`);log(`★ ${a.name} evolved ${a.task} — 96/96`,'good');}if(Object.keys(library).length>before){syncInventions(chronicle,library,world.sweep);for(const p of agents)retargetAgent(p,library,Math.random);}}
function forage(a,c){if(a.lifeRole==='HUNTER'&&(c.game||0)>.01){const take=Math.min(c.game,.012+.015*Math.random());c.game-=take;tribe.food+=take*90*(1+Math.min(.5,tribe.tools*.04));a.energy+=take*170;tribe.totalHunts++;return;}const take=Math.min(c.food,.012+.018*Math.random());c.food-=take;tribe.food+=take*70;a.energy+=take*155;}
function materials(a,c){const wood=Math.min(c.wood||0,.016),stone=Math.min(c.stone||c.ore||0,.013);c.wood=Math.max(0,(c.wood||0)-wood);c.stone=Math.max(0,(c.stone||0)-stone);tribe.wood+=wood*60;tribe.stone+=stone*60;a.energy-=.06;}
function craft(a){if(tribe.wood>=2&&tribe.stone>=1){tribe.wood-=2;tribe.stone-=1;tribe.tools++;tribe.totalCrafts++;a.morale=Math.min(100,a.morale+1.8);recordHistory(chronicle,world.sweep,`${a.name} made a reusable composite tool.`,'TECH',tribe.tools===1?'first-tool':null);return true;}return false;}
function remember(a,c){a.memory.regions[c.region]=(a.memory.regions[c.region]||0)+1;a.memory.lastRegion=c.region;}
function chooseLifeAction(a,c){if(a.energy<24)return c.shelter>.28?'SHELTER':'FORAGE';if(c.flood>.58)return'EXPLORE';if(a.lifeRole==='THINKER'&&a.energy>36&&Math.random()<.60)return'WORK';if(a.lifeRole==='GAMER'&&PROJECTS.some(p=>['COIN_CHASE','HAPPY_WALKER'].includes(p.id)&&projectReady(p,library))&&a.morale<90&&Math.random()<.48)return'PLAY';if(a.lifeRole==='CRAFTER'&&tribe.wood>=2&&tribe.stone>=1&&Math.random()<.52)return'WORK';if(a.lifeRole==='HUNTER'&&(c.game||0)>.12&&Math.random()<.62)return'FORAGE';if(a.lifeRole==='GATHERER'&&c.food>.12&&Math.random()<.62)return'FORAGE';if(Math.hypot(a.tx-a.x,a.ty-a.y)<22||Math.random()<.08)return'EXPLORE';return chooseAction(a.brain,{hunger:clamp((72-a.energy)/62),flood:c.flood,food:c.food,jobs:c.jobs,shelter:c.shelter,danger:c.danger,crowd:clamp(c.agents.length/8),poor:0},Math.random);}
function act(a,c,action){a.lastAction=action;a.energy-=.10;a.morale=Math.max(0,a.morale-.004);remember(a,c);if(action==='FORAGE')forage(a,c);else if(action==='WORK'){if(a.lifeRole==='THINKER')programWork(a,c);else if(a.lifeRole==='CRAFTER'&&!craft(a))materials(a,c);else materials(a,c);}else if(action==='PLAY'){const r=runGamerSoftware(a,library,chronicle,world.sweep);if(r.used)tribe.totalGames++;else a.morale=Math.min(100,a.morale+.2);}else if(action==='SHELTER'){a.energy+=.30*c.shelter+(tribe.fire>20?.10:0);const h=world.chunks[a.homeId]||world.chunks[world.campId];setTarget(a,h);}else if(action==='REST'){a.energy+=.18;a.vx*=.4;a.vy*=.4;}else if(action==='SOCIAL'){const peers=c.agents.filter(x=>x!==a&&x.alive);if(peers.length)socialLearn(a,peers[(Math.random()*peers.length)|0],Math.random);a.morale=Math.min(100,a.morale+.12);}else if(action==='EXPLORE'){setTarget(a,chooseDestination(a,c));a.energy-=.04;}else if(action==='FIGHT'){a.energy-=.5;}if(!['REST','PLAY'].includes(action))move(a,c.flood>.4?.55:1);a.energy=Math.min(100,a.energy);}
function stepAgent(a,c){if(!a.alive)return;a.age++;act(a,c,chooseLifeAction(a,c));if(a.energy>78&&a.morale>68&&a.age>380&&agents.length<popCap&&Math.random()<.0008){const child=spawn(a);if(child){child.x=a.x;child.y=a.y;recordHistory(chronicle,world.sweep,`${child.name} was born.`,'BIRTH',`birth:${child.id}`);}}if(a.energy<=0||a.age>14000+Math.random()*4000){a.alive=false;recordHistory(chronicle,world.sweep,`${a.name} died.`,'DEATH',`death:${a.id}`);}}
function processChunk(c){updateEnvironment(c,{floodLevel:flood,rain});c.visits++;for(const a of c.agents.slice())stepAgent(a,c);}
function finishSweep(){agents=agents.filter(a=>a.alive);rebuildOccupancy(world,agents);updateClock(chronicle,world.sweep);chronicle.era=eraProgress(chronicle,library,tribe);syncInventions(chronicle,library,world.sweep);const need=agents.length*.055,eat=Math.min(tribe.food,need);tribe.food-=eat;if(eat<need)for(const a of agents)a.energy-=((need-eat)/Math.max(.01,need))*.35;if(world.sweep%4===0)applyFireKeeper(tribe,library,chronicle,world.sweep);if(rain>0){rain=Math.max(0,rain-.014);flood=Math.min(1,flood+.005*rain);}else flood=Math.max(0,flood-.0028);if(Math.random()<.004){rain=.5+Math.random()*.5;recordHistory(chronicle,world.sweep,'A storm crossed the region.','WEATHER');}if(!agents.length)paused=true;}
function simBatch(){tick++;simOps++;const before=world.sweep;for(const c of takeChunkBatch(world,6))processChunk(c);if(world.sweep!==before)finishSweep();}
function reset(){paused=false;tick=rain=flood=0;nextId=1;library=emptyLibrary();setActiveLibrary(library);chronicle=createChronicle();tribe=createTribeState();events=[];world=createWorld((Math.random()*0xffffffff)>>>0);agents=[];for(let i=0;i<5;i++)spawn();placeFounders();rebuildOccupancy(world,agents);selected=agents[0];recordHistory(chronicle,0,`Five founders made camp in ${world.chunks[world.campId].region}.`,'FOUNDING','founding');log(`WORLD ${world.seed.toString(16).toUpperCase()} · ${CHUNK_COUNT} regions · ${Object.keys(world.summary.biomes).length} biomes`,'good');renderPanel();}
function bar(v){return`<span class="mini-bar"><i style="width:${clamp(v)*100}%"></i></span>`;}
function renderTribe(){const a=selected?.alive?selected:agents[0];if(!a){panel.innerHTML='<section><h2>Extinct</h2><p>Start a new world.</p></section>';return;}selected=a;const c=currentChunk(a),report=evaluateProgram(a.bestProgram||a.program,a.task,VERIFY_CASES);panel.innerHTML=`<section><h2>Five founders → living lineage</h2><div class="people-list">${agents.slice(0,30).map(p=>`<button class="person-chip ${p===a?'selected':''}" data-agent="${p.id}">☺ ${esc(p.name)}<small>${p.lifeRole} · ${p.lastAction}</small></button>`).join('')}</div></section><section class="person-head"><pre> \\☺/\n  |\n / \\</pre><div><h2>${esc(a.name)}</h2><div>${a.lifeRole} · gen ${a.generation}</div><div class="status">${a.lastAction} in ${esc(c.region)}</div></div></section><section><h3>Body + mind</h3><div class="facts"><span>energy <b>${a.energy.toFixed(0)}</b></span><span>morale <b>${a.morale.toFixed(0)}</b></span><span>biome <b>${c.biome}</b></span><span>rock <b>${c.geology}</b></span><span>regions known <b>${Object.keys(a.memory.regions).length}</b></span><span>software uses <b>${a.softwareUses||0}</b></span></div></section><section><h3>Current coding attempt</h3><b>${a.task}</b><div class="progress-line">${bar(report.passRate)} ${report.passed}/96</div><p class="note">Only 96/96 becomes civilization knowledge.</p></section>`;panel.querySelectorAll('[data-agent]').forEach(b=>b.onclick=()=>{selected=agents.find(x=>x.id===+b.dataset.agent)||selected;renderPanel();});}
function renderSoftware(){panel.innerHTML=`<section><h2>Software civilization</h2><p>Nothing here is granted by the tech tree. A build opens only after its runtime modules actually evolve and verify.</p></section>${PROJECTS.map(p=>{const q=projectProgress(p,library),ready=projectReady(p,library);return`<section class="project ${ready?'ready':''}"><div class="row"><b>${p.title}</b><span>${ready?'READY':`${q.learned.length}/${q.total}`}</span></div><p>${p.description}</p>${bar(q.ratio)}<button data-project="${p.id}" ${ready?'':'disabled'}>${ready?'▶ RUN':'LOCKED'}</button></section>`;}).join('')}${activeProject&&projectState?`<section class="runner-box"><div class="row"><b>${activeProject}</b><button id="closeProject">×</button></div><pre class="game-screen">${esc(renderProjectAscii(projectState))}</pre><button id="stepProject">RUN STEP</button></section>`:''}`;panel.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{activeProject=b.dataset.project;projectState=createProjectState(activeProject);renderSoftware();});$('closeProject')?.addEventListener('click',()=>{activeProject=null;projectState=null;renderSoftware();});$('stepProject')?.addEventListener('click',()=>{stepProject(projectState,library,1);renderSoftware();});}
function renderHistory(){panel.innerHTML=`<section><h2>${chronicle.era}</h2><div class="facts"><span>year <b>${chronicle.year}</b></span><span>season <b>${chronicle.season}</b></span><span>tools <b>${tribe.tools}</b></span><span>games <b>${tribe.totalGames}</b></span></div></section>${chronicle.entries.map(e=>`<div class="event"><b>Y${e.year} ${e.season}</b> · ${esc(e.text)}</div>`).join('')}`;}
function renderWorld(){const c=selected?currentChunk(selected):world.chunks[world.campId],biomes=Object.entries(world.summary.biomes).sort((a,b)=>b[1]-a[1]).slice(0,8),rocks=Object.entries(world.summary.geology).sort((a,b)=>b[1]-a[1]);panel.innerHTML=`<section><h2>${esc(c.region)}</h2><div class="facts"><span>biome <b>${c.biome}</b></span><span>geology <b>${c.geology}</b></span><span>elevation <b>${Math.round(c.elevation*100)}</b></span><span>moisture <b>${Math.round(c.moisture*100)}</b></span><span>wildlife <b>${Math.round((c.game||0)*100)}</b></span><span>danger <b>${Math.round(c.danger*100)}</b></span></div></section><section><h3>Generated planet slice</h3><p>${CHUNK_COUNT} regions · ${world.summary.rivers} river regions · ${world.summary.caves} caves · ${world.summary.ruins} ruins</p><div class="legend">${biomes.map(([k,v])=>`<span>${k} <b>${v}</b></span>`).join('')}</div></section><section><h3>Rock layers</h3><div class="legend">${rocks.map(([k,v])=>`<span>${k} <b>${v}</b></span>`).join('')}</div></section><section><h3>Map key</h3><div class="legend">${LEGEND.map(([g,n])=>`<span><b>${g}</b> ${n}</span>`).join('')}</div></section>`;}
function renderPanel(){if(tab==='tribe')renderTribe();else if(tab==='software')renderSoftware();else if(tab==='history')renderHistory();else renderWorld();}
function renderHud(){hud.innerHTML=`<b>${chronicle.era}</b> · Y${chronicle.year} ${chronicle.season} · ☺ ${agents.length}<br>food ${tribe.food.toFixed(0)} · wood ${tribe.wood.toFixed(0)} · stone ${tribe.stone.toFixed(0)} · tools ${tribe.tools} · learned ${Object.keys(library).length}/${Object.keys(TASKS).length}<br>${world.chunks[world.campId].region} · ${Object.keys(world.summary.biomes).length} biomes · speed ×${turbo}`;}
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),tx=clamp(Math.floor((e.clientX-r.left)/r.width*MAP_COLS),0,MAP_COLS-1),ty=clamp(Math.floor((e.clientY-r.top)/r.height*MAP_ROWS),0,MAP_ROWS-1),wp=mapTileToWorld(tx,ty);let best=null,bd=(WORLD_W/MAP_COLS*3)**2;for(const a of agents){const d=(a.x-wp.x)**2+(a.y-wp.y)**2;if(d<bd){bd=d;best=a;}}if(best){selected=best;tab='tribe';document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('on',b.dataset.tab==='tribe'));renderPanel();}});
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('on',x===b));renderPanel();});$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶ RESUME':'⏸ PAUSE';};$('turbo').onclick=()=>{turbo=turbo===1?4:turbo===4?16:turbo===16?64:1;$('turbo').textContent=`⚡ SPEED ×${turbo}`;};$('rain').onclick=()=>{rain=1;flood=Math.min(1,flood+.08);};$('zero').onclick=reset;$('popCap').oninput=e=>{popCap=+e.target.value;$('popValue').textContent=popCap;};
function serialize(){return{version:8,tick,rain,flood,nextId,library,chronicle,tribe,agents,world};}$('save').onclick=()=>localStorage.setItem('genesis-codehood-v8',JSON.stringify(serialize()));$('export').onclick=()=>{const blob=new Blob([JSON.stringify(serialize(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`genesis-v8-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);};
function load(){try{const raw=localStorage.getItem('genesis-codehood-v8');if(!raw)return false;const s=JSON.parse(raw);if(s.version!==8)return false;({tick=0,rain=0,flood=0,nextId=1}=s);library=s.library||emptyLibrary();setActiveLibrary(library);chronicle=s.chronicle||createChronicle();tribe=s.tribe||createTribeState();agents=s.agents||[];world=s.world||createWorld();for(const a of agents){attachCavemanIdentity(a);a.memory=a.memory||{regions:{},lastRegion:null};}rebuildOccupancy(world,agents);selected=agents[0]||null;return true;}catch{return false;}}
function boot(){const steps=[['FORMING TECTONIC PLATES',15],['CARVING 4 RIVER SYSTEMS',31],['SOLVING CLIMATE + BIOMES',49],['LAYING ROCK STRATA + CAVES',67],['SPAWNING WILDLIFE + RESOURCES',82],['PLACING 5 FOUNDERS',94],['ALIFE RUNNING',100]];let i=0;const go=()=>{const [label,n]=steps[i++];$('bootLabel').textContent=label;$('bootPercent').textContent=`${n}%`;$('bootBar').style.width=`${n}%`;$('bootDetail').textContent=i<steps.length?'World generation is deterministic from the seed; only one primitive camp is placed.':'Click a ☺ to follow a life.';if(i<steps.length)setTimeout(go,65);else setTimeout(()=>$('boot').classList.add('done'),130);};go();}
if(!load())reset();else renderPanel();boot();
function loop(now){if(!paused){const start=performance.now();for(let i=0;i<turbo;i++){simBatch();if(performance.now()-start>8.5)break;}}const target=innerWidth<900?33:22;if(now-lastDraw>=target){drawAsciiWorld(ctx,world,agents,selected?.id,W,H);renderHud();frames++;lastDraw=now;}if(now-lastUI>500){renderPanel();lastUI=now;}if(now-lastStats>1000){fps=frames*1000/(now-lastStats);ops=simOps*1000/(now-lastStats);$('fps').textContent=fps.toFixed(0);$('bps').textContent=ops.toFixed(0);$('sps').textContent=(world.sweep/(Math.max(1,tick))*ops).toFixed(1);frames=simOps=0;lastStats=now;}requestAnimationFrame(loop);}requestAnimationFrame(loop);
