import { createWorld,WORLD_W,WORLD_H,CHUNK_COLS,CHUNK_ROWS,CHUNK_SIZE,chunkIndexFor,rebuildOccupancy,takeChunkBatch,updateEnvironment,neighboringChunks } from './world.js';
import { createPixelEngine } from './pixel_engine.js';
import { createAgent,emptyLibrary,setActiveLibrary,scoreCandidate,retargetAgent,socialLearn } from './evolution.js';
import { chooseAction } from './brain.js';
import { attachCavemanIdentity,createChronicle,createTribeState,recordHistory,updateClock,syncInventions,runGamerSoftware,applyFireKeeper } from './caveman.js';
import { PROJECTS,createProjectState,projectReady,projectProgress,stepProject,renderProjectAscii } from './projects.js';
import { disassemble } from './vm.js';

const $=id=>document.getElementById(id),canvas=$('world'),panel=$('panel'),hud=$('hud');
let world,engine,agents=[],animals=[],library,chronicle,tribe,selected=null,nextId=1,tick=0,rain=0,flood=0,paused=false,speed=1,last=performance.now(),acc=0,lastPanel=0,activeProject=null,projectState=null,huntReq=1,pendingHunts=new Set();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let eco=null;
function decorateWorld(w){w.width=WORLD_W;w.height=WORLD_H;w.cols=CHUNK_COLS;w.rows=CHUNK_ROWS;return w;}
function camp(){return world.chunks[world.campId];}
function center(c){return{x:c.cx*CHUNK_SIZE+CHUNK_SIZE/2,y:c.cy*CHUNK_SIZE+CHUNK_SIZE/2};}
function log(text,type='WORLD',key=null){recordHistory(chronicle,world.sweep,text,type,key);}
function spawn(parent=null){const a=createAgent(nextId++,Math.random,parent,library);attachCavemanIdentity(a,a.id-1);a.curiosity=parent?clamp((parent.curiosity||.55)+(Math.random()-.5)*.12,0,1):.35+Math.random()*.55;a.memory={visited:new Set(),discoveries:0};a.morale=a.morale||68;agents.push(a);return a;}
function placeFounders(){const c=camp(),p=center(c),neighbors=neighboringChunks(world,c);agents.forEach((a,i)=>{a.x=p.x+(i-2)*10;a.y=p.y+(i%2?6:-6);const n=neighbors[i%neighbors.length]||c;const q=center(n);a.tx=q.x;a.ty=q.y;});}
function initEcology(){try{eco?.terminate();eco=new Worker('./src/ecology_worker.js',{type:'module'});eco.onmessage=e=>{const m=e.data||{};if(m.type==='snapshot')animals=m.animals||[];else if(m.type==='huntResult'){pendingHunts.delete(m.requestId);if(m.ok){tribe.food+=m.meat;tribe.totalHunts++;log(`A hunter brought back ${m.meat.toFixed(0)} food from the living ecosystem.`,'SURVIVAL',tribe.totalHunts===1?'first-wild-hunt':null);}}};eco.postMessage({type:'init',seed:world.seed,width:WORLD_W,height:WORLD_H});}catch(err){animals=[];}}
function reset(){tick=0;rain=flood=0;library=emptyLibrary();setActiveLibrary(library);chronicle=createChronicle();tribe=createTribeState();world=decorateWorld(createWorld((Math.random()*0xffffffff)>>>0));agents=[];nextId=1;for(let i=0;i<5;i++)spawn();placeFounders();rebuildOccupancy(world,agents);selected=agents[0];engine?.rebuild();initEcology();log('Five founders entered a living world with no solved programs.','FOUNDING','founding');renderPanel(true);}
function currentChunk(a){return world.chunks[chunkIndexFor(a.x,a.y)];}
function moveToward(a,mult=1){const dx=a.tx-a.x,dy=a.ty-a.y,d=Math.hypot(dx,dy)||1;a.vx=a.vx*.72+dx/d*.28;a.vy=a.vy*.72+dy/d*.28;const s=(2.4+.9*(a.curiosity||.5))*mult;a.x=clamp(a.x+a.vx*s,0,WORLD_W-1);a.y=clamp(a.y+a.vy*s,0,WORLD_H-1);}
function chooseDestination(a,c){const ns=neighboringChunks(world,c);if(!ns.length)return;let best=null,bestScore=-Infinity;for(const n of ns){const seen=a.memory.visited.has(n.id)?-.18:.22*(a.curiosity||.5);let score=seen+n.food*.28+n.water*.14+n.game*.22+n.wood*.12+n.ore*.08-n.danger*.35-n.flood*.45;if(a.lifeRole==='HUNTER')score+=n.game*.42;if(a.lifeRole==='GATHERER')score+=n.food*.40;if(a.lifeRole==='CRAFTER')score+=(n.wood+n.ore)*.22;if(score>bestScore){bestScore=score;best=n;}}if(best){const p=center(best);a.tx=p.x+(Math.random()-.5)*CHUNK_SIZE*.55;a.ty=p.y+(Math.random()-.5)*CHUNK_SIZE*.55;}}
function programWork(a,c){const before=Object.keys(library).length,out=scoreCandidate(a,library,Math.random);c.programs++;if(out.shipped&&out.improved){log(`${a.name} evolved verified ${a.task} software: 96/96 tests.`,'SOFTWARE',`skill:${a.task}`);}if(Object.keys(library).length>before){syncInventions(chronicle,library,world.sweep);for(const p of agents)retargetAgent(p,library,Math.random);}}
function askHunt(a){if(!eco||pendingHunts.size>3)return;const id=huntReq++;pendingHunts.add(id);eco.postMessage({type:'hunt',requestId:id,x:a.x,y:a.y,radius:130});}
function gather(a,c){const amount=Math.min(c.food,.018+Math.random()*.018);c.food=Math.max(0,c.food-amount);tribe.food+=amount*65;a.energy=Math.min(100,a.energy+amount*120);}
function craft(a,c){const wood=Math.min(c.wood||0,.02),stone=Math.min(c.ore||0,.015);c.wood=Math.max(0,(c.wood||0)-wood);c.ore=Math.max(0,(c.ore||0)-stone);tribe.wood+=wood*38;tribe.stone+=stone*38;if(tribe.wood>2&&tribe.stone>1&&Math.random()<.08){tribe.wood-=2;tribe.stone-=1;tribe.tools++;a.morale=Math.min(100,a.morale+2);log(`${a.name} improvised tool #${tribe.tools} from gathered material.`,'TECH',tribe.tools===1?'first-tool':null);}}
function baseAction(a,c){const o={hunger:clamp((60-a.energy)/50,0,1),flood:c.flood,food:c.food,jobs:c.jobs,shelter:c.shelter,danger:c.danger,crowd:clamp(c.agents.length/8,0,1),poor:clamp((35-a.money)/35,0,1)};let action=chooseAction(a.brain,o,Math.random);if(a.energy<24)return c.shelter>.35?'SHELTER':'FORAGE';if(a.lifeRole==='THINKER'&&a.energy>38&&Math.random()<.62)return'WORK';if(a.lifeRole==='GAMER'&&a.morale<82&&PROJECTS.some(p=>p.kind.includes('GAME')&&projectReady(p,library))&&Math.random()<.48)return'PLAY';if(a.lifeRole==='HUNTER'&&Math.random()<.42)return'FORAGE';if(a.lifeRole==='CRAFTER'&&Math.random()<.38)return'WORK';return action;}
function stepHuman(a){if(!a.alive)return;const c=currentChunk(a);a.memory.visited.add(c.id);a.age++;a.energy-=.035;a.morale=Math.max(0,a.morale-.004);let action=baseAction(a,c);a.lastAction=action;
  if(action==='FORAGE'){if(a.lifeRole==='HUNTER'&&Math.random()<.18)askHunt(a);else gather(a,c);if(Math.random()<.22)chooseDestination(a,c);moveToward(a,.75);}
  else if(action==='WORK'){if(a.lifeRole==='THINKER'||Math.random()<.32)programWork(a,c);else craft(a,c);if(Math.random()<.12)chooseDestination(a,c);}
  else if(action==='PLAY'){const r=runGamerSoftware(a,library,chronicle,world.sweep);if(!r.used)a.morale=Math.min(100,a.morale+.12);}
  else if(action==='SHELTER'||action==='REST'){const home=camp(),p=center(home);a.tx=p.x;a.ty=p.y;a.energy=Math.min(100,a.energy+.16+.22*home.shelter);moveToward(a,.85);}
  else if(action==='SOCIAL'){const peers=c.agents.filter(x=>x!==a&&x.alive);if(peers.length)socialLearn(a,peers[(Math.random()*peers.length)|0],Math.random);a.morale=Math.min(100,a.morale+.1);}
  else {if(Math.hypot(a.tx-a.x,a.ty-a.y)<25||Math.random()<.07)chooseDestination(a,c);moveToward(a,c.flood>.4?.55:1);}
  if(a.energy<=0||a.age>18000){a.alive=false;log(`${a.name} died after ${a.age} life ticks.`,'DEATH',`death:${a.id}`);}if(a.energy>82&&a.morale>70&&a.age>800&&agents.length<30&&Math.random()<.00045){const child=spawn(a),p=center(c);child.x=p.x;child.y=p.y;log(`${child.name} was born into the lineage.`,'BIRTH',`birth:${child.id}`);}}
function simStep(){tick++;const batch=takeChunkBatch(world,18);for(const c of batch)updateEnvironment(c,{floodLevel:flood,rain});for(const a of agents)stepHuman(a);if(tick%4===0)rebuildOccupancy(world,agents);if(tick%12===0){updateClock(chronicle,world.sweep);syncInventions(chronicle,library,world.sweep);applyFireKeeper(tribe,library,chronicle,world.sweep);const eat=Math.min(tribe.food,agents.length*.045);tribe.food-=eat;if(eat<agents.length*.045)for(const a of agents)a.energy-=.25;if(rain>0){rain=Math.max(0,rain-.025);flood=Math.min(1,flood+.01*rain);}else flood=Math.max(0,flood-.004);}agents=agents.filter(a=>a.alive);if(!agents.length)paused=true;}
function renderLives(){const a=selected&&selected.alive?selected:agents[0];if(!a){panel.innerHTML='<section><h2>Extinct</h2><p>Generate a new world.</p></section>';return;}selected=a;const c=currentChunk(a);panel.innerHTML=`<section><h2>Living individuals</h2><div class="people-list">${agents.map(p=>`<button data-person="${p.id}" class="person-chip ${p===a?'selected':''}"><b>${esc(p.name)}</b><small>${p.lifeRole} · ${p.lastAction}</small></button>`).join('')}</div></section><section><h2>${esc(a.name)}</h2><div class="facts"><span>role <b>${a.lifeRole}</b></span><span>energy <b>${a.energy.toFixed(0)}</b></span><span>morale <b>${a.morale.toFixed(0)}</b></span><span>regions seen <b>${a.memory.visited.size}</b></span><span>biome <b>${c.biome}</b></span><span>geology <b>${c.geology}</b></span></div><p>Currently <b>${a.lastAction}</b>. Their controller is inherited/mutated; their role only biases opportunities.</p></section><section><h3>Current program experiment</h3><p><b>${a.task}</b> · best ${(a.bestPassRate*96|0)}/96 tests</p><pre class="code">${esc(disassemble(a.bestProgram||a.program))}</pre></section>`;panel.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{selected=agents.find(a=>a.id===+b.dataset.person)||selected;renderPanel(true);});}
function openProject(id){const p=PROJECTS.find(x=>x.id===id);if(!p||!projectReady(p,library))return;activeProject=id;projectState=createProjectState(id);renderPanel(true);}
function renderSoftware(){const learned=Object.keys(library);panel.innerHTML=`<section><h2>Evolved software laboratory</h2><p>No finished solution is injected. Random executable variants compete; only 96/96 verification enters shared software.</p><div class="facts"><span>verified <b>${learned.length}</b></span><span>wildlife <b>${animals.length}</b></span></div></section>${activeProject?`<section class="runner-box"><h3>${PROJECTS.find(p=>p.id===activeProject)?.title}</h3><pre class="game-screen">${esc(renderProjectAscii(projectState))}</pre><div class="runner-controls"><button id="left">◀</button><button id="step">STEP</button><button id="right">▶</button><button id="closeRun">CLOSE</button></div></section>`:''}${PROJECTS.map(p=>{const q=projectProgress(p,library),ready=projectReady(p,library);return`<section class="project ${ready?'ready':''}"><div class="row"><b>${p.title}</b><span>${ready?'RUNNABLE':`${q.learned.length}/${q.total}`}</span></div><p>${p.description}</p><button data-project="${p.id}" ${ready?'':'disabled'}>▶ RUN</button></section>`;}).join('')}`;panel.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.project));const run=input=>{if(projectState){stepProject(projectState,library,input);renderSoftware();}};if($('left'))$('left').onclick=()=>run(-1);if($('right'))$('right').onclick=()=>run(1);if($('step'))$('step').onclick=()=>run(0);if($('closeRun'))$('closeRun').onclick=()=>{activeProject=null;projectState=null;renderSoftware();};}
function renderHistory(){panel.innerHTML=`<section><h2>Generated history</h2><p>${chronicle.era} · year ${chronicle.year} ${chronicle.season}</p></section>${chronicle.entries.slice(0,80).map(e=>`<div class="event"><b>Y${e.year} ${e.season}</b> · ${esc(e.text)}</div>`).join('')||'<p>No history yet.</p>'}`;}
function renderWorld(){const c=selected?currentChunk(selected):camp();const s=world.summary||{};panel.innerHTML=`<section><h2>World engine</h2><div class="facts"><span>regions <b>${world.chunks.length}</b></span><span>wildlife <b>${animals.length}</b></span><span>rivers <b>${s.rivers||0}</b></span><span>caves <b>${s.caves||0}</b></span></div><p>Ecology runs in a worker thread. Terrain is rendered at a low internal resolution and nearest-neighbor scaled for crisp pixels.</p></section><section><h3>Selected region</h3><div class="facts"><span>${c.region}</span><span>${c.biome}</span><span>${c.geology}</span><span>food ${c.food.toFixed(2)}</span><span>game ${c.game.toFixed(2)}</span><span>danger ${c.danger.toFixed(2)}</span></div></section>`;}
function renderPanel(force=false){const now=performance.now();if(!force&&now-lastPanel<300)return;lastPanel=now;const tab=document.querySelector('.tabs button.on')?.dataset.tab||'lives';if(tab==='software')renderSoftware();else if(tab==='history')renderHistory();else if(tab==='world')renderWorld();else renderLives();}
function statusText(){const thinkers=agents.filter(a=>a.lastAction==='WORK').length;return thinkers?`${thinkers} experimenting with programs`:`${agents.filter(a=>a.lastAction==='EXPLORE').length} exploring`;}
function frame(now){const dt=Math.min(80,now-last);last=now;if(!paused){acc+=dt*speed;while(acc>=33){simStep();acc-=33;}}engine.render({world,humans:agents,animals,selectedId:selected?.id,storm:rain,year:chronicle.year,learned:Object.keys(library).length,programs:agents.reduce((n,a)=>n+(a.stats?.attempts||0),0),status:statusText()},now);hud.textContent=`${chronicle.era} · Y${chronicle.year} ${chronicle.season} · food ${tribe.food.toFixed(0)} · tools ${tribe.tools} · animals ${animals.length}`;renderPanel();requestAnimationFrame(frame);}
function bind(){document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('on',x===b));renderPanel(true);});$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'▶ PLAY':'⏸ PAUSE';eco?.postMessage({type:'pause',running:!paused});};$('turbo').onclick=()=>{speed=speed===1?4:speed===4?16:speed===16?64:1;$('turbo').textContent=`⚡ SPEED ×${speed}`;};$('rain').onclick=()=>{rain=1;log('A god-triggered storm crossed the world.','WEATHER');};$('zero').onclick=()=>reset();window.addEventListener('resize',()=>engine.resize());canvas.onclick=e=>{const p=engine.screenToWorld(e.clientX,e.clientY,world),near=agents.slice().sort((a,b)=>(a.x-p.x)**2+(a.y-p.y)**2-((b.x-p.x)**2+(b.y-p.y)**2))[0];if(near&&Math.hypot(near.x-p.x,near.y-p.y)<180){selected=near;renderPanel(true);}};}
world=decorateWorld(createWorld(0xBADC0DE));engine=createPixelEngine(canvas,world);bind();reset();requestAnimationFrame(frame);
