import { disassemble } from './vm.js';
import { TASKS,VERIFY_CASES,evaluateProgram,unlockedTaskNames } from './tasks.js';
import { behaviorSignature,chooseAction } from './brain.js';
import { createAgent,critiqueAgent,emptyLibrary,retargetAgent,scoreCandidate,socialLearn,setActiveLibrary } from './evolution.js';
import { CHUNK_COUNT,CHUNK_SIZE,WORLD_H,WORLD_W,chunkIndexFor,createWorld,neighboringChunks,rebuildOccupancy,takeChunkBatch,updateEnvironment } from './world.js';
import { LEGEND,MAP_COLS,MAP_ROWS,drawAsciiWorld,mapTileToWorld } from './ascii.js';
import { PROJECTS,createProjectState,projectProgress,projectReady,renderProjectAscii,stepProject } from './projects.js';
import { attachCavemanIdentity,createChronicle,createTribeState,updateClock,recordHistory,syncInventions,chooseResourceNeighbor,runGamerSoftware,applyFireKeeper,eraProgress } from './caveman.js';

const $=id=>document.getElementById(id);
const canvas=$('world'),ctx=canvas.getContext('2d',{alpha:false}),panel=$('panel'),hud=$('hud');
let W=1000,H=700,DPR=1;
let paused=false,turbo=1,tick=0,rain=0,flood=0,totalMoney=0,births=0,deaths=0,murders=0,jobs=0;
let frames=0,batchesThisSec=0,sweepsThisSec=0,lastStat=performance.now(),lastDraw=0,fps=0,bps=0,sps=0,nextId=1;
let agents=[],selected=null,tab='tribe',library=emptyLibrary(),artifacts=[],events=[];
let world=createWorld(0xBADC0DE),popCap=+$('popCap').value,activeProject=null,projectState=null;
let chronicle=createChronicle(),tribe=createTribeState();
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const pct=v=>`${Math.round(clamp(v)*100)}%`;
function log(msg,type='info'){events.unshift({msg,type,tick});if(events.length>30)events.length=30;}
function bar(v){return `<span class="mini-bar"><i style="width:${clamp(v)*100}%"></i></span>`;}
function resize(){const r=canvas.getBoundingClientRect();DPR=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(r.width*DPR));canvas.height=Math.max(1,Math.floor(r.height*DPR));W=r.width;H=r.height;ctx.setTransform(DPR,0,0,DPR,0,0);}addEventListener('resize',resize);resize();
function currentChunk(a){return world.chunks[chunkIndexFor(a.x,a.y)];}
function spawn(parent=null){if(agents.length>=popCap)return null;const a=createAgent(nextId++,Math.random,parent,library);attachCavemanIdentity(a,a.id-1);if(parent){a.x=clamp(parent.x+(Math.random()-.5)*24,0,WORLD_W-1);a.y=clamp(parent.y+(Math.random()-.5)*24,0,WORLD_H-1);if(Math.random()<.45)a.lifeRole=parent.lifeRole;}agents.push(a);births++;return a;}
function placeFounders(){const camp=world.chunks.find(c=>c.site==='HOME')||world.chunks.find(c=>c.site==='CAVE')||world.chunks[0];for(let i=0;i<agents.length;i++){const a=agents[i];a.x=camp.cx*CHUNK_SIZE+CHUNK_SIZE*.50+(i-2)*8;a.y=camp.cy*CHUNK_SIZE+CHUNK_SIZE*.52+(i%2?5:-5);a.tx=a.x;a.ty=a.y;}}
function resetZero(){paused=false;tick=rain=flood=totalMoney=births=deaths=murders=jobs=0;nextId=1;library=emptyLibrary();setActiveLibrary(library);artifacts=[];events=[];selected=null;activeProject=null;projectState=null;chronicle=createChronicle();tribe=createTribeState();world=createWorld((Math.random()*0xffffffff)>>>0);agents=[];for(let i=0;i<5;i++)spawn();placeFounders();rebuildOccupancy(world,agents);selected=agents[0]||null;recordHistory(chronicle,0,'Five people founded a camp beside the fire. They know no solved programs.','FOUNDING','founding');log('CAVEMAN AGE: five people, one campfire, zero solved programs.','good');renderPanel();}
function localPeer(c,a){if(c.agents.length<2)return null;for(let i=0;i<6;i++){const b=c.agents[(Math.random()*c.agents.length)|0];if(b&&b!==a&&b.alive)return b;}return null;}
function obs(a,c){return{hunger:clamp((72-a.energy)/62),flood:c.flood,food:c.food,jobs:c.jobs,shelter:c.shelter,danger:c.danger,crowd:clamp(c.agents.length/12),poor:clamp((45-a.money)/45)};}
function targetChunk(a,c){a.tx=c.cx*CHUNK_SIZE+12+Math.random()*(CHUNK_SIZE-24);a.ty=c.cy*CHUNK_SIZE+12+Math.random()*(CHUNK_SIZE-24);}
function move(a,mult=1){const dx=a.tx-a.x,dy=a.ty-a.y,d=Math.hypot(dx,dy)||1;a.vx=a.vx*.67+(dx/d)*.33;a.vy=a.vy*.67+(dy/d)*.33;a.x=clamp(a.x+a.vx*5*mult,0,WORLD_W-1);a.y=clamp(a.y+a.vy*5*mult,0,WORLD_H-1);}
function programWork(a,c){const before=Object.keys(library).length,out=scoreCandidate(a,library,Math.random);jobs++;totalMoney+=out.pay;c.programs++;if(out.improvedPersonal&&a.bestPassRate>.08&&Math.random()<.10)log(`${a.name} improved ${a.task}: ${Math.round(a.bestPassRate*96)}/96 tests after ${out.attempts} variants.`,'info');if(out.shipped&&out.improved){const skill=library[a.task];skill.tick=tick;artifacts.unshift({name:`${a.task.toLowerCase()}_${a.id}_v${skill.version}.vm`,task:a.task,program:skill.program,author:a.label,tick,verified:true});artifacts.length=Math.min(120,artifacts.length);recordHistory(chronicle,world.sweep,`${a.name} discovered verified ${a.task} code (96/96 tests).`,'CODE',`skill:${a.task}`);log(`★ ${a.name} LEARNED ${a.task} — 96/96 tests.`,'good');}if(Object.keys(library).length>before){syncInventions(chronicle,library,world.sweep);const unlocked=unlockedTaskNames(library);for(const p of agents)retargetAgent(p,library,Math.random);log(`New programming work opened: ${unlocked.join(' · ')}`,'money');}}
function hunt(a,c){const take=Math.min(c.game??0,.018+.012*Math.random());if(take<=.002){a.energy-=.20;return false;}c.game=Math.max(0,(c.game??0)-take);const toolBonus=1+Math.min(.55,tribe.tools*.05),meat=take*85*toolBonus;tribe.food+=meat;a.energy=Math.min(100,a.energy+take*190);a.morale=Math.min(100,a.morale+.5);tribe.totalHunts++;recordHistory(chronicle,world.sweep,`${a.name} made the tribe's first successful hunt.`,'SURVIVAL','first-hunt');return true;}
function gather(a,c){const take=Math.min(c.food,.020+.014*Math.random());c.food=Math.max(0,c.food-take);const food=take*70;tribe.food+=food;a.energy=Math.min(100,a.energy+take*180);a.stats.food+=take;a.morale=Math.min(100,a.morale+.15);return take>.002;}
function gatherMaterials(a,c){const wood=Math.min(c.wood??0,.018),stone=Math.min(c.ore??0,.014);c.wood=Math.max(0,(c.wood??0)-wood);c.ore=Math.max(0,(c.ore??0)-stone);tribe.wood+=wood*55;tribe.stone+=stone*55;a.energy-=.08;return wood+stone>0;}
function craft(a){if(tribe.wood>=2&&tribe.stone>=1){tribe.wood-=2;tribe.stone-=1;tribe.tools++;tribe.totalCrafts++;a.morale=Math.min(100,a.morale+2);recordHistory(chronicle,world.sweep,`${a.name} made the tribe's first composite tool from wood and stone.`,'TECH','first-tool');if(tribe.tools===5)recordHistory(chronicle,world.sweep,'The tribe accumulated five reusable tools.','TECH','five-tools');return true;}return false;}
function fight(a,b,c){if(!b?.alive)return;a.stats.conflicts++;b.stats.conflicts++;const atk=a.energy*.35+a.skill*.18+Math.random()*18,def=b.energy*.35+b.skill*.18+Math.random()*18;a.energy-=1.7;b.energy-=atk>def?3.6:1.2;if(atk>def*1.55&&b.energy<11&&Math.random()<.08){b.alive=false;deaths++;murders++;c.deaths++;recordHistory(chronicle,world.sweep,`${b.name} died during a fight.`,'DEATH');log(`A fight killed ${b.name}.`,'bad');}}
function act(a,c,action){a.lastAction=action;a.actionTicks++;a.energy-=.12;a.morale=Math.max(0,a.morale-.008);a.money=Math.max(0,a.money-.006);a.energy-=c.flood*(action==='SHELTER'?.08:.48);if(action==='FORAGE'){if(a.lifeRole==='HUNTER'){if(!hunt(a,c))gather(a,c);}else if(a.lifeRole==='CRAFTER'&&a.energy>48){if(!gatherMaterials(a,c))gather(a,c);}else gather(a,c);}else if(action==='WORK'){if(a.lifeRole==='CRAFTER'&&craft(a)){a.energy-=.25;}else if(a.lifeRole==='THINKER'||c.site==='LAB'||Math.random()<.35)programWork(a,c);else gatherMaterials(a,c);if(a.role==='CRITIC'||a.role==='TESTER'||a.role==='SECURITY'){const t=localPeer(c,a);if(t){const f=critiqueAgent(a,t);if(f&&Math.random()<.06)log(`${a.name} found a failing ${t.task} case (${f.a}, ${f.b}).`,'bad');}}}else if(action==='PLAY'){const r=runGamerSoftware(a,library,chronicle,world.sweep);if(r.used){tribe.totalGames++;a.energy-=.03;}else{a.lastAction='SOCIAL';a.morale=Math.min(100,a.morale+.20);}}else if(action==='SHELTER'){a.energy+=.25*c.shelter+(tribe.fire>20?.12:0);a.morale=Math.min(100,a.morale+.06);a.stats.shelter++;a.tx=c.cx*CHUNK_SIZE+CHUNK_SIZE*.5;a.ty=c.cy*CHUNK_SIZE+CHUNK_SIZE*.5;}else if(action==='EXPLORE'){a.energy-=.05;if(Math.hypot(a.tx-a.x,a.ty-a.y)<20||Math.random()<.16){const n=neighboringChunks(world,c);let next=null;const route=PROJECTS.find(p=>p.id==='ROUTE_PLANNER');if(route&&projectReady(route,library))next=chooseResourceNeighbor(a,n,library,Math.random);if(!next&&n.length)next=n[(Math.random()*n.length)|0];if(next)targetChunk(a,next);}}else if(action==='REST'){a.energy+=.42*c.shelter+.08+(tribe.fire>25?.06:0);a.vx*=.5;a.vy*=.5;a.morale=Math.min(100,a.morale+.04);}else if(action==='SOCIAL'){const b=localPeer(c,a);if(b){socialLearn(a,b,Math.random);a.tx=b.x;a.ty=b.y;}a.energy-=.02;a.morale=Math.min(100,a.morale+.16);}else if(action==='FIGHT')fight(a,localPeer(c,a),c);if(!['REST','PLAY'].includes(action))move(a,c.flood>.45?.5:1);a.energy=Math.min(100,a.energy);}
function chooseLifeAction(a,c){let action=chooseAction(a.brain,obs(a,c),Math.random);const canPlay=PROJECTS.some(p=>['HAPPY_WALKER','COIN_CHASE'].includes(p.id)&&projectReady(p,library));if(a.lifeRole==='GAMER'&&canPlay&&a.morale<88&&Math.random()<.62)return'PLAY';if(a.lifeRole==='THINKER'&&c.jobs>.25&&Math.random()<.68)return'WORK';if(a.lifeRole==='CRAFTER'&&(tribe.wood>=2&&tribe.stone>=1)&&Math.random()<.60)return'WORK';if(a.lifeRole==='HUNTER'&&(c.game??0)>.10&&a.energy<96&&Math.random()<.68)return'FORAGE';if(a.lifeRole==='GATHERER'&&c.food>.08&&a.energy<96&&Math.random()<.72)return'FORAGE';if(a.energy<30)return c.shelter>.25?'SHELTER':'FORAGE';return action;}
function stepAgent(a,c){if(!a.alive)return;a.age++;const action=chooseLifeAction(a,c);act(a,c,action);if(a.energy>80&&a.morale>70&&a.age>260&&agents.length<popCap&&Math.random()<.0012){a.energy-=12;const child=spawn(a);if(child){a.stats.children++;c.births++;recordHistory(chronicle,world.sweep,`${child.name} was born into the tribe.`,'BIRTH',`birth:${child.id}`);}}if(a.energy<=0||a.age>12000+Math.random()*3500){a.alive=false;deaths++;c.deaths++;recordHistory(chronicle,world.sweep,`${a.name} died.`,'DEATH',`death:${a.id}`);}}
function processChunk(c){updateEnvironment(c,{floodLevel:flood,rain});c.visits++;for(const a of c.agents.slice())stepAgent(a,c);}
function finishSweep(){agents=agents.filter(a=>a.alive);rebuildOccupancy(world,agents);sweepsThisSec++;updateClock(chronicle,world.sweep);chronicle.era=eraProgress(chronicle,library,tribe);syncInventions(chronicle,library,world.sweep);const need=agents.length*.07,eaten=Math.min(tribe.food,need);tribe.food-=eaten;if(eaten<need){const shortage=(need-eaten)/Math.max(.01,need);for(const a of agents)a.energy-=shortage*.45;}if(world.sweep%4===0)applyFireKeeper(tribe,library,chronicle,world.sweep);if(chronicle.season==='WINTER'&&tribe.fire<18)for(const a of agents)a.energy-=.15;if(rain>0){rain=Math.max(0,rain-.012);flood=Math.min(1,flood+.006*rain);}else flood=Math.max(0,flood-.0035);if(Math.random()<.006){rain=.55+Math.random()*.45;recordHistory(chronicle,world.sweep,'A storm front crossed the tribe lands.','WEATHER');log('Storm front: river and marshes are rising.','info');}if(world.chunks.some(c=>c.pumpActive))recordHistory(chronicle,world.sweep,'Evolved pump-control software actively drained floodwater.','SOFTWARE','first-pump-use');if(!agents.length){paused=true;recordHistory(chronicle,world.sweep,'The tribe went extinct.','EXTINCTION','extinction');log('TRIBE EXTINCT — start a new world.','bad');}}
function simBatch(){tick++;batchesThisSec++;const before=world.sweep,batch=takeChunkBatch(world,6);for(const c of batch)processChunk(c);if(world.sweep!==before)finishSweep();}
function bestByTask(){const out={};for(const a of agents){const p=out[a.task];if(!p||a.bestPassRate>p.bestPassRate)out[a.task]=a;}return out;}
function selectedSprite(a){const face=a.energy<24?'☹':a.lastAction==='PLAY'?'☻':'☺';return` \\${face}/\n  |\n / \\`;}
function renderTribe(){const a=selected&&selected.alive?selected:agents[0];if(!a){panel.innerHTML='<section><h2>No living tribe</h2><p>Start a new world.</p></section>';return;}selected=a;const c=currentChunk(a),report=evaluateProgram(a.bestProgram||a.program,a.task,VERIFY_CASES),sig=behaviorSignature(a.brain),roster=agents.map(p=>`<button class="person-chip ${p===a?'selected':''}" data-agent="${p.id}">☺ ${p.name}<small>${p.lifeRole} · ${p.lastAction}</small></button>`).join('');panel.innerHTML=`<section class="explain"><h2>${chronicle.era} · YEAR ${chronicle.year}</h2><p>Five founders began here. Every person has a survival job and can inherit/evolve behavior and executable code.</p><div class="people-list">${roster}</div></section><section class="person-head"><pre>${esc(selectedSprite(a))}</pre><div><h2>${esc(a.name)}</h2><div>${a.lifeRole} · coding role ${a.role}</div><div class="status">NOW: ${a.lastAction}</div></div></section><section><h3>Life</h3><div class="facts"><span>energy <b>${a.energy.toFixed(0)}</b></span><span>morale <b>${a.morale.toFixed(0)}</b></span><span>biome <b>${c.biome}</b></span><span>place <b>${c.site}</b></span><span>games <b>${a.gamesPlayed}</b></span><span>software uses <b>${a.softwareUses}</b></span></div></section><section><h3>Current coding experiment</h3><div class="lesson-name">${a.task}</div><p>${TASKS[a.task].label}</p><div class="progress-line">${bar(report.passRate)} <b>${report.passed}/96 tests</b></div><p class="note">Last work cycle tried ${a.lastAttempts||0} executable variants. Only 96/96 becomes tribe knowledge.</p><pre class="code">${esc(disassemble(a.bestProgram||a.program))}</pre></section><section><h3>Evolved survival habits</h3><div class="facts"><span>hungry → <b>${sig.hungry}</b></span><span>flood → <b>${sig.flooded}</b></span><span>broke → <b>${sig.broke}</b></span><span>danger → <b>${sig.danger}</b></span></div></section>`;panel.querySelectorAll('[data-agent]').forEach(b=>b.addEventListener('click',()=>{selected=agents.find(x=>x.id===+b.dataset.agent)||selected;renderTribe();}));}
function renderSoftware(){const best=bestByTask(),cards=PROJECTS.map(p=>{const prog=projectProgress(p,library),ready=projectReady(p,library),inv=chronicle.inventions[p.id],worldTool=p.kind==='WORLD TOOL';return`<section class="project ${ready?'ready':''}"><div class="row"><div><b>${p.title}</b> <span class="kind">${p.kind}</span></div><span>${ready?(worldTool?'INSTALLED':'RUNNABLE'):`${prog.learned.length}/${prog.total}`}</span></div><p>${p.description}</p><div class="progress-line">${bar(prog.ratio)} ${pct(prog.ratio)}</div><div class="note">${ready?`Invented year ${inv?.year??chronicle.year}. Runtime uses: ${inv?.uses??0}`:`Still needs: ${prog.missing.join(', ')}`}</div><button data-project="${p.id}" ${ready?'':'disabled'}>${ready?'▶ RUN / INSPECT':'NOT BUILT YET'}</button></section>`;}).join(''),skills=Object.entries(TASKS).map(([name])=>{const learned=library[name],a=best[name],rate=learned?1:(a?.bestPassRate||0);return`<div class="skill-row"><span>${learned?'✓':'·'} ${name}</span><span>${learned?'96/96':`${Math.round(rate*96)}/96`}</span></div>`;}).join('');panel.innerHTML=`<section class="explain"><h2>Tribe software</h2><p>Games can be played by you and the GAMER NPC. World tools run automatically inside survival systems. Simulations stay runnable here.</p></section>${activeProject?renderProjectRunner():''}${cards}<section><h3>Underlying learned modules</h3>${skills}</section>`;panel.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project)));bindProjectControls();}
function renderProjectRunner(){const p=PROJECTS.find(x=>x.id===activeProject);if(!p||!projectState)return'';const manual=['HAPPY_WALKER','COIN_CHASE'].includes(p.id)?'<button id="projLeft">◀</button><button id="projRight">▶</button>':'<button id="projStep">STEP</button><button id="projRun">RUN ×20</button>';return`<section class="runner-box"><div class="row"><b>RUNNING: ${p.title}</b><button id="closeProject">×</button></div><pre class="game-screen">${esc(renderProjectAscii(projectState))}</pre><div class="runner-controls">${manual}</div><div class="note">This runner calls the tribe's verified evolved bytecode at runtime.</div></section>`;}
function openProject(id){activeProject=id;projectState=createProjectState(id);renderSoftware();}
function projectInput(input){if(!projectState)return;stepProject(projectState,library,input);renderSoftware();}
function bindProjectControls(){$('closeProject')?.addEventListener('click',()=>{activeProject=null;projectState=null;renderSoftware();});$('projLeft')?.addEventListener('click',()=>projectInput(-1));$('projRight')?.addEventListener('click',()=>projectInput(1));$('projStep')?.addEventListener('click',()=>projectInput(0));$('projRun')?.addEventListener('click',()=>{for(let i=0;i<20;i++)stepProject(projectState,library,0);renderSoftware();});}
function renderHistory(){panel.innerHTML=`<section class="explain"><h2>${chronicle.era}</h2><p>YEAR ${chronicle.year} · ${chronicle.season}. The history below comes from actual simulation events and verified inventions.</p></section><section><h3>Tribe stockpile</h3><div class="facts"><span>food <b>${tribe.food.toFixed(1)}</b></span><span>wood <b>${tribe.wood.toFixed(1)}</b></span><span>stone <b>${tribe.stone.toFixed(1)}</b></span><span>tools <b>${tribe.tools}</b></span><span>fire <b>${tribe.fire.toFixed(0)}%</b></span><span>games played <b>${tribe.totalGames}</b></span></div></section><section><h3>Chronicle</h3>${chronicle.entries.map(e=>`<div class="event"><b>Y${e.year} ${e.season}</b> · ${esc(e.text)}</div>`).join('')||'<div class="note">History has just begun.</div>'}</section>`;}
function renderWorld(){const biomes=Object.fromEntries(['PLAINS','FOREST','DESERT','MARSH','HIGHLAND','RIVER','RUINS'].map(b=>[b,world.chunks.filter(c=>c.biome===b).length])),wildlife=world.chunks.reduce((s,c)=>s+(c.game??0),0);panel.innerHTML=`<section><h2>Prehistoric world</h2><div class="legend">${LEGEND.map(([g,n])=>`<span><b>${g}</b> ${n}</span>`).join('')}</div></section><section><h3>World state</h3><div class="facts"><span>people <b>${agents.length}</b></span><span>chunks <b>${CHUNK_COUNT}</b></span><span>wildlife <b>${wildlife.toFixed(1)}</b></span><span>flood <b>${pct(flood)}</b></span></div><pre class="code">${Object.entries(biomes).map(([k,v])=>`${k.padEnd(9)} ${v}`).join('\n')}</pre></section><section><h3>Recent events</h3>${events.slice(0,14).map(e=>`<div class="event ${e.type}">${esc(e.msg)}</div>`).join('')||'<div class="note">Quiet so far.</div>'}</section>`;}
function renderPanel(){if(tab==='tribe')renderTribe();else if(tab==='software')renderSoftware();else if(tab==='history')renderHistory();else renderWorld();}
function renderHud(){const learned=Object.keys(library).length,inventions=Object.keys(chronicle.inventions).length;hud.innerHTML=`<b>${chronicle.era} · YEAR ${chronicle.year} · ${chronicle.season}</b><br>☺ ${agents.length} · fire ${tribe.fire.toFixed(0)}% · food ${tribe.food.toFixed(1)} · tools ${tribe.tools}<br>verified skills ${learned}/${Object.keys(TASKS).length} · software ${inventions}/${PROJECTS.length} · speed ×${turbo}`;}
function draw(){drawAsciiWorld(ctx,world,agents,selected?.id,W,H);renderHud();frames++;}
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),tx=clamp(Math.floor((e.clientX-r.left)/r.width*MAP_COLS),0,MAP_COLS-1),ty=clamp(Math.floor((e.clientY-r.top)/r.height*MAP_ROWS),0,MAP_ROWS-1),wp=mapTileToWorld(tx,ty);let best=null,bd=(WORLD_W/MAP_COLS*2.4)**2;for(const a of agents){if(!a.alive)continue;const d=(a.x-wp.x)**2+(a.y-wp.y)**2;if(d<bd){bd=d;best=a;}}if(best){selected=best;tab='tribe';document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('on',b.dataset.tab==='tribe'));renderPanel();}});
document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('on',x===b));renderPanel();}));
$('pause').addEventListener('click',()=>{paused=!paused;$('pause').textContent=paused?'▶ RESUME':'⏸ PAUSE';});$('turbo').addEventListener('click',()=>{turbo=turbo===1?4:turbo===4?16:turbo===16?64:1;$('turbo').textContent=`⚡ SPEED ×${turbo}`;});$('rain').addEventListener('click',()=>{rain=1;flood=Math.min(1,flood+.10);recordHistory(chronicle,world.sweep,'A violent storm was triggered over the region.','WEATHER');log('Storm triggered.','info');});$('zero').addEventListener('click',()=>resetZero());$('popCap').addEventListener('input',e=>{popCap=+e.target.value;$('popValue').textContent=popCap;});
function serialize(){return{version:7,tick,rain,flood,totalMoney,births,deaths,murders,jobs,nextId,library,artifacts,agents:agents.slice(0,500),world,chronicle,tribe};}
$('save').addEventListener('click',()=>{localStorage.setItem('genesis-codehood-v7',JSON.stringify(serialize()));log('Caveman world saved on this device.','good');});$('export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(serialize(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`codehood-caveman-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
function load(){try{const raw=localStorage.getItem('genesis-codehood-v7');if(!raw)return false;const s=JSON.parse(raw);if(s.version!==7)return false;tick=s.tick||0;rain=s.rain||0;flood=s.flood||0;totalMoney=s.totalMoney||0;births=s.births||0;deaths=s.deaths||0;murders=s.murders||0;jobs=s.jobs||0;nextId=s.nextId||1;library=s.library||{};setActiveLibrary(library);artifacts=s.artifacts||[];agents=(s.agents||[]).map((a,i)=>attachCavemanIdentity(a,i));world=s.world||createWorld();chronicle=s.chronicle||createChronicle();tribe=s.tribe||createTribeState();rebuildOccupancy(world,agents);selected=agents[0]||null;syncInventions(chronicle,library,world.sweep);log('Loaded Caveman Age save.','good');return true;}catch(err){console.warn(err);return false;}}
function boot(){const steps=[['MAKING PREHISTORY',18],['CARVING RIVER + CAVES',36],['SPAWNING 5 CAVEMEN',56],['PLACING WILDLIFE',70],['LIGHTING CAMPFIRE',82],['STARTING ZERO-SOLUTION CODE EVOLUTION',94],['READY',100]];let i=0;const next=()=>{const[label,n]=steps[i++];$('bootLabel').textContent=label;$('bootPercent').textContent=`${n}%`;$('bootBar').style.width=`${n}%`;$('bootDetail').textContent=i<steps.length?'No solved programs are being loaded.':'Click a ☺ person. SOFTWARE lets you run anything they actually invent.';if(i<steps.length)setTimeout(next,55);else setTimeout(()=>$('boot').classList.add('done'),130);};next();}
if(!load())resetZero();else renderPanel();boot();
function loop(now){if(!paused){const start=performance.now();for(let i=0;i<turbo;i++){simBatch();if(performance.now()-start>10)break;}}if(now-lastDraw>33){draw();lastDraw=now;}if(now-lastStat>1000){fps=frames*1000/(now-lastStat);bps=batchesThisSec*1000/(now-lastStat);sps=sweepsThisSec*1000/(now-lastStat);$('fps').textContent=fps.toFixed(0);$('bps').textContent=bps.toFixed(0);$('sps').textContent=sps.toFixed(1);frames=batchesThisSec=sweepsThisSec=0;lastStat=now;renderPanel();}requestAnimationFrame(loop);}requestAnimationFrame(loop);
