const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export const LIFE_SKILLS=Object.freeze(['forage','track','hunt','haul','craft','build','cook','heal','explore','social','story','tinker','program','play']);
const TITLES={forage:['Forager','Herb Seeker','Gatherer'],track:['Tracker','Trail Reader','Scout'],hunt:['Hunter','Game Stalker','Trapper'],haul:['Carrier','Hauler','Storekeeper'],craft:['Crafter','Toolmaker','Stoneworker'],build:['Builder','Shelter Maker','Woodworker'],cook:['Cook','Fire Tender','Food Keeper'],heal:['Healer','Caregiver','Bone Setter'],explore:['Explorer','Pathfinder','Wanderer'],social:['Mediator','Host','Organizer'],story:['Storykeeper','Singer','Lorekeeper'],tinker:['Tinkerer','Mechanist','Experimenter'],program:['Code Tinkerer','Programmer','Logic Maker'],play:['Gamer','Game Maker','Performer']};
function inherited(parent,key,rng,spread=.12){return parent?clamp(Number(parent[key]??.5)+(rng()+rng()-1)*spread):clamp(.18+rng()*.72);}
export function decoratePersonV10(agent,index=0,rng=Math.random,parent=null){
  agent.personality={curiosity:inherited(parent?.personality,'curiosity',rng),bravery:inherited(parent?.personality,'bravery',rng),sociability:inherited(parent?.personality,'sociability',rng),patience:inherited(parent?.personality,'patience',rng),empathy:inherited(parent?.personality,'empathy',rng),industry:inherited(parent?.personality,'industry',rng),creativity:inherited(parent?.personality,'creativity',rng)};
  agent.aptitudes={};agent.lifeSkills={};for(const k of LIFE_SKILLS){const p=parent?.aptitudes?.[k];agent.aptitudes[k]=p==null?clamp(.15+rng()*.70):clamp(p+(rng()+rng()-1)*.10);agent.lifeSkills[k]=parent?.lifeSkills?.[k]?Math.max(0,parent.lifeSkills[k]*.16+rng()*.08):rng()*.06;}
  agent.needs={food:.25+rng()*.20,safety:.15+rng()*.20,rest:.10+rng()*.20,social:.10+rng()*.35,novelty:.15+rng()*.40,creation:.10+rng()*.35};
  agent.appearance={skin:(parent?.appearance?.skin??(rng()*6|0)+((rng()-.5)*2|0)+6)%6,hair:(parent?.appearance?.hair??(rng()*8|0)+((rng()-.5)*2|0)+8)%8,cloth:(parent?.appearance?.cloth??(rng()*8|0)+((rng()-.5)*2|0)+8)%8,height:parent?clamp(parent.appearance.height+(rng()+rng()-1)*.08,.72,1.25):.82+rng()*.30,build:parent?clamp(parent.appearance.build+(rng()+rng()-1)*.10,.65,1.35):.72+rng()*.48};
  agent.memories=[];agent.visited=new Set();agent.currentRole='Wanderer';agent.roleReason='new life';agent.carrying=null;agent.anim='idle';agent.doorUse=0;agent.lifeRole=agent.currentRole;return refreshGeneratedRole(agent,rng);
}
export function practice(agent,skill,amount=.01){if(!agent.lifeSkills||!Object.hasOwn(agent.lifeSkills,skill))return;const aptitude=.55+(agent.aptitudes?.[skill]??.5)*.9;agent.lifeSkills[skill]=Math.max(0,agent.lifeSkills[skill]+amount*aptitude);}
export function refreshGeneratedRole(agent,rng=Math.random){if(!agent.lifeSkills)return agent;const ranked=LIFE_SKILLS.map(k=>[k,agent.lifeSkills[k]+(agent.aptitudes?.[k]??0)*.18]).sort((a,b)=>b[1]-a[1]);const [first,score]=ranked[0],second=ranked[1]?.[0];let title=(TITLES[first]||['Wanderer'])[(Math.abs((agent.id||1)*17+first.length)%((TITLES[first]||['Wanderer']).length))];if(score<.18)title=agent.personality?.curiosity>.68?'Curious Wanderer':agent.personality?.sociability>.68?'Camp Friend':'Generalist';else if(second&&ranked[1][1]>score*.88&&score>.35){const prefix={forage:'Wild',track:'Trail',hunt:'Game',haul:'Store',craft:'Stone',build:'Shelter',cook:'Fire',heal:'Care',explore:'Far',social:'People',story:'Lore',tinker:'Machine',program:'Logic',play:'Game'}[second]||'';title=`${prefix} ${title}`;}
agent.currentRole=title;agent.lifeRole=title;agent.roleReason=`strongest practice: ${first} ${agent.lifeSkills[first].toFixed(2)} · aptitude ${agent.aptitudes[first].toFixed(2)}`;return agent;}
export function updateNeeds(agent,context={}){const p=agent.personality||{};agent.needs.food=clamp((60-agent.energy)/58);agent.needs.safety=clamp((context.danger||0)*.72+(context.flood||0)*.65+(agent.energy<24?.20:0));agent.needs.rest=clamp((40-agent.energy)/45+(agent.age%900)/2200);agent.needs.social=clamp((agent.needs.social||.2)+.003*(p.sociability||.5)-(context.peers||0)*.012);agent.needs.novelty=clamp((agent.needs.novelty||.2)+.002*(p.curiosity||.5)-(context.newRegion?.18:0));agent.needs.creation=clamp((agent.needs.creation||.2)+.0015*(p.creativity||.5)-(context.created?.20:0));return agent.needs;}
export function generatedIntent(agent,c,rng=Math.random){const n=agent.needs,p=agent.personality,s=agent.lifeSkills,a=agent.aptitudes;const options=[['REST',n.rest*1.4+c.shelter*.25],['FORAGE',n.food*1.25+c.food*.35+a.forage*.12],['HUNT',n.food*.82+c.game*.45+a.hunt*.18+p.bravery*.08],['EXPLORE',n.novelty*.9+p.curiosity*.55+a.explore*.18-c.danger*.35],['SOCIAL',n.social*.9+p.sociability*.5+(c.agents?.length||0)*.04],['CRAFT',n.creation*.65+p.creativity*.30+a.craft*.26+(c.wood+c.stone)*.10],['BUILD',n.safety*.42+n.creation*.45+a.build*.28+c.wood*.16],['PROGRAM',n.creation*.50+p.creativity*.38+p.patience*.20+a.program*.35],['PLAY',n.social*.28+n.novelty*.22+a.play*.25]];for(const o of options)o[1]+=rng()*.16;options.sort((x,y)=>y[1]-x[1]);return options[0][0];}
export function remember(agent,text,tick){agent.memories.unshift({text,tick});if(agent.memories.length>8)agent.memories.length=8;}
