const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export const LIFE_SKILLS=Object.freeze(['forage','track','hunt','haul','craft','build','cook','heal','explore','social','story','tinker','program','play']);
const TITLES={forage:['Forager','Herb Seeker','Gatherer'],track:['Tracker','Trail Reader','Scout'],hunt:['Hunter','Game Stalker','Trapper'],haul:['Carrier','Hauler','Storekeeper'],craft:['Crafter','Toolmaker','Stoneworker'],build:['Builder','Shelter Maker','Woodworker'],cook:['Cook','Fire Tender','Food Keeper'],heal:['Healer','Caregiver','Bone Setter'],explore:['Explorer','Pathfinder','Wanderer'],social:['Mediator','Host','Organizer'],story:['Storykeeper','Singer','Lorekeeper'],tinker:['Tinkerer','Mechanist','Experimenter'],program:['Code Tinkerer','Programmer','Logic Maker'],play:['Gamer','Game Maker','Performer']};
const INTENTS=['REST','FORAGE','HUNT','EXPLORE','SOCIAL','CRAFT','BUILD','PROGRAM','PLAY'];
function inherited(parent,key,rng,spread=.12){return parent?clamp(Number(parent[key]??.5)+(rng()+rng()-1)*spread):clamp(.18+rng()*.72);}
function memoryAffinity(agent,word){let score=0;for(const m of agent.memories||[]){if(String(m.text||'').toLowerCase().includes(word))score+=Number(m.strength??.25);}return clamp(score,0,1);}
export function decoratePersonV10(agent,index=0,rng=Math.random,parent=null){
  agent.personality={curiosity:inherited(parent?.personality,'curiosity',rng),bravery:inherited(parent?.personality,'bravery',rng),sociability:inherited(parent?.personality,'sociability',rng),patience:inherited(parent?.personality,'patience',rng),empathy:inherited(parent?.personality,'empathy',rng),industry:inherited(parent?.personality,'industry',rng),creativity:inherited(parent?.personality,'creativity',rng)};
  agent.behavior={commitment:inherited(parent?.behavior,'commitment',rng,.08),riskTolerance:inherited(parent?.behavior,'riskTolerance',rng,.09),hungerSensitivity:inherited(parent?.behavior,'hungerSensitivity',rng,.08),noveltyDrive:inherited(parent?.behavior,'noveltyDrive',rng,.08),socialDrive:inherited(parent?.behavior,'socialDrive',rng,.08)};
  agent.aptitudes={};agent.lifeSkills={};for(const k of LIFE_SKILLS){const p=parent?.aptitudes?.[k];agent.aptitudes[k]=p==null?clamp(.15+rng()*.70):clamp(p+(rng()+rng()-1)*.10);agent.lifeSkills[k]=parent?.lifeSkills?.[k]?Math.max(0,parent.lifeSkills[k]*.16+rng()*.08):rng()*.06;}
  agent.needs={food:.25+rng()*.20,safety:.15+rng()*.20,rest:.10+rng()*.20,social:.10+rng()*.35,novelty:.15+rng()*.40,creation:.10+rng()*.35};
  agent.appearance={skin:(parent?.appearance?.skin??(rng()*6|0)+((rng()-.5)*2|0)+6)%6,hair:(parent?.appearance?.hair??(rng()*8|0)+((rng()-.5)*2|0)+8)%8,cloth:(parent?.appearance?.cloth??(rng()*8|0)+((rng()-.5)*2|0)+8)%8,height:parent?clamp(parent.appearance.height+(rng()+rng()-1)*.08,.72,1.25):.82+rng()*.30,build:parent?clamp(parent.appearance.build+(rng()+rng()-1)*.10,.65,1.35):.72+rng()*.48};
  agent.memories=[];agent.visited=new Set();agent.currentRole='Wanderer';agent.roleReason='new life';agent.carrying=null;agent.anim='idle';agent.doorUse=0;agent.lifeRole=agent.currentRole;agent.decision={intent:'EXPLORE',age:0,utility:{}};return refreshGeneratedRole(agent,rng);
}
export function practice(agent,skill,amount=.01){if(!agent.lifeSkills||!Object.hasOwn(agent.lifeSkills,skill))return;const aptitude=.55+(agent.aptitudes?.[skill]??.5)*.9;agent.lifeSkills[skill]=Math.max(0,agent.lifeSkills[skill]+amount*aptitude);}
export function refreshGeneratedRole(agent,rng=Math.random){if(!agent.lifeSkills)return agent;const ranked=LIFE_SKILLS.map(k=>[k,agent.lifeSkills[k]+(agent.aptitudes?.[k]??0)*.18]).sort((a,b)=>b[1]-a[1]);const [first,score]=ranked[0],second=ranked[1]?.[0];let title=(TITLES[first]||['Wanderer'])[(Math.abs((agent.id||1)*17+first.length)%((TITLES[first]||['Wanderer']).length))];if(score<.18)title=agent.personality?.curiosity>.68?'Curious Wanderer':agent.personality?.sociability>.68?'Camp Friend':'Generalist';else if(second&&ranked[1][1]>score*.88&&score>.35){const prefix={forage:'Wild',track:'Trail',hunt:'Game',haul:'Store',craft:'Stone',build:'Shelter',cook:'Fire',heal:'Care',explore:'Far',social:'People',story:'Lore',tinker:'Machine',program:'Logic',play:'Game'}[second]||'';title=`${prefix} ${title}`;}
agent.currentRole=title;agent.lifeRole=title;agent.roleReason=`strongest practice: ${first} ${agent.lifeSkills[first].toFixed(2)} · aptitude ${agent.aptitudes[first].toFixed(2)}`;return agent;}
export function updateNeeds(agent,context={}){const p=agent.personality||{},b=agent.behavior||{};const hunger=clamp((64-agent.energy)/62)*(0.72+(b.hungerSensitivity??.5)*.56);agent.needs.food=clamp(hunger);agent.needs.safety=clamp((context.danger||0)*(.55+(1-(b.riskTolerance??.5))*.65)+(context.flood||0)*.72+(agent.energy<22?.24:0));agent.needs.rest=clamp((42-agent.energy)/48+(agent.age%1100)/3200);const peerRelief=Math.min(.18,(context.peers||0)*.03);agent.needs.social=clamp((agent.needs.social||.2)+.0018*(p.sociability||.5)+.0012*(b.socialDrive||.5)-peerRelief);agent.needs.novelty=clamp((agent.needs.novelty||.2)+.0014*(p.curiosity||.5)+.0011*(b.noveltyDrive||.5)-(context.newRegion?.22:0));agent.needs.creation=clamp((agent.needs.creation||.2)+.0011*(p.creativity||.5)+.0008*(p.industry||.5)-(context.created?.22:0));return agent.needs;}
function utilities(agent,c){const n=agent.needs,p=agent.personality,s=agent.lifeSkills,a=agent.aptitudes,b=agent.behavior||{};const u={};u.REST=n.rest*1.55+n.safety*.25+c.shelter*.40+(agent.energy<20?.50:0);u.FORAGE=n.food*1.45+c.food*.55+a.forage*.18+s.forage*.08;u.HUNT=n.food*.92+c.game*.58+a.hunt*.24+s.track*.08+p.bravery*.08-(1-(b.riskTolerance??.5))*c.danger*.20;u.EXPLORE=n.novelty*1.02+p.curiosity*.58+a.explore*.20+(b.noveltyDrive??.5)*.10-c.danger*(.30+(1-(b.riskTolerance??.5))*.22);u.SOCIAL=n.social*1.02+p.sociability*.54+(b.socialDrive??.5)*.15+(c.agents?.length||0)*.04;u.CRAFT=n.creation*.72+p.creativity*.34+a.craft*.31+(c.wood+c.stone)*.12+s.craft*.05;u.BUILD=n.safety*.46+n.creation*.52+a.build*.32+c.wood*.18+s.build*.06;u.PROGRAM=n.creation*.55+p.creativity*.40+p.patience*.23+a.program*.36+s.program*.06;u.PLAY=n.social*.31+n.novelty*.26+a.play*.28+p.creativity*.10;
  u.HUNT+=memoryAffinity(agent,'successful hunt')*.20;u.BUILD+=memoryAffinity(agent,'built a shelter')*.20;u.PROGRAM+=memoryAffinity(agent,'verified')*.16;u.FORAGE+=memoryAffinity(agent,'food')*.08;return u;
}
export function generatedIntent(agent,c,rng=Math.random){if(!agent.decision)agent.decision={intent:agent.lastAction||'EXPLORE',age:0,utility:{}};const u=utilities(agent,c);for(const key of INTENTS)u[key]+=(rng()-.5)*.05;const current=agent.decision.intent||agent.lastAction||'EXPLORE';const commitment=.10+(agent.behavior?.commitment??.5)*.38;u[current]=(u[current]??0)+commitment*Math.exp(-agent.decision.age/130);const ranked=INTENTS.map(k=>[k,u[k]??-Infinity]).sort((x,y)=>y[1]-x[1]);const best=ranked[0],currentScore=u[current]??-Infinity;const minHold=10+Math.round((agent.behavior?.commitment??.5)*34);const switchMargin=.05+(agent.behavior?.commitment??.5)*.12;let chosen=current;if(!INTENTS.includes(chosen)||agent.decision.age>=minHold&&best[1]>currentScore+switchMargin)chosen=best[0];if(chosen!==current){agent.decision.intent=chosen;agent.decision.age=0;}else agent.decision.age++;agent.decision.utility=u;return chosen;}
export function remember(agent,text,tick){const existing=(agent.memories||[]).find(m=>m.text===text);if(existing){existing.tick=tick;existing.strength=clamp((existing.strength??.35)+.18);return;}agent.memories.unshift({text,tick,strength:.42});for(const m of agent.memories)m.strength=clamp((m.strength??.35)*.97,.05,1);if(agent.memories.length>12)agent.memories.length=12;}
