import { dimensionsFor,sanitizeWorldSettings } from './v10_config.js';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function hash32(x){x|=0;x=(x+0x7ed55d16)+(x<<12);x=(x^0xc761c23c)^(x>>>19);x=(x+0x165667b1)+(x<<5);x=(x+0xd3a2646c)^(x<<9);x=(x+0xfd7046c5)+(x<<3);x=(x^0xb55a4f09)^(x>>>16);return x>>>0;}
export function noise(seed,x,y,salt=0){return hash32(seed^(x*73856093)^(y*19349663)^salt)/4294967295;}
const smooth=t=>t*t*(3-2*t),lerp=(a,b,t)=>a+(b-a)*t;
function valueNoise(seed,x,y,salt=0){const x0=Math.floor(x),y0=Math.floor(y),tx=smooth(x-x0),ty=smooth(y-y0),a=noise(seed,x0,y0,salt),b=noise(seed,x0+1,y0,salt),c=noise(seed,x0,y0+1,salt),d=noise(seed,x0+1,y0+1,salt);return lerp(lerp(a,b,tx),lerp(c,d,tx),ty);}
function fbm(seed,x,y,salt=0,oct=5){let sum=0,norm=0,amp=.56,f=.11;for(let i=0;i<oct;i++){sum+=valueNoise(seed,x*f,y*f,salt+i*97)*amp;norm+=amp;amp*=.52;f*=2.07;}return sum/norm;}
const idx=(x,y,cols)=>y*cols+x;
function neighbors(x,y,cols,rows){const out=[];for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){if(!ox&&!oy)continue;const xx=x+ox,yy=y+oy;if(xx>=0&&yy>=0&&xx<cols&&yy<rows)out.push([xx,yy]);}return out;}
function geology(seed,x,y,elev,rough){const r=noise(seed,x,y,401);if(elev>.80&&rough>.5)return r>.48?'GRANITE':'BASALT';if(elev<.38)return r>.55?'ALLUVIUM':'CLAY';if(r>.80)return'LIMESTONE';if(r>.59)return'SANDSTONE';if(r>.36)return'SHALE';return'GRANITE';}
function nameRegion(seed,x,y){const a=['Ash','Moss','Silver','Red','Mist','Cold','Sun','Rain','Wolf','Deep','Bright','Stone','Green','Black','Wind','Moon','Pine','Glass','Iron','Quiet'];const b=['Reach','Vale','Basin','Hollow','Ridge','Fen','Run','Moor','Fields','Spine','Coast','Steppe','Wood','Scar','Crown','March','Wash','Heights'];return a[(noise(seed,x,y,701)*a.length)|0]+b[(noise(seed,x,y,702)*b.length)|0];}
function baseResources(biome,geo,settings){const t={OCEAN:[.04,.00,.02,1,.02,.02,.55],BEACH:[.10,.05,.24,.66,.18,.18,.24],RIVER:[.58,.18,.12,1,.80,.16,.48],LAKE:[.48,.10,.08,1,.66,.12,.42],MARSH:[.66,.42,.10,.98,.88,.15,.55],RAINFOREST:[.72,1,.16,.64,.82,.20,.90],FOREST:[.58,.92,.22,.48,.72,.27,.82],TAIGA:[.34,.80,.34,.40,.48,.35,.57],TUNDRA:[.17,.08,.44,.28,.20,.50,.30],DESERT:[.06,.025,.48,.05,.10,.42,.12],SAVANNA:[.50,.30,.24,.24,.62,.27,.74],BADLANDS:[.12,.05,.68,.09,.15,.58,.26],HIGHLAND:[.20,.20,.82,.26,.24,.73,.38],ALPINE:[.07,.02,.94,.18,.04,.88,.16],PLAINS:[.45,.33,.25,.32,.80,.27,.76]};let [food,wood,stone,water,soil,ore,game]=t[biome]||t.PLAINS;let clay=(geo==='CLAY'||geo==='ALLUVIUM')?.88:.16;ore=clamp(ore*(.45+settings.minerals*1.1));if(geo==='BASALT')ore=clamp(ore+.10);if(geo==='LIMESTONE')stone=clamp(stone+.10);return{food,wood,stone,water,soil,ore,clay,game};}
function chooseCamp(chunks,world){const cx=(world.cols-1)/2,cy=(world.rows-1)/2;return chunks.filter(c=>!['OCEAN','RIVER','LAKE','MARSH','ALPINE'].includes(c.biome)).sort((a,b)=>scoreCamp(b)-scoreCamp(a))[0]||chunks.find(c=>c.biome!=='OCEAN')||chunks[0];function scoreCamp(c){const central=1-Math.min(1,Math.hypot(c.cx-cx,c.cy-cy)/Math.max(world.cols,world.rows));return c.water*.95+c.food*.85+c.wood*.52+c.stone*.28+c.soil*.25+central*.18-c.danger*.7;}}
function carveRivers(seed,elev,land,cols,rows,count){const river=new Set(),sources=[];for(let y=1;y<rows-1;y++)for(let x=1;x<cols-1;x++){const i=idx(x,y,cols);if(land[i]&&elev[i]>.62)sources.push({x,y,e:elev[i],r:noise(seed,x,y,811)});}sources.sort((a,b)=>(b.e+b.r*.12)-(a.e+a.r*.12));for(let r=0;r<count&&sources.length;r++){let s=sources[(r*Math.max(1,Math.floor(sources.length/count)))%sources.length],x=s.x,y=s.y;const seen=new Set();for(let step=0;step<Math.max(cols,rows)*3;step++){const id=idx(x,y,cols);if(seen.has(id))break;seen.add(id);river.add(id);if(!land[id])break;let best=null,bestScore=Infinity;for(const [nx,ny] of neighbors(x,y,cols,rows)){const ni=idx(nx,ny,cols),edge=Math.min(nx,ny,cols-1-nx,rows-1-ny),down=elev[ni]-elev[id],wander=(noise(seed,nx,ny,900+r)-.5)*.045;let score=elev[ni]+Math.max(0,down)*.45+edge*.001+wander;if(!land[ni])score-=.22;if(seen.has(ni))score+=2;if(score<bestScore){bestScore=score;best=[nx,ny];}}if(!best)break;[x,y]=best;if(!land[idx(x,y,cols)]){river.add(idx(x,y,cols));break;}}}return river;}
export function createWorldV10(raw={}){const settings=sanitizeWorldSettings(raw),dim=dimensionsFor(settings),{cols,rows,cell,width,height}=dim,seed=settings.seed;const count=cols*rows,elev=new Float32Array(count),moist=new Float32Array(count),heat=new Float32Array(count),land=new Uint8Array(count);const sea=.53-(settings.landmass-.5)*.34;
for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const i=idx(x,y,cols),nx=x/Math.max(1,cols-1)*2-1,ny=y/Math.max(1,rows-1)*2-1,edge=clamp(1-Math.pow(Math.max(Math.abs(nx),Math.abs(ny)),1.45)),continental=fbm(seed,x,y,11,5),detail=fbm(seed,x+41,y-23,19,5),ridge=Math.abs(fbm(seed,x-17,y+31,27,4)-.5)*2;const base=.20+continental*.47+edge*.24+(detail-.5)*.13;const mountain=Math.pow(ridge,2.8)*settings.roughness*.28;elev[i]=clamp(base+mountain);land[i]=elev[i]>=sea?1:0;const latitude=1-Math.abs(y/Math.max(1,rows-1)-.5)*1.55;moist[i]=clamp(fbm(seed,x-13,y+7,51,5)*.62+settings.wetness*.32+(1-elev[i])*.10);heat[i]=clamp(latitude*.52+settings.temperature*.38+fbm(seed,x+9,y+11,61,4)*.18-elev[i]*.30);}
const riverCount=Math.max(1,Math.round(1+settings.rivers*8)),river=carveRivers(seed,elev,land,cols,rows,riverCount),lake=new Set();for(let y=1;y<rows-1;y++)for(let x=1;x<cols-1;x++){const i=idx(x,y,cols);if(!land[i]||river.has(i))continue;const low=neighbors(x,y,cols,rows).every(([nx,ny])=>elev[i]<=elev[idx(nx,ny,cols)]+.025);if(low&&moist[i]>.64&&noise(seed,x,y,1001)>.72)lake.add(i);}
const chunks=[];for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const i=idx(x,y,cols),e=elev[i],m=moist[i],h=heat[i],geo=geology(seed,x,y,e,settings.roughness);let biome='PLAINS';if(!land[i])biome='OCEAN';else if(river.has(i))biome='RIVER';else if(lake.has(i))biome='LAKE';else {const coast=neighbors(x,y,cols,rows).some(([nx,ny])=>!land[idx(nx,ny,cols)]);if(coast&&e<sea+.075)biome='BEACH';else if(e>.84)biome='ALPINE';else if(e>.69)biome=h<.30?'TUNDRA':'HIGHLAND';else if(m>.78&&e<.56)biome='MARSH';else if(h<.24)biome=m>.50?'TAIGA':'TUNDRA';else if(h>.72&&m<.30)biome='DESERT';else if(h>.62&&m<.48)biome='SAVANNA';else if(m>.67+(.5-settings.forests)*.20)biome=h>.62?'RAINFOREST':'FOREST';else if(geo==='SANDSTONE'&&m<.40)biome='BADLANDS';}
const res=baseResources(biome,geo,settings),r=noise(seed,x,y,1201);let site='WILDS';if(['HIGHLAND','ALPINE'].includes(biome)||geo==='LIMESTONE'){if(r>.82)site='CAVE';}if(site==='WILDS'&&r>1-settings.ruins*.12&&biome!=='OCEAN')site='RUIN';if(site==='WILDS'&&['FOREST','RAINFOREST','TAIGA'].includes(biome)&&r>.92)site='GROVE';if(site==='WILDS'&&['HIGHLAND','PLAINS','FOREST'].includes(biome)&&r<.025)site='SPRING';const danger=clamp(.025+(biome==='MARSH'?.11:biome==='BADLANDS'?.09:biome==='ALPINE'?.12:.035)+noise(seed,x,y,1301)*.15+settings.predators*.13);chunks.push({id:i,cx:x,cy:y,biome,geology:geo,site,type:site,elevation:e,moisture:m,heat:h,region:nameRegion(seed,x,y),...res,danger,shelter:site==='CAVE'?.58:site==='RUIN'?.30:.06,flood:biome==='RIVER'?.18:biome==='MARSH'?.07:0,agents:[],visits:0,programs:0});}
const world={seed,settings,cols,rows,cell,width,height,chunks,sweep:0,cursor:0,processed:0,riverCount,campId:0};const camp=chooseCamp(chunks,world);camp.site=camp.type='CAMP';camp.shelter=clamp(camp.shelter+.35);camp.food=clamp(camp.food+.06);world.campId=camp.id;world.summary=summarizeWorld(world);return world;}
export function summarizeWorld(world){const biomes={},geology={};for(const c of world.chunks){biomes[c.biome]=(biomes[c.biome]||0)+1;geology[c.geology]=(geology[c.geology]||0)+1;}return{biomes,geology,rivers:world.chunks.filter(c=>c.biome==='RIVER').length,lakes:world.chunks.filter(c=>c.biome==='LAKE').length,caves:world.chunks.filter(c=>c.site==='CAVE').length,ruins:world.chunks.filter(c=>c.site==='RUIN').length,ocean:world.chunks.filter(c=>c.biome==='OCEAN').length};}
export function chunkIndexForV10(world,x,y){const cx=Math.max(0,Math.min(world.cols-1,Math.floor(x/world.cell))),cy=Math.max(0,Math.min(world.rows-1,Math.floor(y/world.cell)));return cy*world.cols+cx;}
export function currentChunkV10(world,a){return world.chunks[chunkIndexForV10(world,a.x,a.y)];}
export function rebuildOccupancyV10(world,agents){for(const c of world.chunks)c.agents.length=0;for(const a of agents)if(a.alive)world.chunks[chunkIndexForV10(world,a.x,a.y)].agents.push(a);}
export function neighboringChunksV10(world,c){const out=[];for(const [x,y] of neighbors(c.cx,c.cy,world.cols,world.rows))out.push(world.chunks[idx(x,y,world.cols)]);return out;}
export function updateEnvironmentV10(c,weather={}){const rain=Number(weather.rain||0),flood=Number(weather.flood||0),natural=c.biome==='RIVER'?.18:c.biome==='MARSH'?.065:c.biome==='LAKE'?.12:0;c.flood=clamp(natural+Math.max(0,flood-c.elevation*.72)*1.5+rain*.10);const dry=1-c.flood,foodRegen=(['FOREST','RAINFOREST','MARSH'].includes(c.biome)?.014:['PLAINS','SAVANNA'].includes(c.biome)?.009:.0025);c.food=clamp(c.food+foodRegen*dry-c.flood*.004);c.game=clamp(c.game+(.0035+c.food*.002)*dry-(c.agents.length*.00005));if(['FOREST','RAINFOREST','TAIGA'].includes(c.biome))c.wood=clamp(c.wood+.0012*dry);c.danger=clamp(c.danger*.9997+c.flood*.0005);}
export function takeWorldBatchV10(world,n=16){const out=[];for(let i=0;i<n;i++){out.push(world.chunks[world.cursor]);world.cursor++;if(world.cursor>=world.chunks.length){world.cursor=0;world.sweep++;}}world.processed=world.cursor/world.chunks.length;return out;}
