import { runProgram } from './vm.js';
import { getActiveLibrary } from './evolution.js';
import { generateWorldChunks,chooseCampChunk,worldSummary } from './worldgen.js';
export const WORLD_W=2400,WORLD_H=1600,CHUNK_SIZE=100,CHUNK_COLS=WORLD_W/CHUNK_SIZE,CHUNK_ROWS=WORLD_H/CHUNK_SIZE,CHUNK_COUNT=CHUNK_COLS*CHUNK_ROWS;
export const BIOMES=Object.freeze(['PLAINS','FOREST','DESERT','MARSH','HIGHLAND','RIVER','TUNDRA','TAIGA','SAVANNA','BADLANDS','ALPINE']);
export const DISTRICT_TYPES=Object.freeze(['WILDS','HOME','CAVE','RUIN','BRIDGE','SPRING','GROVE']);
const clamp=v=>Math.max(0,Math.min(1,v));
function campify(c){c.site=c.type='HOME';c.shelter=clamp(c.shelter+.72);c.jobs=clamp(c.jobs+.34);c.food=clamp(c.food+.10);c.name=`camp-${c.region}`;return c;}
function learnedCall(name,a,b=0){const skill=getActiveLibrary()?.[name];if(!skill?.report?.verified)return null;const r=runProgram(skill.program,{a,b});return r.ok?r.value:null;}
function applyLearnedInfrastructure(c){c.floodAlarm=false;c.pumpActive=false;c.pumpRate=0;const water=Math.round(c.flood*100),alarm=learnedCall('IS_AHEAD',water,38);if(alarm===1)c.floodAlarm=true;if(c.floodAlarm&&['HOME','BRIDGE'].includes(c.site)){const excess=Math.max(0,water-38),pump=learnedCall('PICK_LOW',excess,6);if(Number.isFinite(pump)&&pump>0){c.pumpActive=true;c.pumpRate=Math.max(0,Math.min(6,pump));c.drainage=clamp((c.drainage||0)+c.pumpRate/140);}}}
export function createWorld(seed=0xBADC0DE){const chunks=generateWorldChunks(seed,CHUNK_COLS,CHUNK_ROWS),camp=campify(chooseCampChunk(chunks,CHUNK_COLS,CHUNK_ROWS));return{seed,chunks,campId:camp.id,summary:worldSummary(chunks),sweep:0,cursor:0,processed:0,visualRevision:1};}
export function chunkIndexFor(x,y){const cx=Math.max(0,Math.min(CHUNK_COLS-1,Math.floor(x/CHUNK_SIZE))),cy=Math.max(0,Math.min(CHUNK_ROWS-1,Math.floor(y/CHUNK_SIZE)));return cy*CHUNK_COLS+cx;}
export function rebuildOccupancy(world,agents){for(const c of world.chunks)c.agents.length=0;for(const a of agents)if(a.alive)world.chunks[chunkIndexFor(a.x,a.y)].agents.push(a);}
export function updateEnvironment(c,{floodLevel=0,rain=0}={}){c.drainage=(c.drainage||0)*.986;const natural=c.biome==='RIVER'?.20:c.biome==='MARSH'?.07:0,floodPressure=Math.max(0,floodLevel-c.elevation*.74);c.flood=clamp(natural+floodPressure*1.72+rain*.11-c.drainage);applyLearnedInfrastructure(c);c.flood=clamp(c.flood-c.pumpRate/180);const dry=1-c.flood,foodRegen=(c.site==='HOME'?.010:c.biome==='FOREST'?.020:c.biome==='MARSH'?.025:c.biome==='SAVANNA'?.017:c.biome==='PLAINS'?.012:.004),gameRegen=(c.biome==='FOREST'?.009:c.biome==='SAVANNA'?.010:c.biome==='PLAINS'?.007:c.biome==='TAIGA'?.005:.001);c.food=clamp(c.food+foodRegen*dry-c.flood*.006);c.game=clamp((c.game??.2)+gameRegen*dry-(c.agents?.length||0)*.00004);if(['FOREST','TAIGA','GROVE'].includes(c.biome)||c.site==='GROVE')c.wood=clamp((c.wood??.2)+.0022*dry);if(['RIVER','MARSH'].includes(c.biome)||c.site==='SPRING')c.water=1;if(c.site==='HOME')c.shelter=clamp(c.shelter+.0012*dry);c.danger=clamp(Math.max(.015,c.danger*.9994+c.flood*.001));}
export function takeChunkBatch(world,count=8){const out=[],seen=new Set(),active=world.chunks.filter(c=>c.agents.length);for(let i=0;i<active.length&&out.length<Math.ceil(count*.58);i++){const c=active[(world.cursor+i)%active.length];if(!seen.has(c.id)){seen.add(c.id);out.push(c);}}while(out.length<count){const c=world.chunks[world.cursor];world.cursor++;if(world.cursor>=world.chunks.length){world.cursor=0;world.sweep++;world.visualRevision++;}if(!seen.has(c.id)){seen.add(c.id);out.push(c);}}world.processed=world.cursor/world.chunks.length;return out;}
export function chunkCenter(c){return{x:c.cx*CHUNK_SIZE+CHUNK_SIZE/2,y:c.cy*CHUNK_SIZE+CHUNK_SIZE/2};}
export function neighboringChunks(world,c){const out=[];for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){if(!ox&&!oy)continue;const x=c.cx+ox,y=c.cy+oy;if(x>=0&&y>=0&&x<CHUNK_COLS&&y<CHUNK_ROWS)out.push(world.chunks[y*CHUNK_COLS+x]);}return out;}
