const TAU=Math.PI*2;
const clamp=v=>Math.max(0,Math.min(1,v));
function hash32(x){x|=0;x=(x+0x7ed55d16)+(x<<12);x=(x^0xc761c23c)^(x>>>19);x=(x+0x165667b1)+(x<<5);x=(x+0xd3a2646c)^(x<<9);x=(x+0xfd7046c5)+(x<<3);x=(x^0xb55a4f09)^(x>>>16);return x>>>0;}
export function noise(seed,x,y,salt=0){return hash32(seed^(x*73856093)^(y*19349663)^salt)/4294967295;}
function smooth(t){return t*t*(3-2*t);}function lerp(a,b,t){return a+(b-a)*t;}
function valueNoise(seed,x,y,salt=0){const x0=Math.floor(x),y0=Math.floor(y),tx=smooth(x-x0),ty=smooth(y-y0);const a=noise(seed,x0,y0,salt),b=noise(seed,x0+1,y0,salt),c=noise(seed,x0,y0+1,salt),d=noise(seed,x0+1,y0+1,salt);return lerp(lerp(a,b,tx),lerp(c,d,tx),ty);}
function fbm(seed,x,y,salt=0){let sum=0,amp=.55,freq=.18,norm=0;for(let i=0;i<5;i++){sum+=valueNoise(seed,x*freq,y*freq,salt+i*101)*amp;norm+=amp;amp*=.52;freq*=2.03;}return sum/norm;}
function plateField(seed,cx,cy,cols,rows){const plates=[];for(let i=0;i<9;i++)plates.push({x:noise(seed,i,0,201)*cols,y:noise(seed,i,0,202)*rows,u:noise(seed,i,0,203)*2-1,v:noise(seed,i,0,204)*2-1,lift:noise(seed,i,0,205)});let a=null,b=null,da=1e9,db=1e9;for(const p of plates){const d=(p.x-cx)**2+(p.y-cy)**2;if(d<da){b=a;db=da;a=p;da=d;}else if(d<db){b=p;db=d;}}const boundary=1-clamp(Math.abs(Math.sqrt(db)-Math.sqrt(da))/3.2);const convergence=b?clamp(((a.u-b.u)*(b.x-a.x)+(a.v-b.v)*(b.y-a.y))*-.06+.5):.5;return{boundary,convergence,lift:a?.lift??.5};}
function riverDistance(seed,cx,cy,rows){let best=99;for(let r=0;r<4;r++){const phase=noise(seed,r,0,301)*TAU,phase2=noise(seed,r,0,302)*TAU,base=(.18+r*.20)*rows;const y=base+Math.sin(cx*(.22+r*.027)+phase)*(.75+r*.18)+Math.sin(cx*.071+phase2)*1.15;best=Math.min(best,Math.abs((cy+.5)-y));}return best;}
function geologyFor(seed,cx,cy,elevation,plate){const r=noise(seed,cx,cy,401);if(plate.boundary>.73&&plate.convergence>.55)return'GRANITE';if(plate.boundary>.76&&plate.convergence<.44)return'BASALT';if(elevation<.28)return r>.48?'CLAY':'ALLUVIUM';if(r>.78)return'LIMESTONE';if(r>.54)return'SANDSTONE';if(r>.28)return'SHALE';return'GRANITE';}
function biomeFor({elevation,moisture,heat,river,geology}){if(river<.42)return'RIVER';if(elevation>.82)return'ALPINE';if(elevation>.68)return heat<.36?'TUNDRA':'HIGHLAND';if(moisture>.76&&elevation<.48)return'MARSH';if(heat<.24)return moisture>.52?'TAIGA':'TUNDRA';if(heat>.72&&moisture<.30)return'DESERT';if(heat>.62&&moisture<.47)return'SAVANNA';if(moisture>.61)return'FOREST';if(geology==='SANDSTONE'&&moisture<.40)return'BADLANDS';return'PLAINS';}
function resourceBase(biome,geology){const table={RIVER:[.45,.08,.04,1,.72,.18,.30],MARSH:[.64,.38,.08,.98,.84,.16,.48],FOREST:[.52,.95,.18,.46,.70,.25,.88],TAIGA:[.32,.82,.28,.40,.48,.34,.62],TUNDRA:[.16,.08,.42,.24,.18,.52,.25],ALPINE:[.08,.03,.92,.20,.05,.90,.18],HIGHLAND:[.18,.20,.82,.26,.22,.76,.38],DESERT:[.06,.03,.46,.04,.08,.40,.10],SAVANNA:[.46,.28,.24,.22,.58,.26,.74],BADLANDS:[.12,.05,.70,.08,.16,.58,.28],PLAINS:[.42,.34,.24,.31,.78,.26,.78]};const base=table[biome]||table.PLAINS;let food=base[0],wood=base[1],stone=base[2],water=base[3],soil=base[4],ore=base[5],game=base[6];const clay=(geology==='CLAY'||geology==='ALLUVIUM')?.9:.18;if(geology==='BASALT')ore=Math.min(1,ore+.12);if(geology==='LIMESTONE')stone=Math.min(1,stone+.08);if(geology==='GRANITE')stone=Math.min(1,stone+.10);return{food,wood,stone,water,soil,ore,clay,game};}
function siteFor(seed,cx,cy,biome,geology,elevation){const r=noise(seed,cx,cy,501);if(biome==='RIVER')return r>.88?'BRIDGE':'WILDS';if((biome==='ALPINE'||biome==='HIGHLAND'||geology==='LIMESTONE')&&r>.78)return'CAVE';if(r>.965&&elevation>.28)return'RUIN';if(r>.91&&['FOREST','PLAINS','SAVANNA'].includes(biome))return'GROVE';if(r>.89&&['RIVER','MARSH','HIGHLAND'].includes(biome))return'SPRING';return'WILDS';}
function regionName(seed,cx,cy){const a=['Ash','Stone','Rain','Wolf','Moss','Red','Black','Bright','Cold','Deep','Old','Wild','Sun','Moon','Mist','Iron'];const b=['Reach','Vale','Basin','March','Wood','Steppe','Hollow','Ridge','Wash','Fen','Crown','Run','Fields','Scar','Moor','Spine'];return`${a[Math.floor(noise(seed,cx,cy,601)*a.length)]}${b[Math.floor(noise(seed,cx,cy,602)*b.length)]}`;}
export function generateWorldChunks(seed,cols,rows){const chunks=[];for(let cy=0;cy<rows;cy++)for(let cx=0;cx<cols;cx++){const plate=plateField(seed,cx,cy,cols,rows),continental=fbm(seed,cx,cy,11),detail=fbm(seed,cx+31,cy-17,21),ridge=Math.pow(plate.boundary,2.2)*(.18+.24*plate.convergence),elevation=clamp(.08+continental*.64+detail*.18+ridge+(plate.lift-.5)*.12),lat=cy/Math.max(1,rows-1),latitudeHeat=1-Math.abs(lat-.52)*1.52,moisture=clamp(fbm(seed,cx-21,cy+13,31)*.74+(1-elevation)*.14+noise(seed,cx,cy,33)*.12),heat=clamp(latitudeHeat*.66+fbm(seed,cx+9,cy+7,41)*.30-elevation*.30+.10),river=riverDistance(seed,cx,cy,rows),geology=geologyFor(seed,cx,cy,elevation,plate),biome=biomeFor({elevation,moisture,heat,river,geology}),resources=resourceBase(biome,geology),site=siteFor(seed,cx,cy,biome,geology,elevation),danger=clamp(.03+(biome==='MARSH'?.16:biome==='BADLANDS'?.12:biome==='ALPINE'?.13:.05)+noise(seed,cx,cy,701)*.20);chunks.push({id:cy*cols+cx,cx,cy,biome,geology,site,type:site,elevation,moisture,heat,plateStress:plate.boundary,riverDistance:river,region:regionName(seed,cx,cy),...resources,danger,shelter:site==='CAVE'?.62:site==='RUIN'?.38:.08,jobs:.06,learning:0,flood:biome==='RIVER'?.18:biome==='MARSH'?.06:0,drainage:0,floodAlarm:false,pumpActive:false,pumpRate:0,agents:[],visits:0,deaths:0,births:0,programs:0});}return chunks;}
export function chooseCampChunk(chunks,cols,rows){const cx=(cols-1)/2,cy=(rows-1)/2;return chunks.filter(c=>!['RIVER','MARSH','ALPINE'].includes(c.biome)).sort((a,b)=>{const sa=a.water*.9+a.food*.8+a.wood*.55+a.stone*.25+a.shelter*.35-a.danger*.75-Math.hypot(a.cx-cx,a.cy-cy)*.018,sb=b.water*.9+b.food*.8+b.wood*.55+b.stone*.25+b.shelter*.35-b.danger*.75-Math.hypot(b.cx-cx,b.cy-cy)*.018;return sb-sa;})[0]||chunks[0];}
export function worldSummary(chunks){const biomes=new Map(),geology=new Map();for(const c of chunks){biomes.set(c.biome,(biomes.get(c.biome)||0)+1);geology.set(c.geology,(geology.get(c.geology)||0)+1);}return{biomes:Object.fromEntries(biomes),geology:Object.fromEntries(geology),caves:chunks.filter(c=>c.site==='CAVE').length,ruins:chunks.filter(c=>c.site==='RUIN').length,rivers:chunks.filter(c=>c.biome==='RIVER').length};}
