(async()=>{const C=document.getElementById('c'),stats=document.getElementById('stats'),mode=document.getElementById('mode');try{
async function loadKernel(){const s=document.createElement('script');s.src='./kernel.js?v=3';document.head.appendChild(s);await new Promise((r,j)=>{s.onload=r;s.onerror=()=>j(new Error('kernel.js failed to load'))});if(typeof createOuroborosKernel!=='function')throw new Error('WASM factory missing');return await createOuroborosKernel({locateFile:p=>'./'+p+'?v=3'});}
const mod=await loadKernel();if(!mod.HEAPF32)throw new Error('HEAPF32 not exported by WASM build');const N=mod._ok_n(),C0=N*N;mod._ok_reset();function arr(fn){return()=>new Float32Array(mod.HEAPF32.buffer,mod[fn](),C0)}const get={terrain:arr('_ok_terrain'),sand:arr('_ok_sand'),water:arr('_ok_water'),lava:arr('_ok_lava'),steam:arr('_ok_steam')};
const ua=navigator.userAgent||'',isIOS=/iPhone|iPad|iPod/.test(ua);let engine;if(!isIOS&&navigator.gpu){try{engine=new BABYLON.WebGPUEngine(C,{antialias:false});await engine.initAsync();mode.textContent='C++ WASM • WebGPU'}catch{engine=null}}if(!engine){engine=new BABYLON.Engine(C,true,{adaptToDeviceRatio:true,preserveDrawingBuffer:false,stencil:false});engine.setHardwareScalingLevel(isIOS?Math.max(1,window.devicePixelRatio/1.35):1);mode.textContent=isIOS?'C++ WASM • iPhone WebGL stable mode':'C++ WASM • WebGL';}
const sc=new BABYLON.Scene(engine);sc.clearColor=new BABYLON.Color4(.006,.014,.022,1);sc.fogMode=BABYLON.Scene.FOGMODE_EXP2;sc.fogDensity=.012;sc.fogColor=new BABYLON.Color3(.025,.055,.07);const cam=new BABYLON.ArcRotateCamera('cam',-1.2,1.03,76,new BABYLON.Vector3(0,0,0),sc);cam.lowerRadiusLimit=15;cam.upperRadiusLimit=130;cam.pinchPrecision=70;cam.wheelPrecision=30;cam.attachControl(C,true);new BABYLON.HemisphericLight('sky',new BABYLON.Vector3(.2,1,.1),sc).intensity=.7;const sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.4,-1,.25),sc);sun.intensity=2.4;
const world=64,dx=world/(N-1);function mkMat(n,c,r,a=1,e=null){const m=new BABYLON.PBRMaterial(n,sc);m.albedoColor=c;m.roughness=r;m.alpha=a;if(e)m.emissiveColor=e;return m}const earth=mkMat('earth',new BABYLON.Color3(.12,.095,.07),.98),wm=mkMat('water',new BABYLON.Color3(.015,.19,.36),.09,.72),lm=mkMat('lava',new BABYLON.Color3(.52,.035,.004),.25,1,new BABYLON.Color3(1,.08,.003));
function grid(n,m){const p=[],ind=[],nor=[];for(let z=0;z<N;z++)for(let x=0;x<N;x++)p.push(x*dx-world/2,0,z*dx-world/2);for(let z=0;z<N-1;z++)for(let x=0;x<N-1;x++){const a=z*N+x,b=a+1,c=a+N,d=c+1;ind.push(a,c,b,b,c,d)}BABYLON.VertexData.ComputeNormals(p,ind,nor);const vd=new BABYLON.VertexData();vd.positions=p;vd.indices=ind;vd.normals=nor;const mesh=new BABYLON.Mesh(n,sc);vd.applyToMesh(mesh,true);mesh.material=m;return{mesh,ind}}
const ground=grid('terrain',earth),water=grid('water',wm),lava=grid('lava',lm);let frame=0;function upd(obj,type){const T=get.terrain(),S=get.sand(),F=get[type](),p=obj.mesh.getVerticesData(BABYLON.VertexBuffer.PositionKind);for(let i=0;i<C0;i++){let y=T[i]+S[i];if(type==='water')y+=F[i]>.003?F[i]+.035:-30;else if(type==='lava')y+=F[i]>.003?F[i]+.07:-30;p[i*3+1]=y}obj.mesh.updateVerticesData(BABYLON.VertexBuffer.PositionKind,p,false,false);if((frame&3)===0){const nor=[];BABYLON.VertexData.ComputeNormals(p,obj.ind,nor);obj.mesh.updateVerticesData(BABYLON.VertexBuffer.NormalKind,nor)}}function updGround(){const T=get.terrain(),S=get.sand(),p=ground.mesh.getVerticesData(BABYLON.VertexBuffer.PositionKind);for(let i=0;i<C0;i++)p[i*3+1]=T[i]+S[i];ground.mesh.updateVerticesData(BABYLON.VertexBuffer.PositionKind,p,false,false);if((frame&7)===0){const nor=[];BABYLON.VertexData.ComputeNormals(p,ground.ind,nor);ground.mesh.updateVerticesData(BABYLON.VertexBuffer.NormalKind,nor)}}
let acc=0,last=performance.now(),fc=0,ft=0;engine.runRenderLoop(()=>{const now=performance.now(),real=Math.min(.04,(now-last)/1000);last=now;acc+=real;let n=0;const maxSteps=isIOS?3:6;while(acc>=1/90&&n++<maxSteps){mod._ok_step(1/90);acc-=1/90}frame++;updGround();upd(water,'water');upd(lava,'lava');sc.render();fc++;ft+=real;if(ft>.5){stats.textContent=`RUNNING • ticks ${Number(mod._ok_ticks())} • water ${mod._ok_mass_water().toFixed(1)} • rock ${mod._ok_mass_rock().toFixed(1)} • ${(fc/ft).toFixed(0)} fps`;fc=0;ft=0}});document.getElementById('water').onclick=()=>mod._ok_inject_water(20,12,18);document.getElementById('lava').onclick=()=>mod._ok_inject_lava(49,12,10,1280);document.getElementById('reset').onclick=()=>mod._ok_reset();addEventListener('resize',()=>engine.resize());
}catch(e){console.error(e);stats.textContent='MOBILE BOOT ERROR';mode.className='bad';mode.textContent=(e&&e.message)||String(e)}})();