const C=document.getElementById('c'),stats=document.getElementById('stats'),mode=document.getElementById('mode');
async function loadKernel(){try{const s=document.createElement('script');s.src='./kernel.js?v=1';document.head.appendChild(s);await new Promise((r,j)=>{s.onload=r;s.onerror=()=>j(new Error('kernel.js missing: WASM build has not been published'))});return await createOuroborosKernel({locateFile:p=>'./'+p+'?v=1'});}catch(e){mode.className='bad';mode.textContent=e.message;throw e}}
const mod=await loadKernel();const N=mod._ok_n(),C0=N*N;mod._ok_reset();
function arr(fn){return()=>new Float32Array(mod.HEAP8.buffer,mod[fn](),C0)}
const get={terrain:arr('_ok_terrain'),sand:arr('_ok_sand'),water:arr('_ok_water'),lava:arr('_ok_lava'),temp:arr('_ok_lava_temp'),steam:arr('_ok_steam'),sed:arr('_ok_sediment')};
let engine;try{if(navigator.gpu){engine=new BABYLON.WebGPUEngine(C,{antialias:true});await engine.initAsync();mode.textContent='C++ WASM authority • Babylon WebGPU viewer'}else throw 0}catch(_){engine=new BABYLON.Engine(C,true,{adaptToDeviceRatio:true});mode.textContent='C++ WASM authority • WebGL fallback viewer'}
const sc=new BABYLON.Scene(engine);sc.clearColor=new BABYLON.Color4(.006,.014,.022,1);sc.fogMode=BABYLON.Scene.FOGMODE_EXP2;sc.fogDensity=.015;sc.fogColor=new BABYLON.Color3(.025,.055,.07);const cam=new BABYLON.ArcRotateCamera('cam',-1.2,1.02,80,new BABYLON.Vector3(0,0,0),sc);cam.lowerRadiusLimit=15;cam.upperRadiusLimit=130;cam.attachControl(C,true);const hemi=new BABYLON.HemisphericLight('sky',new BABYLON.Vector3(.2,1,.1),sc);hemi.intensity=.65;const sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.4,-1,.25),sc);sun.intensity=3.0;
const world=64,dx=world/(N-1);function mkMat(name,c,rough,alpha=1,emit=null){const m=new BABYLON.PBRMaterial(name,sc);m.albedoColor=c;m.roughness=rough;m.alpha=alpha;if(emit)m.emissiveColor=emit;return m}const earth=mkMat('earth',new BABYLON.Color3(.12,.095,.07),.98),wm=mkMat('water',new BABYLON.Color3(.015,.19,.36),.08,.74),lm=mkMat('lava',new BABYLON.Color3(.5,.035,.005),.24,1,new BABYLON.Color3(1,.08,.005));wm.indexOfRefraction=1.333;
function makeGrid(name,mat){const pos=[],ind=[],nor=[];for(let z=0;z<N;z++)for(let x=0;x<N;x++)pos.push(x*dx-world/2,0,z*dx-world/2);for(let z=0;z<N-1;z++)for(let x=0;x<N-1;x++){const a=z*N+x,b=a+1,c=a+N,d=c+1;ind.push(a,c,b,b,c,d)}BABYLON.VertexData.ComputeNormals(pos,ind,nor);const vd=new BABYLON.VertexData();vd.positions=pos;vd.indices=ind;vd.normals=nor;const mesh=new BABYLON.Mesh(name,sc);vd.applyToMesh(mesh,true);mesh.material=mat;return{mesh,pos,ind}}
const ground=makeGrid('terrain',earth),water=makeGrid('water',wm),lava=makeGrid('lava',lm);water.mesh.alphaIndex=1;lava.mesh.alphaIndex=2;
function updateSurface(obj,type){const T=get.terrain(),S=get.sand(),F=get[type](),p=obj.mesh.getVerticesData(BABYLON.VertexBuffer.PositionKind);for(let i=0;i<C0;i++){let y=T[i]+S[i];if(type==='water')y+=F[i]>.002?F[i]+.035:-20;if(type==='lava')y+=F[i]>.002?F[i]+.07:-20;p[i*3+1]=y}obj.mesh.updateVerticesData(BABYLON.VertexBuffer.PositionKind,p,false,false);const nor=[];BABYLON.VertexData.ComputeNormals(p,obj.ind,nor);obj.mesh.updateVerticesData(BABYLON.VertexBuffer.NormalKind,nor)}
function updateGround(){const T=get.terrain(),S=get.sand(),p=ground.mesh.getVerticesData(BABYLON.VertexBuffer.PositionKind);for(let i=0;i<C0;i++)p[i*3+1]=T[i]+S[i];ground.mesh.updateVerticesData(BABYLON.VertexBuffer.PositionKind,p,false,false);const nor=[];BABYLON.VertexData.ComputeNormals(p,ground.ind,nor);ground.mesh.updateVerticesData(BABYLON.VertexBuffer.NormalKind,nor)}
const steamProto=BABYLON.MeshBuilder.CreateSphere('steamP',{diameter:.55,segments:5},sc);const sm=mkMat('steam',new BABYLON.Color3(.65,.72,.74),.9,.16);steamProto.material=sm;steamProto.isVisible=false;const steam=[];for(let i=0;i<120;i++)steam.push(steamProto.createInstance('s'+i));
function updateSteam(){const A=get.steam(),gp=ground.mesh.getVerticesData(BABYLON.VertexBuffer.PositionKind);let k=0;for(let i=0;i<C0&&k<steam.length;i++)if(A[i]>.002){const x=i%N,z=(i/N)|0,m=steam[k++];m.isVisible=true;m.position.set(x*dx-world/2,gp[i*3+1]+2+A[i]*18,z*dx-world/2);m.scaling.setAll(.5+Math.min(2,A[i]*50))}for(;k<steam.length;k++)steam[k].isVisible=false}
let acc=0,last=performance.now(),frames=0,ft=0;engine.runRenderLoop(()=>{const now=performance.now(),real=Math.min(.05,(now-last)/1000);last=now;acc+=real;let n=0;while(acc>=1/120&&n++<8){mod._ok_step(1/120);acc-=1/120}updateGround();updateSurface(water,'water');updateSurface(lava,'lava');updateSteam();sc.render();frames++;ft+=real;if(ft>.4){stats.textContent=`ticks ${Number(mod._ok_ticks())} • water ${mod._ok_mass_water().toFixed(1)} • rock ${mod._ok_mass_rock().toFixed(1)} • erosion ${mod._ok_eroded().toFixed(2)} • steam ${mod._ok_evaporated().toFixed(2)} • solid ${mod._ok_solidified().toFixed(2)} • ${(frames/ft).toFixed(0)} fps`;frames=0;ft=0}});
document.getElementById('water').onclick=()=>mod._ok_inject_water(20,12,18);document.getElementById('lava').onclick=()=>mod._ok_inject_lava(49,12,10,1280);document.getElementById('reset').onclick=()=>mod._ok_reset();addEventListener('resize',()=>engine.resize());