(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.GenesisAudit=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const REQUIRED=['index.html','forge/index.html','forge/forge.js','forge/audit-core.js','forge/promotion-core.js','forge/runner-core.js','forge/runner-worker.js','project/state.json','genesis-codehood/index.html','genesis-codehood/package.json','genesis-codehood/native-ray-volume.js','genesis-codehood/native-main.js','genesis-codehood/tests/native_cpp_boot.test.mjs','volume3d/worker.js','volume3d/solver.cpp','volume3d/solver_test.cpp','volume3d/wasm.test.mjs','volume3d/solver.v3.manifest.json','volume3d/solver.v3.part0.b64','volume3d/solver.v3.part1.b64','volume3d/solver.v3.part2.b64','volume3d/solver.v3.part3.b64','volume3d/solver.v3.part4.b64','native-body/body.cpp','native-body/body_test.cpp','native-body/body_wasm.test.mjs','native-body/wasm_runtime.cpp','native-body/MODEL.md','.github/workflows/native-body-v1.yml','volume3d/body.cpp','volume3d/body_test.cpp','.github/workflows/body-mechanics.yml','genesis-codehood/scratch/sim-core.js','genesis-codehood/scratch/alife.js','genesis-codehood/scratch/navigation.js','genesis-codehood/scratch/deep-world.js','genesis-codehood/scratch/deep-bind.js','genesis-codehood/scratch/deep-nav.js','genesis-codehood/scratch/deep-render.js','genesis-codehood/scratch/environment.js','genesis-codehood/scratch/organic-render.js','genesis-codehood/scratch/environment-worker.js','genesis-codehood/scratch/main.js','genesis-codehood/scratch/style.css','genesis-codehood/physical-creature-v1/index.html','genesis-codehood/physical-creature-v1/model.js','genesis-codehood/physical-creature-v1/model.test.mjs'];
const levels=['IMPLEMENTED','TESTED','CI_PASS','LIVE_TESTED','DEVICE_TESTED','VERIFIED'];
function checkState(state){const stack=state?.active_experience?.stack||[],truth=String(state?.native_volume_renderer?.truth||'').toLowerCase(),fluid=state?.native_cpp_kernel||{},body=state?.native_body_mechanics||{},shims=body.compatibility_shims||[];return[
{id:'state.schema',label:'Project schema is 1',pass:state?.schema===1,actual:state?.schema},
{id:'state.project',label:'Project is GENESIS',pass:state?.project==='GENESIS',actual:state?.project},
{id:'state.phase',label:'Engineering phase is native body mechanics v1',pass:state?.phase==='native-body-mechanics-v1',actual:state?.phase},
{id:'state.experience',label:'Active GENESIS route exists',pass:state?.active_experience?.route==='/genesis-codehood/',actual:state?.active_experience?.route||'missing'},
{id:'state.stack',label:'Active browser stack remains compiler-proven fluid v3',pass:['native-ray-volume.js','native-main.js','../volume3d/worker.js','../volume3d/solver.v3.manifest.json','../volume3d/solver.cpp'].every(x=>stack.includes(x)),actual:stack},
{id:'state.level',label:'Active route verification is explicit',pass:levels.includes(state?.active_experience?.verification_level),actual:state?.active_experience?.verification_level},
{id:'fluid.level',label:'Native fluid remains CI passed',pass:fluid.verification_level==='CI_PASS'&&fluid.status==='PASS'&&fluid.ci?.status==='PASS',actual:{level:fluid.verification_level,status:fluid.status,ci:fluid.ci?.status}},
{id:'fluid.version',label:'Native fluid model version is pressure projection v1',pass:fluid.model_version==='0x00040001',actual:fluid.model_version},
{id:'fluid.hash',label:'Active browser fluid payload is compiler-proven v3 SHA',pass:fluid.compiled_payload_sha256==='573eea6bccc8ef38ab828ccfa57d7d91861e5ac04254ca5aea523c3438bb55c0',actual:fluid.compiled_payload_sha256},
{id:'renderer.truth',label:'Renderer forbids fake water motion and pressure-as-turbidity',pass:truth.includes('time-driven fake water-normal animation is forbidden')&&truth.includes('never pressure'),actual:state?.native_volume_renderer?.truth||'missing'},
{id:'body.exists',label:'Authoritative native body state exists',pass:!!body,actual:body.source||'missing'},
{id:'body.level',label:'Authoritative native body is CI passed but not active',pass:body.verification_level==='CI_PASS'&&body.status==='PASS_STANDALONE_NATIVE_CANDIDATE'&&body.loaded_by_active_route===false,actual:{level:body.verification_level,status:body.status,active:body.loaded_by_active_route}},
{id:'body.source',label:'Fixed-point native-body source is authoritative',pass:body.source==='native-body/body.cpp'&&body.test==='native-body/body_test.cpp'&&body.wasm_test==='native-body/body_wasm.test.mjs',actual:{source:body.source,test:body.test,wasm_test:body.wasm_test}},
{id:'body.version',label:'Native body model version is fixed-point v1',pass:body.model_version==='0x00010001',actual:body.model_version},
{id:'body.numeric',label:'Body truth declares fixed-point numeric model',pass:String(body.numeric_model||'').includes('Q16.16'),actual:body.numeric_model},
{id:'body.fixture',label:'Body reference fixture proves 18-node articulated replay',pass:body.reference_fixture?.nodes===18&&body.reference_fixture?.structural_links===22&&body.reference_fixture?.bend_ranges===4&&body.reference_fixture?.hash===3632292203,actual:body.reference_fixture},
{id:'body.wasm',label:'Body WASM is zero-import native semantic parity',pass:body.wasm?.imports===0&&body.wasm?.bytes===26250&&body.wasm?.sha256==='b48c15ff1e504f5e78deaba846661aa4d95415132a6202e6c4452ffe32f8755f'&&body.wasm?.semantic_parity==='PASS',actual:body.wasm},
{id:'body.shims',label:'Legacy volume body paths are compatibility-only shims',pass:shims.includes('volume3d/body.cpp')&&shims.includes('volume3d/body_test.cpp'),actual:shims},
{id:'state.noLiveInflation',label:'Live/device evidence is not inflated',pass:state?.active_experience?.browser_exercise?.live_pages!=='LIVE_TESTED'&&state?.active_experience?.browser_exercise?.iphone_safari!=='DEVICE_TESTED',actual:state?.active_experience?.browser_exercise||'missing'},
{id:'state.scratch',label:'Prior scratch proof is preserved but not active',pass:state?.scratch_engine?.status==='PRESERVED_NOT_LOADED_BY_ACTIVE_ROUTE',actual:state?.scratch_engine?.status},
{id:'state.legacy',label:'Legacy ecosystem stack is archived',pass:state?.legacy_ecosystem_stack?.status==='ARCHIVED_NOT_LOADED_BY_ACTIVE_ROUTE',actual:state?.legacy_ecosystem_stack?.status},
{id:'state.proof',label:'Physical Creature proof remains preserved',pass:state?.physical_creature_v1?.verification_level==='CI_PASS',actual:state?.physical_creature_v1?.verification_level},
{id:'state.objective',label:'Active objective exists',pass:typeof state?.active_objective==='string'&&state.active_objective.length>0,actual:state?.active_objective||'missing'},
{id:'state.next',label:'Next gate exists',pass:typeof state?.next_gate==='string'&&state.next_gate.length>0,actual:state?.next_gate||'missing'}];}
function audit(input){const state=input?.state||null,files=input?.files||{},checks=[];for(const path of REQUIRED)checks.push({id:'file:'+path,label:path+' reachable',pass:files[path]===true,actual:files[path]===true?'present':'missing'});checks.push(...checkState(state));const pass=checks.every(c=>c.pass===true);return{schema:1,kind:'GENESIS_FORGE_CANONICAL_AUDIT',status:pass?'PASS':'FAIL',checks,summary:{passed:checks.filter(c=>c.pass).length,total:checks.length},project:state?.project||'UNKNOWN',phase:state?.phase||'UNKNOWN',active_route:state?.active_experience?.route||'UNKNOWN',verification_level:state?.active_experience?.verification_level||'UNKNOWN',native_kernel_level:state?.native_cpp_kernel?.verification_level||'UNKNOWN',native_body_level:state?.native_body_mechanics?.verification_level||'UNKNOWN',native_volume_level:state?.native_volume_renderer?.verification_level||'UNKNOWN',stable_verified:state?.stable?.verified===true,active_objective:state?.active_objective||'UNKNOWN',next_gate:state?.next_gate||'UNKNOWN'};}
function failureDrill(input){const baseline=audit(input),brokenFiles={...(input?.files||{})},injected='native-body/body.cpp';brokenFiles[injected]=false;const candidate=audit({state:input?.state||null,files:brokenFiles}),recovered=audit(input),pass=baseline.status==='PASS'&&candidate.status==='FAIL'&&recovered.status==='PASS';return{schema:1,kind:'GENESIS_FORGE_FAIL_CLOSED_DRILL',status:pass?'PASS':'FAIL',injected_failure:{type:'missing-required-file',target:injected},baseline_status:baseline.status,candidate_status:candidate.status,recovered_status:recovered.status,stable_preserved:recovered.status===baseline.status&&recovered.summary.passed===baseline.summary.passed,checks:[{id:'drill.baseline',label:'Baseline starts healthy',pass:baseline.status==='PASS',actual:baseline.status},{id:'drill.reject',label:'Missing authoritative native body source is rejected',pass:candidate.status==='FAIL',actual:candidate.status},{id:'drill.recover',label:'Baseline recovers',pass:recovered.status==='PASS',actual:recovered.status}],baseline,candidate,recovered};}
function stableStringify(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(stableStringify).join(',')+']';return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+stableStringify(value[k])).join(',')+'}';}
async function sha256(text){if(typeof crypto!=='undefined'&&crypto.subtle){const bytes=new TextEncoder().encode(text),digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');}if(typeof require==='function'){const c=require('node:crypto');return c.createHash('sha256').update(text).digest('hex');}throw new Error('SHA-256 unavailable');}
async function receipt(result,meta={}){const body={...result,generated_at:new Date().toISOString(),environment:meta.environment||'unknown',source:meta.source||'unknown'};body.evidence_sha256=await sha256(stableStringify(body));return body;}
return{REQUIRED,audit,failureDrill,checkState,stableStringify,sha256,receipt};
});
