(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.GenesisAudit=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const REQUIRED=['index.html','forge/index.html','forge/forge.js','forge/audit-core.js','forge/promotion-core.js','forge/runner-core.js','forge/runner-worker.js','project/state.json','genesis-codehood/index.html','genesis-codehood/old_sim_upgrade.js','genesis-codehood/old_sim_upgrade.css','genesis-codehood/fluid_refinement.js','genesis-codehood/tests/fluid_refinement.test.mjs','genesis-codehood/creature_world_overhaul.js','genesis-codehood/tests/creature_rig_overhaul.test.mjs','genesis-codehood/feeding_truth.js','genesis-codehood/tests/feeding_truth.test.mjs','genesis-codehood/mobile_observer.js','genesis-codehood/mobile_observer.css','genesis-codehood/rig25_sound.js','genesis-codehood/tests/rig25_sound.test.mjs','genesis-codehood/hydro_geomorph25.js','genesis-codehood/tests/hydro_geomorph25.test.mjs','genesis-codehood/physical-creature-v1/index.html','genesis-codehood/physical-creature-v1/model.js','genesis-codehood/physical-creature-v1/model.test.mjs'];
function checkState(state){return[
  {id:'state.schema',label:'Project schema is 1',pass:state?.schema===1,actual:state?.schema},
  {id:'state.project',label:'Project is GENESIS',pass:state?.project==='GENESIS',actual:state?.project},
  {id:'state.phase',label:'Active phase is ecosystem-hydro-geomorphology25',pass:state?.phase==='ecosystem-hydro-geomorphology25',actual:state?.phase},
  {id:'state.stable',label:'Stable record exists',pass:!!state?.stable&&typeof state.stable.verified==='boolean',actual:state?.stable?.verified},
  {id:'state.experience',label:'Active ecosystem experience exists',pass:state?.active_experience?.route==='/genesis-codehood/',actual:state?.active_experience?.route||'missing'},
  {id:'state.level',label:'Active experience verification is explicit',pass:['IMPLEMENTED','TESTED','CI_PASS','LIVE_TESTED','DEVICE_TESTED','VERIFIED'].includes(state?.active_experience?.verification_level),actual:state?.active_experience?.verification_level},
  {id:'state.fluid',label:'Fluid refinement state exists',pass:!!state?.fluid_refinement,actual:state?.fluid_refinement?.verification_level||'missing'},
  {id:'state.fluidLevel',label:'Fluid refinement verification is explicit',pass:['IMPLEMENTED','TESTED','CI_PASS','LIVE_TESTED','DEVICE_TESTED','VERIFIED'].includes(state?.fluid_refinement?.verification_level),actual:state?.fluid_refinement?.verification_level},
  {id:'state.rig25',label:'Rig25 acoustic state exists',pass:!!state?.rig25_acoustic,actual:state?.rig25_acoustic?.verification_level||'missing'},
  {id:'state.rig25Level',label:'Rig25 verification is explicit',pass:['IMPLEMENTED','TESTED','CI_PASS','LIVE_TESTED','DEVICE_TESTED','VERIFIED'].includes(state?.rig25_acoustic?.verification_level),actual:state?.rig25_acoustic?.verification_level},
  {id:'state.hydro25',label:'Hydro geomorphology state exists',pass:!!state?.hydro_geomorph25,actual:state?.hydro_geomorph25?.verification_level||'missing'},
  {id:'state.hydro25Level',label:'Hydro geomorphology verification is explicit',pass:['IMPLEMENTED','TESTED','CI_PASS','LIVE_TESTED','DEVICE_TESTED','VERIFIED'].includes(state?.hydro_geomorph25?.verification_level),actual:state?.hydro_geomorph25?.verification_level},
  {id:'state.proof',label:'Physical Creature proof slice remains preserved',pass:state?.physical_creature_v1?.verification_level==='CI_PASS',actual:state?.physical_creature_v1?.verification_level||'missing'},
  {id:'state.objective',label:'Active objective exists',pass:typeof state?.active_objective==='string'&&state.active_objective.length>0,actual:state?.active_objective||'missing'},
  {id:'state.next',label:'Next gate exists',pass:typeof state?.next_gate==='string'&&state.next_gate.length>0,actual:state?.next_gate||'missing'}
];}
function audit(input){const state=input?.state||null;const files=input?.files||{};const checks=[];for(const path of REQUIRED)checks.push({id:'file:'+path,label:path+' reachable',pass:files[path]===true,actual:files[path]===true?'present':'missing'});checks.push(...checkState(state));const pass=checks.every(c=>c.pass===true);return{schema:1,kind:'GENESIS_FORGE_CANONICAL_AUDIT',status:pass?'PASS':'FAIL',checks,summary:{passed:checks.filter(c=>c.pass).length,total:checks.length},project:state?.project||'UNKNOWN',phase:state?.phase||'UNKNOWN',active_route:state?.active_experience?.route||'UNKNOWN',verification_level:state?.active_experience?.verification_level||'UNKNOWN',fluid_refinement_level:state?.fluid_refinement?.verification_level||'UNKNOWN',rig25_level:state?.rig25_acoustic?.verification_level||'UNKNOWN',hydro25_level:state?.hydro_geomorph25?.verification_level||'UNKNOWN',preserved_physical_creature_level:state?.physical_creature_v1?.verification_level||'UNKNOWN',stable_verified:state?.stable?.verified===true,active_objective:state?.active_objective||'UNKNOWN',next_gate:state?.next_gate||'UNKNOWN'}}
function failureDrill(input){const baseline=audit(input);const brokenFiles={...(input?.files||{})};const injected='genesis-codehood/hydro_geomorph25.js';brokenFiles[injected]=false;const candidate=audit({state:input?.state||null,files:brokenFiles});const recovered=audit(input);const pass=baseline.status==='PASS'&&candidate.status==='FAIL'&&recovered.status==='PASS';return{schema:1,kind:'GENESIS_FORGE_FAIL_CLOSED_DRILL',status:pass?'PASS':'FAIL',injected_failure:{type:'missing-required-file',target:injected},baseline_status:baseline.status,candidate_status:candidate.status,recovered_status:recovered.status,stable_preserved:recovered.status===baseline.status&&recovered.summary.passed===baseline.summary.passed,checks:[{id:'drill.baseline',label:'Baseline starts healthy',pass:baseline.status==='PASS',actual:baseline.status},{id:'drill.reject',label:'Missing active hydro layer is rejected',pass:candidate.status==='FAIL',actual:candidate.status},{id:'drill.recover',label:'Untouched baseline still passes after failure',pass:recovered.status==='PASS',actual:recovered.status},{id:'drill.preserve',label:'Baseline evidence count is preserved',pass:recovered.summary.passed===baseline.summary.passed,actual:`${recovered.summary.passed}/${baseline.summary.passed}`}],baseline,candidate,recovered}}
function stableStringify(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(stableStringify).join(',')+']';return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+stableStringify(value[k])).join(',')+'}'}
async function sha256(text){if(typeof crypto!=='undefined'&&crypto.subtle){const bytes=new TextEncoder().encode(text);const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('')}if(typeof require==='function'){const c=require('node:crypto');return c.createHash('sha256').update(text).digest('hex')}throw new Error('SHA-256 unavailable')}
async function receipt(result,meta={}){const body={...result,generated_at:new Date().toISOString(),environment:meta.environment||'unknown',source:meta.source||'unknown'};body.evidence_sha256=await sha256(stableStringify(body));return body}
return{REQUIRED,audit,failureDrill,checkState,stableStringify,sha256,receipt};
});