(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.GenesisAudit=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const REQUIRED=['index.html','forge/index.html','forge/forge.js','forge/audit-core.js','forge/promotion-core.js','forge/runner-core.js','forge/runner-worker.js','project/state.json','genesis-codehood/index.html','genesis-codehood/package.json','genesis-codehood/scratch/sim-core.js','genesis-codehood/scratch/alife.js','genesis-codehood/scratch/navigation.js','genesis-codehood/scratch/deep-world.js','genesis-codehood/scratch/deep-bind.js','genesis-codehood/scratch/deep-nav.js','genesis-codehood/scratch/deep-render.js','genesis-codehood/scratch/environment.js','genesis-codehood/scratch/organic-render.js','genesis-codehood/scratch/environment-worker.js','genesis-codehood/scratch/main.js','genesis-codehood/scratch/style.css','genesis-codehood/tests/scratch_sim.test.mjs','genesis-codehood/tests/scratch_alife.test.mjs','genesis-codehood/tests/scratch_environment.test.mjs','genesis-codehood/tests/scratch_navigation.test.mjs','genesis-codehood/tests/scratch_render.test.mjs','genesis-codehood/tests/deep_world.test.mjs','genesis-codehood/physical-creature-v1/index.html','genesis-codehood/physical-creature-v1/model.js','genesis-codehood/physical-creature-v1/model.test.mjs'];
const levels=['IMPLEMENTED','TESTED','CI_PASS','LIVE_TESTED','DEVICE_TESTED','VERIFIED'];
function checkState(state){return[
{id:'state.schema',label:'Project schema is 1',pass:state?.schema===1,actual:state?.schema},
{id:'state.project',label:'Project is GENESIS',pass:state?.project==='GENESIS',actual:state?.project},
{id:'state.phase',label:'Active phase is scratch-deep-world',pass:state?.phase==='scratch-deep-world',actual:state?.phase},
{id:'state.experience',label:'Active scratch route exists',pass:state?.active_experience?.route==='/genesis-codehood/',actual:state?.active_experience?.route||'missing'},
{id:'state.stack',label:'Active stack contains deep world/nav/render modules',pass:Array.isArray(state?.active_experience?.stack)&&['scratch/deep-world.js','scratch/deep-bind.js','scratch/deep-nav.js','scratch/deep-render.js','scratch/environment-worker.js'].every(x=>state.active_experience.stack.includes(x)),actual:state?.active_experience?.stack},
{id:'state.level',label:'Active experience verification is explicit',pass:levels.includes(state?.active_experience?.verification_level),actual:state?.active_experience?.verification_level},
{id:'state.deep',label:'Deep world state exists',pass:!!state?.deep_world,actual:state?.deep_world?.verification_level||'missing'},
{id:'state.deepLevel',label:'Deep world verification is explicit',pass:levels.includes(state?.deep_world?.verification_level),actual:state?.deep_world?.verification_level},
{id:'state.scratch',label:'Scratch engine state exists',pass:!!state?.scratch_engine,actual:state?.scratch_engine?.verification_level||'missing'},
{id:'state.legacy',label:'Legacy stack is archived',pass:state?.legacy_ecosystem_stack?.status==='ARCHIVED_NOT_LOADED_BY_ACTIVE_ROUTE',actual:state?.legacy_ecosystem_stack?.status||'missing'},
{id:'state.proof',label:'Physical Creature proof remains preserved',pass:state?.physical_creature_v1?.verification_level==='CI_PASS',actual:state?.physical_creature_v1?.verification_level||'missing'},
{id:'state.objective',label:'Active objective exists',pass:typeof state?.active_objective==='string'&&state.active_objective.length>0,actual:state?.active_objective||'missing'},
{id:'state.next',label:'Next gate exists',pass:typeof state?.next_gate==='string'&&state.next_gate.length>0,actual:state?.next_gate||'missing'}];}
function audit(input){const state=input?.state||null,files=input?.files||{},checks=[];for(const path of REQUIRED)checks.push({id:'file:'+path,label:path+' reachable',pass:files[path]===true,actual:files[path]===true?'present':'missing'});checks.push(...checkState(state));const pass=checks.every(c=>c.pass===true);return{schema:1,kind:'GENESIS_FORGE_CANONICAL_AUDIT',status:pass?'PASS':'FAIL',checks,summary:{passed:checks.filter(c=>c.pass).length,total:checks.length},project:state?.project||'UNKNOWN',phase:state?.phase||'UNKNOWN',active_route:state?.active_experience?.route||'UNKNOWN',verification_level:state?.active_experience?.verification_level||'UNKNOWN',deep_world_level:state?.deep_world?.verification_level||'UNKNOWN',stable_verified:state?.stable?.verified===true,active_objective:state?.active_objective||'UNKNOWN',next_gate:state?.next_gate||'UNKNOWN'};}
function failureDrill(input){const baseline=audit(input),brokenFiles={...(input?.files||{})},injected='genesis-codehood/scratch/deep-world.js';brokenFiles[injected]=false;const candidate=audit({state:input?.state||null,files:brokenFiles}),recovered=audit(input),pass=baseline.status==='PASS'&&candidate.status==='FAIL'&&recovered.status==='PASS';return{schema:1,kind:'GENESIS_FORGE_FAIL_CLOSED_DRILL',status:pass?'PASS':'FAIL',injected_failure:{type:'missing-required-file',target:injected},baseline_status:baseline.status,candidate_status:candidate.status,recovered_status:recovered.status,stable_preserved:recovered.status===baseline.status&&recovered.summary.passed===baseline.summary.passed,checks:[{id:'drill.baseline',label:'Baseline starts healthy',pass:baseline.status==='PASS',actual:baseline.status},{id:'drill.reject',label:'Missing active deep-world module is rejected',pass:candidate.status==='FAIL',actual:candidate.status},{id:'drill.recover',label:'Baseline recovers',pass:recovered.status==='PASS',actual:recovered.status}],baseline,candidate,recovered};}
function stableStringify(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(stableStringify).join(',')+']';return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+stableStringify(value[k])).join(',')+'}';}
async function sha256(text){if(typeof crypto!=='undefined'&&crypto.subtle){const bytes=new TextEncoder().encode(text),digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');}if(typeof require==='function'){const c=require('node:crypto');return c.createHash('sha256').update(text).digest('hex');}throw new Error('SHA-256 unavailable');}
async function receipt(result,meta={}){const body={...result,generated_at:new Date().toISOString(),environment:meta.environment||'unknown',source:meta.source||'unknown'};body.evidence_sha256=await sha256(stableStringify(body));return body;}
return{REQUIRED,audit,failureDrill,checkState,stableStringify,sha256,receipt};
});