const q=id=>document.getElementById(id);
let lastReceipt=null,lastDrill=null,lastPromotion=null,lastJob=null;
const REQUIRED=GenesisAudit.REQUIRED;
function set(id,state,detail=''){const el=q(id);if(!el)return;el.textContent=detail?`${state} · ${detail}`:state;el.className='status '+(state==='PASS'?'pass':state==='FAIL'?'fail':'unknown')}
async function reachable(path){try{const r=await fetch('../'+path+'?audit='+Date.now(),{cache:'no-store'});return r.ok}catch{return false}}
async function loadInputs(){const files={};for(const path of REQUIRED)files[path]=await reachable(path);let state=null;try{const r=await fetch('../project/state.json?audit='+Date.now(),{cache:'no-store'});if(r.ok)state=await r.json()}catch{}return{state,files}}
async function saveReceipt(key,result,source){const rec=await GenesisAudit.receipt(result,{environment:navigator.userAgent,source});localStorage.setItem(key,JSON.stringify(rec));return rec}
async function runAudit(){q('run').disabled=true;q('run').textContent='Running…';set('s1','RUNNING');set('s2','WAITING');set('s3','WAITING');set('s4','WAITING');const input=await loadInputs();const result=GenesisAudit.audit(input);set('s1',input.files['project/state.json']?'PASS':'FAIL');set('s2',result.status,`${result.summary.passed}/${result.summary.total}`);try{lastReceipt=await saveReceipt('genesis-forge:last-foundation-receipt',result,location.href+'#foundation');set('s3',result.status,lastReceipt.evidence_sha256.slice(0,12))}catch(err){lastReceipt={...result,receipt_error:String(err)};set('s3','FAIL','receipt hash unavailable')}set('s4',result.status==='PASS'?'READY':'BLOCKED',result.status==='PASS'?'failure drill unlocked':'repair foundation first');q('report').textContent=JSON.stringify(lastReceipt,null,2);q('run').disabled=false;q('run').textContent='Run foundation audit';refreshLast()}
async function runDrill(){q('drill').disabled=true;q('drill').textContent='Injecting controlled failure…';set('s5','RUNNING');set('s6','WAITING');const input=await loadInputs();const drill=GenesisAudit.failureDrill(input);try{lastDrill=await saveReceipt('genesis-forge:last-recovery-receipt',drill,location.href+'#fail-closed-drill');set('s5',drill.candidate_status==='FAIL'?'PASS':'FAIL',`candidate=${drill.candidate_status}`);set('s6',drill.status,drill.stable_preserved?'stable preserved':'preservation failed');q('report').textContent=JSON.stringify(lastDrill,null,2)}catch(err){set('s5','FAIL');set('s6','FAIL','receipt error');q('report').textContent=String(err)}q('drill').disabled=false;q('drill').textContent='Run controlled failure + recovery drill';refreshLast()}
async function runPromotion(){q('promote').disabled=true;q('promote').textContent='Checking real branches…';set('s7','RUNNING');set('s8','WAITING');try{const mainHas=await reachable('lab/experiment.json');const raw='https://raw.githubusercontent.com/Toymaker474/html5.github.io/genesis-lab/lab/experiment.json?ts='+Date.now();const r=await fetch(raw,{cache:'no-store'});if(!r.ok)throw new Error('genesis-lab manifest HTTP '+r.status);const lab=await r.json();const result=GenesisPromotion.evaluate({main_has_experiment:mainHas,lab_manifest:lab});lastPromotion=await saveReceipt('genesis-forge:last-promotion-receipt',result,location.href+'#stable-lab');set('s7',mainHas?'FAIL':'PASS',mainHas?'Stable contaminated':'Stable clean');set('s8',result.status,result.promotion_allowed?'candidate isolated':'promotion blocked');q('report').textContent=JSON.stringify(lastPromotion,null,2)}catch(err){set('s7','UNKNOWN','branch check unavailable');set('s8','BLOCKED','needs network/CI');q('report').textContent='Stable/Lab branch check could not complete:\n'+String(err)}q('promote').disabled=false;q('promote').textContent='Run real Stable ↔ Lab gate';refreshLast()}
function runWorkerJob(job,timeBudgetMs=2000){return new Promise(resolve=>{const request_id=(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random());const worker=new Worker('./runner-worker.js');let done=false;const finish=result=>{if(done)return;done=true;clearTimeout(timer);worker.terminate();resolve(result)};const timer=setTimeout(()=>finish({schema:1,kind:'GENESIS_FORGE_JOB_RESULT',job_id:job.id,status:'TIMEOUT',error:{code:'TIME_BUDGET_EXCEEDED',message:`Exceeded ${timeBudgetMs} ms`}}),timeBudgetMs);worker.onmessage=e=>{if(e.data?.type==='RESULT'&&e.data.request_id===request_id)finish(e.data.result)};worker.onerror=e=>finish({schema:1,kind:'GENESIS_FORGE_JOB_RESULT',job_id:job.id,status:'FAIL',error:{code:'WORKER_ERROR',message:e.message||'Worker failed'}});worker.postMessage({type:'RUN',request_id,job})})}
async function runJobs(){q('jobs').disabled=true;q('jobs').textContent='Running isolated jobs…';set('s9','RUNNING');set('s10','WAITING');set('s11','WAITING');const good=await runWorkerJob(GenesisRunner.JOBS['deterministic-kernel'],2000);const bad=await runWorkerJob(GenesisRunner.JOBS['expected-failure'],2000);const goodValid=GenesisRunner.validate(good).status==='PASS';const badValid=GenesisRunner.validate(bad).status==='PASS';const contractPass=good.status==='PASS'&&bad.status==='FAIL'&&goodValid&&badValid;const result={schema:1,kind:'GENESIS_FORGE_RUNNER_DRILL',status:contractPass?'PASS':'FAIL',good_job:good,bad_job:bad,checks:[{id:'runner.good',pass:good.status==='PASS',actual:good.status},{id:'runner.bad',pass:bad.status==='FAIL',actual:bad.status},{id:'runner.good_shape',pass:goodValid},{id:'runner.bad_shape',pass:badValid}]};try{lastJob=await saveReceipt('genesis-forge:last-runner-receipt',result,location.href+'#job-runner');set('s9',good.status,good.metrics?`${good.metrics.iterations} iterations`:'no metrics');set('s10',bad.status==='FAIL'?'PASS':'FAIL',`controlled=${bad.status}`);set('s11',result.status,lastJob.evidence_sha256.slice(0,12));q('report').textContent=JSON.stringify(lastJob,null,2)}catch(err){set('s11','FAIL','receipt error');q('report').textContent=String(err)}q('jobs').disabled=false;q('jobs').textContent='Run isolated job + failure fixture';refreshLast()}
function readLocal(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function refreshLast(){const keys=[['FOUNDATION','genesis-forge:last-foundation-receipt'],['RECOVERY','genesis-forge:last-recovery-receipt'],['PROMOTION','genesis-forge:last-promotion-receipt'],['RUNNER','genesis-forge:last-runner-receipt']];q('last').textContent=keys.map(([name,key])=>{const v=readLocal(key);return v?`${name} ${v.status} · ${v.generated_at}\n${v.evidence_sha256||'no hash'}`:`${name} no receipt`}).join('\n\n')}
q('run').onclick=runAudit;q('drill').onclick=runDrill;q('promote').onclick=runPromotion;q('jobs').onclick=runJobs;
q('copy').onclick=async()=>{const obj=lastJob||lastPromotion||lastDrill||lastReceipt||readLocal('genesis-forge:last-runner-receipt')||readLocal('genesis-forge:last-promotion-receipt')||readLocal('genesis-forge:last-recovery-receipt')||readLocal('genesis-forge:last-foundation-receipt');if(!obj){await runAudit();return}const text=JSON.stringify(obj,null,2);try{await navigator.clipboard.writeText(text);q('copy').textContent='Copied receipt';setTimeout(()=>q('copy').textContent='Copy latest evidence',1200)}catch{q('report').textContent=text+'\n\nClipboard unavailable; select text manually.'}};
q('clear').onclick=()=>{['genesis-forge:last-foundation-receipt','genesis-forge:last-recovery-receipt','genesis-forge:last-promotion-receipt','genesis-forge:last-runner-receipt'].forEach(k=>localStorage.removeItem(k));lastReceipt=lastDrill=lastPromotion=lastJob=null;q('report').textContent='Local receipts cleared. Canonical project files were not changed.';refreshLast()};
refreshLast();