import fs from 'node:fs';
import crypto from 'node:crypto';
const manifest=JSON.parse(fs.readFileSync('world-weather/weather.wasm.manifest.json','utf8'));
const names=['weather.wasm.part0.b64','weather.wasm.part1.b64','weather.wasm.part2.b64','weather.wasm.part3a.b64','weather.wasm.part3b.b64','weather.wasm.part3c.b64','weather.wasm.part3d.b64'];
const parts=names.map(n=>fs.readFileSync(`world-weather/${n}`,'utf8').trim()).join('');
const bytes=Buffer.from(parts,'base64');
const sha=crypto.createHash('sha256').update(bytes).digest('hex');
if(bytes.length!==manifest.compiled_bytes)throw new Error(`payload bytes ${bytes.length} != ${manifest.compiled_bytes}`);
if(sha!==manifest.sha256)throw new Error(`payload SHA ${sha} != ${manifest.sha256}`);
if(sha!=='d95d030df7ca6594d1d8641c483fec234d185d5ad7de6ef0ded56207b627929c')throw new Error('unexpected promoted compiler SHA');
const mod=await WebAssembly.compile(bytes);
const imports=WebAssembly.Module.imports(mod);
if(imports.length!==0)throw new Error(`committed payload imports ${JSON.stringify(imports)}`);
const {exports:e}=await WebAssembly.instantiate(mod,{});
if(e.genesis_weather_model_version()!==0x00010001)throw new Error('model version mismatch');
if(e.genesis_weather_width()!==192||e.genesis_weather_height()!==128)throw new Error('world resolution mismatch');
e.genesis_weather_reset(0x7721);e.genesis_weather_seed_river_basin();e.genesis_weather_seed_supercell(124,64);e.genesis_weather_step(6);
if(e.genesis_weather_cloud_cells()<=100||e.genesis_weather_rain_cells()<=20||e.genesis_weather_tornado_cells()<=0)throw new Error('native atmosphere/tornado browser payload gate failed');
e.genesis_weather_step(90);
if(e.genesis_weather_max_discharge()<=2600||e.genesis_weather_river_cells()<=0)throw new Error('native river browser payload gate failed');
const page=fs.readFileSync('world-weather/index.html','utf8');
const ui=fs.readFileSync('world-weather/weather-view.js','utf8');
for(const required of ['192×128','24,576','Native C++ → verified WASM'])if(!page.includes(required))throw new Error(`missing page truth label ${required}`);
for(const required of ['genesis_weather_cloud_at','genesis_weather_rain_at','genesis_weather_discharge_at','genesis_weather_tornado_at'])if(!ui.includes(required))throw new Error(`renderer is not reading native field ${required}`);
if(ui.includes('Math.random'))throw new Error('browser renderer must not invent stochastic simulation state');
console.log(JSON.stringify({model:'genesis-world-weather-v1',bytes:bytes.length,sha256:sha,imports:imports.length,resolution:'192x128',cells:24576,cloudCells:e.genesis_weather_cloud_cells(),riverCells:e.genesis_weather_river_cells(),maxDischarge:e.genesis_weather_max_discharge()}));
console.log('PASS GENESIS browser payload contract: exact compiler WASM and native-state-only world rendering inputs');
