import fs from 'node:fs';
import crypto from 'node:crypto';
const manifest=JSON.parse(fs.readFileSync('world-weather/weather3d.manifest.json','utf8'));
if(manifest.wasm_file!=='weather3d.wasm')throw new Error('browser must consume direct compiler-produced WASM');
const bytes=fs.readFileSync(`world-weather/${manifest.wasm_file}`);
const sha=crypto.createHash('sha256').update(bytes).digest('hex');
if(bytes.length!==13433||bytes.length!==manifest.wasm_bytes)throw new Error(`browser payload bytes=${bytes.length}`);
if(sha!=='91491be5228fd3724ffb173b11e769d574eda164b98e21d08fbbb40bb2f21db8'||sha!==manifest.wasm_sha256)throw new Error(`browser payload SHA=${sha}`);
const mod=await WebAssembly.compile(bytes);const imports=WebAssembly.Module.imports(mod);if(imports.length)throw new Error(`browser WASM has imports ${JSON.stringify(imports)}`);
const {exports:e}=await WebAssembly.instantiate(mod,{});
if(e.genesis_weather3d_model_version()!==0x00020001)throw new Error('browser native model version mismatch');
if(e.genesis_weather3d_width()!==96||e.genesis_weather3d_height()!==48||e.genesis_weather3d_depth()!==96)throw new Error('browser native volume not 96x48x96');
e.genesis_weather3d_reset(0x7721);e.genesis_weather3d_seed_river_basin();e.genesis_weather3d_seed_supercell(52,48);
if(e.genesis_weather3d_cloud_cells()<=3000||e.genesis_weather3d_tornado_cells()<=0)throw new Error('browser native storm semantics failed');
let vertical=0;for(let y=8;y<40;y++)if(e.genesis_weather3d_cloud_at(52,y,48)>700)vertical++;if(vertical<=8)throw new Error(`browser cloud is not volumetric: ${vertical}`);
const page=fs.readFileSync('world-weather/index.html','utf8');
const ui=fs.readFileSync('world-weather/weather3d-view.js','utf8');
for(const s of ['442,368 simulated atmosphere cells','96×48×96','C++/WASM','WEBGPU VOLUME','weather3d-view.js'])if(!page.includes(s))throw new Error(`missing active truth label ${s}`);
for(const s of ["weather3d.wasm", "getContext('webgpu')",'var<storage,read> atmo','boxHit(','cloudNormal(','genesis_weather3d_cloud_ptr','genesis_weather3d_tornado_ptr','genesis_weather3d_terrain_ptr','device.queue.writeBuffer'])if(!ui.includes(s))throw new Error(`missing true 3D browser mechanism ${s}`);
for(const forbidden of ["getContext('2d')",'weather-view.js','THREE.','three.js','babylon','Math.random','.wasm.part'])if(ui.includes(forbidden)||page.includes(forbidden))throw new Error(`forbidden flat/fake/legacy browser mechanism ${forbidden}`);
if(/from\s+['\"][^'\"]+['\"]/.test(ui))throw new Error('active 3D renderer must not import external JS libraries');
const shader=ui.match(/const WGSL=String\.raw`([\s\S]*?)`;/)?.[1];
if(!shader)throw new Error('WGSL source missing from active renderer');
if(/\b(?:let|var|const)\s+[A-Za-z_]\w*\s*=[^\n;]+,\s*[A-Za-z_]\w*\s*=/.test(shader))throw new Error('WGSL contains C++/JS-style comma multi-declaration rejected by Safari');
if(/\b1\.0\s*\/\s*rd\b/.test(shader))throw new Error('WGSL scalar/vector reciprocal is not explicit enough for portable validation');
if(!shader.includes('let ex=vec3<f32>(1.0,0.0,0.0);')||!shader.includes('let ey=vec3<f32>(0.0,1.0,0.0);')||!shader.includes('let ez=vec3<f32>(0.0,0.0,1.0);'))throw new Error('portable cloud gradient basis declarations missing');
const reserved=new Set(`NULL Self abstract active alignas alignof as asm asm_fragment async attribute auto await become cast catch class co_await co_return co_yield coherent column_major common compile compile_fragment concept const_cast consteval constexpr constinit crate debugger decltype delete demote demote_to_helper do dynamic_cast enum explicit export extends extern external fallthrough filter final finally friend from fxgroup get goto groupshared highp impl implements import inline instanceof interface layout lowp macro macro_rules match mediump meta mod module move mut mutable namespace new nil noexcept noinline nointerpolation non_coherent noncoherent noperspective null nullptr of operator package packoffset partition pass patch pixelfragment precise precision premerge priv protected pub public readonly ref regardless register reinterpret_cast require resource restrict self set shared sizeof smooth snorm static static_assert static_cast std subroutine super target template this thread_local throw trait try type typedef typeid typename typeof union unless unorm unsafe unsized use using varying virtual volatile wgsl where with writeonly yield`.split(/\s+/));
const lexical=shader.replace(/\/\/.*$/gm,' ').replace(/\/\*[\s\S]*?\*\//g,' ');
const reservedHits=[...new Set((lexical.match(/[A-Za-z_][A-Za-z0-9_]*/g)||[]).filter(token=>reserved.has(token)))];
if(reservedHits.length)throw new Error(`WGSL contains reserved word(s): ${reservedHits.join(', ')}`);
if(!shader.includes('let focusPoint=vec3<f32>(48.0,13.0,48.0);'))throw new Error('portable camera focus declaration missing');
console.log(JSON.stringify({model:manifest.model,bytes:bytes.length,sha256:sha,imports:imports.length,resolution:'96x48x96',cells:442368,verticalCloudCells:vertical,cloudCells:e.genesis_weather3d_cloud_cells(),tornadoCells:e.genesis_weather3d_tornado_cells(),wgslPortableDeclarations:true,wgslReservedWords:0}));
console.log('PASS GENESIS true 3D browser contract: direct compiler C++ WASM + WebGPU perspective volume; Canvas2D forbidden; Safari WGSL lexical regression guarded');