(()=>{'use strict';const $=id=>document.getElementById(id),canvas=$('view'),status=$('status'),hud=$('hud'),quality=$('quality'),brush=$('brush'),brushV=$('brushV'),cohesion=$('cohesion'),cohesionV=$('cohesionV');let worker=null,renderer=null,state=null,meta=null,tool='orbit',drag=false,lastX=0,lastY=0,busy=false,paused=false,renderFrames=0,renderTime=0,lastFrame=performance.now(),fps=0,wasmBytes=0;
function dims(){return quality.value.split('x').map(Number)}function setStatus(t,good=false){status.textContent=t;status.className=good?'good':'warn'}function fatal(msg){setStatus('RUNTIME BLOCKED');$('fatalText').textContent=msg;$('fatal').hidden=false;}
async function start(){if(worker)worker.terminate();renderer=null;state=null;meta=null;busy=false;$('fatal').hidden=true;const [w,h,d]=dims();setStatus('LOADING C++ → WASM');worker=new Worker('./worker.js?v=vol3-1');worker.onmessage=async ev=>{let m=ev.data||{};if(m.type==='fatal'){fatal(m.message);return;}if(m.type==='error'){fatal(m.message);return;}if(m.type==='ready'){wasmBytes=m.wasmBytes;try{renderer=await GenesisVolumeRenderer.create(canvas,w,h,d);setStatus('C++ WASM + WEBGPU · TRUE 3D',true);}catch(err){fatal('WebGPU 3D renderer failed: '+String(err?.message||err));}return;}if(m.type==='state'){state=new Uint32Array(m.buffer);meta=m.meta;busy=false;renderer?.updateState(state);if(!paused)step();}};worker.onerror=e=>fatal('Worker failed: '+(e.message||'unknown'));worker.postMessage({type:'init',w,h,d,seed:0x3d5a17,cohesion:+cohesion.value});}
function step(){if(!worker||busy||paused)return;busy=true;worker.postMessage({type:'step',iterations:1});}
function paint(ev){if(!renderer||tool==='orbit')return;let place=tool!=='carve',p=renderer.pick(ev.clientX,ev.clientY,place);if(!p)return;let kind={sand:1,water:2,rock:3,carve:4,wet:5}[tool];worker.postMessage({type:'paint',kind,x:p.x,y:p.y,z:p.z,radius:+brush.value});}
canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture?.(e.pointerId);paint(e);e.preventDefault()});canvas.addEventListener('pointermove',e=>{if(!drag)return;let dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;if(tool==='orbit')renderer?.orbit(dx,dy);else paint(e);e.preventDefault()});for(const n of ['pointerup','pointercancel','pointerleave'])canvas.addEventListener(n,()=>drag=false);canvas.addEventListener('wheel',e=>{renderer?.zoom(e.deltaY);e.preventDefault()},{passive:false});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));$('mode').textContent=tool.toUpperCase()});quality.onchange=start;brush.oninput=()=>brushV.textContent=brush.value;cohesion.oninput=()=>cohesionV.textContent=cohesion.value;$('reset').onclick=()=>worker?.postMessage({type:'reset'});$('camera').onclick=()=>renderer?.resetCamera();$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume':'Pause';if(!paused)step()};$('rain').onclick=()=>{if(!meta)return;worker?.postMessage({type:'paint',kind:2,x:Math.floor(meta.w*.70),y:Math.floor(meta.h*.78),z:Math.floor(meta.d*.35),radius:5})};$('dune').onclick=()=>{if(!meta)return;worker?.postMessage({type:'paint',kind:1,x:Math.floor(meta.w*.45),y:Math.floor(meta.h*.70),z:Math.floor(meta.d*.52),radius:6})};
function updateHud(){if(!meta)return;hud.innerHTML=`<span>${meta.w}×${meta.h}×${meta.d}</span><span>${meta.w*meta.h*meta.d} voxels</span><span>sand ${(meta.sandUnits/255).toFixed(0)} eq</span><span>water ${meta.waterVoxels}</span><span>erosion ${meta.erosion}</span><span>deposit ${meta.deposition}</span><span>${fps.toFixed(0)} fps</span><span>WASM ${(wasmBytes/1024).toFixed(1)}KB</span><span>${meta.invariant?'PASS':'FAIL'}</span>`;}
function frame(now){let dt=(now-lastFrame)/1000;lastFrame=now;renderFrames++;renderTime+=dt;if(renderTime>.5){fps=renderFrames/renderTime;renderFrames=0;renderTime=0;updateHud()}try{renderer?.render(now)}catch(err){fatal('Render failed: '+String(err?.message||err));renderer=null}requestAnimationFrame(frame)}brushV.textContent=brush.value;cohesionV.textContent=cohesion.value;start();requestAnimationFrame(frame);
})();
