(()=>{'use strict';
const WGSL=String.raw`
struct Params{grid:vec4f,camPos:vec4f,camRight:vec4f,camUp:vec4f,camForward:vec4f,render:vec4f,sun:vec4f};
@group(0) @binding(0) var<storage,read> cells:array<u32>;
@group(0) @binding(1) var<uniform> p:Params;
fn matAt(i:u32)->u32{return cells[i]&255u;} fn wetAt(i:u32)->f32{return f32((cells[i]>>8u)&255u)/255.0;} fn sedAt(i:u32)->f32{return f32((cells[i]>>16u)&255u)/255.0;}
fn indexOf(c:vec3u)->u32{return (c.y*u32(p.grid.z)+c.z)*u32(p.grid.x)+c.x;}
fn inside(c:vec3i)->bool{return all(c>=vec3i(0))&&c.x<i32(p.grid.x)&&c.y<i32(p.grid.y)&&c.z<i32(p.grid.z);}
fn hash31(v:vec3f)->f32{return fract(sin(dot(v,vec3f(12.9898,78.233,37.719)))*43758.5453);}
fn project(w:vec3f)->vec4f{let r=w-p.camPos.xyz;let x=dot(r,p.camRight.xyz);let y=dot(r,p.camUp.xyz);let z=max(.04,dot(r,p.camForward.xyz));let near=.05;let far=120.0;return vec4f(x/(p.render.y*p.render.x),y/p.render.y,(far/(far-near))*z-(near*far/(far-near)),z);}
fn tone(c:vec3f)->vec3f{let x=max(c*p.render.w,vec3f(0));return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),vec3f(0),vec3f(1));}
fn sky(ray:vec3f)->vec3f{let h=clamp(ray.y*.5+.5,0.0,1.0);var c=mix(vec3f(.34,.16,.075),vec3f(.035,.16,.31),smoothstep(.05,.75,h));c=mix(c,vec3f(.012,.035,.075),smoothstep(.72,1.0,h));let s=max(dot(ray,normalize(p.sun.xyz)),0.0);return c+vec3f(1.0,.54,.18)*pow(s,30.0)*.35+vec3f(1.0,.94,.80)*pow(s,1000.0)*4.5;}
struct SkyOut{@builtin(position)pos:vec4f,@location(0)uv:vec2f};@vertex fn skyVs(@builtin(vertex_index)i:u32)->SkyOut{var a=array<vec2f,3>(vec2f(-1,-1),vec2f(3,-1),vec2f(-1,3));var o:SkyOut;o.pos=vec4f(a[i],.9999,1);o.uv=a[i];return o;}@fragment fn skyFs(i:SkyOut)->@location(0)vec4f{let ray=normalize(p.camForward.xyz+p.camRight.xyz*i.uv.x*p.render.x*p.render.y+p.camUp.xyz*i.uv.y*p.render.y);return vec4f(tone(sky(ray)),1);}
fn faceNormal(f:u32)->vec3f{switch f{case 0u:{return vec3f(1,0,0);}case 1u:{return vec3f(-1,0,0);}case 2u:{return vec3f(0,1,0);}case 3u:{return vec3f(0,-1,0);}case 4u:{return vec3f(0,0,1);}default:{return vec3f(0,0,-1);}}}
fn faceCorner(f:u32,v:u32)->vec3f{var q=array<vec2f,6>(vec2f(-1,-1),vec2f(1,-1),vec2f(-1,1),vec2f(-1,1),vec2f(1,-1),vec2f(1,1));let u=q[v];switch f{case 0u:{return vec3f(.5,u.y*.5,-u.x*.5);}case 1u:{return vec3f(-.5,u.y*.5,u.x*.5);}case 2u:{return vec3f(u.x*.5,.5,-u.y*.5);}case 3u:{return vec3f(u.x*.5,-.5,u.y*.5);}case 4u:{return vec3f(u.x*.5,u.y*.5,.5);}default:{return vec3f(-u.x*.5,u.y*.5,-.5);}}}
struct VoxOut{@builtin(position)pos:vec4f,@location(0)world:vec3f,@location(1)n:vec3f,@location(2)@interpolate(flat) cell:vec3u,@location(3)@interpolate(flat) material:u32,@location(4)wet:f32,@location(5)sed:f32};
@vertex fn voxVs(@builtin(vertex_index)vid:u32,@builtin(instance_index)iid:u32)->VoxOut{let w=u32(p.grid.x);let d=u32(p.grid.z);let x=iid%w;let t=iid/w;let z=t%d;let y=t/d;let c=vec3u(x,y,z);let m=matAt(iid);let f=vid/6u;let local=faceCorner(f,vid%6u);let scale=p.grid.w;let center=(vec3f(f32(x),f32(y),f32(z))-vec3f(p.grid.x*.5,0,p.grid.z*.5))*scale;let world=center+local*scale;var o:VoxOut;o.pos=select(project(world),vec4f(2,2,2,1),m==0u);o.world=world;o.n=faceNormal(f);o.cell=c;o.material=m;o.wet=wetAt(iid);o.sed=sedAt(iid);return o;}
fn neighborMaterial(c:vec3u,n:vec3f)->u32{let q=vec3i(c)+vec3i(i32(n.x),i32(n.y),i32(n.z));if(!inside(q)){return 0u;}return matAt(indexOf(vec3u(q)));}
fn aboveMaterial(c:vec3u)->u32{if(c.y+1u>=u32(p.grid.y)){return 0u;}return matAt(indexOf(vec3u(c.x,c.y+1u,c.z)));}
fn shadow(c:vec3u)->f32{var occ=0.0;for(var k=1;k<=4;k++){let q=vec3i(c)+vec3i(k,k,(k+1)/2);if(inside(q)&&matAt(indexOf(vec3u(q)))!=0u){occ+=.16;}}return clamp(1.0-occ,.38,1.0);}
@fragment fn opaqueFs(i:VoxOut)->@location(0)vec4f{if(i.material==0u||i.material==2u){discard;}let nb=neighborMaterial(i.cell,i.n);if(nb!=0u&&nb!=2u){discard;}let rnd=hash31(floor(i.world*31.0));var n=normalize(i.n);if(i.material==1u){n=normalize(n+(vec3f(hash31(i.world*71.0),hash31(i.world*83.0),hash31(i.world*97.0))-.5)*.12);}let sun=normalize(p.sun.xyz);let ndl=max(dot(n,sun),0.0);let sh=shadow(i.cell);let view=normalize(p.camPos.xyz-i.world);let halfv=normalize(sun+view);var base=vec3f(.16,.15,.14);var rough=.9;if(i.material==1u){base=mix(vec3f(.38,.18,.055),vec3f(.95,.62,.20),rnd);base=mix(base,vec3f(.18,.09,.025),i.wet*.72);rough=mix(.92,.62,i.wet);}else if(i.material==3u){base=mix(vec3f(.065,.06,.058),vec3f(.25,.23,.20),rnd*.45);}let spec=pow(max(dot(n,halfv),0.0),mix(22.0,90.0,1.0-rough))*.18;var c=base*(.17+1.05*ndl*sh)+base*vec3f(.12,.18,.24)*(.35+.35*max(n.y,0.0))+spec*vec3f(1,.78,.48);let dist=distance(p.camPos.xyz,i.world);c=mix(c,vec3f(.16,.21,.24),clamp(1.0-exp(-dist*.025),0.0,.68));return vec4f(tone(c),1);}
@fragment fn waterFs(i:VoxOut)->@location(0)vec4f{if(i.material!=2u){discard;}if(neighborMaterial(i.cell,i.n)==2u){discard;}var n=normalize(i.n);let t=p.render.z;n=normalize(n+vec3f(sin(i.world.z*7.0+t*1.6),0,cos(i.world.x*6.0-t*1.1))*.045);let view=normalize(p.camPos.xyz-i.world);let sun=normalize(p.sun.xyz);let fres=pow(1.0-max(dot(n,view),0.0),5.0);let spec=pow(max(dot(n,normalize(view+sun)),0.0),150.0)*2.5;let muddy=i.sed;var c=mix(vec3f(.018,.16,.22),vec3f(.18,.105,.045),muddy*.72);c=mix(c,sky(reflect(-view,n)),.18+.58*fres)+spec*vec3f(1,.82,.58);return vec4f(tone(c),.43+.30*fres);}
struct GrainOut{@builtin(position)pos:vec4f,@location(0)uv:vec2f,@location(1)wet:f32,@location(2)alive:f32,@location(3)rnd:f32};
fn quad(v:u32)->vec2f{var q=array<vec2f,6>(vec2f(-1,-1),vec2f(1,-1),vec2f(-1,1),vec2f(-1,1),vec2f(1,-1),vec2f(1,1));return q[v];}
@vertex fn grainVs(@builtin(vertex_index)vid:u32,@builtin(instance_index)iid:u32)->GrainOut{let w=u32(p.grid.x);let d=u32(p.grid.z);let x=iid%w;let t=iid/w;let z=t%d;let y=t/d;let m=matAt(iid);let above=aboveMaterial(vec3u(x,y,z));let alive=select(0.0,1.0,m==1u&&above==0u);let r=hash31(vec3f(f32(x),f32(y),f32(z))*vec3f(1.7,2.3,3.1));let s=p.grid.w;let center=(vec3f(f32(x),f32(y)+.52,f32(z))-vec3f(p.grid.x*.5,0,p.grid.z*.5))*s+(vec3f(hash31(vec3f(f32(x),f32(y),f32(z))+1.0),0,hash31(vec3f(f32(z),f32(x),f32(y))+5.0))-.5)*vec3f(s*.65,0,s*.65);let q=quad(vid);let size=s*(.07+.04*r);let world=center+(p.camRight.xyz*q.x+p.camUp.xyz*q.y)*size;var o:GrainOut;o.pos=select(project(world),vec4f(2,2,2,1),alive<.5);o.uv=q;o.wet=wetAt(iid);o.alive=alive;o.rnd=r;return o;}
@fragment fn grainFs(i:GrainOut)->@location(0)vec4f{if(i.alive<.5){discard;}let rr=length(i.uv);if(rr>1.0){discard;}let a=1.0-smoothstep(.45,1.0,rr);let dry=mix(vec3f(.48,.21,.055),vec3f(1.0,.73,.30),i.rnd);let c=mix(dry,vec3f(.16,.075,.02),i.wet*.72);return vec4f(tone(c*1.18),a*.9);}`;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const norm=v=>{let l=Math.hypot(...v)||1;return v.map(x=>x/l)};const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
class Renderer{
 constructor(canvas,device,context,format,w,h,d){this.canvas=canvas;this.device=device;this.context=context;this.format=format;this.w=w;this.h=h;this.d=d;this.kind='WebGPU volumetric 3D';this.state=null;this.scale=.19;this.yaw=.72;this.pitch=.48;this.distance=Math.max(9,w*this.scale*1.15);this.target=[0,h*this.scale*.22,0];this.depth=null;this.depthView=null;this.lost=false;this.uniform=device.createBuffer({size:112,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});this.cells=device.createBuffer({size:w*h*d*4,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});const module=device.createShaderModule({code:WGSL,label:'GENESIS volumetric material shader'});const bgl=device.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,buffer:{type:'read-only-storage'}},{binding:1,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}}]});let layout=device.createPipelineLayout({bindGroupLayouts:[bgl]});this.sky=device.createRenderPipeline({layout,vertex:{module,entryPoint:'skyVs'},fragment:{module,entryPoint:'skyFs',targets:[{format}]},primitive:{topology:'triangle-list'}});this.opaque=device.createRenderPipeline({layout,vertex:{module,entryPoint:'voxVs'},fragment:{module,entryPoint:'opaqueFs',targets:[{format}]},primitive:{topology:'triangle-list',cullMode:'back'},depthStencil:{format:'depth24plus',depthWriteEnabled:true,depthCompare:'less'}});const blend={color:{srcFactor:'src-alpha',dstFactor:'one-minus-src-alpha',operation:'add'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha',operation:'add'}};this.water=device.createRenderPipeline({layout,vertex:{module,entryPoint:'voxVs'},fragment:{module,entryPoint:'waterFs',targets:[{format,blend}]},primitive:{topology:'triangle-list',cullMode:'back'},depthStencil:{format:'depth24plus',depthWriteEnabled:false,depthCompare:'less-equal'}});this.grains=device.createRenderPipeline({layout,vertex:{module,entryPoint:'grainVs'},fragment:{module,entryPoint:'grainFs',targets:[{format,blend}]},primitive:{topology:'triangle-list'},depthStencil:{format:'depth24plus',depthWriteEnabled:false,depthCompare:'less-equal'}});this.bind=device.createBindGroup({layout:bgl,entries:[{binding:0,resource:{buffer:this.cells}},{binding:1,resource:{buffer:this.uniform}}]});device.lost.then(()=>this.lost=true);}
 static async create(canvas,w,h,d){if(!navigator.gpu)throw new Error('WebGPU unavailable');let adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter)throw new Error('No WebGPU adapter');let device=await adapter.requestDevice();let context=canvas.getContext('webgpu');if(!context)throw new Error('WebGPU canvas unavailable');let format=navigator.gpu.getPreferredCanvasFormat();context.configure({device,format,alphaMode:'opaque'});let r=new Renderer(canvas,device,context,format,w,h,d);device.pushErrorScope('validation');r.render(performance.now());await device.queue.onSubmittedWorkDone();let err=await device.popErrorScope();if(err)throw new Error(err.message||String(err));return r;}
 resize(){let dpr=Math.min(devicePixelRatio||1,1.7),w=Math.max(1,Math.round(this.canvas.clientWidth*dpr)),h=Math.max(1,Math.round(this.canvas.clientHeight*dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.depth?.destroy();this.depth=this.device.createTexture({size:[w,h],format:'depth24plus',usage:GPUTextureUsage.RENDER_ATTACHMENT});this.depthView=this.depth.createView();}}
 updateState(a){this.state=a;this.device.queue.writeBuffer(this.cells,0,a);}
 basis(){let cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),pos=[this.target[0]+this.distance*cp*sy,this.target[1]+this.distance*sp,this.target[2]+this.distance*cp*cy],f=norm([this.target[0]-pos[0],this.target[1]-pos[1],this.target[2]-pos[2]]),r=norm(cross(f,[0,1,0])),u=norm(cross(r,f));return{pos,f,r,u};}
 params(now){let b=this.basis(),aspect=this.canvas.width/Math.max(1,this.canvas.height),fov=Math.tan(.58);let a=new Float32Array(28);a.set([this.w,this.h,this.d,this.scale],0);a.set([...b.pos,0],4);a.set([...b.r,0],8);a.set([...b.u,0],12);a.set([...b.f,0],16);a.set([aspect,fov,now*.001,1.15],20);a.set([.48,.84,.26,1],24);return a;}
 render(now){this.resize();if(!this.depthView)return;this.device.queue.writeBuffer(this.uniform,0,this.params(now));let enc=this.device.createCommandEncoder(),view=this.context.getCurrentTexture().createView(),pass=enc.beginRenderPass({colorAttachments:[{view,clearValue:{r:.01,g:.025,b:.045,a:1},loadOp:'clear',storeOp:'store'}],depthStencilAttachment:{view:this.depthView,depthClearValue:1,depthLoadOp:'clear',depthStoreOp:'store'}});pass.setBindGroup(0,this.bind);pass.setPipeline(this.sky);pass.draw(3);let count=this.w*this.h*this.d;pass.setPipeline(this.opaque);pass.draw(36,count);pass.setPipeline(this.grains);pass.draw(6,count);pass.setPipeline(this.water);pass.draw(36,count);pass.end();this.device.queue.submit([enc.finish()]);}
 orbit(dx,dy){this.yaw-=dx*.006;this.pitch=clamp(this.pitch-dy*.005,.12,1.22);}zoom(dy){this.distance=clamp(this.distance*Math.exp(dy*.0012),4,38);}resetCamera(){this.yaw=.72;this.pitch=.48;this.distance=Math.max(9,this.w*this.scale*1.15);}
 pick(clientX,clientY,place=false){if(!this.state)return null;let rect=this.canvas.getBoundingClientRect(),nx=((clientX-rect.left)/rect.width)*2-1,ny=1-((clientY-rect.top)/rect.height)*2,b=this.basis(),aspect=rect.width/Math.max(1,rect.height),t=Math.tan(.58),dir=norm([b.f[0]+b.r[0]*nx*aspect*t+b.u[0]*ny*t,b.f[1]+b.r[1]*nx*aspect*t+b.u[1]*ny*t,b.f[2]+b.r[2]*nx*aspect*t+b.u[2]*ny*t]);let prev=null,step=this.scale*.32,max=80;for(let s=.1;s<max;s+=step){let wx=b.pos[0]+dir[0]*s,wy=b.pos[1]+dir[1]*s,wz=b.pos[2]+dir[2]*s,x=Math.floor(wx/this.scale+this.w*.5+.5),y=Math.floor(wy/this.scale+.5),z=Math.floor(wz/this.scale+this.d*.5+.5);if(x<0||x>=this.w||y<0||y>=this.h||z<0||z>=this.d)continue;let i=(y*this.d+z)*this.w+x,m=this.state[i]&255;if(m!==0)return place&&prev?prev:{x,y,z};prev={x,y,z};}return null;}
}
globalThis.GenesisVolumeRenderer=Renderer;
})();
