'use strict';
let wasm=null,e=null,memory=null,ready=false,lastInit={w:40,h:28,d:40,seed:0x3d5a17,cohesion:72};const queue=[];
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha256Bytes(bytes){return hex(await crypto.subtle.digest('SHA-256',bytes));}
async function loadVerifiedWasm(){const mr=await fetch('./solver.v3.manifest.json?v=projection-v1',{cache:'no-store'});if(!mr.ok)throw new Error('WASM manifest HTTP '+mr.status);const m=await mr.json();let joined='';for(const p of m.parts){const r=await fetch('./'+p.file+'?v=projection-v1',{cache:'no-store'});if(!r.ok)throw new Error(p.file+' HTTP '+r.status);const t=(await r.text()).trim();if(t.length!==p.chars)throw new Error(p.file+' length mismatch');const textHash=await sha256Bytes(new TextEncoder().encode(t));if(textHash!==p.sha256)throw new Error(p.file+' SHA mismatch');joined+=t;}if(joined.length!==m.base64_chars)throw new Error('WASM base64 length mismatch');const joinedHash=await sha256Bytes(new TextEncoder().encode(joined));if(joinedHash!==m.base64_sha256)throw new Error('WASM base64 SHA mismatch');const bin=Uint8Array.from(atob(joined),c=>c.charCodeAt(0));if(bin.byteLength!==m.decoded_bytes)throw new Error('WASM byte length mismatch');if(await sha256Bytes(bin)!==m.decoded_sha256)throw new Error('WASM decoded SHA mismatch');return{bin,manifest:m};}
function meta(){return{w:e.genesis_width(),h:e.genesis_height(),d:e.genesis_depth(),step:e.genesis_step_index()>>>0,hash:e.genesis_hash()>>>0,sandUnits:e.genesis_sand_mass_units()>>>0,waterVoxels:e.genesis_water_cells()>>>0,waterMomentum:e.genesis_water_momentum()>>>0,pressureSum:e.genesis_pressure_sum()>>>0,fluidDivBefore:e.genesis_fluid_divergence_before()>>>0,fluidDivAfter:e.genesis_fluid_divergence_after()>>>0,fluidKinetic:e.genesis_fluid_kinetic_energy()>>>0,fluidMomentumX:e.genesis_fluid_momentum_x()|0,fluidMomentumY:e.genesis_fluid_momentum_y()|0,fluidMomentumZ:e.genesis_fluid_momentum_z()|0,sandMoves:e.genesis_sand_moves()>>>0,waterMoves:e.genesis_water_moves()>>>0,erosion:e.genesis_erosion_events()>>>0,deposition:e.genesis_deposition_events()>>>0,invariant:e.genesis_invariant()===1};}
function emit(){const ptr=e.genesis_pack()>>>0,count=e.genesis_cell_count()>>>0,src=new Uint32Array(memory.buffer,ptr,count),out=new Uint32Array(src);postMessage({type:'state',buffer:out.buffer,meta:meta()},[out.buffer]);}
function init(o=lastInit){lastInit={w:o.w||40,h:o.h||28,d:o.d||40,seed:(o.seed>>>0)||0x3d5a17,cohesion:Math.max(0,Math.min(100,o.cohesion|0||72))};e.genesis_init(lastInit.w,lastInit.h,lastInit.d,lastInit.seed,lastInit.cohesion);e.genesis_seed_scene();emit();}
function handle(m){if(m.type==='init')init(m);else if(m.type==='step'){e.genesis_step(Math.max(1,Math.min(4,m.iterations|0||1)));emit();}else if(m.type==='paint'){e.genesis_paint(m.kind|0,m.x|0,m.y|0,m.z|0,Math.max(1,m.radius|0||2));emit();}else if(m.type==='impulse'){e.genesis_impulse_water(m.x|0,m.y|0,m.z|0,Math.max(1,m.radius|0||2),m.ix|0,m.iy|0,m.iz|0);emit();}else if(m.type==='reset')init(lastInit);}
onmessage=ev=>{const m=ev.data||{};if(!ready){queue.push(m);return;}try{handle(m);}catch(err){postMessage({type:'error',message:String(err?.stack||err)});}};
(async()=>{try{const{bin,manifest}=await loadVerifiedWasm();const result=await WebAssembly.instantiate(bin,{});wasm=result.instance;e=wasm.exports;memory=e.memory;if((e.genesis_model_version()>>>0)!==0x00040001)throw new Error('WASM model version mismatch');for(const name of ['genesis_fluid_divergence_before','genesis_fluid_divergence_after','genesis_fluid_kinetic_energy','genesis_impulse_water'])if(typeof e[name]!=='function')throw new Error('missing native projection export '+name);ready=true;postMessage({type:'ready',wasmBytes:bin.byteLength,wasmSha256:manifest.decoded_sha256,modelVersion:e.genesis_model_version()>>>0});while(queue.length)handle(queue.shift());}catch(err){postMessage({type:'fatal',message:'C++ WebAssembly failed: '+String(err?.message||err)});}})();
