'use strict';
let wasm=null,e=null,memory=null,ready=false,lastInit={w:40,h:28,d:40,seed:0x3d5a17,cohesion:72};
const queue=[];
function meta(){return{w:e.genesis_width(),h:e.genesis_height(),d:e.genesis_depth(),step:e.genesis_step_index()>>>0,hash:e.genesis_hash()>>>0,sandUnits:e.genesis_sand_mass_units()>>>0,waterVoxels:e.genesis_water_cells()>>>0,sandMoves:e.genesis_sand_moves()>>>0,waterMoves:e.genesis_water_moves()>>>0,erosion:e.genesis_erosion_events()>>>0,deposition:e.genesis_deposition_events()>>>0,invariant:e.genesis_invariant()===1};}
function emit(){const ptr=e.genesis_pack()>>>0,count=e.genesis_cell_count()>>>0,src=new Uint32Array(memory.buffer,ptr,count),out=new Uint32Array(src);postMessage({type:'state',buffer:out.buffer,meta:meta()},[out.buffer]);}
function init(o=lastInit){lastInit={w:o.w||40,h:o.h||28,d:o.d||40,seed:(o.seed>>>0)||0x3d5a17,cohesion:Math.max(0,Math.min(100,o.cohesion|0||72))};e.genesis_init(lastInit.w,lastInit.h,lastInit.d,lastInit.seed,lastInit.cohesion);e.genesis_seed_scene();emit();}
function handle(m){if(m.type==='init')init(m);else if(m.type==='step'){e.genesis_step(Math.max(1,Math.min(4,m.iterations|0||1)));emit();}else if(m.type==='paint'){e.genesis_paint(m.kind|0,m.x|0,m.y|0,m.z|0,Math.max(1,m.radius|0||2));emit();}else if(m.type==='reset')init(lastInit);}
onmessage=ev=>{const m=ev.data||{};if(!ready){queue.push(m);return;}try{handle(m);}catch(err){postMessage({type:'error',message:String(err?.stack||err)});}};
(async()=>{try{const response=await fetch('./solver.v1.wasm.b64?v=ci-31317006965',{cache:'no-store'});if(!response.ok)throw new Error('WASM payload HTTP '+response.status);const text=await response.text(),bin=Uint8Array.from(atob(text.trim()),c=>c.charCodeAt(0));const result=await WebAssembly.instantiate(bin,{});wasm=result.instance;e=wasm.exports;memory=e.memory;if((e.genesis_model_version()>>>0)!==0x00030001)throw new Error('WASM model version mismatch');ready=true;postMessage({type:'ready',wasmBytes:bin.byteLength});while(queue.length)handle(queue.shift());}catch(err){postMessage({type:'fatal',message:'C++ WebAssembly failed: '+String(err?.message||err)});}})();
