const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function key(x,y){return x+','+y}
function chaikin(points,passes=2){let p=points;for(let n=0;n<passes;n++){if(p.length<4)break;const q=[];for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length];q.push([a[0]*.75+b[0]*.25,a[1]*.75+b[1]*.25],[a[0]*.25+b[0]*.75,a[1]*.25+b[1]*.75])}p=q}return p}
export function boundaryLoops(deep,predicate){const edges=[],C=deep.cols,R=deep.rows,has=(x,y)=>x>=0&&x<C&&y>=0&&y<R&&predicate(x,y,deep.idx(x,y));for(let y=0;y<R;y++)for(let x=0;x<C;x++){if(!has(x,y))continue;if(!has(x,y-1))edges.push([[x,y],[x+1,y]]);if(!has(x+1,y))edges.push([[x+1,y],[x+1,y+1]]);if(!has(x,y+1))edges.push([[x+1,y+1],[x,y+1]]);if(!has(x-1,y))edges.push([[x,y+1],[x,y]])}
 const byStart=new Map();for(const e of edges){const k=key(e[0][0],e[0][1]);if(!byStart.has(k))byStart.set(k,[]);byStart.get(k).push(e)}const loops=[];while(edges.length){let e=edges.pop();if(!e||e.used)continue;e.used=true;const loop=[e[0],e[1]],start=key(e[0][0],e[0][1]);let end=key(e[1][0],e[1][1]),guard=0;while(end!==start&&guard++<20000){const list=byStart.get(end)||[];let next=null;for(const q of list)if(!q.used){next=q;break}if(!next)break;next.used=true;loop.push(next[1]);end=key(next[1][0],next[1][1])}if(loop.length>4&&end===start)loops.push(loop)}return loops}
function drawLoops(ctx,deep,loops,view,fill,stroke=null,alpha=1,smoothPasses=2){ctx.save();ctx.globalAlpha=alpha;ctx.beginPath();for(const raw of loops){const pts=chaikin(raw,smoothPasses);if(!pts.length)continue;ctx.moveTo(view.sx(pts[0][0]*deep.cell),view.sy(pts[0][1]*deep.cell));for(let i=1;i<pts.length;i++)ctx.lineTo(view.sx(pts[i][0]*deep.cell),view.sy(pts[i][1]*deep.cell));ctx.closePath()}ctx.fillStyle=fill;ctx.fill('evenodd');if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=Math.max(.7,view.cam.z);ctx.stroke()}ctx.restore()}
export function drawDeepTerrain(ctx,deep,view){
 const solid=boundaryLoops(deep,(x,y,i)=>deep.mat[i]!==0),g=ctx.createLinearGradient(0,0,0,view.H);g.addColorStop(0,'#48564a');g.addColorStop(.28,'#26372f');g.addColorStop(.72,'#111b18');g.addColorStop(1,'#060a08');drawLoops(ctx,deep,solid,view,g,'rgba(118,145,126,.18)',1,3);
 const mats=[{id:3,c:'rgba(153,132,86,.31)'},{id:4,c:'rgba(111,83,68,.28)'},{id:5,c:'rgba(111,127,116,.22)'},{id:6,c:'rgba(47,57,56,.44)'},{id:7,c:'rgba(74,89,54,.28)'}];for(const m of mats){const loops=boundaryLoops(deep,(x,y,i)=>deep.mat[i]===m.id);drawLoops(ctx,deep,loops,view,m.c,null,1,2)}
 ctx.save();ctx.globalCompositeOperation='screen';for(let y=2;y<deep.rows-2;y+=3)for(let x=2;x<deep.cols-2;x+=3){const i=deep.idx(x,y);if(deep.mat[i]===0)continue;const sup=deep.support[i],wet=deep.moisture[i];if(sup>.82&&wet<.4)continue;const px=view.sx(deep.wx(x)),py=view.sy(deep.wy(y));if(px<-30||px>view.W+30||py<-30||py>view.H+30)continue;ctx.fillStyle=`rgba(${wet>.65?116:91},${wet>.65?128:106},${wet>.65?111:94},${clamp((1-sup)*.035+wet*.018,.008,.055)})`;ctx.beginPath();ctx.arc(px,py,Math.max(.5,deep.cell*.16*view.cam.z),0,Math.PI*2);ctx.fill()}ctx.restore();
}
export function drawDeepWater(ctx,deep,view){const loops=boundaryLoops(deep,(x,y,i)=>deep.mat[i]===0&&deep.water[i]>.035);if(!loops.length)return;const g=ctx.createLinearGradient(0,0,0,view.H);g.addColorStop(0,'rgba(129,215,214,.66)');g.addColorStop(.45,'rgba(38,126,144,.66)');g.addColorStop(1,'rgba(5,46,62,.9)');drawLoops(ctx,deep,loops,view,g,'rgba(207,244,235,.42)',1,3);ctx.save();ctx.globalCompositeOperation='screen';for(let y=1;y<deep.rows-1;y+=2)for(let x=1;x<deep.cols-1;x+=2){const i=deep.idx(x,y),w=deep.water[i];if(w<.12)continue;const sp=Math.hypot(deep.waterVX[i],deep.waterVY[i]);if(sp<.04)continue;const px=view.sx(deep.wx(x)),py=view.sy(deep.wy(y)),len=clamp(sp*.55,2,11)*view.cam.z,ang=Math.atan2(deep.waterVY[i],deep.waterVX[i]);ctx.strokeStyle=`rgba(219,250,242,${clamp(.05+sp*.012,.05,.2)})`;ctx.lineWidth=Math.max(.55,.7*view.cam.z);ctx.beginPath();ctx.moveTo(px-Math.cos(ang)*len*.5,py-Math.sin(ang)*len*.5);ctx.quadraticCurveTo(px,py-len*.12,px+Math.cos(ang)*len*.5,py+Math.sin(ang)*len*.5);ctx.stroke()}ctx.restore()}
export function drawDeepAtmosphere(ctx,deep,view){ctx.save();ctx.globalCompositeOperation='screen';for(let y=2;y<deep.rows-2;y+=4)for(let x=2;x<deep.cols-2;x+=4){const i=deep.idx(x,y);if(deep.mat[i]!==0)continue;const co=deep.co2[i],v=deep.vapor[i];if(co<.004&&v<.009)continue;const px=view.sx(deep.wx(x)),py=view.sy(deep.wy(y)),r=deep.cell*(1.5+clamp(co*25+v*18,0,2))*view.cam.z;if(px<-r||px>view.W+r||py<-r||py>view.H+r)continue;const gr=ctx.createRadialGradient(px,py,0,px,py,r);gr.addColorStop(0,co>.015?`rgba(94,72,61,${clamp(co*1.7,.012,.08)})`:`rgba(117,158,152,${clamp(v*2.5,.012,.07)})`);gr.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=gr;ctx.fillRect(px-r,py-r,r*2,r*2)}ctx.restore()}
export const DEEP_RENDER_META={cellsVisible:false,terrain:'boundary extraction + Chaikin-smoothed closed contours',liquid:'contours extracted from simulated liquid occupancy',simpleCellRects:false,preRenderedSprites:false};