const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class Heap{constructor(){this.a=[]}push(n){const a=this.a;a.push(n);let i=a.length-1;while(i){const p=(i-1)>>1;if(a[p].f<=n.f)break;a[i]=a[p];i=p}a[i]=n}pop(){const a=this.a;if(!a.length)return null;const root=a[0],last=a.pop();if(a.length){let i=0;while(1){let l=i*2+1,r=l+1;if(l>=a.length)break;let c=r<a.length&&a[r].f<a[l].f?r:l;if(a[c].f>=last.f)break;a[i]=a[c];i=c}a[i]=last}return root}get size(){return this.a.length}}
export function walkable(deep,x,y,profile={}){if(!deep.valid(x,y)||deep.isSolid(x,y))return false;const below=y+1>=deep.rows?true:deep.isSolid(x,y+1);const cling=profile.cling&&([[-1,0],[1,0],[0,-1],[0,1]].some(([dx,dy])=>deep.valid(x+dx,y+dy)&&deep.isSolid(x+dx,y+dy)));return below||cling}
function hazard(deep,x,y){const i=deep.idx(x,y),w=deep.water[i],co=deep.co2[i],t=deep.temp[i];return Math.max(0,w-.3)*1.8+Math.max(0,co-.01)*30+Math.max(0,t-42)*.08+Math.max(0,4-t)*.08}
export function planCellPath(deep,start,goal,opts={}){
 const s=deep.nearestWalkable(start.x,start.y,opts.snap??10),g=deep.nearestWalkable(goal.x,goal.y,opts.snap??12);if(!s||!g)return{reachable:false,points:[],expanded:0,reason:'no_walkable_endpoint'};
 const C=deep.cols,N=deep.N,startI=deep.idx(s.x,s.y),goalI=deep.idx(g.x,g.y),gScore=new Float32Array(N);gScore.fill(Infinity);const came=new Int32Array(N);came.fill(-1);const closed=new Uint8Array(N),open=new Heap(),h=(x,y)=>Math.abs(x-g.x)+Math.abs(y-g.y);gScore[startI]=0;open.push({i:startI,x:s.x,y:s.y,f:h(s.x,s.y)});let expanded=0,found=false,max=opts.maxExpanded??18000;
 const dirs=[[1,0,1],[-1,0,1],[1,-1,1.45],[-1,-1,1.45],[1,1,1.2],[-1,1,1.2],[0,-1,1.6],[0,1,1.35]];
 while(open.size&&expanded<max){const cur=open.pop();if(closed[cur.i])continue;closed[cur.i]=1;expanded++;if(cur.i===goalI){found=true;break}for(const [dx,dy,base]of dirs){const x=cur.x+dx,y=cur.y+dy;if(!walkable(deep,x,y,opts.profile))continue;if(Math.abs(dy)>0&&Math.abs(dx)>0&&!walkable(deep,cur.x+dx,cur.y,opts.profile)&&!walkable(deep,cur.x,cur.y+dy,opts.profile))continue;const ni=deep.idx(x,y);if(closed[ni])continue;let extra=hazard(deep,x,y);if(dy<0)extra+=.45;if(deep.water[ni]>.8&&!opts.profile?.swim)extra+=4;const ng=gScore[cur.i]+base+extra;if(ng<gScore[ni]){gScore[ni]=ng;came[ni]=cur.i;open.push({i:ni,x,y,f:ng+h(x,y)})}}
 }
 if(!found)return{reachable:false,points:[],expanded,reason:'search_exhausted'};
 const cells=[];let at=goalI;while(at!==-1){const y=(at/C)|0,x=at-y*C;cells.push({x,y,wx:deep.wx(x),wy:deep.wy(y)});if(at===startI)break;at=came[at]}cells.reverse();
 const points=[];for(let i=0;i<cells.length;i++){const a=cells[Math.max(0,i-1)],b=cells[i],c=cells[Math.min(cells.length-1,i+1)],cross=(b.x-a.x)*(c.y-b.y)-(b.y-a.y)*(c.x-b.x);if(i===0||i===cells.length-1||cross!==0||i%4===0)points.push(b)}
 return{reachable:true,points,expanded,cost:gScore[goalI],start:s,goal:g};
}
export function followCellPath(state,path,body,dt){if(!path?.reachable||!path.points.length)return{heading:0,target:{x:body.x,y:body.y},speed:0,index:0};state.index=clamp(state.index??0,0,path.points.length-1);while(state.index<path.points.length-1&&Math.hypot(path.points[state.index].wx-body.x,path.points[state.index].wy-body.y)<18)state.index++;const look=path.points[Math.min(path.points.length-1,state.index+1)]||path.points[state.index],dx=look.wx-body.x,dy=look.wy-body.y,heading=Math.abs(dx)<3?0:Math.sign(dx);state.steer=(state.steer??0)+(heading-(state.steer??0))*(1-Math.exp(-dt*5));state.speed=(state.speed??0)+(1-(state.speed??0))*(1-Math.exp(-dt*2.8));return{heading:Math.abs(state.steer)>.35?Math.sign(state.steer):0,target:{x:look.wx,y:look.wy},vertical:dy,speed:state.speed,index:state.index}}
export const DEEP_NAV_META={kind:'A* over persistent 2D material-volume walk cells',straightLineTargeting:false,usesWorldCollisionCells:true,hazards:['water','carbon_dioxide','temperature'],supportsCaveRoutes:true};