import {MAT,MAT_INFO} from './deep-world.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function h(x,y,s){let n=(Math.imul(x,73856093)^Math.imul(y,19349663)^Math.imul(s,83492791))>>>0;n^=n>>>13;n=Math.imul(n,1274126177);return((n^(n>>>16))>>>0)/4294967295}
function carveEllipse(deep,cx,cy,rx,ry){for(let y=Math.max(1,cy-ry|0);y<Math.min(deep.rows-1,cy+ry);y++)for(let x=Math.max(1,cx-rx|0);x<Math.min(deep.cols-1,cx+rx);x++){const dx=(x-cx)/rx,dy=(y-cy)/ry;if(dx*dx+dy*dy<1){const i=deep.idx(x,y);deep.mat[i]=MAT.AIR;deep.integrity[i]=0;deep.moisture[i]=0;deep.o2[i]=.205;deep.co2[i]=.001;deep.vapor[i]=.008+h(x,y,deep.seed+7)*.006}}}
export function bindDeepToWorld(deep,world){
 const C=deep.cols,R=deep.rows,s=deep.seed;deep.water.fill(0);deep.waterVX.fill(0);deep.waterVY.fill(0);
 for(let x=0;x<C;x++){const wx=deep.wx(x),surface=clamp(Math.floor(world.surfaceY(wx)/deep.cell),2,R-4);for(let y=0;y<R;y++){const i=deep.idx(x,y),d=y-surface;if(d<0){deep.mat[i]=MAT.AIR;deep.integrity[i]=0;deep.moisture[i]=0;deep.nutrient[i]=0;deep.o2[i]=.21;deep.co2[i]=.0006;deep.vapor[i]=.006;deep.temp[i]=22-y*.02;continue}const r=h(x,y,s+11),r2=h(x>>1,y>>1,s+29);let m=d<3?MAT.SOIL:d<7?(r>.63?MAT.CLAY:MAT.SOIL):d<20?(r2>.58?MAT.LIMESTONE:MAT.STONE):(r>.72?MAT.BASALT:MAT.STONE);if(d<6&&r>.78)m=MAT.SAND;deep.mat[i]=m;deep.integrity[i]=MAT_INFO[m].hardness;deep.moisture[i]=clamp(.12+d*.004+h(x,y,s+41)*.2,0,.86);deep.nutrient[i]=m===MAT.SOIL?.28+h(x,y,s+53)*.52:.035;deep.temp[i]=21+d*.05;deep.o2[i]=0;deep.co2[i]=0;deep.vapor[i]=0}}
 const rooms=20;for(let k=0;k<rooms;k++){const cx=8+Math.floor(h(k,2,s+101)*(C-16)),wx=deep.wx(cx),surf=clamp(Math.floor(world.surfaceY(wx)/deep.cell),3,R-8),cy=clamp(surf+7+Math.floor(h(k,4,s+109)*(R-surf-12)),surf+5,R-5),rx=3+Math.floor(h(k,6,s+113)*10),ry=2+Math.floor(h(k,8,s+127)*6);carveEllipse(deep,cx,cy,rx,ry);if(k%3===0){let x=cx;for(let y=surf;y<cy;y++){x=clamp(x+Math.round((h(k,y,s+137)-.5)*2),1,C-2);for(let q=-1;q<=1;q++){const i=deep.idx(x+q,y);deep.mat[i]=MAT.AIR;deep.integrity[i]=0;deep.o2[i]=.21;deep.co2[i]=.0008;deep.vapor[i]=.008}}}}
 for(let y=1;y<R-1;y++)for(let x=1;x<C-1;x++){const i=deep.idx(x,y);if(deep.mat[i]!==MAT.AIR)continue;const depth=y-clamp(Math.floor(world.surfaceY(deep.wx(x))/deep.cell),0,R-1);deep.o2[i]=Math.max(deep.o2[i],.21-Math.max(0,depth)*.0007);deep.co2[i]=Math.max(deep.co2[i],.0006+Math.max(0,depth)*.00009);deep.vapor[i]=Math.max(deep.vapor[i],.006+Math.max(0,depth)*.00012);if(depth>8&&h(x,y,s+173)>.985)deep.water[i]=.25+h(y,x,s+181)*.7}
 deep.recomputeSupport();return deep;
}
export const BIND_META={source:'surface world geometry seeds persistent 2D volume',caves:'deterministic chambers + shafts',paintedBackground:false};