const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class Environment{
 constructor(world,opts={}){this.world=world;this.cell=opts.cell||24;this.cols=Math.ceil(world.n*world.dx/this.cell);this.rows=opts.rows||30;this.top=world.worldH-this.rows*this.cell;const N=this.cols*this.rows;this.solid=new Uint8Array(N);this.o2=new Float32Array(N);this.co2=new Float32Array(N);this.vapor=new Float32Array(N);this.water=new Float32Array(N);this.urine=new Float32Array(N);this.temp=new Float32Array(N);this.cloud=new Float32Array(this.cols);this.surfaceUrine=new Float32Array(world.n);this.wind=0;this.time=0;this.generate();}
 idx(x,y){return y*this.cols+x} valid(x,y){return x>=0&&x<this.cols&&y>=0&&y<this.rows} wx(x){return(x+.5)*this.cell} wy(y){return this.top+(y+.5)*this.cell} cellAt(wx,wy){return{x:clamp(Math.floor(wx/this.cell),0,this.cols-1),y:clamp(Math.floor((wy-this.top)/this.cell),0,this.rows-1)}}
 hash(x,y){let n=(x*73856093^y*19349663^this.world.seed*83492791)>>>0;n^=n>>>13;n=Math.imul(n,1274126177);return((n^(n>>>16))>>>0)/4294967295}
 generate(){const w=this.world;for(let y=0;y<this.rows;y++)for(let x=0;x<this.cols;x++){const i=this.idx(x,y),wx=this.wx(x),wy=this.wy(y),surface=w.surfaceY(wx);this.solid[i]=wy>surface?1:0;this.temp[i]=18-(wy-surface)*.008;}
  const carve=(cx,cy,rx,ry)=>{for(let y=Math.max(1,cy-ry|0);y<Math.min(this.rows-1,cy+ry);y++)for(let x=Math.max(1,cx-rx|0);x<Math.min(this.cols-1,cx+rx);x++){const dx=(x-cx)/rx,dy=(y-cy)/ry;if(dx*dx+dy*dy<1)this.solid[this.idx(x,y)]=0;}};
  for(let k=0;k<16;k++){const cx=4+Math.floor(this.hash(k,2)*(this.cols-8)),cy=Math.floor(this.rows*.45+this.hash(k,4)*this.rows*.42),rx=3+Math.floor(this.hash(k,6)*8),ry=2+Math.floor(this.hash(k,8)*5);carve(cx,cy,rx,ry);if(k%4===0){for(let y=Math.max(1,cy-10);y<=cy;y++){const x=clamp(cx+Math.round(Math.sin(y*.7+k)*1.2),1,this.cols-2);this.solid[this.idx(x,y)]=0;}}}
  for(let y=0;y<this.rows;y++)for(let x=0;x<this.cols;x++){const i=this.idx(x,y);if(!this.solid[i]){this.o2[i]=.21;this.co2[i]=.0006;this.vapor[i]=.006+this.hash(x,y)*.004;if(y>this.rows*.65&&this.hash(x,y)>.91)this.water[i]=.2+this.hash(y,x)*.65;}}
 }
 totalLiquid(){let s=0;for(let i=0;i<this.water.length;i++)s+=this.water[i]+this.urine[i];for(const v of this.surfaceUrine)s+=v;return s}
 gasAt(wx,wy){const c=this.cellAt(wx,wy),i=this.idx(c.x,c.y);return this.solid[i]?{o2:0,co2:0,vapor:0,temp:this.temp[i]}:{o2:this.o2[i],co2:this.co2[i],vapor:this.vapor[i],temp:this.temp[i]}}
 exchangeGas(a,b,rate){const d=(a[0][a[1]]-b[0][b[1]])*rate;a[0][a[1]]-=d;b[0][b[1]]+=d}
 stepGas(dt){const C=this.cols,R=this.rows;for(let y=0;y<R;y++)for(let x=0;x<C;x++){const i=this.idx(x,y);if(this.solid[i])continue;for(const [dx,dy] of [[1,0],[0,1]]){const nx=x+dx,ny=y+dy;if(!this.valid(nx,ny))continue;const j=this.idx(nx,ny);if(this.solid[j])continue;const r=clamp(dt*.9,0,.18);for(const arr of [this.o2,this.co2,this.vapor]){const d=(arr[i]-arr[j])*r;arr[i]-=d;arr[j]+=d;}const td=(this.temp[i]-this.temp[j])*r*.28;this.temp[i]-=td;this.temp[j]+=td;}}
  for(let y=1;y<R;y++)for(let x=0;x<C;x++){const i=this.idx(x,y),u=this.idx(x,y-1);if(this.solid[i]||this.solid[u])continue;const co=Math.min(this.co2[u],Math.max(0,this.co2[u]-this.co2[i])*.08*dt*60);this.co2[u]-=co;this.co2[i]+=co;const vap=Math.min(this.vapor[i],Math.max(0,this.vapor[i]-this.vapor[u])*.035*dt*60);this.vapor[i]-=vap;this.vapor[u]+=vap;}}
 stepLiquids(dt){const C=this.cols,R=this.rows;for(let y=R-2;y>=0;y--)for(let x=0;x<C;x++){const i=this.idx(x,y);if(this.solid[i])continue;for(const arr of [this.water,this.urine]){let m=arr[i];if(m<=1e-5)continue;const down=this.idx(x,y+1);if(!this.solid[down]){const cap=Math.max(0,1-(this.water[down]+this.urine[down])),a=Math.min(m,cap,dt*3.8);arr[i]-=a;arr[down]+=a;m-=a;}if(m>.001){const dirs=(this.hash(x+(this.time*7|0),y)>.5)?[-1,1]:[1,-1];for(const d of dirs){const nx=x+d;if(nx<0||nx>=C)continue;const j=this.idx(nx,y);if(this.solid[j])continue;const here=this.water[i]+this.urine[i],there=this.water[j]+this.urine[j],a=Math.min(arr[i],Math.max(0,(here-there)*.32),dt*1.8);arr[i]-=a;arr[j]+=a;}}}}
  for(let i=0;i<this.water.length;i++){if(this.urine[i]>.0001&&this.water[i]>.0001){const mix=Math.min(this.urine[i],this.water[i])*.002*dt*60;this.urine[i]-=mix*.15;this.water[i]+=mix*.15;}}
 }
 stepClouds(dt){const C=this.cols,w=this.world;this.wind=Math.sin(this.time*.11)*.7+Math.sin(this.time*.031)*.35;const next=new Float32Array(C);for(let x=0;x<C;x++){const wx=this.wx(x),wi=clamp(Math.floor(wx/w.dx),0,w.n-1),surfaceWet=w.water[wi],evap=(surfaceWet*.00006+this.vapor[this.idx(x,0)]*.001)*dt*60;this.vapor[this.idx(x,0)]+=evap;const cap=.012+Math.max(-.004,(this.temp[this.idx(x,0)]-15)*.00022),ex=Math.max(0,this.vapor[this.idx(x,0)]-cap),cond=ex*.16*dt*60;this.vapor[this.idx(x,0)]-=cond;this.cloud[x]+=cond;const shift=this.wind*dt*.55,xi=clamp(Math.round(x+shift),0,C-1);next[xi]+=this.cloud[x]*.04;this.cloud[x]*=.96;}
  for(let x=0;x<C;x++){this.cloud[x]+=next[x];if(this.cloud[x]>.018){const rain=Math.min(this.cloud[x],(.004+this.cloud[x]*.07)*dt*60);this.cloud[x]-=rain;const wi=clamp(Math.floor(this.wx(x)/w.dx),0,w.n-1);w.water[wi]+=rain*7;}}
 }
 coupleSurface(dt){const w=this.world;for(let x=0;x<this.cols;x++){const wx=this.wx(x),wi=clamp(Math.floor(wx/w.dx),1,w.n-2),surface=w.surfaceY(wx),c=this.cellAt(wx,surface+this.cell*.7),i=this.idx(c.x,c.y);if(!this.solid[i]&&w.water[wi]>4){const leak=Math.min(w.water[wi],dt*.08);w.water[wi]-=leak;this.water[i]+=leak*.08;}const u=this.surfaceUrine[wi];if(u>.0001){const move=Math.min(u,dt*.02);this.surfaceUrine[wi]-=move;if(!this.solid[i])this.urine[i]+=move;else{w.moisture[wi]=clamp(w.moisture[wi]+move*.03,0,1);w.nutrient[wi]=clamp(w.nutrient[wi]+move*.01,0,1);}}}}
 stepOrganisms(dt){const w=this.world;for(const c of w.creatures){if(!c.alive||c.gone)continue;if(c.bladder==null)c.bladder=0;if(c.oxygen==null)c.oxygen=1;const body=c.nodes[2],g=this.gasAt(body.x,body.y),need=.00012*dt*60,available=Math.max(0,g.o2);if(available>need){const ce=this.cellAt(body.x,body.y),i=this.idx(ce.x,ce.y);this.o2[i]=Math.max(0,this.o2[i]-need);this.co2[i]+=need*.92;c.oxygen=clamp(c.oxygen+dt*.16,0,1);}else c.oxygen=clamp(c.oxygen-dt*.42,0,1);if(c.oxygen<.22){c.health-=dt*.055;c.energy=Math.max(0,c.energy-dt*.025);c.mind.stress=clamp(c.mind.stress+dt*.25,0,1);}c.bladder=clamp(c.bladder+dt*(.002+.003*c.hydration+.002*c.stomach),0,1);if(c.bladder>.72&&c.mind.intent!=='flee'){const wi=clamp(Math.floor(body.x/w.dx),0,w.n-1),amount=Math.min(c.bladder-.35,.12);this.surfaceUrine[wi]+=amount;c.bladder-=amount;}}
 }
 step(dt){this.time+=dt;this.stepGas(dt);this.stepLiquids(dt);this.stepClouds(dt);this.coupleSurface(dt);this.stepOrganisms(dt)}
 metrics(){let o=0,c=0,v=0,w=0,u=0,air=0;for(let i=0;i<this.solid.length;i++)if(!this.solid[i]){o+=this.o2[i];c+=this.co2[i];v+=this.vapor[i];w+=this.water[i];u+=this.urine[i];air++;}let cl=0;for(const q of this.cloud)cl+=q;return{o2:air?o/air:0,co2:air?c/air:0,vapor:air?v/air:0,caveWater:w,urine:u,cloud:cl,airCells:air}}
}
export const ENV_META={solver:'cellular cave gas + multi-liquid transport with separate surface shallow-water coupling',cfd:false,full3D:false,gases:['oxygen','carbon_dioxide','water_vapor'],liquids:['water','urine'],cloudCondensation:true};