import {World} from './sim-core.js';
import {Environment} from './environment.js';
import {DeepWorld} from './deep-world.js';
import {bindDeepToWorld} from './deep-bind.js';
import {drawDeepTerrain,drawDeepWater,drawDeepAtmosphere} from './deep-render.js';
import {drawOrganicClouds} from './organic-render.js';
let canvas,ctx,W=390,H=844,DPR=1,paused=false,speed=1,last=0,acc=0,selected=1,frame=0,lastTelemetry=0,deepAccumulator=0;
let world,env,deep;const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),poseCache=new Map();
function makeSystems(seed=1337){world=new World({seed,n:512,dx:6,worldH:720});env=new Environment(world,{cell:18,rows:40});deep=bindDeepToWorld(new DeepWorld({seed,cell:8,cols:Math.ceil(world.n*world.dx/8),rows:90,chunkSize:32}),world);world.deep=deep;poseCache.clear();selected=1;}
makeSystems();
let cam={x:930,y:360,z:1.05,targetX:930,targetY:360,targetZ:1.05};
const sx=(x,d=0)=>(x-cam.x)*cam.z+W*.5+d*20*cam.z,sy=(y,d=0)=>(y-cam.y)*cam.z+H*.48-d*8*cam.z,view=()=>({sx,sy,cam,W,H});
function visible(){const hw=W/(2*cam.z)+130;return{l:Math.max(0,Math.floor((cam.x-hw)/world.dx)),r:Math.min(world.n-1,Math.ceil((cam.x+hw)/world.dx))}}
function smoothPose(key,p,rate=.3){let q=poseCache.get(key);if(!q){q={x:p.x,y:p.y};poseCache.set(key,q)}q.x+=(p.x-q.x)*rate;q.y+=(p.y-q.y)*rate;return q}
function closedSpline(points){if(points.length<3)return;ctx.beginPath();const n=points.length;const p0=points[0],pn=points[n-1];ctx.moveTo((pn[0]+p0[0])*.5,(pn[1]+p0[1])*.5);for(let i=0;i<n;i++){const a=points[i],b=points[(i+1)%n];ctx.quadraticCurveTo(a[0],a[1],(a[0]+b[0])*.5,(a[1]+b[1])*.5)}ctx.closePath()}
function openSpline(points){if(points.length<2)return;ctx.beginPath();ctx.moveTo(points[0][0],points[0][1]);for(let i=1;i<points.length-1;i++){const p=points[i],n=points[i+1];ctx.quadraticCurveTo(p[0],p[1],(p[0]+n[0])*.5,(p[1]+n[1])*.5)}ctx.lineTo(points.at(-1)[0],points.at(-1)[1])}
function bg(){ctx.fillStyle='#04100e';ctx.fillRect(0,0,W,H);for(let layer=5;layer>=1;layer--){const pts=[];for(let x=-80;x<=W+80;x+=24){const wx=cam.x+(x-W*.5)/cam.z*(.35+.1*layer),h=70+36*layer+Math.sin(wx*.004+layer*1.8)*22+Math.sin(wx*.011-layer)*12;pts.push([x,H*.39-h*.22])}pts.push([W+80,H],[ -80,H]);ctx.fillStyle=`rgba(${3+layer},${15+layer*5},${14+layer*4},${.11+.04*layer})`;closedSpline(pts);ctx.fill()}const shafts=7;ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<shafts;i++){const x=((i*139+frame*.08)%(W+220))-110,w=28+(i*17)%56;ctx.fillStyle=`rgba(126,169,148,${.012+(i%3)*.006})`;ctx.beginPath();ctx.moveTo(x-w*.18,0);ctx.lineTo(x+w*.18,0);ctx.lineTo(x+w,H);ctx.lineTo(x-w,H);ctx.closePath();ctx.fill()}ctx.restore()}
function surfaceWater(){const b=visible();let start=-1;const seg=(l,r)=>{const top=[],bot=[];for(let i=l;i<=r;i++){const wx=i*world.dx;top.push([sx(wx),sy(world.waterSurfaceY(wx))]);bot.push([sx(wx),sy(world.surfaceY(wx))])}const p=[...top,...bot.reverse()];ctx.fillStyle='rgba(24,101,121,.55)';closedSpline(p);ctx.fill();ctx.strokeStyle='rgba(183,231,225,.45)';ctx.lineWidth=Math.max(.7,cam.z);openSpline(top);ctx.stroke()};for(let i=b.l;i<=b.r+1;i++){const wet=i<=b.r&&world.water[i]>.65;if(wet&&start<0)start=i;if((!wet||i>b.r)&&start>=0){if(i-start>1)seg(start,i-1);start=-1}}}
function plant(p,d=0){if(!p.alive)return;const wx=p.x*world.dx,y0=world.surfaceY(wx),x=sx(wx,d),y=sy(y0,d),s=(13+32*p.biomass)*cam.z,b=p.bend*s*.34,seed=p.seed;const stem=[[x,y],[x+b*.1,y-s*.28],[x+b*.35,y-s*.58],[x+b,y-s]];ctx.strokeStyle=p.type==='reed'?'#708f72':'#58745e';ctx.lineWidth=Math.max(1.1,1.6*cam.z);ctx.lineCap='round';openSpline(stem);ctx.stroke();const branches=p.type==='shrub'?7:p.type==='fern'?6:p.type==='fungus'?2:4;for(let j=0;j<branches;j++){const t=.24+(j+1)/(branches+2)*.68,dir=((j+(seed|0))&1)?-1:1,bx=x+b*t,by=y-s*t,len=s*(.18+.055*Math.sin(seed+j*2.4));const ex=bx+dir*len,ey=by-len*(.12+.12*Math.sin(seed*.1+j));ctx.strokeStyle='#496a51';ctx.lineWidth=Math.max(.65,.9*cam.z);ctx.beginPath();ctx.moveTo(bx,by);ctx.quadraticCurveTo((bx+ex)*.5,by-len*.08,ex,ey);ctx.stroke();const nx=dir,ny=-.25,leaf=[[ex,ey],[ex+nx*len*.22,ey+ny*len*.18],[ex+nx*len*.31,ey+ny*len*.02],[ex+nx*len*.13,ey-ny*len*.08],[ex,ey]];ctx.fillStyle=p.type==='fungus'?'#729e88':'#53775b';closedSpline(leaf);ctx.fill()}}
function taperedSegment(a,b,r0,r1,fill,stroke){const dx=b.x-a.x,dy=b.y-a.y,m=Math.hypot(dx,dy)||1,nx=-dy/m,ny=dx/m,pts=[[sx(a.x+nx*r0),sy(a.y+ny*r0)],[sx(b.x+nx*r1),sy(b.y+ny*r1)],[sx(b.x-nx*r1),sy(b.y-ny*r1)],[sx(a.x-nx*r0),sy(a.y-ny*r0)]];ctx.fillStyle=fill;closedSpline(pts);ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=Math.max(.55,.7*cam.z);ctx.stroke()}}
function limb(c,l,d,idx){const a=smoothPose(`${c.id}:a${l.anchor}`,c.nodes[l.anchor]),k=smoothPose(`${c.id}:k${idx}`,l.knee),f=smoothPose(`${c.id}:f${idx}`,l.foot),alive=c.alive,fill=alive?'#263b34':'#443f36',edge=alive?'rgba(135,161,145,.42)':'rgba(105,98,84,.34)';taperedSegment(a,k,2.35,1.65,fill,edge);taperedSegment(k,f,1.55,.72,fill,edge);const vx=f.x-k.x,vy=f.y-k.y,m=Math.hypot(vx,vy)||1,ux=vx/m,uy=vy/m,tx=f.x+ux*4.8,ty=f.y+uy*4.8;ctx.strokeStyle=edge;ctx.lineWidth=Math.max(.6,.75*cam.z);ctx.beginPath();ctx.moveTo(sx(f.x),sy(f.y));ctx.lineTo(sx(tx-uy*1.4),sy(ty+ux*1.4));ctx.moveTo(sx(f.x),sy(f.y));ctx.lineTo(sx(tx+uy*1.4),sy(ty-ux*1.4));ctx.stroke()}
function bodyEnvelope(nodes,widths){const up=[],dn=[];for(let i=0;i<nodes.length;i++){const a=nodes[Math.max(0,i-1)],b=nodes[Math.min(nodes.length-1,i+1)],dx=b.x-a.x,dy=b.y-a.y,m=Math.hypot(dx,dy)||1,nx=-dy/m,ny=dx/m,w=widths[i];up.push([sx(nodes[i].x+nx*w),sy(nodes[i].y+ny*w)]);dn.unshift([sx(nodes[i].x-nx*w),sy(nodes[i].y-ny*w)])}return[...up,...dn]}
function creature(c){if(c.gone)return;const nodes=c.nodes.map((n,i)=>smoothPose(`${c.id}:n${i}`,n,.24));for(let i=0;i<c.legs.length;i++)if(c.legs[i].side<0)limb(c,c.legs[i],-.05,i);const widths=[4.8,7.6,9.4,7.8,5.1],body=bodyEnvelope(nodes,widths),alive=c.alive;ctx.fillStyle=alive?(c.oxygen<.3?'#6d625f':'#3d5a50'):'#554f44';closedSpline(body);ctx.fill();ctx.strokeStyle=alive?'rgba(149,172,158,.48)':'rgba(116,108,92,.36)';ctx.lineWidth=Math.max(.7,1*cam.z);ctx.stroke();for(let i=0;i<4;i++){const a=nodes[i],b=nodes[i+1],dx=b.x-a.x,dy=b.y-a.y,m=Math.hypot(dx,dy)||1,nx=-dy/m,ny=dx/m,cx=(a.x+b.x)*.5,cy=(a.y+b.y)*.5,w=widths[i+1]*.74;ctx.strokeStyle=alive?'rgba(175,196,181,.16)':'rgba(160,147,122,.12)';ctx.lineWidth=Math.max(.55,.65*cam.z);ctx.beginPath();ctx.moveTo(sx(cx+nx*w),sy(cy+ny*w));ctx.quadraticCurveTo(sx(cx),sy(cy-1.1),sx(cx-nx*w),sy(cy-ny*w));ctx.stroke()}const hi=c.dir>0?4:0,ni=c.dir>0?3:1,head=nodes[hi],neck=nodes[ni],dx=head.x-neck.x,dy=head.y-neck.y,m=Math.hypot(dx,dy)||1,ux=dx/m,uy=dy/m,nx=-uy,ny=ux,baseX=head.x+ux*3.8,baseY=head.y+uy*3.8;for(const side of[-1,1]){const root={x:baseX+nx*side*1.6,y:baseY+ny*side*1.6},tip={x:baseX+ux*6.5+nx*side*2.8,y:baseY+uy*6.5+ny*side*2.8};taperedSegment(root,tip,1.15,.35,alive?'#293c35':'#4b453b',null)}for(const f of c.feelers||[]){const tip=smoothPose(`${c.id}:feel${f.side}`,f.tip,.2);ctx.strokeStyle=alive?'rgba(162,193,174,.56)':'rgba(121,112,95,.38)';ctx.lineWidth=Math.max(.5,.62*cam.z);ctx.beginPath();ctx.moveTo(sx(head.x),sy(head.y));ctx.bezierCurveTo(sx(head.x+ux*5+nx*f.side*2),sy(head.y+uy*5+ny*f.side*2),sx(tip.x-ux*4),sy(tip.y-uy*4),sx(tip.x),sy(tip.y));ctx.stroke()}for(let i=0;i<c.legs.length;i++)if(c.legs[i].side>0)limb(c,c.legs[i],.05,i)}
function rain(){let intensity=world.rain,cm=0;for(const q of env.cloud)cm+=q;intensity+=Math.min(.35,cm/env.cols*4);if(intensity<.02)return;ctx.strokeStyle=`rgba(183,224,223,${.09+intensity*.26})`;ctx.lineWidth=.8;const count=Math.floor(18+intensity*72);for(let k=0;k<count;k++){const x=((k*97+frame*7)%(W+80))-40,y=((k*53+frame*13)%(H+100))-50,l=10+(k*17)%20;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-4,y+l);ctx.stroke()}}
function coupleDeepSurface(dt){for(let x=1;x<deep.cols-1;x+=2){const wx=deep.wx(x),wi=clamp((wx/world.dx)|0,1,world.n-2),syCell=clamp(Math.floor(world.surfaceY(wx)/deep.cell),1,deep.rows-2),i=deep.idx(x,syCell);if(deep.mat[i]===0&&world.water[wi]>.8){const take=Math.min(world.water[wi]*.0015,dt*.08);world.water[wi]-=take;deep.water[i]+=take*.5}const air=deep.mat[i]===0;if(air){deep.o2[i]+=(.21-deep.o2[i])*dt*.08;deep.co2[i]+=(.0006-deep.co2[i])*dt*.08}}}
function render(){ctx.setTransform(DPR,0,0,DPR,0,0);ctx.clearRect(0,0,W,H);bg();drawOrganicClouds(ctx,env,view());drawDeepTerrain(ctx,deep,view());drawDeepAtmosphere(ctx,deep,view());drawDeepWater(ctx,deep,view());surfaceWater();const b=visible();for(const p of world.plants)if(p.alive&&p.x>=b.l-5&&p.x<=b.r+5)plant(p,-.04);for(const c of world.creatures)if(!c.gone&&c.nodes[2].x/world.dx>=b.l-6&&c.nodes[2].x/world.dx<=b.r+6)creature(c);rain();ctx.fillStyle='rgba(0,0,0,.08)';ctx.fillRect(0,0,W,12);}
function telemetry(now){if(now-lastTelemetry<260)return;lastTelemetry=now;const em=env.metrics(),dm=deep.metrics(),alive=world.creatures.filter(c=>c.alive).length,c=world.creatures.find(q=>q.id===selected),flow=world.q.reduce((s,v)=>s+Math.abs(v),0)/world.q.length;postMessage({type:'telemetry',alive,water:world.totalWater()+dm.water,flow,rain:world.rain,oxygen:dm.o2,co2:dm.co2,caveWater:dm.water,urine:em.urine,cloud:em.cloud,chunks:dm.chunks,activeChunks:dm.activeChunks,selected:c?{id:c.id,alive:c.alive,intent:c.alive?c.mind.intent:'corpse',energy:c.energy,hunger:c.hunger,hydration:c.hydration,fatigue:c.fatigue,stomach:c.stomach,oxygen:c.oxygen??1,bladder:c.bladder??0}:null})}
function loop(now){if(!last)last=now;const dt=Math.min(.05,(now-last)/1000);last=now,ca=1-Math.exp(-dt*8);cam.x+=(cam.targetX-cam.x)*ca;cam.y+=(cam.targetY-cam.y)*ca;cam.z+=(cam.targetZ-cam.z)*(1-Math.exp(-dt*10));if(!paused){acc+=dt*speed;const step=1/60;let n=0;while(acc>=step&&n<5){deep.setActiveAround([{x:cam.x,y:cam.y},...world.creatures.filter(c=>c.alive).slice(0,24).map(c=>({x:c.nodes[2].x,y:c.nodes[2].y}))]);world.step(step);env.step(step);deepAccumulator+=step;if(deepAccumulator>=1/30){coupleDeepSurface(deepAccumulator);deep.step(deepAccumulator);deepAccumulator=0}acc-=step;n++}}render();telemetry(now);frame++;setTimeout(()=>loop(performance.now()),0)}
function reset(seed){makeSystems(seed);cam.x=world.n*world.dx*.34;cam.targetX=cam.x}
onmessage=e=>{const m=e.data||{};if(m.type==='init'){canvas=m.canvas;DPR=clamp(m.dpr||1,1,2);W=m.w;H=m.h;canvas.width=W*DPR|0;canvas.height=H*DPR|0;ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});cam.x=world.n*world.dx*.34;cam.targetX=cam.x;last=performance.now();loop(last)}else if(m.type==='resize'){W=m.w;H=m.h;DPR=clamp(m.dpr||1,1,2);canvas.width=W*DPR|0;canvas.height=H*DPR|0}else if(m.type==='pan'){cam.targetX=clamp(cam.targetX-m.dx/cam.targetZ,0,world.n*world.dx);cam.targetY=clamp(cam.targetY-m.dy/cam.targetZ,70,world.worldH-40)}else if(m.type==='zoom')cam.targetZ=clamp(cam.targetZ*m.factor,.55,3.1);else if(m.type==='pause')paused=!paused;else if(m.type==='speed')speed=m.value||1;else if(m.type==='rain'){world.rain=m.value;for(let i=0;i<env.cloud.length;i++)env.cloud[i]+=m.value*.003}else if(m.type==='reset')reset(m.seed||((Math.random()*1e9)|0));else if(m.type==='tap'){const wx=cam.x+(m.x-W*.5)/cam.z,wy=cam.y+(m.y-H*.48)/cam.z;let best=null,bd=45/cam.z;for(const c of world.creatures){if(c.gone)continue;const p=c.nodes[2],dist=Math.hypot(p.x-wx,p.y-wy);if(dist<bd){bd=dist;best=c}}if(best)selected=best.id}};