import {World} from './sim-core.js';
import {Environment} from './environment.js';
import {drawOrganicCaves,drawOrganicCaveLiquids,drawOrganicClouds} from './organic-render.js';

let canvas,ctx,W=390,H=844,DPR=1,paused=false,speed=1,last=0,acc=0,selected=1,frame=0,lastTelemetry=0;
let world=new World({seed:1337,n:512,dx:6,worldH:720}),env=new Environment(world,{cell:18,rows:40});
let cam={x:930,y:360,z:1.05,targetX:930,targetY:360,targetZ:1.05};
const poseCache=new Map(),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const sx=(x,d=0)=>(x-cam.x)*cam.z+W*.5+d*20*cam.z,sy=(y,d=0)=>(y-cam.y)*cam.z+H*.48-d*8*cam.z;
const view=()=>({sx,sy,cam,W,H});
function visible(){const hw=W/(2*cam.z)+100;return{l:Math.max(0,Math.floor((cam.x-hw)/world.dx)),r:Math.min(world.n-1,Math.ceil((cam.x+hw)/world.dx))};}
function path(points,close=false){if(points.length<2)return;ctx.beginPath();ctx.moveTo(...points[0]);for(let i=1;i<points.length-1;i++){const p=points[i],n=points[i+1];ctx.quadraticCurveTo(p[0],p[1],(p[0]+n[0])*.5,(p[1]+n[1])*.5);}ctx.lineTo(...points.at(-1));if(close)ctx.closePath();}
function smoothed(key,p,rate=.34){let q=poseCache.get(key);if(!q){q={x:p.x,y:p.y};poseCache.set(key,q);}q.x+=(p.x-q.x)*rate;q.y+=(p.y-q.y)*rate;return q;}

function bg(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#061716');g.addColorStop(.47,'#0a2320');g.addColorStop(1,'#020807');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const sun=ctx.createRadialGradient(W*.64,H*.19,5,W*.64,H*.19,H*.55);sun.addColorStop(0,'rgba(196,225,195,.17)');sun.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=sun;ctx.fillRect(0,0,W,H);for(let l=3;l>=1;l--){const pts=[];for(let i=visible().l;i<=visible().r;i+=5){const wx=i*world.dx,y=world.surfaceY(wx)-70-l*54-Math.sin(i*.1+l)*15;pts.push([sx(wx,-l*.5),sy(y,-l*.5)]);}pts.push([W,H],[0,H]);ctx.fillStyle=`rgba(3,${18+l*6},${16+l*4},${.42-l*.06})`;path(pts,true);ctx.fill();}}

function terrain(){const b=visible(),top=[];for(let i=b.l;i<=b.r;i++){const wx=i*world.dx;top.push([sx(wx),sy(world.surfaceY(wx))]);}const poly=[...top,[top.at(-1)[0],H+30],[top[0][0],H+30]],g=ctx.createLinearGradient(0,H*.36,0,H);g.addColorStop(0,'#46564b');g.addColorStop(.13,'#26372f');g.addColorStop(.6,'#101d18');g.addColorStop(1,'#050a08');ctx.fillStyle=g;path(poly,true);ctx.fill();for(let d=20;d<130;d+=22){ctx.strokeStyle=d%44?'rgba(114,91,65,.14)':'rgba(73,111,91,.12)';ctx.lineWidth=1;ctx.beginPath();for(let i=b.l;i<=b.r;i+=3){const x=sx(i*world.dx),y=sy(world.surfaceY(i*world.dx)+d+Math.sin(i*.15+d)*4);i===b.l?ctx.moveTo(x,y):ctx.lineTo(x,y);}ctx.stroke();}}

function surfaceWater(){const b=visible();let start=-1;const seg=(l,r)=>{const top=[],bot=[];for(let i=l;i<=r;i++){const wx=i*world.dx;top.push([sx(wx),sy(world.waterSurfaceY(wx))]);bot.push([sx(wx),sy(world.surfaceY(wx))]);}const p=[...top,...bot.reverse()],g=ctx.createLinearGradient(0,Math.min(...top.map(v=>v[1])),0,Math.max(...bot.map(v=>v[1])));g.addColorStop(0,'rgba(129,215,214,.72)');g.addColorStop(.18,'rgba(45,139,151,.59)');g.addColorStop(1,'rgba(4,42,52,.82)');ctx.fillStyle=g;path(p,true);ctx.fill();ctx.strokeStyle='rgba(215,247,239,.68)';ctx.lineWidth=1.2*cam.z;path(top);ctx.stroke();for(let i=l;i<=r;i+=3){const h=world.water[i],u=.5*(world.q[i]+world.q[i+1])/Math.max(.2,h);if(h<1||Math.abs(u)<.25)continue;const x=sx(i*world.dx),y=sy(world.waterSurfaceY(i*world.dx));ctx.strokeStyle=`rgba(215,247,239,${clamp(.06+Math.abs(u)*.025,.06,.24)})`;ctx.lineWidth=.65*cam.z;ctx.beginPath();ctx.moveTo(x-7*cam.z,y);ctx.quadraticCurveTo(x,y-1.2*cam.z,x+8*cam.z,y);ctx.stroke();}};for(let i=b.l;i<=b.r+1;i++){const wet=i<=b.r&&world.water[i]>.65;if(wet&&start<0)start=i;if((!wet||i>b.r)&&start>=0){if(i-start>1)seg(start,i-1);start=-1;}}}

function plant(p,d=0){if(!p.alive)return;const wx=p.x*world.dx,y0=world.surfaceY(wx),x=sx(wx,d),y=sy(y0,d),s=(10+28*p.biomass)*cam.z,b=p.bend*s*.4;ctx.strokeStyle=p.type==='reed'?'#648c6e':'#4f765e';ctx.lineWidth=Math.max(1,1.8*cam.z);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+b*.25,y-s*.45,x+b,y-s);ctx.stroke();const n=p.type==='shrub'?5:p.type==='fern'?4:2;for(let j=0;j<n;j++){const t=.3+j/(n+2),dir=j%2?-1:1,bx=x+b*t,by=y-s*t,len=s*(.22+.05*Math.sin(p.seed+j));ctx.strokeStyle='#41694f';ctx.lineWidth=Math.max(.7,1*cam.z);ctx.beginPath();ctx.moveTo(bx,by);ctx.quadraticCurveTo(bx+dir*len*.45,by-len*.06,bx+dir*len,by-len*.18);ctx.stroke();ctx.fillStyle=p.type==='fungus'?'#70c2a8':'#56876a';ctx.beginPath();ctx.ellipse(bx+dir*len,by-len*.18,5*p.biomass*cam.z,2.1*p.biomass*cam.z,dir*.25,0,Math.PI*2);ctx.fill();}}

function limb(c,l,d,idx){const a=smoothed(`${c.id}:a${l.anchor}`,c.nodes[l.anchor]),k=smoothed(`${c.id}:k${idx}`,l.knee),f=smoothed(`${c.id}:f${idx}`,l.foot);ctx.strokeStyle=c.alive?'#111b18':'#393831';ctx.lineWidth=3.15*cam.z;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(sx(a.x,d),sy(a.y,d));ctx.quadraticCurveTo(sx(k.x,d),sy(k.y,d),sx(f.x,d),sy(f.y,d));ctx.stroke();ctx.strokeStyle='rgba(125,151,135,.58)';ctx.lineWidth=.8*cam.z;ctx.stroke();}

function creature(c,d=0){if(c.gone)return;const nodes=c.nodes.map((n,i)=>smoothed(`${c.id}:n${i}`,n));for(let i=0;i<c.legs.length;i++)if(c.legs[i].side<0)limb(c,c.legs[i],d-.06,i);const pts=nodes.map(n=>[sx(n.x,d),sy(n.y,d)]),w=[4.3,7,8.5,7,4.3].map(v=>v*cam.z),up=[],dn=[];for(let i=0;i<pts.length;i++){const a=pts[Math.max(0,i-1)],b=pts[Math.min(pts.length-1,i+1)],dx=b[0]-a[0],dy=b[1]-a[1],m=Math.hypot(dx,dy)||1,nx=-dy/m,ny=dx/m;up.push([pts[i][0]+nx*w[i],pts[i][1]+ny*w[i]]);dn.unshift([pts[i][0]-nx*w[i],pts[i][1]-ny*w[i]]);}const body=[...up,...dn],gr=ctx.createLinearGradient(0,Math.min(...body.map(p=>p[1])),0,Math.max(...body.map(p=>p[1])));if(c.alive){gr.addColorStop(0,c.oxygen<.3?'#7b6a66':'#a6baae');gr.addColorStop(.24,'#546f64');gr.addColorStop(.72,'#22332d');gr.addColorStop(1,'#0a1411');}else{gr.addColorStop(0,'#6c665d');gr.addColorStop(1,'#171813');}ctx.fillStyle=gr;ctx.strokeStyle='#0b1210';ctx.lineWidth=1.25*cam.z;path(body,true);ctx.fill();ctx.stroke();for(const f of c.feelers||[]){const h=nodes[c.dir>0?4:0],tip=smoothed(`${c.id}:feel${f.side}`,f.tip,.28);ctx.strokeStyle='rgba(159,196,176,.64)';ctx.lineWidth=.7*cam.z;ctx.beginPath();ctx.moveTo(sx(h.x,d+.08),sy(h.y,d+.08));ctx.quadraticCurveTo((sx(h.x,d)+sx(tip.x,d+.12))*.5,sy(h.y,d)-f.side*3.5,sx(tip.x,d+.12),sy(tip.y,d+.12));ctx.stroke();}for(let i=0;i<c.legs.length;i++)if(c.legs[i].side>0)limb(c,c.legs[i],d+.06,i);}

function rain(){let intensity=world.rain,cm=0;for(const q of env.cloud)cm+=q;intensity+=Math.min(.38,cm/env.cols*4);if(intensity<.02)return;ctx.strokeStyle=`rgba(183,224,223,${.11+intensity*.31})`;ctx.lineWidth=1;const count=Math.floor(20+intensity*88);for(let k=0;k<count;k++){const x=((k*97+frame*8)%(W+80))-40,y=((k*53+frame*14)%(H+100))-50,l=9+(k*17)%19;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-4,y+l);ctx.stroke();}}

function render(){ctx.setTransform(DPR,0,0,DPR,0,0);ctx.clearRect(0,0,W,H);bg();drawOrganicClouds(ctx,env,view());terrain();drawOrganicCaves(ctx,env,world,view());drawOrganicCaveLiquids(ctx,env,world,view());surfaceWater();const b=visible(),ps=world.plants.filter(p=>p.alive&&p.x>=b.l-4&&p.x<=b.r+4);for(const p of ps)plant(p,-.05);for(const c of world.creatures)if(!c.gone&&c.nodes[2].x/world.dx>=b.l-5&&c.nodes[2].x/world.dx<=b.r+5)creature(c);rain();const vg=ctx.createRadialGradient(W*.5,H*.45,Math.min(W,H)*.25,W*.5,H*.45,Math.max(W,H)*.7);vg.addColorStop(0,'rgba(0,0,0,0)');vg.addColorStop(1,'rgba(0,0,0,.42)');ctx.fillStyle=vg;ctx.fillRect(0,0,W,H);}
function telemetry(now){if(now-lastTelemetry<250)return;lastTelemetry=now;const m=env.metrics(),alive=world.creatures.filter(c=>c.alive).length,flow=world.q.reduce((s,v)=>s+Math.abs(v),0)/world.q.length,c=world.creatures.find(q=>q.id===selected);postMessage({type:'telemetry',alive,water:world.totalWater(),flow,rain:world.rain,oxygen:m.o2,co2:m.co2,caveWater:m.caveWater,urine:m.urine,cloud:m.cloud,selected:c?{id:c.id,alive:c.alive,intent:c.alive?c.mind.intent:'corpse',energy:c.energy,hunger:c.hunger,hydration:c.hydration,fatigue:c.fatigue,stomach:c.stomach,oxygen:c.oxygen??1,bladder:c.bladder??0}:null});}
function loop(now){if(!last)last=now;const dt=Math.min(.05,(now-last)/1000);last=now;const ca=1-Math.exp(-dt*8);cam.x+=(cam.targetX-cam.x)*ca;cam.y+=(cam.targetY-cam.y)*ca;cam.z+=(cam.targetZ-cam.z)*(1-Math.exp(-dt*10));if(!paused){acc+=dt*speed;const step=1/60;let n=0;while(acc>=step&&n<5){world.step(step);env.step(step);acc-=step;n++;}}render();telemetry(now);frame++;setTimeout(()=>loop(performance.now()),0);}
function reset(seed){world=new World({seed,n:512,dx:6,worldH:720});env=new Environment(world,{cell:18,rows:40});poseCache.clear();selected=1;}
onmessage=e=>{const m=e.data||{};if(m.type==='init'){canvas=m.canvas;DPR=clamp(m.dpr||1,1,2);W=m.w;H=m.h;canvas.width=W*DPR|0;canvas.height=H*DPR|0;ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});cam.x=world.n*world.dx*.34;cam.targetX=cam.x;last=performance.now();loop(last);}else if(m.type==='resize'){W=m.w;H=m.h;DPR=clamp(m.dpr||1,1,2);canvas.width=W*DPR|0;canvas.height=H*DPR|0;}else if(m.type==='pan'){cam.targetX=clamp(cam.targetX-m.dx/cam.targetZ,0,world.n*world.dx);cam.targetY=clamp(cam.targetY-m.dy/cam.targetZ,80,world.worldH-60);}else if(m.type==='zoom')cam.targetZ=clamp(cam.targetZ*m.factor,.5,2.8);else if(m.type==='pause')paused=!paused;else if(m.type==='speed')speed=m.value||1;else if(m.type==='rain'){world.rain=m.value;for(let i=0;i<env.cloud.length;i++)env.cloud[i]+=m.value*.003;}else if(m.type==='reset')reset(m.seed||((Math.random()*1e9)|0));else if(m.type==='tap'){const wx=cam.x+(m.x-W*.5)/cam.z,wy=cam.y+(m.y-H*.48)/cam.z;let best=null,bd=45/cam.z;for(const c of world.creatures){if(c.gone)continue;const p=c.nodes[2],dist=Math.hypot(p.x-wx,p.y-wy);if(dist<bd){bd=dist;best=c;}}if(best)selected=best.id;}};
