import {planCellPath,followCellPath,DEEP_NAV_META} from './deep-nav.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
export function terrainProbe(world,wx){const x=clamp(wx/world.dx,1,world.n-2),i=x|0,t=x-i,y=world.surfaceY(wx),yl=world.surfaceY((i-1)*world.dx),yr=world.surfaceY((i+1)*world.dx),slope=Math.abs(yr-yl)/(2*world.dx),water=lerp(world.water[i],world.water[i+1],t),root=lerp(world.rootStrength[i],world.rootStrength[i+1],t),moisture=lerp(world.moisture[i],world.moisture[i+1],t),unstable=clamp(moisture*.9-root*.32,0,1);return{x:wx,y,slope,water,root,moisture,unstable}}
export function traversalCost(p){return 1+p.slope*p.slope*2.4+(p.water<1?0:p.water<5?p.water*.12:p.water<11?.75+(p.water-5)*.32:4+(p.water-11)*.8)+p.unstable*.55}
export function planSurfaceRoute(world,startX,goalX,opts={}){const step=opts.step||Math.max(12,world.dx*3),dir=Math.sign(goalX-startX)||1,maxSlope=opts.maxSlope??1.65,maxWater=opts.maxWater??15,distance=Math.abs(goalX-startX),count=Math.max(1,Math.ceil(distance/step)),points=[],limit=world.n*world.dx-6;let cost=0,reachable=true,blockageX=null;for(let k=0;k<=count;k++){const x=clamp(k===count?goalX:startX+dir*Math.min(distance,k*step),6,limit),p=terrainProbe(world,x),blocked=p.slope>maxSlope||p.water>maxWater;cost+=traversalCost(p);points.push({...p,cost,blocked});if(blocked&&k>0){reachable=false;blockageX=x;points.length=Math.max(1,points.length-1);break}}return{startX,goalX,points,reachable,blockageX,cost}}
function rawDrive(c){const m=c.mind;return m.intent==='flee'?1.2:m.intent==='forage'?.82:m.intent==='drink'?.6:m.intent==='explore'?.55:0}
function replan(world,c,n,goalX){const body=c.nodes[2],volumeCapable=c.locomotionMode==='volume'&&!!world.deep;if(volumeCapable){const goalY=world.surfaceY(goalX)-world.deep.cell*.7;n.deepPath=planCellPath(world.deep,{x:body.x,y:body.y},{x:goalX,y:goalY},{maxExpanded:14000,profile:{cling:!!c.canCling,swim:!!c.canSwim}});n.route=null;n.index=0;n.blocked=!n.deepPath.reachable;n.kind='deep';}else{n.route=planSurfaceRoute(world,body.x,goalX);n.deepPath=null;n.index=0;n.blocked=!n.route.reachable;n.kind='surface';}n.replan=.34+.28*(1-c.mind.curiosity);n.lastGoal=goalX}
export function updateNavigator(world,c,dt,goalX){const m=c.mind,body=c.nodes[2];if(!m.nav)m.nav={route:null,deepPath:null,index:0,replan:0,waypointX:body.x,waypointY:body.y,steer:0,speed:0,blocked:false,lastGoal:goalX,heading:0,kind:'none'};const n=m.nav;n.replan-=dt;const changed=Math.abs((n.lastGoal??goalX)-goalX)>world.dx*3;if((!n.route&&!n.deepPath)||changed||n.replan<=0)replan(world,c,n,goalX);
 let desiredDir=0,targetSpeed=0,waypointX=body.x,waypointY=body.y,reachable=!n.blocked;
 if(n.kind==='deep'&&n.deepPath?.reachable){const f=followCellPath(n,n.deepPath,body,dt);waypointX=f.target.x;waypointY=f.target.y;desiredDir=f.heading;targetSpeed=rawDrive(c)*f.speed;reachable=true;n.index=f.index;}
 else if(n.kind==='surface'&&n.route){const pts=n.route.points;while(n.index<pts.length-1&&Math.abs(pts[n.index].x-body.x)<world.dx*4)n.index++;const wp=pts[Math.min(pts.length-1,n.index+1)]||{x:body.x,y:body.y};waypointX=wp.x;waypointY=wp.y;desiredDir=Math.abs(wp.x-body.x)<world.dx*1.2?0:Math.sign(wp.x-body.x);const probe=terrainProbe(world,body.x+(desiredDir||0)*world.dx*3),hazardSlow=clamp(1-(probe.slope*.36+Math.max(0,probe.water-2)*.045+probe.unstable*.16),.25,1);targetSpeed=rawDrive(c)*hazardSlow*(n.blocked?0:1);reachable=n.route.reachable;}
 const steerRate=1-Math.exp(-dt*(n.blocked?3.6:5.3));n.steer=lerp(n.steer,desiredDir,steerRate);if(desiredDir===0&&Math.abs(n.steer)<.1)n.steer=0;n.heading=Math.abs(n.steer)>.38?Math.sign(n.steer):0;n.speed=lerp(n.speed,n.heading?targetSpeed:0,1-Math.exp(-dt*3.6));n.waypointX=waypointX;n.waypointY=waypointY;return{waypointX,waypointY,steer:n.steer,speed:n.speed,heading:n.heading,blocked:n.blocked,reachable,kind:n.kind}}
export const NAV_META={kind:'persistent route planner matched to body locomotion capability',general2DNavmesh:false,hazards:['solid_material','water','carbon_dioxide','temperature','surface_instability'],persistentWaypoints:true,smoothedSteering:true,committedHeadingTurns:true,straightLineTargeting:false,deepRoutingRequiresCompatibleBody:true,currentCrawlerMode:'surface',deepWorld:DEEP_NAV_META};