import {World} from './sim-core.js';
let canvas,ctx,W=390,H=844,DPR=1;
let world=new World({seed:1337,n:512,dx:6,worldH:720});
let paused=false,speed=1,last=0,acc=0,cam={x:900,y:370,z:1.1,targetX:900,targetY:370,targetZ:1.1};
let selected=1,frame=0,lastTelemetry=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function sx(wx,depth=0){return (wx-cam.x)*cam.z+W*.5+depth*18*cam.z;}
function sy(wy,depth=0){return (wy-cam.y)*cam.z+H*.48-depth*7*cam.z;}
function visible(){const hw=W/(2*cam.z)+80;return{l:Math.max(0,Math.floor((cam.x-hw)/world.dx)),r:Math.min(world.n-1,Math.ceil((cam.x+hw)/world.dx))};}
function smoothPath(points,close=false){if(points.length<2)return;ctx.beginPath();ctx.moveTo(points[0][0],points[0][1]);for(let i=1;i<points.length-1;i++){const p=points[i],n=points[i+1];ctx.quadraticCurveTo(p[0],p[1],(p[0]+n[0])*.5,(p[1]+n[1])*.5);}const q=points[points.length-1];ctx.lineTo(q[0],q[1]);if(close)ctx.closePath();}
function drawBackground(){
  const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#061712');g.addColorStop(.45,'#0a2520');g.addColorStop(1,'#020a08');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
  const rg=ctx.createRadialGradient(W*.62,H*.26,8,W*.62,H*.26,H*.55);rg.addColorStop(0,'rgba(171,212,171,.22)');rg.addColorStop(.25,'rgba(83,137,116,.09)');rg.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=rg;ctx.fillRect(0,0,W,H);
  const b=visible();
  for(let layer=3;layer>=1;layer--){const depth=-layer*.55,pts=[];for(let i=b.l;i<=b.r;i+=4){const y=world.worldH-world.bed[i]-85-layer*55-Math.sin(i*.11+layer)*18;pts.push([sx(i*world.dx,depth),sy(y,depth)]);}pts.push([W,H],[0,H]);ctx.fillStyle=`rgba(${5+layer*3},${25+layer*5},${22+layer*4},${.38-layer*.05})`;smoothPath(pts,true);ctx.fill();}
  for(let k=0;k<9;k++){const wx=(Math.floor(cam.x/380)+k-4)*380+((k*97)%170),x=sx(wx,-.7),width=(42+(k%3)*22)*cam.z;ctx.fillStyle='rgba(2,15,12,.62)';ctx.beginPath();ctx.moveTo(x-width*.35,H);ctx.bezierCurveTo(x-width*.55,H*.65,x-width*.2,H*.35,x-width*.08,0);ctx.lineTo(x+width*.16,0);ctx.bezierCurveTo(x+width*.12,H*.38,x+width*.55,H*.7,x+width*.32,H);ctx.closePath();ctx.fill();}
}
function drawTerrain(){
  const b=visible(),top=[];for(let i=b.l;i<=b.r;i++){const wx=i*world.dx;top.push([sx(wx),sy(world.surfaceY(wx))]);}const poly=[...top,[top[top.length-1][0],H+20],[top[0][0],H+20]];
  const g=ctx.createLinearGradient(0,H*.35,0,H);g.addColorStop(0,'#33433a');g.addColorStop(.16,'#1d2c26');g.addColorStop(.7,'#0a1612');g.addColorStop(1,'#050b09');ctx.fillStyle=g;smoothPath(poly,true);ctx.fill();
  ctx.lineCap='round';for(let i=b.l;i<b.r;i+=2){const wx=i*world.dx,p1=[sx(wx),sy(world.surfaceY(wx))],p2=[sx((i+2)*world.dx),sy(world.surfaceY((i+2)*world.dx))],wet=world.moisture[i];ctx.strokeStyle=`rgba(${55+wet*40|0},${73+wet*55|0},${60+wet*45|0},.85)`;ctx.lineWidth=(2.5+wet*2)*cam.z;ctx.beginPath();ctx.moveTo(...p1);ctx.lineTo(...p2);ctx.stroke();}
  ctx.globalAlpha=.22;for(let d=18;d<92;d+=18){ctx.strokeStyle=d%36?'#846f54':'#41604e';ctx.lineWidth=1;ctx.beginPath();for(let i=b.l;i<=b.r;i+=3){const x=sx(i*world.dx),y=sy(world.surfaceY(i*world.dx)+d+Math.sin(i*.13+d)*4);if(i===b.l)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();}ctx.globalAlpha=1;
}
function drawWater(){
  const b=visible();let start=-1;
  const renderSeg=(l,r)=>{const top=[],bottom=[];for(let i=l;i<=r;i++){const wx=i*world.dx,by=world.surfaceY(wx),wy=world.waterSurfaceY(wx);top.push([sx(wx),sy(wy)]);bottom.push([sx(wx),sy(by)]);}const poly=[...top,...bottom.reverse()],minY=Math.min(...top.map(p=>p[1])),maxY=Math.max(...bottom.map(p=>p[1])),g=ctx.createLinearGradient(0,minY,0,maxY);g.addColorStop(0,'rgba(95,192,200,.68)');g.addColorStop(.12,'rgba(33,119,132,.52)');g.addColorStop(1,'rgba(3,37,43,.74)');ctx.fillStyle=g;smoothPath(poly,true);ctx.fill();ctx.strokeStyle='rgba(185,239,230,.72)';ctx.lineWidth=1.6*cam.z;smoothPath(top);ctx.stroke();ctx.globalCompositeOperation='screen';for(let i=l+2;i<r-2;i+=5){const h=world.water[i];if(h<2)continue;const u=.5*(world.q[i]+world.q[i+1])/Math.max(.2,h),x=sx(i*world.dx),y=sy(world.waterSurfaceY(i*world.dx));ctx.strokeStyle=`rgba(194,244,233,${clamp(.08+Math.abs(u)*.04,.08,.42)})`;ctx.lineWidth=.8*cam.z;ctx.beginPath();ctx.moveTo(x-8*cam.z,y+Math.sin(world.time*2+i)*1.5);ctx.lineTo(x+9*cam.z,y-1);ctx.stroke();}ctx.globalCompositeOperation='source-over';};
  for(let i=b.l;i<=b.r+1;i++){const wet=i<=b.r&&world.water[i]>.7;if(wet&&start<0)start=i;if((!wet||i>b.r)&&start>=0){if(i-start>1)renderSeg(start,i-1);start=-1;}}
}
function plantGeom(p){const wx=p.x*world.dx,baseY=world.surfaceY(wx),s=9+28*p.biomass,bend=p.bend*s*.55;return{wx,baseY,s,bend};}
function drawPlant(p,depth=0){if(!p.alive)return;const {wx,baseY,s,bend}=plantGeom(p),x=sx(wx,depth),y=sy(baseY,depth),seed=p.seed;
  if(p.type==='fungus'){const glow=.18+.22*p.energy;ctx.globalCompositeOperation='screen';const rg=ctx.createRadialGradient(x,y-s*.55,1,x,y-s*.55,s*.9*cam.z);rg.addColorStop(0,`rgba(83,238,191,${glow})`);rg.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=rg;ctx.fillRect(x-s,y-s*1.6,s*2,s*1.8);ctx.globalCompositeOperation='source-over';ctx.strokeStyle='#78978a';ctx.lineWidth=Math.max(1,2*cam.z);ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+bend*.35,y-s*.35,x+bend*.7,y-s*.72);ctx.stroke();ctx.fillStyle='#6fc0a1';ctx.beginPath();ctx.ellipse(x+bend*.7,y-s*.75,s*.32*cam.z,s*.15*cam.z,0,Math.PI,0);ctx.fill();return;}
  const branches=p.type==='shrub'?5:p.type==='fern'?4:2;ctx.strokeStyle=p.type==='reed'?'#5a8969':'#47715c';ctx.lineWidth=Math.max(1.1,(1.7+p.biomass*.8)*cam.z);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+bend*.25,y-s*.45,x+bend,y-s);ctx.stroke();
  for(let j=0;j<branches;j++){const t=.3+j/(branches+2),bx=x+bend*t,by=y-s*t,dir=j%2?-1:1,len=s*(.25+.06*Math.sin(seed+j))*cam.z;ctx.strokeStyle='#3c664f';ctx.lineWidth=Math.max(.8,1.15*cam.z);ctx.beginPath();ctx.moveTo(bx,by);ctx.quadraticCurveTo(bx+dir*len*.45,by-len*.12,bx+dir*len,by-len*.22);ctx.stroke();const lx=bx+dir*len,ly=by-len*.22;ctx.fillStyle=p.type==='fern'?'rgba(69,133,91,.86)':'rgba(68,113,78,.9)';ctx.beginPath();ctx.ellipse(lx,ly,6*p.biomass*cam.z,2.4*p.biomass*cam.z,dir*.25,0,Math.PI*2);ctx.fill();}
}
function drawCreature(c,depth=0){if(!c.alive)return;const nodes=c.nodes,head=c.dir>0?nodes[4]:nodes[0];ctx.lineCap='round';
  for(const leg of c.legs.filter(l=>l.side<0)){const a=nodes[leg.anchor],pts=[[sx(a.x,depth-.06),sy(a.y,depth-.06)],[sx(leg.knee.x,depth-.06),sy(leg.knee.y,depth-.06)],[sx(leg.foot.x,depth-.06),sy(leg.foot.y,depth-.06)]];ctx.strokeStyle='rgba(20,28,25,.95)';ctx.lineWidth=3.5*cam.z;ctx.beginPath();ctx.moveTo(...pts[0]);ctx.lineTo(...pts[1]);ctx.lineTo(...pts[2]);ctx.stroke();ctx.strokeStyle='rgba(88,111,99,.85)';ctx.lineWidth=1.1*cam.z;ctx.stroke();}
  const pts=nodes.map(n=>[sx(n.x,depth),sy(n.y,depth)]),widths=[4.2,7,8.5,7,4.5].map(v=>v*cam.z),nx=[],ny=[];for(let i=0;i<pts.length;i++){const p0=pts[Math.max(0,i-1)],p1=pts[Math.min(pts.length-1,i+1)],dx=p1[0]-p0[0],dy=p1[1]-p0[1],d=Math.hypot(dx,dy)||1;nx[i]=-dy/d;ny[i]=dx/d;}const upper=pts.map((p,i)=>[p[0]+nx[i]*widths[i],p[1]+ny[i]*widths[i]]),lower=pts.map((p,i)=>[p[0]-nx[i]*widths[i],p[1]-ny[i]*widths[i]]).reverse(),body=[...upper,...lower],g=ctx.createLinearGradient(0,Math.min(...body.map(p=>p[1])),0,Math.max(...body.map(p=>p[1])));g.addColorStop(0,'#8da499');g.addColorStop(.22,'#496159');g.addColorStop(.72,'#1d2a27');g.addColorStop(1,'#0b1211');ctx.fillStyle=g;ctx.strokeStyle='#101817';ctx.lineWidth=1.6*cam.z;smoothPath(body,true);ctx.fill();ctx.stroke();
  for(let i=1;i<4;i++){const p=pts[i],a=Math.atan2(pts[Math.min(4,i+1)][1]-pts[Math.max(0,i-1)][1],pts[Math.min(4,i+1)][0]-pts[Math.max(0,i-1)][0]);ctx.save();ctx.translate(p[0],p[1]);ctx.rotate(a);ctx.strokeStyle='rgba(183,204,191,.38)';ctx.lineWidth=.8*cam.z;ctx.beginPath();ctx.ellipse(0,0,6.5*cam.z,7.5*cam.z,0,-1.1,1.1);ctx.stroke();ctx.restore();}
  for(const leg of c.legs.filter(l=>l.side>0)){const a=nodes[leg.anchor],pts2=[[sx(a.x,depth+.06),sy(a.y,depth+.06)],[sx(leg.knee.x,depth+.06),sy(leg.knee.y,depth+.06)],[sx(leg.foot.x,depth+.06),sy(leg.foot.y,depth+.06)]];ctx.strokeStyle='#111a18';ctx.lineWidth=3.2*cam.z;ctx.beginPath();ctx.moveTo(...pts2[0]);ctx.lineTo(...pts2[1]);ctx.lineTo(...pts2[2]);ctx.stroke();ctx.strokeStyle='rgba(111,139,125,.8)';ctx.lineWidth=1*cam.z;ctx.stroke();}
  const hx=sx(head.x,depth+.08),hy=sy(head.y,depth+.08),mx=sx(c.mouth.x,depth+.08),my=sy(c.mouth.y,depth+.08),ang=Math.atan2(my-hy,mx-hx);ctx.save();ctx.translate(hx,hy);ctx.rotate(ang);ctx.fillStyle='#31433d';ctx.strokeStyle='#0c1211';ctx.lineWidth=1.3*cam.z;ctx.beginPath();ctx.ellipse(2*cam.z,0,6.2*cam.z,5*cam.z,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#d8e9de';for(const ey of [-2.4,2.4]){ctx.beginPath();ctx.arc(4.2*cam.z,ey*cam.z,1.15*cam.z,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(4.6*cam.z,ey*cam.z,.45*cam.z,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d8e9de';}ctx.strokeStyle='#b6c5bd';ctx.lineWidth=.9*cam.z;ctx.beginPath();ctx.moveTo(6*cam.z,-1.8*cam.z);ctx.lineTo(10*cam.z,0);ctx.lineTo(6*cam.z,1.8*cam.z);ctx.stroke();ctx.restore();
}
function drawRain(){if(world.rain<.02)return;ctx.strokeStyle=`rgba(175,218,219,${.16+world.rain*.3})`;ctx.lineWidth=1;const count=Math.floor(35+world.rain*85);for(let k=0;k<count;k++){const xx=((k*97+frame*7)%Math.max(1,W+80))-40,yy=((k*53+frame*13)%Math.max(1,H+100))-50,len=10+((k*17)%17);ctx.beginPath();ctx.moveTo(xx,yy);ctx.lineTo(xx-4,yy+len);ctx.stroke();}}
function render(){if(!ctx)return;ctx.setTransform(DPR,0,0,DPR,0,0);ctx.clearRect(0,0,W,H);drawBackground();drawTerrain();drawWater();const b=visible(),plist=world.plants.filter(p=>p.alive&&p.x>=b.l-3&&p.x<=b.r+3);for(const p of plist)drawPlant(p,-.08);for(const c of world.creatures)if(c.alive&&c.nodes[2].x/world.dx>=b.l-4&&c.nodes[2].x/world.dx<=b.r+4)drawCreature(c,0);for(const p of plist.filter((_,i)=>i%5===0))drawPlant(p,.18);drawRain();const vg=ctx.createRadialGradient(W*.5,H*.5,Math.min(W,H)*.25,W*.5,H*.5,Math.max(W,H)*.72);vg.addColorStop(0,'rgba(0,0,0,0)');vg.addColorStop(1,'rgba(0,0,0,.46)');ctx.fillStyle=vg;ctx.fillRect(0,0,W,H);}
function telemetry(now){if(now-lastTelemetry<250)return;lastTelemetry=now;const alive=world.creatures.filter(c=>c.alive).length,water=world.totalWater(),flow=world.q.reduce((s,v)=>s+Math.abs(v),0)/world.q.length,sel=world.creatures.find(c=>c.id===selected);postMessage({type:'telemetry',alive,water,flow,rain:world.rain,selected:sel?{id:sel.id,energy:sel.energy,hunger:sel.hunger,alive:sel.alive}:null});}
function loop(now){if(!last)last=now;const dt=Math.min(.05,(now-last)/1000);last=now;cam.x+=(cam.targetX-cam.x)*.12;cam.y+=(cam.targetY-cam.y)*.12;cam.z+=(cam.targetZ-cam.z)*.14;if(!paused){acc+=dt*speed;const step=1/60;let n=0;while(acc>=step&&n<5){world.step(step);acc-=step;n++;}}render();telemetry(now);frame++;setTimeout(()=>loop(performance.now()),0);}
onmessage=e=>{const m=e.data||{};if(m.type==='init'){canvas=m.canvas;DPR=clamp(m.dpr||1,1,2);W=m.w;H=m.h;canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});cam.x=world.n*world.dx*.34;cam.targetX=cam.x;cam.y=360;cam.targetY=360;last=performance.now();loop(last);}else if(m.type==='resize'){W=m.w;H=m.h;DPR=clamp(m.dpr||1,1,2);canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);}else if(m.type==='pan'){cam.targetX=clamp(cam.targetX-m.dx/cam.targetZ,0,world.n*world.dx);cam.targetY=clamp(cam.targetY-m.dy/cam.targetZ,120,world.worldH-80);}else if(m.type==='zoom'){cam.targetZ=clamp(cam.targetZ*m.factor,.55,2.7);}else if(m.type==='pause'){paused=!paused;}else if(m.type==='speed'){speed=m.value||1;}else if(m.type==='rain'){world.rain=m.value;}else if(m.type==='reset'){world=new World({seed:m.seed||((Math.random()*1e9)|0),n:512,dx:6,worldH:720});}else if(m.type==='tap'){const wx=cam.x+(m.x-W*.5)/cam.z,wy=cam.y+(m.y-H*.48)/cam.z;let best=null,bd=45/cam.z;for(const c of world.creatures){if(!c.alive)continue;const p=c.nodes[2],d=Math.hypot(p.x-wx,p.y-wy);if(d<bd){bd=d;best=c;}}if(best)selected=best.id;}};
