'use strict';
const canvas=document.getElementById('c'),ctx=canvas.getContext('2d',{alpha:false});
const stats=document.getElementById('stats');
const TAU=Math.PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rand=(a=1,b)=>b===undefined?Math.random()*a:a+Math.random()*(b-a);
let DPR=1,W=0,H=0;
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const WORLD={w:2400,h:1500,gravity:20,waterY:120,drag:0.985,viscosity:0.045,temp:19};
const camera={x:WORLD.w*.5,y:WORLD.h*.48,z:.75};
const plants=[], creatures=[], particles=[];
let births=0,deaths=0,bites=0,selected=null,simTime=0;
class P{constructor(x,y,m=1){this.x=x;this.y=y;this.px=x;this.py=y;this.ax=0;this.ay=0;this.m=m;this.r=2} force(x,y){this.ax+=x/this.m;this.ay+=y/this.m} step(dt){const vx=(this.x-this.px)*WORLD.drag,vy=(this.y-this.py)*WORLD.drag;this.px=this.x;this.py=this.y;this.x+=vx+this.ax*dt*dt;this.y+=vy+this.ay*dt*dt;this.ax=0;this.ay=0;if(this.y>WORLD.waterY)this.force(0,WORLD.gravity*this.m);const speed=Math.hypot(vx,vy);if(this.y>WORLD.waterY){this.force(-vx*WORLD.viscosity*(1+speed*.08)/dt,-vy*WORLD.viscosity*(1+speed*.08)/dt)}if(this.y>WORLD.h-25){this.y=WORLD.h-25;this.py=this.y+(this.py-this.y)*.25}if(this.x<8){this.x=8;this.px=this.x}if(this.x>WORLD.w-8){this.x=WORLD.w-8;this.px=this.x}}}
function distConstraint(a,b,len,stiff=1){let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,err=(d-len)/d*.5*stiff;dx*=err;dy*=err;a.x+=dx;a.y+=dy;b.x-=dx;b.y-=dy}
function bendConstraint(a,b,c,target,stiff){const ab=Math.atan2(a.y-b.y,a.x-b.x),cb=Math.atan2(c.y-b.y,c.x-b.x);let e=(cb-ab)-target;while(e>Math.PI)e-=TAU;while(e<-Math.PI)e+=TAU;const la=Math.hypot(a.x-b.x,a.y-b.y),lc=Math.hypot(c.x-b.x,c.y-b.y),q=e*stiff;const ca=Math.cos(q),sa=Math.sin(q);let ax=a.x-b.x,ay=a.y-b.y,cx=c.x-b.x,cy=c.y-b.y;a.x=b.x+ax*ca-ay*sa;a.y=b.y+ax*sa+ay*ca;const cc=Math.cos(-q),ss=Math.sin(-q);c.x=b.x+cx*cc-cy*ss;c.y=b.y+cx*ss+cy*cc;distConstraint(a,b,la,.5);distConstraint(b,c,lc,.5)}
class Plant{constructor(x,y){this.x=x;this.y=y;this.energy=rand(15,45);this.max=this.energy;this.dead=false;this.seed=rand(TAU)} step(dt){this.energy=Math.min(this.max,this.energy+dt*.25*(1+.35*Math.sin(simTime*.03+this.seed)));if(this.energy<.1)this.dead=true}}
class Genome{constructor(parent=null){if(parent){Object.assign(this,parent);for(const k of ['segmentLen','muscle','frequency','sensor','metabolism','size','carnivory','aggression','turnGain'])this[k]=Math.max(.03,this[k]*(1+rand(-.09,.09)));this.hue=(this.hue+rand(-8,8)+360)%360}else{this.segments=Math.round(rand(5,10));this.segmentLen=rand(9,15);this.muscle=rand(.45,1.3);this.frequency=rand(.6,1.8);this.sensor=rand(90,220);this.metabolism=rand(.7,1.25);this.size=rand(.75,1.35);this.carnivory=rand(0,1);this.aggression=rand(.15,.9);this.turnGain=rand(.35,1.3);this.hue=rand(0,360)}}}
class Creature{
 constructor(x,y,g=null){this.g=g||new Genome();this.nodes=[];this.energy=110;this.health=1;this.age=0;this.dead=false;this.repro=rand(95,145);this.osc=rand(TAU);this.intentX=1;this.intentY=0;this.target=null;this.lastBite=0;this.children=0;this.id=(Math.random()*1e9)|0;const a=rand(TAU);for(let i=0;i<this.g.segments;i++){const p=new P(x-Math.cos(a)*i*this.g.segmentLen,y-Math.sin(a)*i*this.g.segmentLen,this.g.size);p.r=this.g.segmentLen*.3*this.g.size;this.nodes.push(p);particles.push(p)}}
 head(){return this.nodes[0]} tail(){return this.nodes[this.nodes.length-1]} mass(){return this.g.segments*this.g.segmentLen*this.g.size}
 sense(){const h=this.head(),R=this.g.sensor;let best=null,bd=R*R;if(this.g.carnivory>.52){for(const c of creatures){if(c===this||c.dead)continue;const q=c.head(),dx=q.x-h.x,dy=q.y-h.y,d=dx*dx+dy*dy;if(d<bd&&c.mass()<this.mass()*1.45){bd=d;best={x:q.x,y:q.y,obj:c,type:'prey'}}}}if(!best||this.energy<65){for(const p of plants){if(p.dead||p.energy<1)continue;const dx=p.x-h.x,dy=p.y-h.y,d=dx*dx+dy*dy;if(d<bd){bd=d;best={x:p.x,y:p.y,obj:p,type:'plant'}}}}this.target=best;if(best){const dx=best.x-h.x,dy=best.y-h.y,d=Math.hypot(dx,dy)||1;this.intentX=dx/d;this.intentY=dy/d}else{const a=this.osc*.11+this.id*.000001;this.intentX=Math.cos(a);this.intentY=Math.sin(a)*.35}}
 step(dt){if(this.dead)return;this.age+=dt;this.osc+=dt*this.g.frequency*TAU;this.lastBite-=dt;this.energy-=dt*(.38*this.g.metabolism+.008*this.mass());if(this.energy<=0||this.health<=0||this.age>420){this.die();return}this.sense();const h=this.head(),n=this.nodes[1],hx=h.x-n.x,hy=h.y-n.y,hl=Math.hypot(hx,hy)||1;const fx=hx/hl,fy=hy/hl,cross=fx*this.intentY-fy*this.intentX;const drive=clamp(this.energy/60,0,1)*this.g.muscle;for(let i=1;i<this.nodes.length-1;i++){const phase=this.osc-i*.7;const desired=Math.sin(phase)*.42*drive + cross*this.g.turnGain*(i/(this.nodes.length-1));const a=this.nodes[i-1],b=this.nodes[i],c=this.nodes[i+1];bendConstraint(a,b,c,desired,.055+.035*this.g.muscle)}const tail=this.tail();const pre=this.nodes[this.nodes.length-2],tx=tail.x-pre.x,ty=tail.y-pre.y,tl=Math.hypot(tx,ty)||1;const sideX=-ty/tl,sideY=tx/tl;const muscleVelocity=Math.cos(this.osc-(this.nodes.length-1)*.7)*this.g.frequency;tail.force(sideX*muscleVelocity*150*this.g.muscle,sideY*muscleVelocity*150*this.g.muscle);
  for(let k=0;k<5;k++){for(let i=1;i<this.nodes.length;i++)distConstraint(this.nodes[i-1],this.nodes[i],this.g.segmentLen,.92);for(let i=1;i<this.nodes.length-1;i++){const phase=this.osc-i*.7;const desired=Math.sin(phase)*.42*drive+cross*this.g.turnGain*(i/(this.nodes.length-1));bendConstraint(this.nodes[i-1],this.nodes[i],this.nodes[i+1],desired,.035)}}
  this.feed();if(this.energy>this.repro&&this.age>18&&creatures.length<180){this.energy*=.58;const q=this.tail();creatures.push(new Creature(q.x+rand(-12,12),q.y+rand(-12,12),new Genome(this.g)));this.children++;births++}
 }
 feed(){if(!this.target||this.lastBite>0)return;const h=this.head(),dx=this.target.x-h.x,dy=this.target.y-h.y,d=Math.hypot(dx,dy);if(d>this.g.segmentLen*1.15)return;if(this.target.type==='plant'){const p=this.target.obj,take=Math.min(p.energy,7);p.energy-=take;this.energy+=take*.72;this.lastBite=.7;bites++}else{const c=this.target.obj;if(c.dead)return;const impulse=clamp(this.mass()/Math.max(1,c.mass()),.35,1.7);c.health-=.08*impulse*this.g.aggression;const ch=c.head();ch.force(dx*18,dy*18);this.energy+=1.5;this.lastBite=.55;bites++;if(c.health<=0){this.energy+=Math.min(35,c.mass()*.12);c.die()}}}
 die(){if(this.dead)return;this.dead=true;deaths++;for(const n of this.nodes)n.m*=.85}
}
for(let i=0;i<450;i++)plants.push(new Plant(rand(40,WORLD.w-40),rand(WORLD.waterY+80,WORLD.h-60)));
for(let i=0;i<42;i++)creatures.push(new Creature(rand(200,WORLD.w-200),rand(WORLD.waterY+120,WORLD.h-200)));
function physics(dt){for(const p of plants)p.step(dt);for(const c of creatures)c.step(dt);for(const p of particles)p.step(dt);for(let pass=0;pass<4;pass++){for(const c of creatures){if(c.dead)continue;for(let i=1;i<c.nodes.length;i++)distConstraint(c.nodes[i-1],c.nodes[i],c.g.segmentLen,.96)}}for(let i=plants.length-1;i>=0;i--)if(plants[i].dead)plants.splice(i,1);if(plants.length<450&&Math.random()<dt*12)plants.push(new Plant(rand(30,WORLD.w-30),rand(WORLD.waterY+100,WORLD.h-40)));for(let i=creatures.length-1;i>=0;i--){const c=creatures[i];if(c.dead&&c.age>450){creatures.splice(i,1)}}simTime+=dt}
function sx(x){return (x-camera.x)*camera.z+W/2}function sy(y){return (y-camera.y)*camera.z+H/2}
function render(){ctx.fillStyle='#061017';ctx.fillRect(0,0,W,H);const gy=sy(WORLD.waterY);const grd=ctx.createLinearGradient(0,Math.max(0,gy),0,H);grd.addColorStop(0,'#0a2631');grd.addColorStop(1,'#06181d');ctx.fillStyle=grd;ctx.fillRect(0,gy,W,H-gy);ctx.strokeStyle='#80fff11f';ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<W;x+=18){const wx=(x-W/2)/camera.z+camera.x;const y=gy+Math.sin(wx*.025+simTime*1.2)*2;ctx.lineTo(x,y)}ctx.stroke();
 for(const p of plants){const x=sx(p.x),y=sy(p.y);if(x<-20||x>W+20||y<-20||y>H+20)continue;const e=p.energy/p.max;ctx.strokeStyle=`hsla(${125+e*30},70%,55%,${.22+.55*e})`;ctx.lineWidth=Math.max(1,2*camera.z);ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+Math.sin(simTime*.7+p.seed)*8*camera.z,y-10*camera.z,x+Math.sin(simTime*.5+p.seed)*12*camera.z,y-22*camera.z);ctx.stroke()}
 for(const c of creatures){const pts=c.nodes.map(n=>({x:sx(n.x),y:sy(n.y)}));if(pts.every(p=>p.x<-80||p.x>W+80||p.y<-80||p.y>H+80))continue;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=c.dead?'#6a7775':`hsla(${c.g.hue},78%,63%,.88)`;ctx.lineWidth=Math.max(2,c.g.segmentLen*c.g.size*.58*camera.z);ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i].x,pts[i].y);ctx.stroke();ctx.strokeStyle=c.dead?'#82908d55':`hsla(${c.g.hue+35},95%,80%,.28)`;ctx.lineWidth=Math.max(1,c.g.segmentLen*.12*camera.z);ctx.stroke();const h=pts[0],n=pts[1],a=Math.atan2(h.y-n.y,h.x-n.x);ctx.fillStyle=c.dead?'#76807f':`hsl(${c.g.hue},82%,68%)`;ctx.beginPath();ctx.arc(h.x,h.y,Math.max(3,c.g.segmentLen*.45*c.g.size*camera.z),0,TAU);ctx.fill();ctx.fillStyle='#dffff4';ctx.beginPath();ctx.arc(h.x+Math.cos(a)*4*camera.z-Math.sin(a)*3*camera.z,h.y+Math.sin(a)*4*camera.z+Math.cos(a)*3*camera.z,Math.max(1,1.7*camera.z),0,TAU);ctx.fill();if(c===selected){ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(h.x,h.y,c.g.sensor*camera.z,0,TAU);ctx.stroke()}}
 if(selected&&!selected.dead){const h=selected.head();ctx.fillStyle='#d9fff1';ctx.font='12px ui-monospace,monospace';ctx.fillText(`id ${selected.id}  E ${selected.energy.toFixed(0)}  health ${(selected.health*100).toFixed(0)}%  age ${selected.age.toFixed(1)}s`,12,H-18)} }
let accumulator=0,last=performance.now(),fps=0,frames=0,fpst=0;
function loop(now){let real=Math.min(.05,(now-last)/1000);last=now;accumulator+=real;const dt=1/120;let steps=0;while(accumulator>=dt&&steps<8){physics(dt);accumulator-=dt;steps++}render();frames++;fpst+=real;if(fpst>.5){fps=frames/fpst;frames=0;fpst=0;const alive=creatures.filter(c=>!c.dead).length;stats.textContent=`life ${alive} • plants ${plants.length} • physics 120 Hz • ${fps.toFixed(0)} fps • births ${births} • deaths ${deaths} • bites ${bites}`;}requestAnimationFrame(loop)}requestAnimationFrame(loop);
let touches=new Map(),dragLast=null,pinchLast=0;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,{x:e.clientX,y:e.clientY});dragLast={x:e.clientX,y:e.clientY};if(touches.size===1){const wx=(e.clientX-W/2)/camera.z+camera.x,wy=(e.clientY-H/2)/camera.z+camera.y;let b=null,bd=35/camera.z;for(const c of creatures){if(c.dead)continue;const h=c.head(),d=Math.hypot(h.x-wx,h.y-wy);if(d<bd){bd=d;b=c}}selected=b}});
canvas.addEventListener('pointermove',e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});const a=[...touches.values()];if(a.length===1&&dragLast){camera.x-= (e.clientX-dragLast.x)/camera.z;camera.y-= (e.clientY-dragLast.y)/camera.z;dragLast={x:e.clientX,y:e.clientY}}else if(a.length>=2){const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinchLast){camera.z=clamp(camera.z*(d/pinchLast),.25,2.6)}pinchLast=d}});
canvas.addEventListener('pointerup',e=>{touches.delete(e.pointerId);pinchLast=0;dragLast=null});canvas.addEventListener('pointercancel',e=>{touches.delete(e.pointerId);pinchLast=0;dragLast=null});
