'use strict';
const canvas=document.getElementById('c'),ctx=canvas.getContext('2d',{alpha:false});
const stats=document.getElementById('stats');
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
let seed=0x6d2b79f5;function rng(){seed|=0;seed=seed+0x6D2B79F5|0;let t=seed;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}function rr(a,b){return a+(b-a)*rng()}
let DPR=1,W=0,H=0;function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const WORLD={w:2200,h:1300,waterY:70,floor:1240,drag:.987,visc:.038,g:11};
const camera={x:1100,y:650,z:.78};let simTime=0,births=0,deaths=0,bites=0,selected=null;
const GW=72,GH=42,N=GW*GH,biomass=new Float32Array(N),nutrient=new Float32Array(N),oxygen=new Float32Array(N),nextB=new Float32Array(N),nextN=new Float32Array(N),nextO=new Float32Array(N);
const idx=(x,y)=>clamp(y,0,GH-1)*GW+clamp(x,0,GW-1),cellX=x=>clamp(Math.floor(x/WORLD.w*GW),0,GW-1),cellY=y=>clamp(Math.floor(y/WORLD.h*GH),0,GH-1);
function lightAtY(y){const depth=clamp((y-WORLD.waterY)/(WORLD.floor-WORLD.waterY),0,1);return Math.exp(-2.45*depth)}
for(let y=0;y<GH;y++)for(let x=0;x<GW;x++){const i=idx(x,y),wy=(y+.5)/GH*WORLD.h,shore=1-clamp(Math.abs(x/GW-.5)*1.65,0,1);nutrient[i]=.28+.62*(wy/WORLD.h)+.12*shore;oxygen[i]=.62+.32*lightAtY(wy);biomass[i]=wy>WORLD.waterY+90?(rr(.08,.22)*lightAtY(wy)*(0.5+.5*nutrient[i])):0}
function fieldStep(dt){for(let y=0;y<GH;y++)for(let x=0;x<GW;x++){const i=idx(x,y),b=biomass[i],n=nutrient[i],o=oxygen[i],wy=(y+.5)/GH*WORLD.h,L=lightAtY(wy),lapB=(biomass[idx(x-1,y)]+biomass[idx(x+1,y)]+biomass[idx(x,y-1)]+biomass[idx(x,y+1)]-4*b),lapN=(nutrient[idx(x-1,y)]+nutrient[idx(x+1,y)]+nutrient[idx(x,y-1)]+nutrient[idx(x,y+1)]-4*n),lapO=(oxygen[idx(x-1,y)]+oxygen[idx(x+1,y)]+oxygen[idx(x,y-1)]+oxygen[idx(x,y+1)]-4*o);const growth=.18*L*n*b*(1-b/.95),resp=.018*b;nextB[i]=clamp(b+dt*(growth-resp+.025*lapB),0,1);nextN[i]=clamp(n+dt*(-growth*.34+resp*.42+.055*lapN),0,1);nextO[i]=clamp(o+dt*(growth*.26-resp*.16+.09*lapO),.03,1)}biomass.set(nextB);nutrient.set(nextN);oxygen.set(nextO)}
class Node{constructor(x,y,m){this.x=x;this.y=y;this.px=x;this.py=y;this.ax=0;this.ay=0;this.m=m}force(x,y){this.ax+=x/this.m;this.ay+=y/this.m}step(dt){let vx=(this.x-this.px)*WORLD.drag,vy=(this.y-this.py)*WORLD.drag;this.px=this.x;this.py=this.y;this.x+=vx+this.ax*dt*dt;this.y+=vy+this.ay*dt*dt;this.ax=this.ay=0;const speed=Math.hypot(vx,vy);this.force(-vx*WORLD.visc*(1+speed*.07)/dt,-vy*WORLD.visc*(1+speed*.07)/dt);this.force(0,WORLD.g*this.m*.05);if(this.y<WORLD.waterY+10){this.y=WORLD.waterY+10;this.py=this.y}if(this.y>WORLD.floor){this.y=WORLD.floor;this.py=this.y+(this.py-this.y)*.18}if(this.x<8){this.x=8;this.px=this.x}if(this.x>WORLD.w-8){this.x=WORLD.w-8;this.px=this.x}}}
function dc(a,b,len,k=1){let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,e=(d-len)/d*.5*k;dx*=e;dy*=e;a.x+=dx;a.y+=dy;b.x-=dx;b.y-=dy}
function bc(a,b,c,target,k){const ab=Math.atan2(a.y-b.y,a.x-b.x),cb=Math.atan2(c.y-b.y,c.x-b.x);let e=(cb-ab)-target;while(e>Math.PI)e-=TAU;while(e<-Math.PI)e+=TAU;const q=e*k,ca=Math.cos(q),sa=Math.sin(q),cc=Math.cos(-q),ss=Math.sin(-q);let ax=a.x-b.x,ay=a.y-b.y,cx=c.x-b.x,cy=c.y-b.y;a.x=b.x+ax*ca-ay*sa;a.y=b.y+ax*sa+ay*ca;c.x=b.x+cx*cc-cy*ss;c.y=b.y+cx*ss+cy*cc}
class Genome{constructor(kind='grazer',p=null){this.kind=kind;if(p){Object.assign(this,p);const mut=(v,s,a,b)=>clamp(v*(1+rr(-s,s)),a,b);this.len=mut(this.len,.045,10,19);this.mass=mut(this.mass,.04,.7,1.8);this.muscle=mut(this.muscle,.05,.55,1.45);this.sensor=mut(this.sensor,.05,110,300);this.freq=mut(this.freq,.04,.7,1.7);this.turn=mut(this.turn,.05,.4,1.5)}else if(kind==='grazer'){this.segments=8;this.len=13;this.mass=.95;this.muscle=.78;this.sensor=185;this.freq=1.05;this.turn=.85}else{this.segments=10;this.len=15;this.mass=1.32;this.muscle=1.15;this.sensor=255;this.freq=1.22;this.turn=1.15}}}
const creatures=[],nodes=[];
class Creature{constructor(x,y,g){this.g=g;this.nodes=[];this.energy=g.kind==='grazer'?92:125;this.health=1;this.age=0;this.dead=false;this.phase=rr(0,TAU);this.cool=0;this.id=(rng()*1e9)|0;this.targetX=x+1;this.targetY=y;this.mode='forage';const a=rr(-.4,.4);for(let i=0;i<g.segments;i++){const n=new Node(x-Math.cos(a)*i*g.len,y-Math.sin(a)*i*g.len,g.mass);this.nodes.push(n);nodes.push(n)}}head(){return this.nodes[0]}mass(){return this.g.segments*this.g.len*this.g.mass}heading(){const a=this.nodes[0],b=this.nodes[1],dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy)||1;return{x:dx/d,y:dy/d}}
 sampleBiomass(angle,dist){const h=this.head(),f=this.heading(),base=Math.atan2(f.y,f.x)+angle,x=h.x+Math.cos(base)*dist,y=h.y+Math.sin(base)*dist;return biomass[idx(cellX(x),cellY(y))]}
 perceive(){const h=this.head(),f=this.heading();if(this.g.kind==='predator'){let best=null,bd=this.g.sensor*this.g.sensor;for(const c of creatures){if(c===this||c.dead||c.g.kind!=='grazer')continue;const q=c.head(),dx=q.x-h.x,dy=q.y-h.y,d=dx*dx+dy*dy;if(d<bd){bd=d;best=q}}if(best){this.targetX=best.x;this.targetY=best.y;this.mode='hunt';return}}const L=this.sampleBiomass(-.55,this.g.sensor*.55),C=this.sampleBiomass(0,this.g.sensor*.55),R=this.sampleBiomass(.55,this.g.sensor*.55);let a=0;if(L>C&&L>R)a=-.55;else if(R>C&&R>L)a=.55;const heading=Math.atan2(f.y,f.x)+a;this.targetX=h.x+Math.cos(heading)*this.g.sensor*.6;this.targetY=h.y+Math.sin(heading)*this.g.sensor*.6;this.mode=this.g.kind==='grazer'?'graze':'search'}
 feed(){const h=this.head(),ci=idx(cellX(h.x),cellY(h.y));if(this.g.kind==='grazer'){const take=Math.min(biomass[ci],.12);if(take>.002){biomass[ci]-=take;this.energy+=take*52;nutrient[ci]=clamp(nutrient[ci]+take*.08,0,1)}}else if(this.cool<=0){let victim=null,bd=(this.g.len*1.15)**2;for(const c of creatures){if(c.dead||c===this||c.g.kind!=='grazer')continue;const q=c.head(),dx=q.x-h.x,dy=q.y-h.y,d=dx*dx+dy*dy;if(d<bd){bd=d;victim=c}}if(victim){const dm=.11*clamp(this.mass()/victim.mass(),.55,1.65);victim.health-=dm;this.energy+=dm*18;this.cool=.5;bites++;if(victim.health<=0)victim.die()}}}
 die(){if(this.dead)return;this.dead=true;deaths++;const h=this.head(),ci=idx(cellX(h.x),cellY(h.y));nutrient[ci]=clamp(nutrient[ci]+Math.min(.55,this.mass()*.0017),0,1)}
 step(dt){if(this.dead)return;this.age+=dt;this.cool=Math.max(0,this.cool-dt);this.perceive();const h=this.head(),f=this.heading(),dx=this.targetX-h.x,dy=this.targetY-h.y,d=Math.hypot(dx,dy)||1,tx=dx/d,ty=dy/d,cross=f.x*ty-f.y*tx,ci=idx(cellX(h.x),cellY(h.y)),oxy=oxygen[ci];const speed=Math.hypot(h.x-h.px,h.y-h.py)/dt;const drive=clamp((this.energy/70)*oxy,0,.95);this.phase+=dt*this.g.freq*TAU*(.6+.6*drive);const cost=dt*(.08*this.mass()*.01+.000025*speed*speed*this.mass()+.11*this.g.muscle*drive);this.energy-=cost;if(this.energy<=0||oxy<.045||this.age>(this.g.kind==='grazer'?520:650)){this.die();return}
 for(let i=1;i<this.nodes.length-1;i++){const wave=Math.sin(this.phase-i*.72)*.34*drive,corr=cross*this.g.turn*(i/(this.nodes.length-1));bc(this.nodes[i-1],this.nodes[i],this.nodes[i+1],wave+corr,.045+.02*this.g.muscle)}const tail=this.nodes[this.nodes.length-1],pre=this.nodes[this.nodes.length-2],vx=tail.x-pre.x,vy=tail.y-pre.y,vl=Math.hypot(vx,vy)||1,sx=-vy/vl,sy=vx/vl;tail.force(sx*Math.cos(this.phase-this.nodes.length*.72)*120*this.g.muscle*drive,sy*Math.cos(this.phase-this.nodes.length*.72)*120*this.g.muscle*drive);for(let p=0;p<4;p++)for(let i=1;i<this.nodes.length;i++)dc(this.nodes[i-1],this.nodes[i],this.g.len,.94);this.feed();const repro=this.g.kind==='grazer'?128:175;if(this.energy>repro&&this.age>55&&creatures.filter(c=>!c.dead).length<90){this.energy*=.56;const q=this.nodes[this.nodes.length-1],child=new Creature(q.x,q.y,new Genome(this.g.kind,this.g));creatures.push(child);births++}}
}
function spawnInitial(){for(let i=0;i<18;i++)creatures.push(new Creature(rr(260,1700),rr(300,1080),new Genome('grazer')));for(let i=0;i<5;i++)creatures.push(new Creature(rr(900,1900),rr(420,1000),new Genome('predator')))}spawnInitial();
function physics(dt){fieldStep(dt);for(const c of creatures)c.step(dt);for(const n of nodes)n.step(dt);simTime+=dt}
const sx=x=>(x-camera.x)*camera.z+W/2,sy=y=>(y-camera.y)*camera.z+H/2;
function render(){ctx.fillStyle='#061017';ctx.fillRect(0,0,W,H);const water=sy(WORLD.waterY);const g=ctx.createLinearGradient(0,water,0,H);g.addColorStop(0,'#123744');g.addColorStop(1,'#07161b');ctx.fillStyle=g;ctx.fillRect(0,water,W,H-water);
 const cw=WORLD.w/GW,ch=WORLD.h/GH;for(let y=0;y<GH;y+=2)for(let x=0;x<GW;x+=2){const b=biomass[idx(x,y)];if(b<.035)continue;const px=sx(x*cw),py=sy(y*ch),ww=cw*2*camera.z,hh=ch*2*camera.z;ctx.fillStyle=`rgba(64,154,92,${clamp(b*.32,.02,.22)})`;ctx.fillRect(px,py,ww,hh)}
 for(const c of creatures){const p=c.nodes.map(n=>({x:sx(n.x),y:sy(n.y)}));if(p.every(q=>q.x<-100||q.x>W+100||q.y<-100||q.y>H+100))continue;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=c.dead?'#68716e':c.g.kind==='predator'?'#c7896a':'#78b89a';ctx.lineWidth=Math.max(3,c.g.len*c.g.mass*.62*camera.z);ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<p.length;i++)ctx.lineTo(p[i].x,p[i].y);ctx.stroke();const h=p[0],n=p[1],a=Math.atan2(h.y-n.y,h.x-n.x);ctx.fillStyle=c.dead?'#747b79':c.g.kind==='predator'?'#deaa89':'#98d5b5';ctx.beginPath();ctx.ellipse(h.x,h.y,c.g.len*.58*c.g.mass*camera.z,c.g.len*.42*c.g.mass*camera.z,a,0,TAU);ctx.fill();ctx.fillStyle='#e9fff8';ctx.beginPath();ctx.arc(h.x+Math.cos(a)*5*camera.z-Math.sin(a)*3*camera.z,h.y+Math.sin(a)*5*camera.z+Math.cos(a)*3*camera.z,Math.max(1.2,1.7*camera.z),0,TAU);ctx.fill();if(c===selected){ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(h.x,h.y,c.g.sensor*camera.z,0,TAU);ctx.stroke()}}
 if(selected&&!selected.dead){ctx.fillStyle='#e4fff5';ctx.font='12px ui-monospace,monospace';ctx.fillText(`${selected.g.kind}  E ${selected.energy.toFixed(1)}  health ${(selected.health*100).toFixed(0)}%  mode ${selected.mode}`,12,H-18)}}
let acc=0,last=performance.now(),frames=0,ft=0,fps=0;function loop(now){const real=Math.min(.05,(now-last)/1000);last=now;acc+=real;const dt=1/120;let s=0;while(acc>=dt&&s<8){physics(dt);acc-=dt;s++}render();frames++;ft+=real;if(ft>.5){fps=frames/ft;frames=0;ft=0;const alive=creatures.filter(c=>!c.dead),g=alive.filter(c=>c.g.kind==='grazer').length,p=alive.filter(c=>c.g.kind==='predator').length;let B=0;for(const v of biomass)B+=v;stats.textContent=`grazers ${g} • predators ${p} • biomass ${(B/N).toFixed(2)} • physics 120 Hz • ${fps.toFixed(0)} fps • births ${births} • deaths ${deaths}`;}requestAnimationFrame(loop)}requestAnimationFrame(loop);
let touches=new Map(),drag=null,pinch=0;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,{x:e.clientX,y:e.clientY});drag={x:e.clientX,y:e.clientY};const wx=(e.clientX-W/2)/camera.z+camera.x,wy=(e.clientY-H/2)/camera.z+camera.y;let best=null,bd=45/camera.z;for(const c of creatures){if(c.dead)continue;const h=c.head(),d=Math.hypot(h.x-wx,h.y-wy);if(d<bd){bd=d;best=c}}selected=best});canvas.addEventListener('pointermove',e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});const a=[...touches.values()];if(a.length===1&&drag){camera.x-= (e.clientX-drag.x)/camera.z;camera.y-= (e.clientY-drag.y)/camera.z;drag={x:e.clientX,y:e.clientY}}else if(a.length>=2){const d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(pinch)camera.z=clamp(camera.z*(d/pinch),.28,2.5);pinch=d}});for(const ev of ['pointerup','pointercancel'])canvas.addEventListener(ev,e=>{touches.delete(e.pointerId);drag=null;pinch=0});