import assert from 'node:assert/strict';
import { createWorld,CHUNK_COUNT,CHUNK_COLS,CHUNK_ROWS,WORLD_W,WORLD_H,BIOMES,DISTRICT_TYPES,chunkIndexFor,rebuildOccupancy,takeChunkBatch,updateEnvironment } from '../src/world.js';
import { emptyLibrary } from '../src/evolution.js';
const i=(op,arg=0)=>({op,arg}),w=createWorld(123);assert.equal(CHUNK_COUNT,384);assert.equal(CHUNK_COLS,24);assert.equal(CHUNK_ROWS,16);assert.equal(w.chunks.length,CHUNK_COUNT);assert.equal(chunkIndexFor(0,0),0);assert.equal(chunkIndexFor(WORLD_W-1,WORLD_H-1),CHUNK_COUNT-1);
const biomes=new Set(w.chunks.map(c=>c.biome)),geology=new Set(w.chunks.map(c=>c.geology)),sites=new Set(w.chunks.map(c=>c.site));assert.ok(biomes.size>=6,`expected >=6 biomes, got ${[...biomes]}`);assert.ok(geology.size>=4,`expected >=4 rock types, got ${[...geology]}`);assert.ok(biomes.has('RIVER'));for(const b of biomes)assert.ok(BIOMES.includes(b));for(const s of sites)assert.ok(DISTRICT_TYPES.includes(s));assert.equal(w.chunks.filter(c=>c.site==='HOME').length,1,'prehistory should begin with one camp, not a prebuilt town');assert.ok(w.chunks.some(c=>c.site==='CAVE'));assert.ok(w.chunks.some(c=>c.site==='GROVE'||c.site==='SPRING'||c.site==='RUIN'));assert.ok(w.summary.rivers>0);assert.ok(Object.keys(w.summary.geology).length>=4);
const camp=w.chunks[w.campId];assert.equal(camp.site,'HOME');assert.ok(camp.shelter>.65);assert.ok(camp.jobs>.25);assert.ok(w.chunks.some(c=>c.biome==='FOREST'&&c.wood>.70));assert.ok(w.chunks.some(c=>c.biome==='RIVER'&&c.water===1));assert.ok(w.chunks.some(c=>c.plateStress>.75));
const lib=emptyLibrary();lib.IS_AHEAD={program:[i('PUSH_A'),i('PUSH_B'),i('GT'),i('HALT')],report:{verified:true}};lib.PICK_LOW={program:[i('PUSH_A'),i('PUSH_B'),i('LT'),i('JZ',2),i('PUSH_A'),i('HALT'),i('PUSH_B'),i('HALT')],report:{verified:true}};camp.drainage=0;updateEnvironment(camp,{floodLevel:1,rain:1});assert.equal(camp.floodAlarm,true);assert.equal(camp.pumpActive,true);assert.ok(camp.pumpRate>0);
const agents=[{alive:true,x:camp.cx*100+50,y:camp.cy*100+50},{alive:true,x:WORLD_W-10,y:WORLD_H-10},{alive:false,x:5,y:5}];rebuildOccupancy(w,agents);assert.equal(w.chunks.reduce((n,c)=>n+c.agents.length,0),2);const before=w.cursor,batch=takeChunkBatch(w,8);assert.equal(batch.length,8);assert.ok(batch.some(c=>c.agents.length),'adaptive scheduler should prioritize occupied chunks');assert.notEqual(w.cursor,before);
console.log(`PASS: ${CHUNK_COUNT} layered chunks, ${biomes.size} biomes, ${geology.size} geology types, one emergent camp, caves/landmarks, evolved flood tools and active-chunk scheduling.`);
