import{World}from'./world.js';
import{TAU,clamp,wrap,ROLE_META,wallet,input,v4State,award,toast,shortest,distance}from'./ecosystem-state-v4.js?v=4';
function roleFor(c,parent){if(parent?.role)return Math.random()<.9?parent.role:Object.keys(ROLE_META)[Math.floor(Math.random()*5)];const n=parseInt(c.brain.genomeHash().slice(0,2),16)/255;return n<.40?'grazer':n<.61?'scavenger':n<.77?'stalker':n<.90?'lurker':'glider'}
function decorate(c,parent){c.role=roleFor(c,parent);const seed=parseInt(c.brain.genomeHash().slice(-4),16);c.morph={segments:2+seed%5,legs:c.role==='glider'?0:2+((seed>>3)%3)*2,eyes:1+((seed>>5)%3),antenna:(seed>>7)%3,spines:c.role==='stalker'||c.role==='lurker',pattern:(seed>>9)%4,tail:.7+((seed%11)/10)};c.ai={mode:'wander',fear:0,hunger:0,targetId:0,den:-1,memoryX:c.x,memoryY:c.y,lastSeen:0,attackCooldown:0};c.trail=[];c.trailClock=0;c.gait=Math.random()*TAU;c.stealth=c.role==='lurker'?1:0;c.kills=0;return c}
export function ensureWorld(w){if(w.v4)return;w.v4={phase:'clear',clock:0,nextRain:48+Math.random()*42,rainDuration:16+Math.random()*13,rain:0,warning:0,cycle:0,carcasses:[],grid:new Map(),gridSize:7,lastRainRewardCycle:-1};w.dens=Array.from({length:11},(_,i)=>{const p=w.randomLand();return{id:i,x:p.x,y:p.y,r:2.2+Math.random()*2.4,hue:(i*47+w.seed)%360,occupants:0}})}
function gridKey(w,x,y){const n=Math.ceil(w.size/w.v4.gridSize),gx=wrap(Math.floor(x/w.v4.gridSize),n),gy=wrap(Math.floor(y/w.v4.gridSize),n);return`${gx},${gy}`}
function rebuildGrid(w){w.v4.grid.clear();for(const c of w.creatures){const k=gridKey(w,c.x,c.y);let bucket=w.v4.grid.get(k);if(!bucket)w.v4.grid.set(k,bucket=[]);bucket.push(c)}}
function nearby(w,c,r=12){const out=[],n=Math.ceil(w.size/w.v4.gridSize),gx=Math.floor(c.x/w.v4.gridSize),gy=Math.floor(c.y/w.v4.gridSize),span=Math.ceil(r/w.v4.gridSize);for(let yy=-span;yy<=span;yy++)for(let xx=-span;xx<=span;xx++){const b=w.v4.grid.get(`${wrap(gx+xx,n)},${wrap(gy+yy,n)}`);if(b)for(const o of b)if(o!==c&&o.alive&&distance(c,o,w.size)<=r)out.push(o)}return out}
export function nearestDen(w,c){let best=w.dens[0],bd=Infinity;for(const d of w.dens){const dd=distance(c,d,w.size);if(dd<bd){bd=dd;best=d}}return{den:best,distance:bd}}
function steer(c,target,w,strength=.12){const dx=shortest(c.x,target.x,w.size),dy=shortest(c.y,target.y,w.size),angle=Math.atan2(dy,dx),turn=Math.atan2(Math.sin(angle-c.angle),Math.cos(angle-c.angle));c.angle+=turn*strength;c.vx+=Math.cos(c.angle)*strength*.12;c.vy+=Math.sin(c.angle)*strength*.12}
function flee(c,target,w,strength=.2){const dx=shortest(target.x,c.x,w.size),dy=shortest(target.y,c.y,w.size),angle=Math.atan2(dy,dx);c.angle+=Math.atan2(Math.sin(angle-c.angle),Math.cos(angle-c.angle))*strength;c.vx+=Math.cos(c.angle)*strength*.16;c.vy+=Math.sin(c.angle)*strength*.16}
function choosePrey(w,c,list){return list.filter(o=>o.role!=='stalker'&&o.role!=='lurker'&&o.size<c.size*1.25).sort((a,b)=>distance(c,a,w.size)-distance(c,b,w.size))[0]||null}
function chooseThreat(w,c,list){return list.filter(o=>(o.role==='stalker'||o.role==='lurker')&&o.size>c.size*.72).sort((a,b)=>distance(c,a,w.size)-distance(c,b,w.size))[0]||null}
function updateWeather(w,dt){const v=w.v4;v.clock+=dt;if(v.phase==='clear'){v.rain=0;v.warning=clamp((v.clock-(v.nextRain-12))/12);if(v.clock>=v.nextRain){v.phase='rain';v.clock=0;v.cycle++;w.log('Sky fracture opened',`Rain cycle ${v.cycle} began. Organisms are searching for dens.`)}}else if(v.phase==='rain'){v.rain=clamp(v.clock/4)*clamp((v.rainDuration-v.clock)/4);if(v.clock>=v.rainDuration){v.phase='aftermath';v.clock=0;v.rain=0;w.log('Rain cycle ended','Survivors leave shelter and compete for fresh growth.')}}else{v.rain=0;if(v.clock>7){v.phase='clear';v.clock=0;v.nextRain=48+Math.random()*42;v.rainDuration=16+Math.random()*13;v.warning=0}}}
function updateBehavior(w,c,dt){if(!c.ai)decorate(c,null);c.ai.attackCooldown=Math.max(0,c.ai.attackCooldown-dt);c.ai.hunger=clamp(1-c.energy/1.4);c.trailClock+=dt;if(c.trailClock>.22){c.trailClock=0;c.trail.push({x:c.x,y:c.y});if(c.trail.length>8)c.trail.shift()}const list=nearby(w,c,14),threat=chooseThreat(w,c,list),rain=w.v4.rain;if(rain>.15){const shelter=nearestDen(w,c);c.ai.mode='shelter';c.ai.den=shelter.den.id;steer(c,shelter.den,w,.22+rain*.18);if(shelter.distance<shelter.den.r){c.health=Math.min(1,c.health+dt*.025);c.energy=Math.min(2.3,c.energy+dt*.006);c.vx*=.78;c.vy*=.78}else{c.energy-=rain*dt*.01;c.health-=rain*dt*.008}}else if(threat&&c.role!=='stalker'&&c.role!=='lurker'&&distance(c,threat,w.size)<9){c.ai.mode='flee';c.ai.fear=1;flee(c,threat,w,.27)}else if(c.role==='stalker'||c.role==='lurker'){const prey=choosePrey(w,c,list);if(prey){c.ai.mode=c.role==='lurker'&&distance(c,prey,w.size)>4?'stalk':'hunt';c.ai.targetId=prey.id;const d=distance(c,prey,w.size);steer(c,prey,w,c.role==='lurker'?(.07+(d<4?.24:0)):.18);if(d<.9+c.size&&c.ai.attackCooldown<=0){const damage=.12+c.size*.12;prey.health-=damage;prey.energy-=damage*.35;c.energy=Math.min(2.3,c.energy+damage*.42);c.ai.attackCooldown=.8;c.kills+=prey.health<=0?1:0;if(prey.health<=0){wallet.hunts++;award(4,0,'Predation witnessed')}}}else c.ai.mode='prowl'}else if(c.role==='scavenger'&&w.v4.carcasses.length){const carc=[...w.v4.carcasses].sort((a,b)=>distance(c,a,w.size)-distance(c,b,w.size))[0],d=distance(c,carc,w.size);c.ai.mode='scavenge';steer(c,carc,w,.16);if(d<1.2&&carc.mass>0){const bite=Math.min(carc.mass,dt*.18);carc.mass-=bite;c.energy=Math.min(2.3,c.energy+bite);c.health=Math.min(1,c.health+bite*.06)}}else if(c.role==='glider'){c.ai.mode='glide';c.gait+=dt*3.2;c.vx+=Math.cos(c.angle+Math.sin(c.gait)*.5)*dt*.018;c.vy+=Math.sin(c.angle+Math.sin(c.gait)*.5)*dt*.018;c.energy+=dt*.0015}else{c.ai.mode=c.energy<.6?'forage':'roam';if(c.role==='grazer'&&w.food[w.idx(c.x,c.y)]>.05)c.energy=Math.min(2.3,c.energy+dt*.004)}if(c.role==='lurker'&&c.ai.mode==='stalk'){c.vx*=.72;c.vy*=.72;c.stealth=clamp(c.stealth+dt*.7)}else c.stealth=clamp(c.stealth-dt*.9);c.gait+=dt*(2+Math.hypot(c.vx,c.vy)*9);if(v4State.possessId===c.id){c.ai.mode='bonded';const m=Math.hypot(input.x,input.y);if(m>.08){const a=Math.atan2(input.y,input.x);c.angle=a;const force=(input.boost?1.8:1)*.055;c.vx+=Math.cos(a)*force;c.vy+=Math.sin(a)*force;c.energy-=dt*(input.boost?.012:.004)}c.health=Math.max(c.health,.02)}}
function ecosystemAfterStep(w,dt){ensureWorld(w);updateWeather(w,dt);rebuildGrid(w);for(const d of w.dens)d.occupants=0;for(const c of w.creatures){updateBehavior(w,c,dt);const nd=nearestDen(w,c);if(nd.distance<nd.den.r)nd.den.occupants++}for(const carc of w.v4.carcasses){carc.age+=dt;carc.mass-=dt*.004;if(carc.mass>0){const i=w.idx(carc.x,carc.y);w.food[i]=Math.min(1,w.food[i]+dt*.003)}}w.v4.carcasses=w.v4.carcasses.filter(x=>x.age<45&&x.mass>.01);const m=w.metrics();if(m.births-wallet.lastBirths>=12){const gain=Math.floor((m.births-wallet.lastBirths)/12);wallet.lastBirths+=gain*12;award(gain)}if(m.species>wallet.lastSpecies){const gain=m.species-wallet.lastSpecies;wallet.lastSpecies=m.species;wallet.discoveries+=gain;award(gain*2)}if(w.v4.phase==='aftermath'&&w.v4.lastRainRewardCycle!==w.v4.cycle){w.v4.lastRainRewardCycle=w.v4.cycle;const bonded=w.creatures.find(c=>c.id===v4State.possessId);if(bonded){wallet.rains++;award(15,wallet.rains%3===0?1:0,'Rain survived')}}}
const oldSpawn=World.prototype.spawnCreature;World.prototype.spawnCreature=function(parent=null,founder=false,mate=null){ensureWorld(this);return decorate(oldSpawn.call(this,parent,founder,mate),parent)};
const oldKill=World.prototype.kill;World.prototype.kill=function(c,reason){ensureWorld(this);if(c?.alive)this.v4.carcasses.push({x:c.x,y:c.y,mass:.35+c.size*.8,age:0,hue:c.hue,role:c.role});oldKill.call(this,c,reason);if(v4State.possessId===c.id){v4State.possessId=0;toast('Bonded creature died — choose a new champion')}};
const oldStep=World.prototype.step;World.prototype.step=function(dt){ensureWorld(this);oldStep.call(this,dt);if(!this.paused)ecosystemAfterStep(this,Math.min(.05,dt)*this.speed)};
const oldMetrics=World.prototype.metrics;World.prototype.metrics=function(){ensureWorld(this);const base=oldMetrics.call(this),roles={grazer:0,stalker:0,scavenger:0,lurker:0,glider:0};for(const c of this.creatures)roles[c.role]=(roles[c.role]||0)+1;return{...base,roles,rain:this.v4.rain,weather:this.v4.phase,carcasses:this.v4.carcasses.length,dens:this.dens.length}};
