import{World}from'./world.js';
import{Renderer}from'./renderer.js';
import{TeacherAgent}from'./teacher.js';

const TWO_HOURS=2*60*60*1000,clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),wrap=(v,m)=>((v%m)+m)%m;
const STORE='god_genic_game_v3';
let state={energy:100,score:0,mission:0,power:'bloom',rating:0,choice:'',storm:false,stormHold:0,balanceHold:0,quality:'auto'};
try{state={...state,...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{}
const powers={bloom:{name:'Nutrient Bloom',icon:'🌱',cost:10,hue:130},mutation:{name:'Mutation Pulse',icon:'🧬',cost:18,hue:300},sanctuary:{name:'Sanctuary',icon:'🛡️',cost:15,hue:175},storm:{name:'Selection Storm',icon:'🌪️',cost:22,hue:25},genesis:{name:'Genesis',icon:'✨',cost:30,hue:205}};
const missions=[
 ['Spark of Life','Grow 120 living organisms.',m=>clamp(m.population/120),20],
 ['Self-Replication','Reach 40 births and generation 3.',m=>clamp(Math.min(m.births/40,m.generation/3)),25],
 ['Natural Selection','Cast a storm and keep 70 creatures alive for 20 seconds.',m=>state.storm?clamp(state.stormHold/20)*clamp(m.population/70):0,30],
 ['Speciation','Evolve 10 living species.',m=>clamp(m.species/10),35],
 ['Living Ecosystem','Hold 60% diversity with 100+ organisms for 25 seconds.',m=>clamp(state.balanceHold/25),40],
 ['Alien Intelligence','Reach generation 14 and teacher score 72.',m=>clamp(Math.min(m.generation/14,(window.__godTeacher?.score||0)/72)),60]
];
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function toast(text){const t=document.getElementById('toast');if(!t)return;t.textContent=text;t.classList.add('show');clearTimeout(window.__v3toast);window.__v3toast=setTimeout(()=>t.classList.remove('show'),1600)}

const terrain=World.prototype.generateTerrain;World.prototype.generateTerrain=function(...args){window.__godWorld=this;return terrain.apply(this,args)};
const build=Renderer.prototype.buildTerrain;Renderer.prototype.buildTerrain=function(...args){window.__godRenderer=this;this.v3Effects=[];this.v3Detail=1;return build.apply(this,args)};

const originalStep=World.prototype.step;
World.prototype.v3BuildSpatial=function(){const cell=6,count=Math.ceil(this.size/cell),grid=new Map;for(const c of this.creatures){if(!c.alive)continue;const gx=Math.floor(c.x/cell),gy=Math.floor(c.y/cell),key=`${wrap(gx,count)},${wrap(gy,count)}`;let bucket=grid.get(key);if(!bucket){bucket=[];grid.set(key,bucket)}bucket.push(c)}this.__v3Spatial={cell,count,grid}};
World.prototype.nearest=function(c){const s=this.__v3Spatial;if(!s)return{creature:null,distance:Infinity};const gx=Math.floor(c.x/s.cell),gy=Math.floor(c.y/s.cell);let best=null,bd=Infinity;for(let oy=-2;oy<=2;oy++)for(let ox=-2;ox<=2;ox++){const bucket=s.grid.get(`${wrap(gx+ox,s.count)},${wrap(gy+oy,s.count)}`);if(!bucket)continue;for(const o of bucket){if(o===c||!o.alive)continue;let dx=Math.abs(o.x-c.x),dy=Math.abs(o.y-c.y);dx=Math.min(dx,this.size-dx);dy=Math.min(dy,this.size-dy);const d=dx*dx+dy*dy;if(d<bd){bd=d;best=o}}}return{creature:best,distance:best?Math.sqrt(bd):Infinity}};
World.prototype.step=function(dt){this.params.targetPopulation=Math.min(420,Math.max(80,this.params.targetPopulation));this.v3BuildSpatial();return originalStep.call(this,dt)};

const oldReview=TeacherAgent.prototype.review;
TeacherAgent.prototype.due=function(now=Date.now()){window.__godTeacher=this;return now-this.lastReviewAt>=TWO_HOURS};
TeacherAgent.prototype.remaining=function(now=Date.now()){window.__godTeacher=this;return Math.max(0,TWO_HOURS-(now-this.lastReviewAt))};
TeacherAgent.prototype.review=function(world,manual=false){window.__godTeacher=this;const row=oldReview.call(this,world,manual);v3AutoTune(row);return row};

const oldRender=Renderer.prototype.render;
Renderer.prototype.render=function(now){oldRender.call(this,now);window.__godRenderer=this;const c=this.ctx,w=this.width,h=this.height,world=this.world;if(!c||!world)return;const list=[...world.creatures].sort((a,b)=>b.energy-a.energy);const limit=state.quality==='battery'?55:state.quality==='high'?150:Math.round(80+(this.v3Detail||1)*40);c.save();c.globalCompositeOperation='screen';for(const creature of list.slice(0,limit)){const p=this.worldToScreen(creature.x,creature.y);if(p.x<-30||p.y<-30||p.x>w+30||p.y>h+30)continue;const r=2.8+creature.size*4.8,pulse=1+Math.sin(now*.005+creature.id)*.12;c.fillStyle=`hsla(${creature.hue},100%,68%,.08)`;c.shadowColor=`hsla(${creature.hue},100%,65%,.72)`;c.shadowBlur=state.quality==='battery'?5:13;c.beginPath();c.arc(p.x,p.y,r*2.6*pulse,0,Math.PI*2);c.fill();c.shadowBlur=0;c.strokeStyle=`hsla(${creature.hue+55},100%,90%,.6)`;c.lineWidth=.7;c.beginPath();c.arc(p.x,p.y,r*.78,0,Math.PI*2);c.stroke();c.fillStyle=`hsla(${creature.hue+170},100%,72%,.72)`;c.beginPath();c.arc(p.x+r*.16,p.y-r*.08,r*.18,0,Math.PI*2);c.fill()}c.restore();
 const effects=this.v3Effects||[];this.v3Effects=effects.filter(e=>(now-e.t)<1200);for(const e of this.v3Effects){const age=(now-e.t)/1200,p=this.worldToScreen(e.x,e.y);c.strokeStyle=`hsla(${e.h},100%,72%,${1-age})`;c.lineWidth=2+(1-age)*5;c.shadowColor=`hsl(${e.h},100%,65%)`;c.shadowBlur=22;c.beginPath();c.arc(p.x,p.y,12+age*95,0,Math.PI*2);c.stroke();c.shadowBlur=0}}
Renderer.prototype.v3Burst=function(x,y,h){(this.v3Effects||(this.v3Effects=[])).push({x,y,h,t:performance.now()})};

function v3AutoTune(){const r=window.__godRenderer,w=window.__godWorld;if(!r||!w)return;const fps=Number(document.getElementById('fpsValue')?.textContent||60);let text='Frame budget and ecosystem load are balanced.';if(fps<42){r.v3Detail=Math.max(.55,(r.v3Detail||1)-.15);w.params.targetPopulation=Math.min(w.params.targetPopulation,300);text='Reduced extra glow detail and population ceiling to protect iPhone speed.'}else if(fps>56){r.v3Detail=Math.min(1.2,(r.v3Detail||1)+.06);text='Performance is healthy, so biological detail increased slightly.'}const out=document.getElementById('engineReviewText');if(out)out.textContent=text;w.log('Two-hour engine review',text)}

function injectUI(){
 const shell=document.querySelector('.world-shell');if(!shell||document.getElementById('v3Mission'))return;
 shell.insertAdjacentHTML('beforeend',`<div id="v3Mission" class="v3-mission glass"><small id="v3MissionNum">MISSION 1 / 6</small><b id="v3MissionTitle">Spark of Life</b><span id="v3MissionText">Grow 120 living organisms.</span><div><i id="v3MissionBar"></i></div><em id="v3MissionPct">0%</em></div><div class="v3-resources glass"><span><small>GOD ENERGY</small><b id="v3Energy">100</b></span><span><small>EVOLUTION</small><b id="v3Score">0</b></span></div><div class="v3-powers glass" id="v3Powers">${Object.entries(powers).map(([key,p])=>`<button data-v3power="${key}" class="${key===state.power?'active':''}"><span>${p.icon}</span><b>${p.name.split(' ')[0]}</b><small>${p.cost}</small></button>`).join('')}</div><div class="v3-hint" id="v3Hint">Tap the world to cast ${powers[state.power].name}</div>`);
 const dock=document.querySelector('.dock');dock?.insertAdjacentHTML('beforeend','<button data-view="feedback"><span>★</span><small>Rate</small></button>');
 document.querySelector('.dashboard')?.insertAdjacentHTML('beforeend',`<article id="view-feedback" class="view"><div class="section-head"><div><span class="eyebrow">NO TYPING REQUIRED</span><h1>Rate the simulation out of 10 stars.</h1><p>Tap a star and one of six choices. Nothing is sent automatically.</p></div></div><article class="v3-feedback glass"><div id="v3Stars" class="v3-stars">${Array.from({length:10},(_,i)=>`<button data-v3star="${i+1}">★</button>`).join('')}</div><b id="v3RatingLabel">Choose 1–10 stars</b><div class="v3-choices"><button data-v3choice="Fun already">🔥<b>Fun already</b></button><button data-v3choice="More graphics">✨<b>More graphics</b></button><button data-v3choice="More evolution">🧬<b>More evolution</b></button><button data-v3choice="More control">🎮<b>More control</b></button><button data-v3choice="Run faster">⚡<b>Run faster</b></button><button data-v3choice="More chaos">🌪️<b>More chaos</b></button></div><button id="v3Share" class="button accent">Share feedback</button><small id="v3FeedbackState">Saved only on this device until you tap Share.</small></article></article>`);
 const teacher=document.querySelector('#view-teacher .section-head');if(teacher){teacher.querySelector('.eyebrow').textContent='TWO-HOUR CURRICULUM AGENT';teacher.querySelector('h1').textContent='The teacher reviews evolution every two hours.';teacher.querySelector('p').textContent='Reviews run while the app is active, or when reopened after becoming due. iOS does not keep the simulation running while closed.';document.querySelector('#view-teacher .panel')?.insertAdjacentHTML('beforeend','<div class="v3-engine-review"><b>Adaptive engine review</b><small id="engineReviewText">Waiting for the next two-hour review.</small></div>')}
 bindV3();renderFeedback();renderGame();
}
function cells(world,x,y,r,fn){for(let yy=Math.floor(y-r);yy<=Math.ceil(y+r);yy++)for(let xx=Math.floor(x-r);xx<=Math.ceil(x+r);xx++){let dx=Math.abs(xx-x),dy=Math.abs(yy-y);dx=Math.min(dx,world.size-dx);dy=Math.min(dy,world.size-dy);const d=Math.hypot(dx,dy);if(d<=r)fn(world.idx(xx,yy),1-d/r)}}
function cast(type,x,y){const w=window.__godWorld,r=window.__godRenderer,p=powers[type];if(!w||!p)return;if(state.energy<p.cost){toast(`Need ${p.cost} God Energy`);return}state.energy-=p.cost;r?.v3Burst(x,y,p.hue);
 if(type==='bloom')cells(w,x,y,9,(i,t)=>w.food[i]=Math.min(1,w.food[i]+.25+t*.7));
 if(type==='mutation'){const near=[...w.creatures].sort((a,b)=>((a.x-x)**2+(a.y-y)**2)-((b.x-x)**2+(b.y-y)**2)).slice(0,3);for(const parent of near)for(let i=0;i<3;i++){const c=w.spawnCreature(parent,false);c.x=wrap(x+(Math.random()-.5)*3,w.size);c.y=wrap(y+(Math.random()-.5)*3,w.size)}}
 if(type==='sanctuary'){cells(w,x,y,10,(i,t)=>w.hazardField[i]=Math.max(0,w.hazardField[i]-.45*t));for(const c of w.creatures){let dx=Math.abs(c.x-x),dy=Math.abs(c.y-y);dx=Math.min(dx,w.size-dx);dy=Math.min(dy,w.size-dy);if(dx*dx+dy*dy<100){c.health=Math.min(1,c.health+.45);c.energy=Math.min(2.3,c.energy+.35)}}}
 if(type==='storm'){state.storm=true;state.stormHold=0;cells(w,x,y,13,(i,t)=>{w.food[i]*=.3;w.hazardField[i]=Math.min(1,w.hazardField[i]+.55*t)});for(const c of w.creatures){let dx=Math.abs(c.x-x),dy=Math.abs(c.y-y);dx=Math.min(dx,w.size-dx);dy=Math.min(dy,w.size-dy);if(Math.hypot(dx,dy)<13){c.energy-=.2;c.vx+=(Math.random()-.5)*.3;c.vy+=(Math.random()-.5)*.3}}}
 if(type==='genesis')for(let i=0;i<14;i++){const c=w.spawnCreature(null,true);c.x=wrap(x+(Math.random()-.5)*8,w.size);c.y=wrap(y+(Math.random()-.5)*8,w.size)}
 state.score+=p.cost*2;w.log(p.name,`Player intervention at ${x.toFixed(0)}, ${y.toFixed(0)}.`);save();renderGame();toast(`${p.name} cast`)}
function renderGame(){const w=window.__godWorld;if(!w||!document.getElementById('v3Mission'))return;const m=w.metrics(),mission=missions[Math.min(state.mission,5)],progress=mission[2](m);document.getElementById('v3MissionNum').textContent=`MISSION ${Math.min(state.mission+1,6)} / 6`;document.getElementById('v3MissionTitle').textContent=mission[0];document.getElementById('v3MissionText').textContent=mission[1];document.getElementById('v3MissionBar').style.width=`${Math.round(progress*100)}%`;document.getElementById('v3MissionPct').textContent=`${Math.round(progress*100)}%`;document.getElementById('v3Energy').textContent=Math.round(state.energy);document.getElementById('v3Score').textContent=Math.round(state.score).toLocaleString();if(progress>=1&&!state.finished){state.energy=Math.min(100,state.energy+mission[3]);state.score+=mission[3]*10;w.log(`Breakthrough: ${mission[0]}`,`+${mission[3]} God Energy and +${mission[3]*10} Evolution Score.`);if(state.mission<5)state.mission++;else state.finished=true;save();toast(`Mission complete: ${mission[0]}`)}}
function renderFeedback(){document.querySelectorAll('[data-v3star]').forEach(b=>b.classList.toggle('on',Number(b.dataset.v3star)<=state.rating));const label=document.getElementById('v3RatingLabel');if(label)label.textContent=state.rating?`${state.rating} / 10 stars`:'Choose 1–10 stars';document.querySelectorAll('[data-v3choice]').forEach(b=>b.classList.toggle('active',b.dataset.v3choice===state.choice))}
async function shareFeedback(){if(!state.rating||!state.choice){toast('Pick stars and one choice');return}const text=`Sandbox God Genic: ${state.rating}/10 stars · ${state.choice}`;try{if(navigator.share)await navigator.share({title:'God Genic Feedback',text,url:location.href});else{await navigator.clipboard.writeText(text);open(`https://github.com/Toymaker474/html5.github.io/issues/new?title=${encodeURIComponent('God Genic '+state.rating+'/10')}&body=${encodeURIComponent(text)}`,'_blank')}}catch{}const out=document.getElementById('v3FeedbackState');if(out)out.textContent=`Saved: ${state.rating}/10 · ${state.choice}`}
function bindV3(){document.querySelectorAll('[data-v3power]').forEach(b=>b.onclick=()=>{state.power=b.dataset.v3power;document.querySelectorAll('[data-v3power]').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('v3Hint').textContent=`Tap the world to cast ${powers[state.power].name}`;save()});document.getElementById('worldCanvas')?.addEventListener('pointerdown',e=>{const r=window.__godRenderer;if(!r)return;const rect=r.canvas.getBoundingClientRect(),scale=Math.min(r.width,r.height)/r.world.size*r.camera.zoom,x=wrap((e.clientX-rect.left-r.width/2)/scale+r.camera.x,r.world.size),y=wrap((e.clientY-rect.top-r.height/2)/scale+r.camera.y,r.world.size);cast(state.power,x,y)});document.querySelectorAll('[data-v3star]').forEach(b=>b.onclick=()=>{state.rating=Number(b.dataset.v3star);save();renderFeedback()});document.querySelectorAll('[data-v3choice]').forEach(b=>b.onclick=()=>{state.choice=b.dataset.v3choice;save();renderFeedback()});document.getElementById('v3Share').onclick=shareFeedback}
let last=performance.now();function loop(now){const dt=Math.min(.1,(now-last)/1000);last=now;const w=window.__godWorld;if(w&&!w.paused){state.energy=Math.min(100,state.energy+dt*.18);const m=w.metrics();if(state.mission===2&&state.storm&&m.population>=70)state.stormHold+=dt;if(state.mission===4&&m.population>=100&&m.diversity>=.6)state.balanceHold+=dt;renderGame()}requestAnimationFrame(loop)}
window.addEventListener('godgenic:booted',()=>{injectUI();requestAnimationFrame(loop)});
