import{TinyBrain}from'./brain.js';
const TAU=Math.PI*2,clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,wrap=(v,max)=>v<0?v+max:v>=max?v-max:v;
const hash=(x,y,s)=>{let n=(x*374761393+y*668265263+s*1442695041)|0;n=(n^(n>>>13))*1274126177;return((n^(n>>>16))>>>0)/4294967295};
const smooth=t=>t*t*(3-2*t);
function noise(x,y,seed){const x0=Math.floor(x),y0=Math.floor(y),tx=smooth(x-x0),ty=smooth(y-y0),a=hash(x0,y0,seed),b=hash(x0+1,y0,seed),c=hash(x0,y0+1,seed),d=hash(x0+1,y0+1,seed);return lerp(lerp(a,b,tx),lerp(c,d,tx),ty)}
function fbm(x,y,seed){let v=0,a=.55,f=1;for(let i=0;i<5;i++){v+=noise(x*f,y*f,seed+i*97)*a;f*=2.04;a*=.48}return v/1.04}
const namesA=['Aero','Velo','Nym','Kora','Zin','Mira','Thal','Oro','Cera','Luma','Pyra','Soli'],namesB=['ling','vore','morph','kin','drift','claw','fin','seed','wisp','shell','runner','bloom'];let nextId=1;
export class World{
 constructor(seed=(Math.random()*2**31)|0,state={}){this.seed=seed|0;this.size=96;this.cells=this.size*this.size;this.time=0;this.day=0;this.season=0;this.paused=false;this.speed=1;this.terrain=new Float32Array(this.cells);this.moisture=new Float32Array(this.cells);this.fertility=new Float32Array(this.cells);this.food=new Float32Array(this.cells);this.hazardField=new Float32Array(this.cells);this.creatures=[];this.deadArchive=[];this.events=[];this.extinctions=0;this.births=0;this.deaths=0;this.recentDeaths=0;this.lastPopulation=0;this.followId=0;this.params={mutation:.04,foodGrowth:1,hazard:.35,targetPopulation:260,...state.params};this.curriculum={motionCost:.008,birthCost:.72,nicheReward:.15,noveltyReward:.1,...state.curriculum};this.history={biomass:[],diversity:[],energy:[],extinctions:[]};this.generateTerrain();const initial=Math.min(this.params.targetPopulation,180);for(let i=0;i<initial;i++)this.spawnCreature(null,true);this.log('Planet germinated',`Seed ${this.seed} · ${initial} founding organisms.`)}
 idx(x,y){return wrap(y|0,this.size)*this.size+wrap(x|0,this.size)}sample(arr,x,y){return arr[this.idx(x,y)]}
 generateTerrain(){for(let y=0;y<this.size;y++)for(let x=0;x<this.size;x++){const i=y*this.size+x,n=fbm(x/28,y/28,this.seed),m=fbm(x/19+40,y/19-30,this.seed+31),r=fbm(x/10-22,y/10+18,this.seed+71);this.terrain[i]=clamp(n*.9+r*.1);this.moisture[i]=clamp(m*.78+(1-this.terrain[i])*.28);this.fertility[i]=clamp(this.moisture[i]*.65+(1-Math.abs(this.terrain[i]-.52)*2)*.45);this.food[i]=this.fertility[i]*(.25+hash(x,y,this.seed+9)*.62);this.hazardField[i]=clamp(fbm(x/13,y/13,this.seed+500)*1.3-.35)}}
 randomLand(){for(let k=0;k<80;k++){const x=Math.random()*this.size,y=Math.random()*this.size;if(this.sample(this.terrain,x,y)>.25)return{x,y}}return{x:this.size/2,y:this.size/2}}
 spawnCreature(parent=null,founder=false,mate=null){const p=parent||{},pos=parent?{x:wrap(parent.x+(Math.random()-.5)*2,this.size),y:wrap(parent.y+(Math.random()-.5)*2,this.size)}:this.randomLand(),mutation=this.params.mutation,brain=parent?(mate?TinyBrain.crossover(parent.brain,mate.brain,mutation):parent.brain.mutate(mutation)):new TinyBrain(),generation=parent?(Math.max(parent.generation,mate?.generation||0)+1):1,hue=parent?wrap(parent.hue+(Math.random()-.5)*34,360):Math.random()*360,speciesKey=`${Math.round(hue/24)}-${Math.round((p.size||.5)*8)}-${brain.genomeHash().slice(0,2)}`;const c={id:nextId++,name:`${namesA[(Math.random()*namesA.length)|0]}${namesB[(Math.random()*namesB.length)|0]}-${(nextId%999).toString().padStart(3,'0')}`,x:pos.x,y:pos.y,vx:0,vy:0,angle:Math.random()*TAU,energy:founder?1.1:.72,health:1,age:0,generation,speciesKey,hue,size:clamp(parent?parent.size+(Math.random()-.5)*.05:.35+Math.random()*.35,.18,.85),speed:clamp(parent?parent.speed+(Math.random()-.5)*.05:.42+Math.random()*.4,.2,1),sense:clamp(parent?parent.sense+(Math.random()-.5)*.05:.45+Math.random()*.45,.25,1),tempPref:clamp(parent?parent.tempPref+(Math.random()-.5)*.04:Math.random(),0,1),brain,birthCooldown:6+Math.random()*5,lastReward:0,eaten:0,children:0,parentId:parent?.id||0,alive:true};this.creatures.push(c);this.births++;return c}
 nearest(c){let best=null,bd=Infinity;for(const o of this.creatures){if(o===c||!o.alive)continue;const dx=Math.abs(o.x-c.x),dy=Math.abs(o.y-c.y),d=Math.min(dx,this.size-dx)**2+Math.min(dy,this.size-dy)**2;if(d<bd){bd=d;best=o}}return{creature:best,distance:Math.sqrt(bd)}}
 updateCreature(c,dt){c.age+=dt;c.birthCooldown-=dt;const i=this.idx(c.x,c.y),food=this.food[i],water=1-this.terrain[i],danger=this.hazardField[i]*this.params.hazard,near=this.nearest(c),kin=near.creature?clamp(1-near.distance/(12*c.sense)):0,temp=.5+.45*Math.sin((this.season+this.day/90)*TAU)+(.5-this.terrain[i])*.2,sensors=new Float32Array([food,water,danger,kin,c.energy/2,1-Math.abs(temp-c.tempPref),c.brain.rewardEMA,Math.random()*2-1]),out=c.brain.forward(sensors);c.angle+=out[0]*2.4*dt;const thrust=clamp((out[1]+1)/2)*c.speed;c.vx=lerp(c.vx,Math.cos(c.angle)*thrust,.18);c.vy=lerp(c.vy,Math.sin(c.angle)*thrust,.18);c.x=wrap(c.x+c.vx*dt*4,this.size);c.y=wrap(c.y+c.vy*dt*4,this.size);const motion=Math.hypot(c.vx,c.vy);c.energy-=dt*(.006+c.size*.003+motion*this.curriculum.motionCost);let reward=-.005;if(out[2]>.05&&this.food[i]>.015){const bite=Math.min(this.food[i],dt*(.13+c.size*.08));this.food[i]-=bite;c.energy+=bite*.95;c.eaten+=bite;reward+=bite*4}if(danger>.18){const hit=dt*danger*.065;c.health-=hit;c.energy-=hit*.35;reward-=hit*5}const tempStress=Math.abs(temp-c.tempPref);c.energy-=dt*Math.max(0,tempStress-.38)*.01;if(out[3]>.45&&c.birthCooldown<=0&&c.energy>this.curriculum.birthCost+.35&&this.creatures.length<this.params.targetPopulation*1.45){const mate=near.creature&&near.distance<2.6&&near.creature.energy>.8?near.creature:null,child=this.spawnCreature(c,false,mate);c.energy-=this.curriculum.birthCost;c.children++;c.birthCooldown=10+Math.random()*8;reward+=.35;if(mate){mate.energy-=this.curriculum.birthCost*.28;mate.children++}if(child.generation>1&&child.generation%8===0)this.log('Neural lineage advanced',`${child.name} reached generation ${child.generation}.`)}c.energy=Math.min(2.3,c.energy);c.health=Math.min(1,c.health+dt*.006);reward+=this.curriculum.nicheReward*Math.abs(c.tempPref-.5)*.002+this.curriculum.noveltyReward*Math.abs(out[0])*.001;c.lastReward=reward;c.brain.reinforce(reward);if(c.energy<=0||c.health<=0||c.age>75+c.size*55)this.kill(c,c.energy<=0?'starvation':c.health<=0?'hazard':'old age')}
 kill(c,reason){if(!c.alive)return;c.alive=false;this.deaths++;this.recentDeaths++;this.deadArchive.unshift({name:c.name,speciesKey:c.speciesKey,generation:c.generation,age:c.age,reason,t:Date.now()});this.deadArchive=this.deadArchive.slice(0,120)}
 step(dt){if(this.paused)return;dt=Math.min(.05,dt)*this.speed;this.time+=dt;this.day=this.time/4;this.season=(this.day%360)/360;const growth=dt*.017*this.params.foodGrowth;for(let i=0;i<this.cells;i++){const seasonPulse=.75+.25*Math.sin(this.season*TAU+this.moisture[i]*2);this.food[i]=Math.min(1,this.food[i]+growth*this.fertility[i]*seasonPulse*(1-this.food[i]))}const snapshot=[...this.creatures];for(const c of snapshot)if(c.alive)this.updateCreature(c,dt);this.creatures=this.creatures.filter(c=>c.alive);if(this.creatures.length<12){for(let i=0;i<40;i++)this.spawnCreature(null,true);this.extinctions++;this.log('Mass extinction recovery','Teacher seed vault released 40 new founders.')}if(this.creatures.length<this.params.targetPopulation*.45&&Math.random()<dt*.6)this.spawnCreature(null,true);if(this.creatures.length>this.params.targetPopulation*1.45){const excess=this.creatures.length-Math.round(this.params.targetPopulation*1.45);this.creatures.sort((a,b)=>b.energy-a.energy);for(let i=0;i<excess;i++)this.kill(this.creatures[this.creatures.length-1-i],'population pressure');this.creatures=this.creatures.filter(c=>c.alive)}}
 storm(){const cx=Math.random()*this.size,cy=Math.random()*this.size,r=8+Math.random()*14;for(let y=0;y<this.size;y++)for(let x=0;x<this.size;x++){const dx=Math.min(Math.abs(x-cx),this.size-Math.abs(x-cx)),dy=Math.min(Math.abs(y-cy),this.size-Math.abs(y-cy));if(dx*dx+dy*dy<r*r){const i=y*this.size+x;this.food[i]*=.4;this.hazardField[i]=clamp(this.hazardField[i]+.35)}}this.log('Ion storm crossed the planet',`Radius ${r.toFixed(0)} cells · ecosystems forced to adapt.`)}
 champion(){return[...this.creatures].sort((a,b)=>(b.energy+b.children*.2+b.age*.01)-(a.energy+a.children*.2+a.age*.01))[0]||null}
 species(){const map=new Map;for(const c of this.creatures){let s=map.get(c.speciesKey);if(!s){s={key:c.speciesKey,count:0,hue:c.hue,maxGeneration:0,energy:0,champion:c};map.set(c.speciesKey,s)}s.count++;s.energy+=c.energy;if(c.generation>s.maxGeneration)s.maxGeneration=c.generation;if(c.energy>s.champion.energy)s.champion=c}return[...map.values()].sort((a,b)=>b.count-a.count)}
 metrics(){const pop=this.creatures.length,species=this.species(),energies=this.creatures.map(c=>c.energy),ages=this.creatures.map(c=>c.age),proportions=species.map(s=>s.count/Math.max(1,pop)),entropy=-proportions.reduce((n,p)=>n+(p?p*Math.log(p):0),0),maxEntropy=Math.log(Math.max(2,species.length));return{population:pop,species:species.length,diversity:clamp(entropy/Math.max(.01,maxEntropy)),meanEnergy:energies.reduce((a,b)=>a+b,0)/Math.max(1,pop),meanAge:ages.reduce((a,b)=>a+b,0)/Math.max(1,pop),generation:this.creatures.reduce((m,c)=>Math.max(m,c.generation),1),births:this.births,deaths:this.deaths,recentDeaths:this.recentDeaths,biomass:this.creatures.reduce((n,c)=>n+c.size*c.energy,0),extinctions:this.extinctions}}
 sampleHistory(){const m=this.metrics();this.history.biomass.push(m.biomass);this.history.diversity.push(m.diversity*100);this.history.energy.push(m.meanEnergy*100);this.history.extinctions.push(m.extinctions);for(const a of Object.values(this.history))if(a.length>60)a.shift();this.lastPopulation=m.population;this.recentDeaths=Math.max(0,this.recentDeaths-2)}
 log(title,detail=''){this.events.unshift({t:Date.now(),title,detail});this.events=this.events.slice(0,80)}
 serialize(){return{seed:this.seed,params:this.params,curriculum:this.curriculum,time:this.time,teacherSafe:true,champions:[...this.creatures].sort((a,b)=>b.energy-a.energy).slice(0,12).map(c=>({name:c.name,generation:c.generation,speciesKey:c.speciesKey,hue:c.hue,size:c.size,speed:c.speed,sense:c.sense,tempPref:c.tempPref,brain:c.brain.serialize()})),events:this.events.slice(0,20)}}
}