import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const stats=document.getElementById('stats');
const bootmsg=document.getElementById('bootmsg');
stats.textContent='modules loaded • creating renderer…';
const scene=new THREE.Scene();scene.background=new THREE.Color(0x071018);scene.fog=new THREE.FogExp2(0x071018,0.014);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,1500);camera.position.set(38,24,46);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(2,devicePixelRatio||1));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.prepend(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,4,0);controls.maxPolarAngle=Math.PI*.49;controls.minDistance=7;controls.maxDistance=120;
scene.add(new THREE.HemisphereLight(0x9fdfff,0x102010,1.4));const sun=new THREE.DirectionalLight(0xfff3d0,2.2);sun.position.set(-30,48,20);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);

const worldSize=120;
const terrainGeo=new THREE.PlaneGeometry(worldSize,worldSize,96,96);terrainGeo.rotateX(-Math.PI/2);const pos=terrainGeo.attributes.position;
function height(x,z){return 2.5*Math.sin(x*.055)+1.5*Math.cos(z*.07)+1.2*Math.sin((x+z)*.11)+0.45*Math.sin(x*.31)*Math.cos(z*.27)}
for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);pos.setY(i,height(x,z))}terrainGeo.computeVertexNormals();const terrain=new THREE.Mesh(terrainGeo,new THREE.MeshStandardMaterial({color:0x244c33,roughness:.96,metalness:0}));terrain.receiveShadow=true;scene.add(terrain);
const water=new THREE.Mesh(new THREE.PlaneGeometry(worldSize*.72,worldSize*.28),new THREE.MeshPhysicalMaterial({color:0x153f51,transparent:true,opacity:.74,roughness:.18,metalness:.05,transmission:.06}));water.rotation.x=-Math.PI/2;water.position.set(5,1.15,18);scene.add(water);

const plantMat=new THREE.MeshStandardMaterial({color:0x4d9c4a,roughness:.9});for(let i=0;i<260;i++){const x=(Math.random()-.5)*worldSize*.9,z=(Math.random()-.5)*worldSize*.9,y=height(x,z);if(y<1.4&&z>2)continue;const h=.5+Math.random()*1.7;const m=new THREE.Mesh(new THREE.ConeGeometry(.16+Math.random()*.15,h,5),plantMat);m.position.set(x,y+h*.5,z);m.rotation.z=(Math.random()-.5)*.35;scene.add(m)}

class Organism{
 constructor(x,z,predator=false){this.predator=predator;this.pos=new THREE.Vector3(x,height(x,z)+.65,z);this.vel=new THREE.Vector3();this.energy=predator?130:105;this.mass=predator?1.7:1;this.age=0;this.dead=false;this.sensor=predator?18:12;this.maxSpeed=predator?6.1:4.8;this.target=null;this.group=new THREE.Group();const bodyMat=new THREE.MeshStandardMaterial({color:predator?0xc86848:0x75b96c,roughness:.55});this.body=new THREE.Mesh(new THREE.CapsuleGeometry(predator?.55:.42,predator?1.75:1.35,5,8),bodyMat);this.body.rotation.z=Math.PI/2;this.body.castShadow=true;this.group.add(this.body);this.head=new THREE.Mesh(new THREE.SphereGeometry(predator?.54:.43,12,8),bodyMat);this.head.position.x=predator?1.35:1.08;this.head.castShadow=true;this.group.add(this.head);for(const side of [-1,1])for(const fore of [-.35,.45]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.08,.55,3,6),bodyMat);leg.rotation.z=Math.PI/2;leg.rotation.y=side*.55;leg.position.set(fore,0,side*(predator?.52:.42));this.group.add(leg)}scene.add(this.group);this.sync()}
 sync(){this.group.position.copy(this.pos);const s=Math.hypot(this.vel.x,this.vel.z);if(s>.05)this.group.rotation.y=Math.atan2(-this.vel.z,this.vel.x)}
 sense(all){let best=null,bd=this.sensor*this.sensor;if(this.predator){for(const o of all){if(o===this||o.dead||o.predator)continue;const d=this.pos.distanceToSquared(o.pos);if(d<bd){bd=d;best=o}}}else{for(const o of all){if(o===this||o.dead||!o.predator)continue;const d=this.pos.distanceToSquared(o.pos);if(d<bd){bd=d;best=o}}}this.target=best}
 step(dt,all){if(this.dead)return;this.age+=dt;this.energy-=dt*(.22+.035*this.vel.lengthSq()+.08*this.mass);this.sense(all);const steer=new THREE.Vector3();if(this.target){steer.subVectors(this.target.pos,this.pos).setY(0);if(!this.predator)steer.multiplyScalar(-1);if(steer.lengthSq()>0)steer.normalize()}else{const gx=-Math.sin(this.pos.x*.08)*.8,gz=Math.cos(this.pos.z*.07)*.6;steer.set(gx,0,gz).normalize()}this.vel.addScaledVector(steer,dt*(this.predator?5.3:4.1));const speed=this.vel.length();if(speed>this.maxSpeed)this.vel.multiplyScalar(this.maxSpeed/speed);this.vel.multiplyScalar(Math.pow(.88,dt*60));this.pos.addScaledVector(this.vel,dt);this.pos.x=THREE.MathUtils.clamp(this.pos.x,-worldSize*.46,worldSize*.46);this.pos.z=THREE.MathUtils.clamp(this.pos.z,-worldSize*.46,worldSize*.46);const ground=height(this.pos.x,this.pos.z)+.65;this.pos.y+=(ground-this.pos.y)*Math.min(1,dt*12);if(this.predator&&this.target&&!this.target.dead&&this.pos.distanceTo(this.target.pos)<1.45){this.target.energy-=dt*42;this.energy+=dt*15;if(this.target.energy<=0)this.target.die()}if(this.energy<=0||this.age>240)this.die();this.sync()}
 die(){if(this.dead)return;this.dead=true;this.group.traverse(o=>{if(o.material)o.material=o.material.clone(),o.material.color.multiplyScalar(.35)});this.group.rotation.z=Math.PI*.48}
}
const organisms=[];for(let i=0;i<26;i++){const x=(Math.random()-.5)*70,z=(Math.random()-.5)*70;organisms.push(new Organism(x,z,false))}for(let i=0;i<6;i++){const x=(Math.random()-.5)*70,z=(Math.random()-.5)*70;organisms.push(new Organism(x,z,true))}

if(bootmsg)bootmsg.textContent='3D renderer booted • preview kernel active';
const clock=new THREE.Clock();let acc=0,frames=0,ft=0,fps=0;function loop(){requestAnimationFrame(loop);const real=Math.min(.05,clock.getDelta());acc+=real;const dt=1/120;let steps=0;while(acc>=dt&&steps<8){for(const o of organisms)o.step(dt,organisms);acc-=dt;steps++}controls.update();renderer.render(scene,camera);frames++;ft+=real;if(ft>.5){fps=frames/ft;frames=0;ft=0;const alive=organisms.filter(o=>!o.dead).length,pred=organisms.filter(o=>!o.dead&&o.predator).length;stats.textContent=`3D preview • life ${alive} • predators ${pred} • sim 120 Hz • ${fps.toFixed(0)} fps`;}}loop();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
