import {createWorld,stepWorld,applyDamage,healPart,placeFoodAt,invariants,NODE,NODE_NAMES,FIXED_DT,GROUND_Y} from './model.js';

const C=document.querySelector('#world'),X=C.getContext('2d',{alpha:false});
const els={perf:document.querySelector('#perf'),summary:document.querySelector('#summary'),parts:document.querySelector('#parts'),joints:document.querySelector('#joints'),muscles:document.querySelector('#muscles'),phys:document.querySelector('#phys'),pause:document.querySelector('#pause'),verify:document.querySelector('#verify')};
let world=createWorld(20260810),paused=false,last=performance.now(),acc=0,fps=0,frames=0,fpsT=last,simMs=0;

function resize(){const d=Math.min(devicePixelRatio||1,2.5),r=C.getBoundingClientRect();C.width=Math.max(1,Math.floor(r.width*d));C.height=Math.max(1,Math.floor(r.height*d));X.setTransform(d,0,0,d,0,0);X.imageSmoothingEnabled=true}addEventListener('resize',resize);resize();
const sx=x=>x-40, sy=y=>y-60;
function line(a,b,w,col){X.strokeStyle=col;X.lineWidth=w;X.lineCap='round';X.beginPath();X.moveTo(sx(world.body.x[a]),sy(world.body.y[a]));X.lineTo(sx(world.body.x[b]),sy(world.body.y[b]));X.stroke()}
function draw(){const b=world.body,w=C.clientWidth,h=C.clientHeight;X.fillStyle='#07100f';X.fillRect(0,0,w,h);const g=X.createLinearGradient(0,0,0,h);g.addColorStop(0,'#0b1815');g.addColorStop(1,'#060a09');X.fillStyle=g;X.fillRect(0,0,w,h);
  X.fillStyle='#101815';X.fillRect(0,sy(GROUND_Y),w,h-sy(GROUND_Y));X.strokeStyle='#47604f';X.lineWidth=2;X.beginPath();X.moveTo(0,sy(GROUND_Y));X.lineTo(w,sy(GROUND_Y));X.stroke();
  for(const m of b.muscles){const a=m.joint,c=m.child,act=m.activation;X.strokeStyle=`rgba(207,86,76,${.16+act*.62})`;X.lineWidth=2+act*4;X.beginPath();X.moveTo(sx(b.x[a]),sy(b.y[a]));X.lineTo(sx(b.x[c]),sy(b.y[c]));X.stroke()}
  for(const bone of b.bones)line(bone.a,bone.b,4,bone.integrity>.6?'#d8d4c5':'#9b6962');
  const core=[NODE.PELVIS,NODE.TORSO,NODE.HEAD];X.fillStyle=b.alive?'rgba(92,133,105,.72)':'rgba(90,90,82,.52)';X.beginPath();for(let i=0;i<core.length;i++){const n=core[i],r=b.radius[n]+7,p={x:sx(b.x[n]),y:sy(b.y[n])};if(i===0)X.moveTo(p.x-r,p.y);X.arc(p.x,p.y,r,0,Math.PI*2)}X.fill();
  for(let i=0;i<b.x.length;i++){const px=sx(b.x[i]),py=sy(b.y[i]),r=b.radius[i];X.fillStyle=i===NODE.JAW?'#ad9d86':'#7fa288';X.beginPath();X.arc(px,py,r,0,Math.PI*2);X.fill();X.strokeStyle=b.integrity[i]>.55?'#c7e1d1':'#ef8b82';X.lineWidth=1;X.stroke();if(b.damage[i]>.1){X.strokeStyle=`rgba(190,45,44,${Math.min(1,b.damage[i]+.2)})`;X.beginPath();X.moveTo(px-r,py-r*.4);X.lineTo(px+r,py+r*.4);X.stroke()}}
  const torso={x:sx(b.x[NODE.TORSO]),y:sy(b.y[NODE.TORSO])};X.fillStyle=`rgba(125,190,190,${.18+b.respiration.integrity*.4})`;X.beginPath();X.ellipse(torso.x-4,torso.y,5,8,0,0,Math.PI*2);X.fill();X.fillStyle='rgba(177,112,87,.55)';X.beginPath();X.ellipse(torso.x+7,torso.y+7,6,5,0,0,Math.PI*2);X.fill();
  const f=world.food;if(f.active){X.fillStyle=f.captured?'#ffd67b':'#d0b06b';X.beginPath();X.arc(sx(f.x),sy(f.y),f.radius,0,Math.PI*2);X.fill();if(f.captured){X.strokeStyle='#ffe7a8';X.beginPath();X.moveTo(sx(f.x),sy(f.y));X.lineTo(sx((b.x[NODE.HEAD]+b.x[NODE.JAW])*.5),sy((b.y[NODE.HEAD]+b.y[NODE.JAW])*.5));X.stroke()}}
  X.fillStyle='#93a69c';X.font='10px ui-monospace,monospace';X.fillText('ground surface',12,sy(GROUND_Y)-8);
}
function pct(v){return `${(v*100).toFixed(1)}%`}function row(k,v,cls=''){return `<span class="dim">${k}</span><b class="${cls}">${v}</b>`}
function inspect(){const b=world.body,inv=invariants(world);els.summary.innerHTML=row('state',b.alive?(b.unconscious?'UNCONSCIOUS':'ALIVE'):`DEAD · ${b.causeOfDeath}`,(b.alive&&!b.unconscious)?'good':'bad')+row('time',`${world.time.toFixed(2)} s`)+row('energy',b.energy.toFixed(2))+row('blood',pct(b.bloodVolume),b.bloodVolume<.35?'bad':'')+row('oxygen',pct(b.oxygenation),b.oxygenation<.25?'bad':'')+row('invariants',inv.pass?'PASS':inv.failures.join(', '),inv.pass?'good':'bad');
  els.parts.innerHTML='<div class="rows">'+NODE_NAMES.map((name,i)=>`<div class="row"><b>${name}</b><div class="kv">${row('pos',`${b.x[i].toFixed(1)}, ${b.y[i].toFixed(1)}`)}${row('vel',`${b.vx[i].toFixed(1)}, ${b.vy[i].toFixed(1)}`)}${row('mass',b.mass[i].toFixed(2))}${row('structure',pct(b.integrity[i]))}${row('skin',pct(b.skinIntegrity[i]))}${row('flesh mass',b.fleshMass[i].toFixed(2))}${row('temp',`${b.temperature[i].toFixed(1)}°C`)}${row('hydration',pct(b.hydration[i]))}</div></div>`).join('')+'</div>';
  els.joints.innerHTML='<div class="rows">'+b.joints.map(j=>`<div class="row"><b>${j.name}</b><div class="kv">${row('integrity',pct(j.integrity))}${row('limits',`${j.minAngle.toFixed(2)}–${j.maxAngle.toFixed(2)} rad`)}</div></div>`).join('')+b.bones.map(o=>`<div class="row"><b>${o.name}</b><div class="kv">${row('length',o.len.toFixed(1))}${row('integrity',pct(o.integrity))}</div></div>`).join('')+'</div>';
  els.muscles.innerHTML='<div class="rows">'+b.muscles.map(m=>`<div class="row"><b>${m.name}</b><div class="kv">${row('activation',pct(m.activation))}${row('max torque',m.maxTorque.toFixed(0))}</div><div class="bar" style="color:#d45e55"><i style="width:${m.activation*100}%"></i></div></div>`).join('')+'</div>';
  els.phys.innerHTML='<div class="summary">'+row('controller',b.brain.controller)+row('authored stabilizer',b.brain.stabilizerAssist.toFixed(2),'warn')+row('mouth intent',b.brain.mouthIntent)+row('lung integrity',pct(b.respiration.integrity))+row('ventilation',pct(b.respiration.ventilation))+row('hypoxia',`${b.respiration.hypoxiaSeconds.toFixed(2)} s`)+row('stomach mass',b.stomach.contentsMass.toFixed(3))+row('digestible energy',b.stomach.digestibleEnergy.toFixed(2))+row('digested energy',b.stomach.digestedEnergy.toFixed(2))+row('waste mass',b.wasteMass.toFixed(3))+row('food physical',world.food.active?`${world.food.captured?'CAPTURED':'WORLD'}${world.food.swallowing?' → throat':''}`:'IN STOMACH')+row('mouth contacts',world.metrics.mouthContacts)+row('swallows',world.metrics.swallows)+'</div>';
}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;acc+=dt;let steps=0;const t0=performance.now();if(!paused){while(acc>=FIXED_DT&&steps<8){stepWorld(world,1);acc-=FIXED_DT;steps++}}simMs=performance.now()-t0;draw();if(frames++%6===0)inspect();if(now-fpsT>500){fps=frames*1000/(now-fpsT);frames=0;fpsT=now}els.perf.textContent=`FPS ${fps.toFixed(0)} · sim ${(1/FIXED_DT).toFixed(0)} Hz\nstep ${simMs.toFixed(2)} ms · nodes ${world.body.x.length}`;requestAnimationFrame(frame)}
const smokeMode=new URLSearchParams(location.search).has('smoke');
if(smokeMode){for(let i=0;i<240;i++)stepWorld(world,1);draw();inspect();document.documentElement.dataset.genesisSmoke=invariants(world).pass?'pass':'fail';}
else requestAnimationFrame(frame);

document.querySelectorAll('[data-dmg]').forEach(btn=>btn.onclick=()=>applyDamage(world,btn.dataset.dmg,btn.dataset.dmg==='torso'?.38:.55,btn.dataset.dmg==='torso'?.08:.018));
document.querySelector('#heal').onclick=()=>{for(const n of NODE_NAMES)healPart(world,n,1);world.body.bloodVolume=1;world.body.oxygenation=1;world.body.respiration.integrity=1;world.body.wounds.length=0};
document.querySelector('#food').onclick=()=>{const b=world.body;placeFoodAt(world,b.x[NODE.HEAD]+26,GROUND_Y-8)};
document.querySelector('#reset').onclick=()=>world=createWorld(20260810);els.pause.onclick=()=>{paused=!paused;els.pause.textContent=paused?'RESUME':'PAUSE'};

window.GENESIS_CREATURE_V1={get world(){return world},reset(){world=createWorld(20260810)},stepFor(seconds){const n=Math.round(seconds/FIXED_DT);for(let i=0;i<n;i++)stepWorld(world,1);return this.selfCheck()},damage(part,amount=.5,bleed=.02){return applyDamage(world,part,amount,bleed)},placeFood(){placeFoodAt(world,world.body.x[NODE.HEAD]+20,GROUND_Y-8)},selfCheck(){return {ready:true,invariants:invariants(world),time:world.time,energy:world.body.energy,blood:world.body.bloodVolume,oxygen:world.body.oxygenation,mouthContacts:world.metrics.mouthContacts,swallows:world.metrics.swallows}}};
document.documentElement.dataset.genesisCreature='ready';
