'use strict';
let e=null,memory=null,ready=false,lastInit={seed:0x3d5a17};const queue=[];
const EXPECTED_MODEL=0x00010001,EXPECTED_BYTES=38910,EXPECTED_SHA='3fbec5c7f18a07e9c809a32f1b4444480d5dcfc28a7a9577a4d87e8404f437ae';
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha256Bytes(bytes){return hex(await crypto.subtle.digest('SHA-256',bytes));}
async function loadVerifiedWasm(){
  const mr=await fetch('./weather_volume_bridge.manifest.json?v=runtime-v1',{cache:'no-store'});if(!mr.ok)throw new Error('bridge manifest HTTP '+mr.status);
  const m=await mr.json();if(m.model!=='genesis-weather3d-volume-coupling-v1')throw new Error('bridge model mismatch');
  if(m.model_version!=='0x00010001'||m.wasm?.bytes!==EXPECTED_BYTES||m.wasm?.sha256!==EXPECTED_SHA||m.wasm?.imports!==0)throw new Error('bridge manifest identity mismatch');
  const r=await fetch('./weather_volume_bridge.wasm?v=runtime-v1',{cache:'no-store'});if(!r.ok)throw new Error('bridge WASM HTTP '+r.status);
  const bin=new Uint8Array(await r.arrayBuffer());if(bin.byteLength!==EXPECTED_BYTES)throw new Error('bridge WASM byte length mismatch');
  if(await sha256Bytes(bin)!==EXPECTED_SHA)throw new Error('bridge WASM SHA mismatch');
  const mod=new WebAssembly.Module(bin);if(WebAssembly.Module.imports(mod).length!==0)throw new Error('bridge WASM imports are forbidden');
  return bin;
}
function meta(){return{w:e.genesis_width(),h:e.genesis_height(),d:e.genesis_depth(),step:e.genesis_step_index()>>>0,hash:e.genesis_world_coupling_hash()>>>0,sandUnits:e.genesis_sand_mass_units()>>>0,waterVoxels:e.genesis_water_cells()>>>0,pressureSum:e.genesis_pressure_sum()>>>0,fluidDivBefore:e.genesis_fluid_divergence_before()>>>0,fluidDivAfter:e.genesis_fluid_divergence_after()>>>0,fluidKinetic:e.genesis_fluid_kinetic_energy()>>>0,fluidMomentumX:e.genesis_fluid_momentum_x()|0,fluidMomentumY:e.genesis_fluid_momentum_y()|0,fluidMomentumZ:e.genesis_fluid_momentum_z()|0,erosion:e.genesis_erosion_events()>>>0,deposition:e.genesis_deposition_events()>>>0,invariant:e.genesis_invariant()===1,couplingInjected:e.genesis_world_coupling_injected_voxels()>>>0,couplingEvaporated:e.genesis_world_coupling_evaporated_voxels()>>>0,couplingTerrain:e.genesis_world_coupling_terrain_feedback_cells()>>>0,couplingWeatherRemoved:e.genesis_world_coupling_weather_removed_units()>>>0,couplingVolumeAdded:e.genesis_world_coupling_volume_added_units()>>>0,couplingVolumeRemoved:e.genesis_world_coupling_volume_removed_units()>>>0,couplingWeatherAdded:e.genesis_world_coupling_weather_added_units()>>>0,couplingError:e.genesis_world_coupling_conservation_error()>>>0};}
function emit(){const ptr=e.genesis_pack()>>>0,count=e.genesis_cell_count()>>>0,src=new Uint32Array(memory.buffer,ptr,count),out=new Uint32Array(src);postMessage({type:'state',buffer:out.buffer,meta:meta()},[out.buffer]);}
function init(o=lastInit){lastInit={seed:(o.seed>>>0)||0x3d5a17};e.genesis_world_coupling_reset(lastInit.seed);emit();}
function handle(m){if(m.type==='init')init(m);else if(m.type==='step'){e.genesis_world_coupling_step(Math.max(1,Math.min(8,m.weatherSteps|0||1)),Math.max(1,Math.min(4,m.volumeSteps|0||1)));emit();}else if(m.type==='paint'){e.genesis_paint(m.kind|0,m.x|0,m.y|0,m.z|0,Math.max(1,m.radius|0||2));emit();}else if(m.type==='impulse'){e.genesis_impulse_water(m.x|0,m.y|0,m.z|0,Math.max(1,m.radius|0||2),m.ix|0,m.iy|0,m.iz|0);emit();}else if(m.type==='exchange'){e.genesis_world_coupling_exchange();emit();}else if(m.type==='reset')init(lastInit);}
onmessage=ev=>{const m=ev.data||{};if(!ready){queue.push(m);return;}try{handle(m);}catch(err){postMessage({type:'error',message:String(err?.stack||err)});}};
(async()=>{try{const bin=await loadVerifiedWasm(),result=await WebAssembly.instantiate(bin,{});e=result.instance.exports;memory=e.memory;if((e.genesis_world_coupling_model_version()>>>0)!==EXPECTED_MODEL)throw new Error('bridge model version mismatch');for(const n of ['genesis_world_coupling_reset','genesis_world_coupling_step','genesis_world_coupling_exchange','genesis_world_coupling_conservation_error','genesis_pack'])if(typeof e[n]!=='function')throw new Error('missing bridge export '+n);ready=true;postMessage({type:'ready',wasmBytes:bin.byteLength,wasmSha256:EXPECTED_SHA,modelVersion:EXPECTED_MODEL,massUnits:e.genesis_world_coupling_mass_units_per_voxel()>>>0});while(queue.length)handle(queue.shift());}catch(err){postMessage({type:'fatal',message:'Weather3D-volume C++ WebAssembly failed: '+String(err?.message||err)});}})();
